;;! target = "aarch64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation=false -W memory64 -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0xffff0000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load8_u offset=0xffff0000))

;; wasm[0]::function[0]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       mov     w9, #-0xffff
;;       adds    x9, x4, x9
;;       b.hs    #0x38
;;   14: ldr     x10, [x2, #0x40]
;;       cmp     x9, x10
;;       b.hi    #0x3c
;;   20: ldr     x12, [x2, #0x38]
;;       add     x12, x12, x4
;;       mov     x13, #0xffff0000
;;       strb    w5, [x12, x13]
;;       ldp     x29, x30, [sp], #0x10
;;       ret
;;   38: udf     #0xc11f
;;   3c: udf     #0xc11f
;;
;; wasm[0]::function[1]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       mov     w9, #-0xffff
;;       adds    x9, x4, x9
;;       b.hs    #0x78
;;   54: ldr     x10, [x2, #0x40]
;;       cmp     x9, x10
;;       b.hi    #0x7c
;;   60: ldr     x12, [x2, #0x38]
;;       add     x12, x12, x4
;;       mov     x13, #0xffff0000
;;       ldrb    w2, [x12, x13]
;;       ldp     x29, x30, [sp], #0x10
;;       ret
;;   78: udf     #0xc11f
;;   7c: udf     #0xc11f
