;;! target = "aarch64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation=false -O static-memory-forced -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0xffff0000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0xffff0000))

;; wasm[0]::function[0]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       mov     w10, w4
;;       mov     x9, #0xfffc
;;       cmp     x10, x9
;;       cset    x12, hi
;;       uxtb    w11, w12
;;       cbnz    x11, #0x38
;;   20: ldr     x12, [x2, #0x38]
;;       add     x12, x12, w4, uxtw
;;       mov     x13, #0xffff0000
;;       str     w5, [x12, x13]
;;       ldp     x29, x30, [sp], #0x10
;;       ret
;;   38: .byte   0x1f, 0xc1, 0x00, 0x00
;;
;; wasm[0]::function[1]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       mov     w10, w4
;;       mov     x9, #0xfffc
;;       cmp     x10, x9
;;       cset    x12, hi
;;       uxtb    w11, w12
;;       cbnz    x11, #0x78
;;   60: ldr     x12, [x2, #0x38]
;;       add     x12, x12, w4, uxtw
;;       mov     x13, #0xffff0000
;;       ldr     w2, [x12, x13]
;;       ldp     x29, x30, [sp], #0x10
;;       ret
;;   78: .byte   0x1f, 0xc1, 0x00, 0x00
