;;! target = "aarch64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation=false -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0xffff0000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load8_u offset=0xffff0000))

;; wasm[0]::function[0]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       mov     w12, w4
;;       mov     w13, #-0xffff
;;       adds    x12, x12, x13
;;       b.hs    #0x44
;;   18: ldr     x13, [x2, #0x68]
;;       cmp     x12, x13
;;       cset    x14, hi
;;       uxtb    w14, w14
;;       cbnz    x14, #0x48
;;   2c: ldr     x15, [x2, #0x60]
;;       add     x15, x15, w4, uxtw
;;       mov     x0, #0xffff0000
;;       strb    w5, [x15, x0]
;;       ldp     x29, x30, [sp], #0x10
;;       ret
;;   44: .byte   0x1f, 0xc1, 0x00, 0x00
;;   48: .byte   0x1f, 0xc1, 0x00, 0x00
;;
;; wasm[0]::function[1]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       mov     w12, w4
;;       mov     w13, #-0xffff
;;       adds    x12, x12, x13
;;       b.hs    #0xa4
;;   78: ldr     x13, [x2, #0x68]
;;       cmp     x12, x13
;;       cset    x14, hi
;;       uxtb    w14, w14
;;       cbnz    x14, #0xa8
;;   8c: ldr     x15, [x2, #0x60]
;;       add     x15, x15, w4, uxtw
;;       mov     x0, #0xffff0000
;;       ldrb    w2, [x15, x0]
;;       ldp     x29, x30, [sp], #0x10
;;       ret
;;   a4: .byte   0x1f, 0xc1, 0x00, 0x00
;;   a8: .byte   0x1f, 0xc1, 0x00, 0x00
