;;! target = "aarch64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation=false -W memory64 -O static-memory-forced -O static-memory-guard-size=4294967295 -O dynamic-memory-guard-size=4294967295"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store offset=0x1000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load offset=0x1000))

;; wasm[0]::function[0]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       mov     w6, #-0x1004
;;       cmp     x4, x6
;;       b.hi    #0x28
;;   14: ldr     x8, [x2, #0x38]
;;       add     x8, x8, #1, lsl #12
;;       str     w5, [x8, x4]
;;       ldp     x29, x30, [sp], #0x10
;;       ret
;;   28: udf     #0xc11f
;;
;; wasm[0]::function[1]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       mov     w6, #-0x1004
;;       cmp     x4, x6
;;       b.hi    #0x68
;;   54: ldr     x8, [x2, #0x38]
;;       add     x7, x8, #1, lsl #12
;;       ldr     w2, [x7, x4]
;;       ldp     x29, x30, [sp], #0x10
;;       ret
;;   68: udf     #0xc11f
