;;! target = "aarch64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-forced -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0xffff0000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load8_u offset=0xffff0000))

;; wasm[0]::function[0]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       mov     w11, w4
;;       mov     x12, #0
;;       ldr     x13, [x2, #0x38]
;;       add     x13, x13, w4, uxtw
;;       mov     x14, #0xffff0000
;;       add     x13, x13, x14
;;       mov     x10, #0xffff
;;       cmp     x11, x10
;;       csel    x13, x12, x13, hi
;;       strb    w5, [x13]
;;       ldp     x29, x30, [sp], #0x10
;;       ret
;;
;; wasm[0]::function[1]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       mov     w11, w4
;;       mov     x12, #0
;;       ldr     x13, [x2, #0x38]
;;       add     x13, x13, w4, uxtw
;;       mov     x14, #0xffff0000
;;       add     x13, x13, x14
;;       mov     x10, #0xffff
;;       cmp     x11, x10
;;       csel    x13, x12, x13, hi
;;       ldrb    w2, [x13]
;;       ldp     x29, x30, [sp], #0x10
;;       ret
