;;! target = "aarch64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-forced -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0x1000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load8_u offset=0x1000))

;; wasm[0]::function[0]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       mov     w10, w4
;;       mov     x11, #0
;;       ldr     x12, [x2, #0x38]
;;       add     x12, x12, w4, uxtw
;;       add     x12, x12, #1, lsl #12
;;       mov     w9, #-0x1001
;;       cmp     x10, x9
;;       csel    x12, x11, x12, hi
;;       strb    w5, [x12]
;;       ldp     x29, x30, [sp], #0x10
;;       ret
;;
;; wasm[0]::function[1]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       mov     w10, w4
;;       mov     x11, #0
;;       ldr     x12, [x2, #0x38]
;;       add     x12, x12, w4, uxtw
;;       add     x12, x12, #1, lsl #12
;;       mov     w9, #-0x1001
;;       cmp     x10, x9
;;       csel    x12, x11, x12, hi
;;       ldrb    w2, [x12]
;;       ldp     x29, x30, [sp], #0x10
;;       ret
