;;! target = "aarch64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation=false -O static-memory-forced -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0))

;; wasm[0]::function[0]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       mov     w6, w4
;;       mov     x7, #0xfffffffc
;;       cmp     x6, x7
;;       b.hi    #0x28
;;   18: ldr     x8, [x2, #0x38]
;;       str     w5, [x8, w4, uxtw]
;;       ldp     x29, x30, [sp], #0x10
;;       ret
;;   28: udf     #0xc11f
;;
;; wasm[0]::function[1]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       mov     w6, w4
;;       mov     x7, #0xfffffffc
;;       cmp     x6, x7
;;       b.hi    #0x68
;;   58: ldr     x8, [x2, #0x38]
;;       ldr     w2, [x8, w4, uxtw]
;;       ldp     x29, x30, [sp], #0x10
;;       ret
;;   68: udf     #0xc11f
