;;! target = "aarch64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -W memory64 -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store offset=0)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load offset=0))

;; function u0:0:
;; block0:
;;   ldr x11, [x0, #88]
;;   ldr x10, [x0, #80]
;;   sub x11, x11, #4
;;   movz x12, #0
;;   add x10, x10, x2
;;   subs xzr, x2, x11
;;   csel x11, x12, x10, hi
;;   csdb
;;   str w3, [x11]
;;   b label1
;; block1:
;;   ret
;;
;; function u0:1:
;; block0:
;;   ldr x11, [x0, #88]
;;   ldr x10, [x0, #80]
;;   sub x11, x11, #4
;;   movz x12, #0
;;   add x10, x10, x2
;;   subs xzr, x2, x11
;;   csel x11, x12, x10, hi
;;   csdb
;;   ldr w0, [x11]
;;   b label1
;; block1:
;;   ret
