;;! target = "aarch64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation=false -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0))

;; wasm[0]::function[0]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       ldr     x7, [x2, #0x40]
;;       mov     w8, w4
;;       sub     x7, x7, #4
;;       cmp     x8, x7
;;       b.hi    #0x2c
;;   1c: ldr     x9, [x2, #0x38]
;;       str     w5, [x9, w4, uxtw]
;;       ldp     x29, x30, [sp], #0x10
;;       ret
;;   2c: udf     #0xc11f
;;
;; wasm[0]::function[1]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       ldr     x7, [x2, #0x40]
;;       mov     w8, w4
;;       sub     x7, x7, #4
;;       cmp     x8, x7
;;       b.hi    #0x6c
;;   5c: ldr     x9, [x2, #0x38]
;;       ldr     w2, [x9, w4, uxtw]
;;       ldp     x29, x30, [sp], #0x10
;;       ret
;;   6c: udf     #0xc11f
