;;! target = "aarch64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-forced -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0xffff0000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load8_u offset=0xffff0000))

;; wasm[0]::function[0]:
;;    0: stp     x29, x30, [sp, #-0x10]!
;;    4: mov     x29, sp
;;    8: mov     w12, w2
;;    c: mov     x13, #0
;;   10: ldr     x14, [x0, #0x50]
;;   14: add     x14, x14, w2, uxtw
;;   18: mov     x15, #0xffff0000
;;   1c: add     x14, x14, x15
;;   20: mov     x11, #0xffff
;;   24: cmp     x12, x11
;;   28: csel    x14, x13, x14, hi
;;   2c: csdb
;;   30: strb    w3, [x14]
;;   34: ldp     x29, x30, [sp], #0x10
;;   38: ret
;;
;; wasm[0]::function[1]:
;;   40: stp     x29, x30, [sp, #-0x10]!
;;   44: mov     x29, sp
;;   48: mov     w12, w2
;;   4c: mov     x13, #0
;;   50: ldr     x14, [x0, #0x50]
;;   54: add     x14, x14, w2, uxtw
;;   58: mov     x15, #0xffff0000
;;   5c: add     x14, x14, x15
;;   60: mov     x11, #0xffff
;;   64: cmp     x12, x11
;;   68: csel    x14, x13, x14, hi
;;   6c: csdb
;;   70: ldrb    w0, [x14]
;;   74: ldp     x29, x30, [sp], #0x10
;;   78: ret
