;;! target = "aarch64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation=false -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0x1000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load8_u offset=0x1000))

;; wasm[0]::function[0]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       ldr     x9, [x2, #0x68]
;;       mov     w10, w4
;;       mov     x11, #0x1001
;;       sub     x9, x9, x11
;;       cmp     x10, x9
;;       b.hi    #0x34
;;   20: ldr     x11, [x2, #0x60]
;;       add     x11, x11, #1, lsl #12
;;       strb    w5, [x11, w4, uxtw]
;;       ldp     x29, x30, [sp], #0x10
;;       ret
;;   34: .byte   0x1f, 0xc1, 0x00, 0x00
;;
;; wasm[0]::function[1]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       ldr     x10, [x2, #0x68]
;;       mov     w11, w4
;;       mov     x12, #0x1001
;;       sub     x10, x10, x12
;;       cmp     x11, x10
;;       b.hi    #0x78
;;   60: ldr     x12, [x2, #0x60]
;;       add     x11, x12, #1, lsl #12
;;       ldrb    w13, [x11, w4, uxtw]
;;       uxtb    w2, w13
;;       ldp     x29, x30, [sp], #0x10
;;       ret
;;   78: .byte   0x1f, 0xc1, 0x00, 0x00
