test compile precise-output
target aarch64

function %atomic_store_i64(i64, i64) {
block0(v0: i64, v1: i64):
  atomic_store.i64 v0, v1
  return
}

; VCode:
; block0:
;   stlr x0, [x1]
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   stlr x0, [x1] ; trap: heap_oob
;   ret

function %atomic_store_i32(i32, i64) {
block0(v0: i32, v1: i64):
  atomic_store.i32 v0, v1
  return
}

; VCode:
; block0:
;   stlr w0, [x1]
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   stlr w0, [x1] ; trap: heap_oob
;   ret

function %atomic_store_i16(i16, i64) {
block0(v0: i16, v1: i64):
  atomic_store.i16 v0, v1
  return
}

; VCode:
; block0:
;   stlrh w0, [x1]
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   stlrh w0, [x1] ; trap: heap_oob
;   ret

function %atomic_store_i8(i8, i64) {
block0(v0: i8, v1: i64):
  atomic_store.i8 v0, v1
  return
}

; VCode:
; block0:
;   stlrb w0, [x1]
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   stlrb w0, [x1] ; trap: heap_oob
;   ret

function %atomic_store_i64_i32(i64, i64) {
block0(v0: i64, v1: i64):
  v2 = ireduce.i32 v0
  atomic_store.i32 v2, v1
  return
}

; VCode:
; block0:
;   stlr w0, [x1]
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   stlr w0, [x1] ; trap: heap_oob
;   ret

function %atomic_store_i64_i16(i64, i64) {
block0(v0: i64, v1: i64):
  v2 = ireduce.i16 v0
  atomic_store.i16 v2, v1
  return
}

; VCode:
; block0:
;   stlrh w0, [x1]
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   stlrh w0, [x1] ; trap: heap_oob
;   ret

function %atomic_store_i64_i8(i64, i64) {
block0(v0: i64, v1: i64):
  v2 = ireduce.i8 v0
  atomic_store.i8 v2, v1
  return
}

; VCode:
; block0:
;   stlrb w0, [x1]
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   stlrb w0, [x1] ; trap: heap_oob
;   ret

function %atomic_store_i32_i16(i32, i64) {
block0(v0: i32, v1: i64):
  v2 = ireduce.i16 v0
  atomic_store.i16 v2, v1
  return
}

; VCode:
; block0:
;   stlrh w0, [x1]
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   stlrh w0, [x1] ; trap: heap_oob
;   ret

function %atomic_store_i32_i8(i32, i64) {
block0(v0: i32, v1: i64):
  v2 = ireduce.i8 v0
  atomic_store.i8 v2, v1
  return
}

; VCode:
; block0:
;   stlrb w0, [x1]
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   stlrb w0, [x1] ; trap: heap_oob
;   ret

