test compile precise-output
set unwind_info=false
target aarch64

function %f0(i64) -> i64 {
block0(v0: i64):
    v1 = bswap v0
    return v1
}

; VCode:
; block0:
;   rev64 x0, x0
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   rev x0, x0
;   ret

function %f1(i32) -> i32 {
block0(v0: i32):
    v1 = bswap v0
    return v1
}

; VCode:
; block0:
;   rev32 w0, w0
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   rev w0, w0
;   ret

function %f2(i16) -> i16 {
block0(v0: i16):
    v1 = bswap v0
    return v1
}

; VCode:
; block0:
;   rev16 w0, w0
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   rev16 w0, w0
;   ret

