test compile precise-output
set unwind_info=false
target aarch64 sign_return_address

function %f1(i64) -> i64 {
    fn0 = %g(i64) -> i64

block0(v0: i64):
    v1 = call fn0(v0)
    return v1
}

; VCode:
;   paciasp
;   stp fp, lr, [sp, #-16]!
;   mov fp, sp
; block0:
;   load_ext_name_far x3, TestCase(%g)+0
;   blr x3
;   ldp fp, lr, [sp], #16
;   autiasp ; ret
;
; Disassembled:
; block0: ; offset 0x0
;   paciasp
;   stp x29, x30, [sp, #-0x10]!
;   mov x29, sp
; block1: ; offset 0xc
;   ldr x3, #0x14
;   b #0x1c
;   udf #0 ; reloc_external Abs8 %g 0
;   udf #0
;   blr x3
;   ldp x29, x30, [sp], #0x10
;   autiasp
;   ret

function %f2(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = iadd.i64 v0, v1
    return v2
}

; VCode:
; block0:
;   add x0, x0, x1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   add x0, x0, x1
;   ret

function %tail_convention(i64) -> i64 tail {
    fn0 = %g(i64) -> i64

block0(v0: i64):
    v1 = call fn0(v0)
    return v1
}

; VCode:
;   paciaz
;   stp fp, lr, [sp, #-16]!
;   mov fp, sp
; block0:
;   load_ext_name_far x3, TestCase(%g)+0
;   mov x0, x2
;   blr x3
;   mov x2, x0
;   ldp fp, lr, [sp], #16
;   autiaz ; ret
;
; Disassembled:
; block0: ; offset 0x0
;   paciaz
;   stp x29, x30, [sp, #-0x10]!
;   mov x29, sp
; block1: ; offset 0xc
;   ldr x3, #0x14
;   b #0x1c
;   udf #0 ; reloc_external Abs8 %g 0
;   udf #0
;   mov x0, x2
;   blr x3
;   mov x2, x0
;   ldp x29, x30, [sp], #0x10
;   autiaz
;   ret

function %tail_call(i64) -> i64 tail {
    fn0 = %g(i64) -> i64 tail

block0(v0: i64):
    return_call fn0(v0)
}

; VCode:
; block0:
;   load_ext_name_far x1, TestCase(%g)+0
;   return_call_ind x1 new_stack_arg_size:0 x2=x2
;
; Disassembled:
; block0: ; offset 0x0
;   ldr x1, #8
;   b #0x10
;   udf #0 ; reloc_external Abs8 %g 0
;   udf #0
;   br x1

