test compile precise-output
target aarch64

function %f0(i32) -> i32 {
block0(v0: i32):
    v1 = iconst.i32 127
    v2 = iadd_overflow_trap v0, v1, user0
    return v2
}

; block0:
;   movz x3, #127
;   adds w0, w0, w3
;   b.lo 8 ; udf
;   ret

function %f1(i32) -> i32 {
block0(v0: i32):
    v1 = iconst.i32 127
    v2 = iadd_overflow_trap v1, v0, user0
    return v2
}

; block0:
;   movz x3, #127
;   adds w0, w3, w0
;   b.lo 8 ; udf
;   ret

function %f2(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = iadd_overflow_trap v0, v1, user0
    return v2
}

; block0:
;   adds w0, w0, w1
;   b.lo 8 ; udf
;   ret

function %f3(i64) -> i64 {
block0(v0: i64):
    v1 = iconst.i64 127
    v2 = iadd_overflow_trap v0, v1, user0
    return v2
}

; block0:
;   movz x3, #127
;   adds x0, x0, x3
;   b.lo 8 ; udf
;   ret

function %f3(i64) -> i64 {
block0(v0: i64):
    v1 = iconst.i64 127
    v2 = iadd_overflow_trap v1, v0, user0
    return v2
}

; block0:
;   movz x3, #127
;   adds x0, x3, x0
;   b.lo 8 ; udf
;   ret

function %f4(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = iadd_overflow_trap v0, v1, user0
    return v2
}

; block0:
;   adds x0, x0, x1
;   b.lo 8 ; udf
;   ret

