test compile precise-output
set unwind_info=false
target aarch64

function %load_f16(i64) -> f16 {
block0(v0: i64):
    v1 = load.f16 v0
    return v1
}

; VCode:
; block0:
;   ldr h0, [x0]
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   ldr h0, [x0] ; trap: heap_oob
;   ret

function %load_f128(i64) -> f128 {
block0(v0: i64):
    v1 = load.f128 v0
    return v1
}

; VCode:
; block0:
;   ldr q0, [x0]
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   ldr q0, [x0] ; trap: heap_oob
;   ret

