test compile precise-output
target aarch64

function %call_preserve_all_abi(i64) system_v {
    sig0 = (i64, i64, i64, i64) preserve_all
block0(v0: i64):
    call_indirect sig0, v0(v0, v0, v0, v0)
    call_indirect sig0, v0(v0, v0, v0, v0)
    return
}

; VCode:
;   stp fp, lr, [sp, #-16]!
;   mov fp, sp
; block0:
;   mov x3, x0
;   mov x1, x3
;   mov x2, x3
;   blr x3
;   blr x3
;   ldp fp, lr, [sp], #16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   stp x29, x30, [sp, #-0x10]!
;   mov x29, sp
; block1: ; offset 0x8
;   mov x3, x0
;   mov x1, x3
;   mov x2, x3
;   blr x3
;   blr x3
;   ldp x29, x30, [sp], #0x10
;   ret

function %preserve_all_abi_trampoline(i64) preserve_all {
    fn0 = %libcall(i64) system_v
block0(v0: i64):
    call fn0(v0)
    return
}

; VCode:
;   stp fp, lr, [sp, #-16]!
;   mov fp, sp
;   stp x16, x17, [sp, #-16]!
;   stp x14, x15, [sp, #-16]!
;   stp x12, x13, [sp, #-16]!
;   stp x10, x11, [sp, #-16]!
;   stp x8, x9, [sp, #-16]!
;   stp x6, x7, [sp, #-16]!
;   stp x4, x5, [sp, #-16]!
;   stp x2, x3, [sp, #-16]!
;   stp x0, x1, [sp, #-16]!
;   stp d30, d31, [sp, #-16]!
;   stp d28, d29, [sp, #-16]!
;   stp d26, d27, [sp, #-16]!
;   stp d24, d25, [sp, #-16]!
;   stp d22, d23, [sp, #-16]!
;   stp d20, d21, [sp, #-16]!
;   stp d18, d19, [sp, #-16]!
;   stp d16, d17, [sp, #-16]!
;   stp d14, d15, [sp, #-16]!
;   stp d12, d13, [sp, #-16]!
;   stp d10, d11, [sp, #-16]!
;   stp d8, d9, [sp, #-16]!
;   stp d6, d7, [sp, #-16]!
;   stp d4, d5, [sp, #-16]!
;   stp d2, d3, [sp, #-16]!
;   stp d0, d1, [sp, #-16]!
; block0:
;   load_ext_name_far x2, TestCase(%libcall)+0
;   blr x2
;   ldp d0, d1, [sp], #16
;   ldp d2, d3, [sp], #16
;   ldp d4, d5, [sp], #16
;   ldp d6, d7, [sp], #16
;   ldp d8, d9, [sp], #16
;   ldp d10, d11, [sp], #16
;   ldp d12, d13, [sp], #16
;   ldp d14, d15, [sp], #16
;   ldp d16, d17, [sp], #16
;   ldp d18, d19, [sp], #16
;   ldp d20, d21, [sp], #16
;   ldp d22, d23, [sp], #16
;   ldp d24, d25, [sp], #16
;   ldp d26, d27, [sp], #16
;   ldp d28, d29, [sp], #16
;   ldp d30, d31, [sp], #16
;   ldp x0, x1, [sp], #16
;   ldp x2, x3, [sp], #16
;   ldp x4, x5, [sp], #16
;   ldp x6, x7, [sp], #16
;   ldp x8, x9, [sp], #16
;   ldp x10, x11, [sp], #16
;   ldp x12, x13, [sp], #16
;   ldp x14, x15, [sp], #16
;   ldp x16, x17, [sp], #16
;   ldp fp, lr, [sp], #16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   stp x29, x30, [sp, #-0x10]!
;   mov x29, sp
;   stp x16, x17, [sp, #-0x10]!
;   stp x14, x15, [sp, #-0x10]!
;   stp x12, x13, [sp, #-0x10]!
;   stp x10, x11, [sp, #-0x10]!
;   stp x8, x9, [sp, #-0x10]!
;   stp x6, x7, [sp, #-0x10]!
;   stp x4, x5, [sp, #-0x10]!
;   stp x2, x3, [sp, #-0x10]!
;   stp x0, x1, [sp, #-0x10]!
;   stp d30, d31, [sp, #-0x10]!
;   stp d28, d29, [sp, #-0x10]!
;   stp d26, d27, [sp, #-0x10]!
;   stp d24, d25, [sp, #-0x10]!
;   stp d22, d23, [sp, #-0x10]!
;   stp d20, d21, [sp, #-0x10]!
;   stp d18, d19, [sp, #-0x10]!
;   stp d16, d17, [sp, #-0x10]!
;   stp d14, d15, [sp, #-0x10]!
;   stp d12, d13, [sp, #-0x10]!
;   stp d10, d11, [sp, #-0x10]!
;   stp d8, d9, [sp, #-0x10]!
;   stp d6, d7, [sp, #-0x10]!
;   stp d4, d5, [sp, #-0x10]!
;   stp d2, d3, [sp, #-0x10]!
;   stp d0, d1, [sp, #-0x10]!
; block1: ; offset 0x6c
;   ldr x2, #0x74
;   b #0x7c
;   .byte 0x00, 0x00, 0x00, 0x00 ; reloc_external Abs8 %libcall 0
;   .byte 0x00, 0x00, 0x00, 0x00
;   blr x2
;   ldp d0, d1, [sp], #0x10
;   ldp d2, d3, [sp], #0x10
;   ldp d4, d5, [sp], #0x10
;   ldp d6, d7, [sp], #0x10
;   ldp d8, d9, [sp], #0x10
;   ldp d10, d11, [sp], #0x10
;   ldp d12, d13, [sp], #0x10
;   ldp d14, d15, [sp], #0x10
;   ldp d16, d17, [sp], #0x10
;   ldp d18, d19, [sp], #0x10
;   ldp d20, d21, [sp], #0x10
;   ldp d22, d23, [sp], #0x10
;   ldp d24, d25, [sp], #0x10
;   ldp d26, d27, [sp], #0x10
;   ldp d28, d29, [sp], #0x10
;   ldp d30, d31, [sp], #0x10
;   ldp x0, x1, [sp], #0x10
;   ldp x2, x3, [sp], #0x10
;   ldp x4, x5, [sp], #0x10
;   ldp x6, x7, [sp], #0x10
;   ldp x8, x9, [sp], #0x10
;   ldp x10, x11, [sp], #0x10
;   ldp x12, x13, [sp], #0x10
;   ldp x14, x15, [sp], #0x10
;   ldp x16, x17, [sp], #0x10
;   ldp x29, x30, [sp], #0x10
;   ret

function %preserve_all_call(i64) system_v {
  fn0 = colocated %f(i64) preserve_all
block0(v0: i64):
  call fn0(v0)
  return
}

; VCode:
;   stp fp, lr, [sp, #-16]!
;   mov fp, sp
; block0:
;   bl 0
;   ldp fp, lr, [sp], #16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   stp x29, x30, [sp, #-0x10]!
;   mov x29, sp
; block1: ; offset 0x8
;   bl #8 ; reloc_external Call %f 0
;   ldp x29, x30, [sp], #0x10
;   ret

