test compile precise-output
set enable_simd
target aarch64

function %bnot_i32x4(i32x4) -> i32x4 {
block0(v0: i32x4):
    v1 = bnot v0
    return v1
}

; VCode:
; block0:
;   mvn v0.16b, v0.16b
;   ret
; 
; Disassembled:
; block0: ; offset 0x0
;   mvn v0.16b, v0.16b
;   ret

function %vany_true_i32x4(i32x4) -> i8 {
block0(v0: i32x4):
    v1 = vany_true v0
    return v1
}

; VCode:
; block0:
;   umaxp v2.4s, v0.4s, v0.4s
;   mov x4, v2.d[0]
;   subs xzr, x4, #0
;   cset x0, ne
;   ret
; 
; Disassembled:
; block0: ; offset 0x0
;   umaxp v2.4s, v0.4s, v0.4s
;   mov x4, v2.d[0]
;   cmp x4, #0
;   cset x0, ne
;   ret

function %vall_true_i64x2(i64x2) -> i8 {
block0(v0: i64x2):
    v1 = vall_true v0
    return v1
}

; VCode:
; block0:
;   cmeq v2.2d, v0.2d, #0
;   addp v4.2d, v2.2d, v2.2d
;   fcmp d4, d4
;   cset x0, eq
;   ret
; 
; Disassembled:
; block0: ; offset 0x0
;   cmeq v2.2d, v0.2d, #0
;   addp v4.2d, v2.2d, v2.2d
;   fcmp d4, d4
;   cset x0, eq
;   ret

