test compile precise-output
set unwind_info=false
target aarch64

function %f1() -> i64x2 {
block0:
  v0 = iconst.i64 281474976710657
  v1 = scalar_to_vector.i64x2 v0
  return v1
}

; block0:
;   movz x1, #1
;   movk x1, x1, #1, LSL #48
;   fmov d0, x1
;   ret

function %f2() -> i32x4 {
block0:
  v0 = iconst.i32 42679
  v1 = scalar_to_vector.i32x4 v0
  return v1
}

; block0:
;   movz w0, #42679
;   fmov s0, w0
;   ret

function %f3() -> f32x4 {
block0:
  v0 = f32const 0x1.0
  v1 = scalar_to_vector.f32x4 v0
  return v1
}

; block0:
;   fmov s0, #1
;   fmov s0, s0
;   ret

function %f4() -> f64x2 {
block0:
  v0 = f64const 0x1.0
  v1 = scalar_to_vector.f64x2 v0
  return v1
}

; block0:
;   fmov d0, #1
;   fmov d0, d0
;   ret

