test compile precise-output
set unwind_info=false
target aarch64

function %fn1(i8x16, i8x16) -> i16x8 {
block0(v0: i8x16, v1: i8x16):
  v2 = swiden_low v0
  v3 = swiden_low v1
  v4 = imul v2, v3
  return v4
}

; VCode:
; block0:
;   smull v0.8h, v0.8b, v1.8b
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   smull v0.8h, v0.8b, v1.8b
;   ret

function %fn2(i8x16, i8x16) -> i16x8 {
block0(v0: i8x16, v1: i8x16):
  v2 = swiden_high v0
  v3 = swiden_high v1
  v4 = imul v2, v3
  return v4
}

; VCode:
; block0:
;   smull2 v0.8h, v0.16b, v1.16b
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   smull2 v0.8h, v0.16b, v1.16b
;   ret

function %fn3(i16x8, i16x8) -> i32x4 {
block0(v0: i16x8, v1: i16x8):
  v2 = swiden_low v0
  v3 = swiden_low v1
  v4 = imul v2, v3
  return v4
}

; VCode:
; block0:
;   smull v0.4s, v0.4h, v1.4h
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   smull v0.4s, v0.4h, v1.4h
;   ret

function %fn4(i16x8, i16x8) -> i32x4 {
block0(v0: i16x8, v1: i16x8):
  v2 = swiden_high v0
  v3 = swiden_high v1
  v4 = imul v2, v3
  return v4
}

; VCode:
; block0:
;   smull2 v0.4s, v0.8h, v1.8h
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   smull2 v0.4s, v0.8h, v1.8h
;   ret

function %fn5(i32x4, i32x4) -> i64x2 {
block0(v0: i32x4, v1: i32x4):
  v2 = swiden_low v0
  v3 = swiden_low v1
  v4 = imul v2, v3
  return v4
}

; VCode:
; block0:
;   smull v0.2d, v0.2s, v1.2s
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   smull v0.2d, v0.2s, v1.2s
;   ret

function %fn6(i32x4, i32x4) -> i64x2 {
block0(v0: i32x4, v1: i32x4):
  v2 = swiden_high v0
  v3 = swiden_high v1
  v4 = imul v2, v3
  return v4
}

; VCode:
; block0:
;   smull2 v0.2d, v0.4s, v1.4s
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   smull2 v0.2d, v0.4s, v1.4s
;   ret

function %fn7(i8x16, i8x16) -> i16x8 {
block0(v0: i8x16, v1: i8x16):
  v2 = uwiden_low v0
  v3 = uwiden_low v1
  v4 = imul v2, v3
  return v4
}

; VCode:
; block0:
;   umull v0.8h, v0.8b, v1.8b
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   umull v0.8h, v0.8b, v1.8b
;   ret

function %fn8(i8x16, i8x16) -> i16x8 {
block0(v0: i8x16, v1: i8x16):
  v2 = uwiden_high v0
  v3 = uwiden_high v1
  v4 = imul v2, v3
  return v4
}

; VCode:
; block0:
;   umull2 v0.8h, v0.16b, v1.16b
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   umull2 v0.8h, v0.16b, v1.16b
;   ret

function %fn9(i16x8, i16x8) -> i32x4 {
block0(v0: i16x8, v1: i16x8):
  v2 = uwiden_low v0
  v3 = uwiden_low v1
  v4 = imul v2, v3
  return v4
}

; VCode:
; block0:
;   umull v0.4s, v0.4h, v1.4h
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   umull v0.4s, v0.4h, v1.4h
;   ret

function %fn10(i16x8, i16x8) -> i32x4 {
block0(v0: i16x8, v1: i16x8):
  v2 = uwiden_high v0
  v3 = uwiden_high v1
  v4 = imul v2, v3
  return v4
}

; VCode:
; block0:
;   umull2 v0.4s, v0.8h, v1.8h
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   umull2 v0.4s, v0.8h, v1.8h
;   ret

function %fn11(i32x4, i32x4) -> i64x2 {
block0(v0: i32x4, v1: i32x4):
  v2 = uwiden_low v0
  v3 = uwiden_low v1
  v4 = imul v2, v3
  return v4
}

; VCode:
; block0:
;   umull v0.2d, v0.2s, v1.2s
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   umull v0.2d, v0.2s, v1.2s
;   ret

function %fn12(i32x4, i32x4) -> i64x2 {
block0(v0: i32x4, v1: i32x4):
  v2 = uwiden_high v0
  v3 = uwiden_high v1
  v4 = imul v2, v3
  return v4
}

; VCode:
; block0:
;   umull2 v0.2d, v0.4s, v1.4s
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   umull2 v0.2d, v0.4s, v1.4s
;   ret

