test compile precise-output
set unwind_info=false
target aarch64 has_dotprod

;; Tests the aarch64 `sdot` lowering: the exact-i32 dot-product tree that
;; `i32x4.relaxed_dot_i8x16_i7x16_add_s` decomposes into contracts to one `sdot`.
function %sdot_i8x16(i8x16, i8x16, i32x4) -> i32x4 {
block0(v0: i8x16, v1: i8x16, v2: i32x4):
    v3 = swiden_low v0
    v4 = swiden_low v1
    v5 = imul v3, v4
    v6 = swiden_high v0
    v7 = swiden_high v1
    v8 = imul v6, v7
    v9 = swiden_low v5
    v10 = swiden_high v5
    v11 = iadd_pairwise v9, v10
    v12 = swiden_low v8
    v13 = swiden_high v8
    v14 = iadd_pairwise v12, v13
    v15 = iadd_pairwise v11, v14
    v16 = iadd v15, v2
    return v16
}

; VCode:
; block0:
;   mov v5.16b, v0.16b
;   mov v0.16b, v2.16b
;   sdot v0.4s, v0.4s, v5.4s, v1.4s
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mov v5.16b, v0.16b
;   mov v0.16b, v2.16b
;   sdot v0.4s, v5.16b, v1.16b
;   ret

