test compile precise-output
set enable_simd
target aarch64

function %icmp_ne_32x4(i32x4, i32x4) -> b32x4 {
block0(v0: i32x4, v1: i32x4):
    v2 = icmp ne v0, v1
    return v2
}

; block0:
;   cmeq v0.4s, v0.4s, v1.4s
;   mvn v0.16b, v0.16b
;   ret

function %icmp_ugt_i32x4(i32x4, i32x4) -> b32x4 {
block0(v0: i32x4, v1: i32x4):
    v2 = icmp ugt v0, v1
    return v2
}

; block0:
;   cmhi v0.4s, v0.4s, v1.4s
;   ret

function %icmp_sge_i16x8(i16x8, i16x8) -> b16x8 {
block0(v0: i16x8, v1: i16x8):
    v2 = icmp sge v0, v1
    return v2
}

; block0:
;   cmge v0.8h, v0.8h, v1.8h
;   ret

function %icmp_uge_i8x16(i8x16, i8x16) -> b8x16 {
block0(v0: i8x16, v1: i8x16):
    v2 = icmp uge v0, v1
    return v2
}

; block0:
;   cmhs v0.16b, v0.16b, v1.16b
;   ret

