test compile precise-output
target aarch64

function %store_i8x2(i8x2, i64) {
block0(v0: i8x2, v1: i64):
    store.i8x2 v0, v1
    return
}

; VCode:
; block0:
;   str h0, [x0]
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   str h0, [x0] ; trap: heap_oob
;   ret

function %store_i16x2(i16x2, i64) {
block0(v0: i16x2, v1: i64):
    store.i16x2 v0, v1
    return
}

; VCode:
; block0:
;   str s0, [x0]
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   str s0, [x0] ; trap: heap_oob
;   ret

function %store_i32x2(i32x2, i64) {
block0(v0: i32x2, v1: i64):
    store.i32x2 v0, v1
    return
}

; VCode:
; block0:
;   str d0, [x0]
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   str d0, [x0] ; trap: heap_oob
;   ret

