test compile precise-output
set tls_model=elf_gd
target aarch64

function u0:0(i32) -> i32, i64 {
gv0 = symbol colocated tls u1:0

block0(v0: i32):
    v1 = tls_value.i64 gv0
    return v0, v1
}

; VCode:
;   stp fp, lr, [sp, #-16]!
;   mov fp, sp
; block0:
;   mov x6, x0
;   elf_tls_get_addr x0, x3, userextname0
;   mov x1, x0
;   mov x0, x6
;   ldp fp, lr, [sp], #16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   stp x29, x30, [sp, #-0x10]!
;   mov x29, sp
; block1: ; offset 0x8
;   mov x6, x0
;   adrp x0, #0 ; reloc_external Aarch64TlsDescAdrPage21 u1:0 0
;   ldr x3, [x0] ; reloc_external Aarch64TlsDescLd64Lo12 u1:0 0
;   add x0, x0, #0 ; reloc_external Aarch64TlsDescAddLo12 u1:0 0
;   blr x3 ; reloc_external Aarch64TlsDescCall u1:0 0
;   mrs x3, tpidr_el0
;   add x0, x0, x3
;   mov x1, x0
;   mov x0, x6
;   ldp x29, x30, [sp], #0x10
;   ret

