test compile precise-output
set unwind_info=false
set enable_probestack=false
target aarch64

function %foo() system_v {
    ss0 = explicit_slot 12, align = 4
    sig0 = (i32) system_v
    fn0 = colocated u0:0 sig0

block0:
    v0 = iconst.i32 0
    v1 = iconst.i32 1
    v2 = iconst.i32 2
    v3 = iconst.i32 3

    v4 = stack_addr.i64 ss0
    store notrap v0, v4
    v5 = stack_addr.i64 ss0+4
    store notrap v1, v5
    v6 = stack_addr.i64 ss0+8
    store notrap v2, v6
    call fn0(v0), stack_map=[i32 @ ss0+0, i32 @ ss0+4, i32 @ ss0+8]

    v7 = stack_addr.i64 ss0
    store notrap v1, v7
    v8 = stack_addr.i64 ss0+4
    store notrap v2, v8
    call fn0(v0), stack_map=[i32 @ ss0+0, i32 @ ss0+4]

    v9 = stack_addr.i64 ss0
    store notrap v2, v9
    call fn0(v1), stack_map=[i32 @ ss0+0]

    call fn0(v2)

    return
}

; VCode:
;   stp fp, lr, [sp, #-16]!
;   mov fp, sp
;   str x21, [sp, #-16]!
;   stp x19, x20, [sp, #-16]!
;   sub sp, sp, #16
; block0:
;   movz w21, #0
;   movz w19, #1
;   movz w20, #2
;   str w21, [sp]
;   str w19, [sp, #4]
;   str w20, [sp, #8]
;   mov x0, x21
;   bl 0
;   ; UserStackMap { by_type: [(types::I32, CompoundBitSet {0, 4, 8})], sp_to_sized_stack_slots: None }
;   str w19, [sp]
;   str w20, [sp, #4]
;   mov x0, x21
;   bl 0
;   ; UserStackMap { by_type: [(types::I32, CompoundBitSet {0, 4})], sp_to_sized_stack_slots: None }
;   str w20, [sp]
;   mov x0, x19
;   bl 0
;   ; UserStackMap { by_type: [(types::I32, CompoundBitSet {0})], sp_to_sized_stack_slots: None }
;   mov x0, x20
;   bl 0
;   add sp, sp, #16
;   ldp x19, x20, [sp], #16
;   ldr x21, [sp], #16
;   ldp fp, lr, [sp], #16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   stp x29, x30, [sp, #-0x10]!
;   mov x29, sp
;   str x21, [sp, #-0x10]!
;   stp x19, x20, [sp, #-0x10]!
;   sub sp, sp, #0x10
; block1: ; offset 0x14
;   mov w21, #0
;   mov w19, #1
;   mov w20, #2
;   stur w21, [sp]
;   stur w19, [sp, #4]
;   stur w20, [sp, #8]
;   mov x0, x21
;   bl #0x30 ; reloc_external Call u0:0 0
;   stur w19, [sp]
;   stur w20, [sp, #4]
;   mov x0, x21
;   bl #0x40 ; reloc_external Call u0:0 0
;   stur w20, [sp]
;   mov x0, x19
;   bl #0x4c ; reloc_external Call u0:0 0
;   mov x0, x20
;   bl #0x54 ; reloc_external Call u0:0 0
;   add sp, sp, #0x10
;   ldp x19, x20, [sp], #0x10
;   ldr x21, [sp], #0x10
;   ldp x29, x30, [sp], #0x10
;   ret

function %different_types(i8, i16, i32, i64, f32, f64) -> i8, i16, i32, i64, f32, f64 {
    ss0 = explicit_slot 1
    ss1 = explicit_slot 2, align = 2
    ss2 = explicit_slot 8, align = 4
    ss3 = explicit_slot 16, align = 8
    ss4 = explicit_slot 48, align = 16
    sig0 = () system_v
    fn0 = colocated u0:0 sig0

block0(v0: i8, v1: i16, v2: i32, v3: i64, v4: f32, v5: f64):
    v6 = stack_addr.i64 ss0
    store notrap v0, v6
    v7 = stack_addr.i64 ss1
    store notrap v1, v7
    v8 = stack_addr.i64 ss2
    store notrap v2, v8
    v9 = stack_addr.i64 ss2+4
    store notrap v4, v9
    v10 = stack_addr.i64 ss3
    store notrap v3, v10
    v11 = stack_addr.i64 ss3+8
    store notrap v5, v11
    call fn0(), stack_map=[i8 @ ss0+0, i16 @ ss1+0, i32 @ ss2+0, f32 @ ss2+4, i64 @ ss3+0, f64 @ ss3+8]
    return v0, v1, v2, v3, v4, v5
}

; VCode:
;   stp fp, lr, [sp, #-16]!
;   mov fp, sp
;   stp x21, x23, [sp, #-16]!
;   stp x19, x20, [sp, #-16]!
;   sub sp, sp, #128
; block0:
;   strb w0, [sp]
;   mov x23, x0
;   strh w1, [sp, #8]
;   mov x21, x1
;   str w2, [sp, #16]
;   mov x20, x2
;   str s0, [sp, #20]
;   str q0, [sp, #96]
;   str x3, [sp, #24]
;   mov x19, x3
;   str d1, [sp, #32]
;   str q1, [sp, #112]
;   bl 0
;   ; UserStackMap { by_type: [(types::I8, CompoundBitSet {0}), (types::I16, CompoundBitSet {8}), (types::I32, CompoundBitSet {16}), (types::F32, CompoundBitSet {20}), (types::I64, CompoundBitSet {24}), (types::F64, CompoundBitSet {32})], sp_to_sized_stack_slots: None }
;   mov x0, x23
;   mov x1, x21
;   mov x2, x20
;   mov x3, x19
;   ldr q0, [sp, #96]
;   ldr q1, [sp, #112]
;   add sp, sp, #128
;   ldp x19, x20, [sp], #16
;   ldp x21, x23, [sp], #16
;   ldp fp, lr, [sp], #16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   stp x29, x30, [sp, #-0x10]!
;   mov x29, sp
;   stp x21, x23, [sp, #-0x10]!
;   stp x19, x20, [sp, #-0x10]!
;   sub sp, sp, #0x80
; block1: ; offset 0x14
;   sturb w0, [sp]
;   mov x23, x0
;   sturh w1, [sp, #8]
;   mov x21, x1
;   stur w2, [sp, #0x10]
;   mov x20, x2
;   stur s0, [sp, #0x14]
;   stur q0, [sp, #0x60]
;   stur x3, [sp, #0x18]
;   mov x19, x3
;   stur d1, [sp, #0x20]
;   stur q1, [sp, #0x70]
;   bl #0x44 ; reloc_external Call u0:0 0
;   mov x0, x23
;   mov x1, x21
;   mov x2, x20
;   mov x3, x19
;   ldur q0, [sp, #0x60]
;   ldur q1, [sp, #0x70]
;   add sp, sp, #0x80
;   ldp x19, x20, [sp], #0x10
;   ldp x21, x23, [sp], #0x10
;   ldp x29, x30, [sp], #0x10
;   ret

