;;! target = "s390x"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation=false -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load8_u offset=0))

;; wasm[0]::function[0]:
;;    0: stmg    %r14, %r15, 0x70(%r15)
;;    6: lgr     %r1, %r15
;;    a: aghi    %r15, -0xa0
;;    e: stg     %r1, 0(%r15)
;;   14: lgr     %r3, %r4
;;   18: lg      %r4, 0x58(%r2)
;;   1e: llgfr   %r3, %r3
;;   22: clgr    %r3, %r4
;;   26: jghe    0x3e
;;   2c: lg      %r4, 0x50(%r2)
;;   32: stc     %r5, 0(%r3, %r4)
;;   36: lmg     %r14, %r15, 0x110(%r15)
;;   3c: br      %r14
;;   3e: .byte   0x00, 0x00
;;
;; wasm[0]::function[1]:
;;   40: stmg    %r14, %r15, 0x70(%r15)
;;   46: lgr     %r1, %r15
;;   4a: aghi    %r15, -0xa0
;;   4e: stg     %r1, 0(%r15)
;;   54: lg      %r3, 0x58(%r2)
;;   5a: llgfr   %r5, %r4
;;   5e: clgr    %r5, %r3
;;   62: jghe    0x7c
;;   68: lg      %r3, 0x50(%r2)
;;   6e: llc     %r2, 0(%r5, %r3)
;;   74: lmg     %r14, %r15, 0x110(%r15)
;;   7a: br      %r14
;;   7c: .byte   0x00, 0x00
