;;! target = "s390x"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation=false -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0xffff0000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0xffff0000))

;; wasm[0]::function[0]:
;;       stmg    %r12, %r15, 0x60(%r15)
;;       lgr     %r1, %r15
;;       aghi    %r15, -0xa0
;;       stg     %r1, 0(%r15)
;;       llgfr   %r12, %r4
;;       llilf   %r3, 0xffff0004
;;       algfr   %r3, %r4
;;       jgnle   0x24
;;       lg      %r4, 0x58(%r2)
;;       clgr    %r3, %r4
;;       jgh     0x50
;;       ag      %r12, 0x50(%r2)
;;       llilh   %r3, 0xffff
;;       strv    %r5, 0(%r3, %r12)
;;       lmg     %r12, %r15, 0x100(%r15)
;;       br      %r14
;;       .byte   0x00, 0x00
;;
;; wasm[0]::function[1]:
;;       stmg    %r14, %r15, 0x70(%r15)
;;       lgr     %r1, %r15
;;       aghi    %r15, -0xa0
;;       stg     %r1, 0(%r15)
;;       llgfr   %r5, %r4
;;       llilf   %r3, 0xffff0004
;;       algfr   %r3, %r4
;;       jgnle   0x78
;;       lg      %r4, 0x58(%r2)
;;       clgr    %r3, %r4
;;       jgh     0xa4
;;       ag      %r5, 0x50(%r2)
;;       llilh   %r3, 0xffff
;;       lrv     %r2, 0(%r3, %r5)
;;       lmg     %r14, %r15, 0x110(%r15)
;;       br      %r14
;;       .byte   0x00, 0x00
