;;! target = "s390x"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -W memory64 -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0x1000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load8_u offset=0x1000))

;; wasm[0]::function[0]:
;;       lg      %r1, 8(%r2)
;;       lg      %r1, 0x10(%r1)
;;       la      %r1, 0xa0(%r1)
;;       clgrtle %r15, %r1
;;       stmg    %r14, %r15, 0x70(%r15)
;;       lgr     %r1, %r15
;;       aghi    %r15, -0xa0
;;       stg     %r1, 0(%r15)
;;       lg      %r6, 0x58(%r2)
;;       aghik   %r7, %r6, -0x1001
;;       lghi    %r6, 0
;;       lgr     %r3, %r4
;;       ag      %r3, 0x50(%r2)
;;       aghik   %r2, %r3, 0x1000
;;       clgr    %r4, %r7
;;       locgrh  %r2, %r6
;;       stc     %r5, 0(%r2)
;;       lmg     %r14, %r15, 0x110(%r15)
;;       br      %r14
;;
;; wasm[0]::function[1]:
;;       lg      %r1, 8(%r2)
;;       lg      %r1, 0x10(%r1)
;;       la      %r1, 0xa0(%r1)
;;       clgrtle %r15, %r1
;;       stmg    %r14, %r15, 0x70(%r15)
;;       lgr     %r1, %r15
;;       aghi    %r15, -0xa0
;;       stg     %r1, 0(%r15)
;;       lg      %r5, 0x58(%r2)
;;       aghik   %r6, %r5, -0x1001
;;       lghi    %r5, 0
;;       lgr     %r7, %r4
;;       ag      %r7, 0x50(%r2)
;;       aghi    %r7, 0x1000
;;       clgr    %r4, %r6
;;       locgrh  %r7, %r5
;;       llc     %r2, 0(%r7)
;;       lmg     %r14, %r15, 0x110(%r15)
;;       br      %r14
