;;! target = "s390x"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -W memory64 -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store offset=0)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load offset=0))

;; wasm[0]::function[0]:
;;       lg      %r1, 8(%r2)
;;       lg      %r1, 0(%r1)
;;       la      %r1, 0xa0(%r1)
;;       clgrtle %r15, %r1
;;       stmg    %r13, %r15, 0x68(%r15)
;;       lgr     %r1, %r15
;;       aghi    %r15, -0xa0
;;       stg     %r1, 0(%r15)
;;       lg      %r3, 0x68(%r2)
;;       aghik   %r14, %r3, -4
;;       lghi    %r3, 0
;;       lgr     %r13, %r4
;;       ag      %r13, 0x60(%r2)
;;       clgr    %r4, %r14
;;       locgrh  %r13, %r3
;;       strv    %r5, 0(%r13)
;;       lmg     %r13, %r15, 0x108(%r15)
;;       br      %r14
;;
;; wasm[0]::function[1]:
;;       lg      %r1, 8(%r2)
;;       lg      %r1, 0(%r1)
;;       la      %r1, 0xa0(%r1)
;;       clgrtle %r15, %r1
;;       stmg    %r13, %r15, 0x68(%r15)
;;       lgr     %r1, %r15
;;       aghi    %r15, -0xa0
;;       stg     %r1, 0(%r15)
;;       lg      %r3, 0x68(%r2)
;;       aghik   %r5, %r3, -4
;;       lghi    %r3, 0
;;       lgr     %r13, %r4
;;       ag      %r13, 0x60(%r2)
;;       clgr    %r4, %r5
;;       locgrh  %r13, %r3
;;       lrv     %r2, 0(%r13)
;;       lmg     %r13, %r15, 0x108(%r15)
;;       br      %r14
