;;! target = "s390x"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -W memory64 -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0xffff0000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load8_u offset=0xffff0000))

;; wasm[0]::function[0]:
;;       lg      %r1, 8(%r2)
;;       lg      %r1, 0(%r1)
;;       la      %r1, 0xa0(%r1)
;;       clgrtle %r15, %r1
;;       stmg    %r7, %r15, 0x38(%r15)
;;       lgr     %r1, %r15
;;       aghi    %r15, -0xa0
;;       stg     %r1, 0(%r15)
;;       lgr     %r7, %r4
;;       algfi   %r7, 0xffff0001
;;       jgnle   0x34
;;       lg      %r8, 0x68(%r2)
;;       lghi    %r3, 0
;;       ag      %r4, 0x60(%r2)
;;       llilh   %r2, 0xffff
;;       agr     %r4, %r2
;;       clgr    %r7, %r8
;;       locgrh  %r4, %r3
;;       stc     %r5, 0(%r4)
;;       lmg     %r7, %r15, 0xd8(%r15)
;;       br      %r14
;;
;; wasm[0]::function[1]:
;;       lg      %r1, 8(%r2)
;;       lg      %r1, 0(%r1)
;;       la      %r1, 0xa0(%r1)
;;       clgrtle %r15, %r1
;;       stmg    %r9, %r15, 0x48(%r15)
;;       lgr     %r1, %r15
;;       aghi    %r15, -0xa0
;;       stg     %r1, 0(%r15)
;;       lgr     %r5, %r4
;;       algfi   %r5, 0xffff0001
;;       jgnle   0x98
;;       lg      %r9, 0x68(%r2)
;;       lghi    %r3, 0
;;       ag      %r4, 0x60(%r2)
;;       llilh   %r2, 0xffff
;;       agrk    %r2, %r4, %r2
;;       clgr    %r5, %r9
;;       locgrh  %r2, %r3
;;       llc     %r3, 0(%r2)
;;       llcr    %r2, %r3
;;       lmg     %r9, %r15, 0xe8(%r15)
;;       br      %r14
