;;! target = "s390x"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0xffff0000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load8_u offset=0xffff0000))

;; wasm[0]::function[0]:
;;       lg      %r1, 8(%r2)
;;       lg      %r1, 0x18(%r1)
;;       la      %r1, 0xa0(%r1)
;;       clgrtle %r15, %r1
;;       stmg    %r14, %r15, 0x70(%r15)
;;       lgr     %r1, %r15
;;       aghi    %r15, -0xa0
;;       stg     %r1, 0(%r15)
;;       lgr     %r3, %r2
;;       llgfr   %r7, %r4
;;       llilf   %r2, 0xffff0001
;;       algfr   %r2, %r4
;;       jgnle   0x3c
;;       lgr     %r6, %r3
;;       lg      %r4, 0x40(%r6)
;;       lghi    %r3, 0
;;       ag      %r7, 0x38(%r6)
;;       llilh   %r6, 0xffff
;;       agrk    %r6, %r7, %r6
;;       clgr    %r2, %r4
;;       locgrh  %r6, %r3
;;       stc     %r5, 0(%r6)
;;       lmg     %r14, %r15, 0x110(%r15)
;;       br      %r14
;;
;; wasm[0]::function[1]:
;;       lg      %r1, 8(%r2)
;;       lg      %r1, 0x18(%r1)
;;       la      %r1, 0xa0(%r1)
;;       clgrtle %r15, %r1
;;       stmg    %r14, %r15, 0x70(%r15)
;;       lgr     %r1, %r15
;;       aghi    %r15, -0xa0
;;       stg     %r1, 0(%r15)
;;       lgr     %r3, %r2
;;       llgfr   %r7, %r4
;;       llilf   %r2, 0xffff0001
;;       algfr   %r2, %r4
;;       jgnle   0xac
;;       lgr     %r5, %r3
;;       lg      %r4, 0x40(%r5)
;;       lghi    %r3, 0
;;       ag      %r7, 0x38(%r5)
;;       llilh   %r5, 0xffff
;;       agrk    %r5, %r7, %r5
;;       clgr    %r2, %r4
;;       locgrh  %r5, %r3
;;       llc     %r2, 0(%r5)
;;       lmg     %r14, %r15, 0x110(%r15)
;;       br      %r14
