;;! target = "s390x"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -W memory64 -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store offset=0)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load offset=0))

;; wasm[0]::function[0]:
;;    0: stmg    %r6, %r15, 0x30(%r15)
;;    6: lgr     %r1, %r15
;;    a: aghi    %r15, -0xa0
;;    e: stg     %r1, 0(%r15)
;;   14: lg      %r3, 0x58(%r2)
;;   1a: aghik   %r6, %r3, -4
;;   20: lghi    %r3, 0
;;   24: lgr     %r14, %r4
;;   28: ag      %r14, 0x50(%r2)
;;   2e: clgr    %r4, %r6
;;   32: locgrh  %r14, %r3
;;   36: strv    %r5, 0(%r14)
;;   3c: lmg     %r6, %r15, 0xd0(%r15)
;;   42: br      %r14
;;
;; wasm[0]::function[1]:
;;   44: stmg    %r14, %r15, 0x70(%r15)
;;   4a: lgr     %r1, %r15
;;   4e: aghi    %r15, -0xa0
;;   52: stg     %r1, 0(%r15)
;;   58: lg      %r3, 0x58(%r2)
;;   5e: aghik   %r5, %r3, -4
;;   64: lghi    %r3, 0
;;   68: lgr     %r14, %r4
;;   6c: ag      %r14, 0x50(%r2)
;;   72: clgr    %r4, %r5
;;   76: locgrh  %r14, %r3
;;   7a: lrv     %r2, 0(%r14)
;;   80: lmg     %r14, %r15, 0x110(%r15)
;;   86: br      %r14
