default world test-reactor {

//  import environment: wasi.environment
//  import streams: io.streams

  export add-strings: func(s: list<string>) -> u32
  export get-strings: func() -> list<string>
}
