test inline precise-output
target x86_64

;; The callee uses `notrap aligned` (same as caller) and also `notrap aligned
;; readonly` (not used by caller). After inlining, the caller should define and
;; use both MemFlagsData.

function %callee(i64) -> i32 {
block0(v0: i64):
    ;; notrap aligned
    v1 = load.i32 notrap aligned v0
    ;; notrap aligned readonly
    v2 = load.i32 notrap aligned readonly v0+4
    v3 = iadd v1, v2
    return v3
}

; (no functions inlined into %callee)

function %caller(i64) -> i32 {
    fn0 = %callee(i64) -> i32
block0(v0: i64):
    ;; notrap aligned (same flags as callee's first load)
    v1 = load.i32 notrap aligned v0
    v2 = call fn0(v0)
    v3 = iadd v1, v2
    return v3
}

; function %caller(i64) -> i32 fast {
;     sig0 = (i64) -> i32 fast
;     fn0 = %callee sig0
;
; block0(v0: i64):
;     v1 = load.i32 notrap aligned v0
;     jump block1
;
; block1:
;     v5 = load.i32 notrap aligned v0
;     v6 = load.i32 notrap aligned readonly v0+4
;     v7 = iadd v5, v6
;     jump block2(v7)
;
; block2(v4: i32):
;     v2 -> v4
;     v3 = iadd.i32 v1, v2
;     return v3
; }

