;; Test that `ir::Constant`s, used by `vconst` and others, are properly inlined.

test inline precise-output
target x86_64

function %f0(i32x4) -> i32x4 {
block0(v0: i32x4):
    v1 = vconst.i32x4 0x01
    v2 = iadd v0, v1
    return v2
}

; (no functions inlined into %f0)

function %f1() -> i32x4 {
    fn0 = %f0(i32x4) -> i32x4
block0():
    v0 = vconst.i32x4 0x02
    v1 = call fn0(v0)
    return v1
}

; function %f1() -> i32x4 fast {
;     sig0 = (i32x4) -> i32x4 fast
;     fn0 = %f0 sig0
;     const0 = 0x00000000000000000000000000000002
;     const1 = 0x00000000000000000000000000000001
;
; block0:
;     v0 = vconst.i32x4 const0
;     jump block1
;
; block1:
;     v3 = vconst.i32x4 const1
;     v4 = iadd.i32x4 v0, v3  ; v0 = const0, v3 = const1
;     jump block2(v4)
;
; block2(v2: i32x4):
;     v1 -> v2
;     return v1
; }
