# Documentation for this configuration file can be found here
# https://embarkstudios.github.io/cargo-deny/checks/cfg.html

[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "aarch64-linux-android" },
]

# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[licenses]
allow = [
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Zlib",
    "Unicode-3.0",
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

# https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html
[bans]
multiple-versions = "deny"
wildcards = "allow"
deny = []
skip = [
    { name = "cpufeatures", reason = "requires an update to `sha2` which pulls in a lot of other dependencies which doesn't seem worth it" },
    { name = "hashbrown", reason = "waiting on lots of crates to update" },
    { name = "gimli", reason = "waiting on a few crates to update" },
    { name = "linux-raw-sys", reason = "waiting on `system-interface` to update" },
    { name = "rustix", reason = "waiting on `system-interface` to update" },
]
skip-tree = [
    { name = "rand", reason = "waiting on `proptest` to update" },
    { name = "witx", depth = 20, reason = "dep will never update again" },
    { name = "file-per-thread-logger", reason = "unmaintained dep not updating" },
    { name = "region", reason = "unmaintained dep not updating" },
]
