;;! target = "x86_64"
;;! test = "clif"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -W memory64 -O static-memory-forced -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store offset=0)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load offset=0))

;; function u0:0(i64 vmctx, i64, i64, i32) tail {
;;     region0 = 8 "VMContext+0x8"
;;     region1 = 805306368 "DefinedMemory(StaticModuleIndex(0), DefinedMemoryIndex(0))"
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly can_move region0 gv0+8
;;     gv2 = load.i64 notrap aligned gv1+24
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64, v2: i64, v3: i32):
;; @0040                               v4 = iconst.i64 0xffff_fffc
;; @0040                               v5 = icmp ugt v2, v4  ; v4 = 0xffff_fffc
;; @0040                               v6 = load.i64 notrap aligned readonly can_move v0+56
;; @0040                               v7 = iadd v6, v2
;; @0040                               v8 = iconst.i64 0
;; @0040                               v9 = select_spectre_guard v5, v8, v7  ; v8 = 0
;; @0040                               store little region1 v3, v9
;; @0043                               jump block1
;;
;;                                 block1:
;; @0043                               return
;; }
;;
;; function u0:1(i64 vmctx, i64, i64) -> i32 tail {
;;     region0 = 8 "VMContext+0x8"
;;     region1 = 805306368 "DefinedMemory(StaticModuleIndex(0), DefinedMemoryIndex(0))"
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly can_move region0 gv0+8
;;     gv2 = load.i64 notrap aligned gv1+24
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64, v2: i64):
;; @0048                               v4 = iconst.i64 0xffff_fffc
;; @0048                               v5 = icmp ugt v2, v4  ; v4 = 0xffff_fffc
;; @0048                               v6 = load.i64 notrap aligned readonly can_move v0+56
;; @0048                               v7 = iadd v6, v2
;; @0048                               v8 = iconst.i64 0
;; @0048                               v9 = select_spectre_guard v5, v8, v7  ; v8 = 0
;; @0048                               v10 = load.i32 little region1 v9
;; @004b                               jump block1
;;
;;                                 block1:
;; @004b                               return v10
;; }
