;;! target = "x86_64"
;;! test = "clif"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -W memory64 -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store offset=0x1000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load offset=0x1000))

;; function u0:0(i64 vmctx, i64, i64, i32) tail {
;;     region0 = 8 "VMContext+0x8"
;;     region1 = 134217752 "VMStoreContext+0x18"
;;     region2 = 1207959552 "VMMemoryDefinition+0x0"
;;     region3 = 1207959560 "VMMemoryDefinition+0x8"
;;     region4 = 402653184 "DefinedMemory(StaticModuleIndex(0), DefinedMemoryIndex(0))"
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly can_move region0 gv0+8
;;     gv2 = load.i64 notrap aligned region1 gv1+24
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64, v2: i64, v3: i32):
;; @0040                               v4 = load.i64 notrap aligned region3 v0+64
;; @0040                               v5 = iconst.i64 4100
;; @0040                               v6 = isub v4, v5  ; v5 = 4100
;; @0040                               v7 = icmp ugt v2, v6
;; @0040                               v8 = load.i64 notrap aligned can_move region2 v0+56
;; @0040                               v9 = iadd v8, v2
;; @0040                               v10 = iconst.i64 4096
;; @0040                               v11 = iadd v9, v10  ; v10 = 4096
;; @0040                               v12 = iconst.i64 0
;; @0040                               v13 = select_spectre_guard v7, v12, v11  ; v12 = 0
;; @0040                               store little region4 v3, v13
;; @0044                               jump block1
;;
;;                                 block1:
;; @0044                               return
;; }
;;
;; function u0:1(i64 vmctx, i64, i64) -> i32 tail {
;;     region0 = 8 "VMContext+0x8"
;;     region1 = 134217752 "VMStoreContext+0x18"
;;     region2 = 1207959552 "VMMemoryDefinition+0x0"
;;     region3 = 1207959560 "VMMemoryDefinition+0x8"
;;     region4 = 402653184 "DefinedMemory(StaticModuleIndex(0), DefinedMemoryIndex(0))"
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly can_move region0 gv0+8
;;     gv2 = load.i64 notrap aligned region1 gv1+24
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64, v2: i64):
;; @0049                               v3 = load.i64 notrap aligned region3 v0+64
;; @0049                               v4 = iconst.i64 4100
;; @0049                               v5 = isub v3, v4  ; v4 = 4100
;; @0049                               v6 = icmp ugt v2, v5
;; @0049                               v7 = load.i64 notrap aligned can_move region2 v0+56
;; @0049                               v8 = iadd v7, v2
;; @0049                               v9 = iconst.i64 4096
;; @0049                               v10 = iadd v8, v9  ; v9 = 4096
;; @0049                               v11 = iconst.i64 0
;; @0049                               v12 = select_spectre_guard v6, v11, v10  ; v11 = 0
;; @0049                               v13 = load.i32 little region4 v12
;; @004d                               jump block1
;;
;;                                 block1:
;; @004d                               return v13
;; }
