;;! target = "x86_64"
;;! test = "clif"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation=false -W memory64 -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store offset=0xffff0000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load offset=0xffff0000))

;; function u0:0(i64 vmctx, i64, i64, i32) tail {
;;     region0 = 8 "VMContext+0x8"
;;     region1 = 268435480 "VMStoreContext+0x18"
;;     region2 = 2415919104 "VMMemoryDefinition+0x0"
;;     region3 = 2415919112 "VMMemoryDefinition+0x8"
;;     region4 = 805306368 "DefinedMemory(StaticModuleIndex(0), DefinedMemoryIndex(0))"
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly can_move region0 gv0+8
;;     gv2 = load.i64 notrap aligned region1 gv1+24
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64, v2: i64, v3: i32):
;; @0040                               v4 = iconst.i64 0xffff_0004
;; @0040                               v5 = uadd_overflow_trap v2, v4, heap_oob  ; v4 = 0xffff_0004
;; @0040                               v6 = load.i64 notrap aligned region3 v0+64
;; @0040                               v7 = icmp ugt v5, v6
;; @0040                               trapnz v7, heap_oob
;; @0040                               v8 = load.i64 notrap aligned can_move region2 v0+56
;; @0040                               v9 = iadd v8, v2
;; @0040                               v10 = iconst.i64 0xffff_0000
;; @0040                               v11 = iadd v9, v10  ; v10 = 0xffff_0000
;; @0040                               store little region4 v3, v11
;; @0047                               jump block1
;;
;;                                 block1:
;; @0047                               return
;; }
;;
;; function u0:1(i64 vmctx, i64, i64) -> i32 tail {
;;     region0 = 8 "VMContext+0x8"
;;     region1 = 268435480 "VMStoreContext+0x18"
;;     region2 = 2415919104 "VMMemoryDefinition+0x0"
;;     region3 = 2415919112 "VMMemoryDefinition+0x8"
;;     region4 = 805306368 "DefinedMemory(StaticModuleIndex(0), DefinedMemoryIndex(0))"
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly can_move region0 gv0+8
;;     gv2 = load.i64 notrap aligned region1 gv1+24
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64, v2: i64):
;; @004c                               v3 = iconst.i64 0xffff_0004
;; @004c                               v4 = uadd_overflow_trap v2, v3, heap_oob  ; v3 = 0xffff_0004
;; @004c                               v5 = load.i64 notrap aligned region3 v0+64
;; @004c                               v6 = icmp ugt v4, v5
;; @004c                               trapnz v6, heap_oob
;; @004c                               v7 = load.i64 notrap aligned can_move region2 v0+56
;; @004c                               v8 = iadd v7, v2
;; @004c                               v9 = iconst.i64 0xffff_0000
;; @004c                               v10 = iadd v8, v9  ; v9 = 0xffff_0000
;; @004c                               v11 = load.i32 little region4 v10
;; @0053                               jump block1
;;
;;                                 block1:
;; @0053                               return v11
;; }
