;;! target = "x86_64"
;;! test = "clif"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0xffff0000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0xffff0000))

;; function u0:0(i64 vmctx, i64, i32, i32) tail {
;;     region0 = 8 "VMContext+0x8"
;;     region1 = 268435480 "VMStoreContext+0x18"
;;     region2 = 805306368 "DefinedMemory(StaticModuleIndex(0), DefinedMemoryIndex(0))"
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly can_move region0 gv0+8
;;     gv2 = load.i64 notrap aligned region1 gv1+24
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64, v2: i32, v3: i32):
;; @0040                               v4 = uextend.i64 v2
;; @0040                               v5 = iconst.i64 0xffff_0004
;; @0040                               v6 = uadd_overflow_trap v4, v5, heap_oob  ; v5 = 0xffff_0004
;; @0040                               v7 = load.i64 notrap aligned v0+64
;; @0040                               v8 = icmp ugt v6, v7
;; @0040                               v9 = load.i64 notrap aligned can_move v0+56
;; @0040                               v10 = iadd v9, v4
;; @0040                               v11 = iconst.i64 0xffff_0000
;; @0040                               v12 = iadd v10, v11  ; v11 = 0xffff_0000
;; @0040                               v13 = iconst.i64 0
;; @0040                               v14 = select_spectre_guard v8, v13, v12  ; v13 = 0
;; @0040                               store little region2 v3, v14
;; @0047                               jump block1
;;
;;                                 block1:
;; @0047                               return
;; }
;;
;; function u0:1(i64 vmctx, i64, i32) -> i32 tail {
;;     region0 = 8 "VMContext+0x8"
;;     region1 = 268435480 "VMStoreContext+0x18"
;;     region2 = 805306368 "DefinedMemory(StaticModuleIndex(0), DefinedMemoryIndex(0))"
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly can_move region0 gv0+8
;;     gv2 = load.i64 notrap aligned region1 gv1+24
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64, v2: i32):
;; @004c                               v4 = uextend.i64 v2
;; @004c                               v5 = iconst.i64 0xffff_0004
;; @004c                               v6 = uadd_overflow_trap v4, v5, heap_oob  ; v5 = 0xffff_0004
;; @004c                               v7 = load.i64 notrap aligned v0+64
;; @004c                               v8 = icmp ugt v6, v7
;; @004c                               v9 = load.i64 notrap aligned can_move v0+56
;; @004c                               v10 = iadd v9, v4
;; @004c                               v11 = iconst.i64 0xffff_0000
;; @004c                               v12 = iadd v10, v11  ; v11 = 0xffff_0000
;; @004c                               v13 = iconst.i64 0
;; @004c                               v14 = select_spectre_guard v8, v13, v12  ; v13 = 0
;; @004c                               v15 = load.i32 little region2 v14
;; @0053                               jump block1
;;
;;                                 block1:
;; @0053                               return v15
;; }
