;;! target = "x86_64"
;;! test = "clif"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0))

;; function u0:0(i64 vmctx, i64, i32, i32) tail {
;;     region0 = 8 "VMContext+0x8"
;;     region1 = 268435480 "VMStoreContext+0x18"
;;     region2 = 2415919104 "VMMemoryDefinition+0x0"
;;     region3 = 2415919112 "VMMemoryDefinition+0x8"
;;     region4 = 805306368 "DefinedMemory(StaticModuleIndex(0), DefinedMemoryIndex(0))"
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly can_move region0 gv0+8
;;     gv2 = load.i64 notrap aligned region1 gv1+24
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64, v2: i32, v3: i32):
;; @0040                               v4 = uextend.i64 v2
;; @0040                               v5 = load.i64 notrap aligned region3 v0+64
;; @0040                               v6 = iconst.i64 4
;; @0040                               v7 = isub v5, v6  ; v6 = 4
;; @0040                               v8 = icmp ugt v4, v7
;; @0040                               v9 = load.i64 notrap aligned can_move region2 v0+56
;; @0040                               v10 = iadd v9, v4
;; @0040                               v11 = iconst.i64 0
;; @0040                               v12 = select_spectre_guard v8, v11, v10  ; v11 = 0
;; @0040                               store little region4 v3, v12
;; @0043                               jump block1
;;
;;                                 block1:
;; @0043                               return
;; }
;;
;; function u0:1(i64 vmctx, i64, i32) -> i32 tail {
;;     region0 = 8 "VMContext+0x8"
;;     region1 = 268435480 "VMStoreContext+0x18"
;;     region2 = 2415919104 "VMMemoryDefinition+0x0"
;;     region3 = 2415919112 "VMMemoryDefinition+0x8"
;;     region4 = 805306368 "DefinedMemory(StaticModuleIndex(0), DefinedMemoryIndex(0))"
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly can_move region0 gv0+8
;;     gv2 = load.i64 notrap aligned region1 gv1+24
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64, v2: i32):
;; @0048                               v3 = uextend.i64 v2
;; @0048                               v4 = load.i64 notrap aligned region3 v0+64
;; @0048                               v5 = iconst.i64 4
;; @0048                               v6 = isub v4, v5  ; v5 = 4
;; @0048                               v7 = icmp ugt v3, v6
;; @0048                               v8 = load.i64 notrap aligned can_move region2 v0+56
;; @0048                               v9 = iadd v8, v3
;; @0048                               v10 = iconst.i64 0
;; @0048                               v11 = select_spectre_guard v7, v10, v9  ; v10 = 0
;; @0048                               v12 = load.i32 little region4 v11
;; @004b                               jump block1
;;
;;                                 block1:
;; @004b                               return v12
;; }
