;;! target = "x86_64"

(module
    (func (param i64) (result f32)
        (local.get 0)
        (f32.convert_i64_u)
    )
)
;;      	 55                   	push	rbp
;;      	 4889e5               	mov	rbp, rsp
;;      	 4d8b5e08             	mov	r11, qword ptr [r14 + 8]
;;      	 4d8b1b               	mov	r11, qword ptr [r11]
;;      	 4981c310000000       	add	r11, 0x10
;;      	 4939e3               	cmp	r11, rsp
;;      	 0f8746000000         	ja	0x61
;;   1b:	 4883ec10             	sub	rsp, 0x10
;;      	 48897c2408           	mov	qword ptr [rsp + 8], rdi
;;      	 4c893424             	mov	qword ptr [rsp], r14
;;      	 488b4c2408           	mov	rcx, qword ptr [rsp + 8]
;;      	 4883f900             	cmp	rcx, 0
;;      	 0f8c0a000000         	jl	0x41
;;   37:	 f3480f2ac1           	cvtsi2ss	xmm0, rcx
;;      	 e91a000000           	jmp	0x5b
;;   41:	 4989cb               	mov	r11, rcx
;;      	 49c1eb01             	shr	r11, 1
;;      	 4889c8               	mov	rax, rcx
;;      	 4883e001             	and	rax, 1
;;      	 4c09d8               	or	rax, r11
;;      	 f3480f2ac0           	cvtsi2ss	xmm0, rax
;;      	 f30f58c0             	addss	xmm0, xmm0
;;      	 4883c410             	add	rsp, 0x10
;;      	 5d                   	pop	rbp
;;      	 c3                   	ret	
;;   61:	 0f0b                 	ud2	
