package foo:foo;

interface multi-return {
  mra: func();
  mrb: func() -> ();
  mrc: func() -> u32;
  mrd: func() -> (a: u32);
  mre: func() -> (a: u32, b: f32);
}

world the-world {
  import multi-return;
  export multi-return;
}
