interface multi-return {
  mra: func()
  mrb: func() -> ()
  mrc: func() -> u32
  mrd: func() -> (a: u32)
  mre: func() -> (a: u32, b: float32)
}

default world the-world {
  import imports: self.multi-return
  export exports: self.multi-return
}
