interface http-types{
  record request {
    method: string
  }
  record response {
    body: string
  }
}

default world http-interface {
  export http-handler: interface {
    use self.http-types.{request,response}
    handle-request: func(request: request) -> response
  }
  import http-fetch: interface {
    use self.http-types.{request,response}
    fetch-request: func(request: request) -> response
  }
}
