interface anon {
  enum error {
    success,
    failure,
  }

  option-test: func() -> result<option<string>, error>
}

default world the-world {
  import imports: self.anon
  export exports: self.anon
}
