interface anon {
  enum error {
    success,
    failure,
  }

  option-test: func() -> result<option<string>, error>
}

world the-world {
  import imports: anon
  export exports: anon
  default export anon
}
