interface strings {
  a: func(x: string)
  b: func() -> string
  c: func(a: string, b: string) -> string
}

world the-world {
  import imports: strings
  export exports: strings
  default export strings
}
