// All of the same imports and exports available in the wasi:cli/command world
// with addition of HTTP proxy related imports:
world command-extended {
  import wasi:clocks/wall-clock@0.2.0-rc-2023-10-18;
  import wasi:clocks/monotonic-clock@0.2.0-rc-2023-10-18;
  import wasi:clocks/timezone@0.2.0-rc-2023-10-18;
  import wasi:filesystem/types@0.2.0-rc-2023-10-18;
  import wasi:filesystem/preopens@0.2.0-rc-2023-10-18;
  import wasi:sockets/instance-network@0.2.0-rc-2023-10-18;
  import wasi:sockets/ip-name-lookup@0.2.0-rc-2023-10-18;
  import wasi:sockets/network@0.2.0-rc-2023-10-18;
  import wasi:sockets/tcp-create-socket@0.2.0-rc-2023-10-18;
  import wasi:sockets/tcp@0.2.0-rc-2023-10-18;
  import wasi:sockets/udp-create-socket@0.2.0-rc-2023-10-18;
  import wasi:sockets/udp@0.2.0-rc-2023-10-18;
  import wasi:random/random@0.2.0-rc-2023-10-18;
  import wasi:random/insecure@0.2.0-rc-2023-10-18;
  import wasi:random/insecure-seed@0.2.0-rc-2023-10-18;
  import wasi:io/poll@0.2.0-rc-2023-10-18;
  import wasi:io/streams@0.2.0-rc-2023-10-18;
  import wasi:cli/environment@0.2.0-rc-2023-10-18;
  import wasi:cli/exit@0.2.0-rc-2023-10-18;
  import wasi:cli/stdin@0.2.0-rc-2023-10-18;
  import wasi:cli/stdout@0.2.0-rc-2023-10-18;
  import wasi:cli/stderr@0.2.0-rc-2023-10-18;
  import wasi:cli/terminal-input@0.2.0-rc-2023-10-18;
  import wasi:cli/terminal-output@0.2.0-rc-2023-10-18;
  import wasi:cli/terminal-stdin@0.2.0-rc-2023-10-18;
  import wasi:cli/terminal-stdout@0.2.0-rc-2023-10-18;
  import wasi:cli/terminal-stderr@0.2.0-rc-2023-10-18;

  // We should replace all others with `include self.command`
  // as soon as the unioning of worlds is available:
  // https://github.com/WebAssembly/component-model/issues/169
  import wasi:logging/logging@0.2.0-rc-2023-10-18;
  import wasi:http/outgoing-handler@0.2.0-rc-2023-10-18;
}
