(module
  (import "" "global_i32_mut" (global $global_i32_mut (mut i32)))
  (import "" "global_i32" (global $global_i32 i32))
  (import "" "global_i64_mut" (global $global_i64_mut (mut i64)))
  (import "" "global_i64" (global $global_i64 i64))
  (import "" "global_f32_mut" (global $global_f32_mut (mut f32)))
  (import "" "global_f32" (global $global_f32 f32))
  (import "" "global_f64_mut" (global $global_f64_mut (mut f64)))
  (import "" "global_f64" (global $global_f64 f64))
  (func (export "get_global_i32_mut") (result i32) (global.get $global_i32_mut))
  (func (export "get_global_i32") (result i32) (global.get $global_i32))
  (func (export "set_global_i32_mut") (param i32) (global.set $global_i32_mut (local.get 0)))
  (func (export "get_global_i64_mut") (result i64) (global.get $global_i64_mut))
  (func (export "get_global_i64") (result i64) (global.get $global_i64))
  (func (export "set_global_i64_mut") (param i64) (global.set $global_i64_mut (local.get 0)))
  (func (export "get_global_f32_mut") (result f32) (global.get $global_f32_mut))
  (func (export "get_global_f32") (result f32) (global.get $global_f32))
  (func (export "set_global_f32_mut") (param f32) (global.set $global_f32_mut (local.get 0)))
  (func (export "get_global_f64_mut") (result f64) (global.get $global_f64_mut))
  (func (export "get_global_f64") (result f64) (global.get $global_f64))
  (func (export "set_global_f64_mut") (param f64) (global.set $global_f64_mut (local.get 0)))
)
