(module
  (global $g1 (import "" "global_i32") i32)
  (global $g2 (import "" "global_i32_mut") (mut i32))
  (global $g3 (import "" "global_i64") i64)
  (global $g4 (import "" "global_i64_mut") (mut i64))
  (global $g5 (import "" "global_f32") f32)
  (global $g6 (import "" "global_f32_mut") (mut f32))
  (global $g7 (import "" "global_f64") f64)
  (global $g8 (import "" "global_f64_mut") (mut f64))
  (global $g9 (import "other" "global_from_module") i32)
)
