;;! target = "x86_64"
;;! flags = "-W function-references,gc -C collector=copying"
;;! test = "optimize"
(module
  (global $x (mut i31ref) (ref.i31 (i32.const 42)))
  (func (export "get") (result i31ref)
    (global.get $x)
  )
  (func (export "set") (param i31ref)
    (global.set $x (local.get 0))
  )
)
;; function u0:0(i64 vmctx, i64) -> i32 tail {
;;     region0 = 8 "VMContext+0x8"
;;     region1 = 134217752 "VMStoreContext+0x18"
;;     region2 = 939524096 "DefinedGlobal(StaticModuleIndex(0), DefinedGlobalIndex(0))"
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly can_move region0 gv0+8
;;     gv2 = load.i64 notrap aligned region1 gv1+24
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64):
;; @0036                               v2 = iconst.i64 48
;; @0036                               v3 = iadd v0, v2  ; v2 = 48
;; @0036                               v4 = load.i32 notrap aligned region2 v3
;; @0038                               jump block1
;;
;;                                 block1:
;; @0038                               return v4
;; }
;;
;; function u0:1(i64 vmctx, i64, i32) tail {
;;     region0 = 8 "VMContext+0x8"
;;     region1 = 134217752 "VMStoreContext+0x18"
;;     region2 = 939524096 "DefinedGlobal(StaticModuleIndex(0), DefinedGlobalIndex(0))"
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly can_move region0 gv0+8
;;     gv2 = load.i64 notrap aligned region1 gv1+24
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64, v2: i32):
;; @003d                               v3 = iconst.i64 48
;; @003d                               v4 = iadd v0, v3  ; v3 = 48
;; @003d                               store notrap aligned region2 v2, v4
;; @003f                               jump block1
;;
;;                                 block1:
;; @003f                               return
;; }
