;;! target = "aarch64"
;;!
;;! settings = ['enable_heap_access_spectre_mitigation=false']
;;!
;;! compile = true
;;!
;;! [globals.vmctx]
;;! type = "i64"
;;! vmctx = true
;;!
;;! [globals.heap_base]
;;! type = "i64"
;;! load = { base = "vmctx", offset = 0, readonly = true }
;;!
;;! [globals.heap_bound]
;;! type = "i64"
;;! load = { base = "vmctx", offset = 8, readonly = true }
;;!
;;! [[heaps]]
;;! base = "heap_base"
;;! min_size = 0x10000
;;! offset_guard_size = 0
;;! index_type = "i32"
;;! style = { kind = "dynamic", bound = "heap_bound" }

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0x1000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load8_u offset=0x1000))

;; function u0:0:
;; block0:
;;   mov w9, w0
;;   ldr x10, [x2, #8]
;;   movn x8, #4096
;;   add x10, x10, x8
;;   subs xzr, x9, x10
;;   b.hi label1 ; b label2
;; block2:
;;   ldr x12, [x2]
;;   add x12, x12, #4096
;;   strb w1, [x12, w0, UXTW]
;;   b label3
;; block3:
;;   ret
;; block1:
;;   udf #0xc11f
;;
;; function u0:1:
;; block0:
;;   mov w9, w0
;;   ldr x10, [x1, #8]
;;   movn x8, #4096
;;   add x10, x10, x8
;;   subs xzr, x9, x10
;;   b.hi label1 ; b label2
;; block2:
;;   ldr x12, [x1]
;;   add x11, x12, #4096
;;   ldrb w0, [x11, w0, UXTW]
;;   b label3
;; block3:
;;   ret
;; block1:
;;   udf #0xc11f
