;;! target = "x86_64"

(module
  (table (export "t") 0 100 funcref)
  (func (export "f") (param i32 i32) (result i32)
    (call_indirect (param i32) (result i32) (local.get 0) (local.get 1))
  )
)

;; function u0:0(i64 vmctx, i64, i32, i32) -> i32 tail {
;;     region0 = 8 "VMContext+0x8"
;;     region1 = 134217752 "VMStoreContext+0x18"
;;     region2 = 1342177280 "VMTableDefinition+0x0"
;;     region3 = 1342177288 "VMTableDefinition+0x8"
;;     region4 = 536870912 "PublicTable"
;;     region5 = 40 "VMContext+0x28"
;;     region6 = 3355443204 "TypeIdsArray+0x4"
;;     region7 = 3221225488 "VMFuncRef+0x10"
;;     region8 = 3221225480 "VMFuncRef+0x8"
;;     region9 = 3221225496 "VMFuncRef+0x18"
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly can_move region0 gv0+8
;;     gv2 = load.i64 notrap aligned region1 gv1+24
;;     sig0 = (i64 vmctx, i64, i32) -> i32 tail
;;     sig1 = (i64 vmctx, i32, i64) -> i64 tail
;;     fn0 = colocated u805306368:7 sig1
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64, v2: i32, v3: i32):
;; @0035                               v4 = load.i64 notrap aligned region3 v0+56
;; @0035                               v5 = ireduce.i32 v4
;; @0035                               v6 = icmp uge v3, v5
;; @0035                               v7 = uextend.i64 v3
;; @0035                               v8 = load.i64 notrap aligned region2 v0+48
;; @0035                               v9 = iconst.i64 3
;; @0035                               v10 = ishl v7, v9  ; v9 = 3
;; @0035                               v11 = iadd v8, v10
;; @0035                               v12 = iconst.i64 0
;; @0035                               v13 = select_spectre_guard v6, v12, v11  ; v12 = 0
;; @0035                               v14 = load.i64 user6 aligned region4 v13
;; @0035                               v15 = iconst.i64 -2
;; @0035                               v16 = band v14, v15  ; v15 = -2
;; @0035                               brif v14, block3(v16), block2
;;
;;                                 block2 cold:
;; @0035                               v18 = iconst.i32 0
;; @0035                               v19 = uextend.i64 v3
;; @0035                               v20 = call fn0(v0, v18, v19)  ; v18 = 0
;; @0035                               jump block3(v20)
;;
;;                                 block3(v17: i64):
;; @0035                               v21 = load.i64 notrap aligned readonly can_move region5 v0+40
;; @0035                               v22 = load.i32 notrap aligned readonly can_move region6 v21+4
;; @0035                               v23 = load.i32 user7 aligned readonly region7 v17+16
;; @0035                               v24 = icmp eq v23, v22
;; @0035                               v25 = uextend.i32 v24
;; @0035                               trapz v25, user8
;; @0035                               v26 = load.i64 notrap aligned readonly region8 v17+8
;; @0035                               v27 = load.i64 notrap aligned readonly region9 v17+24
;; @0035                               v28 = call_indirect sig0, v26(v27, v0, v2)
;; @0038                               jump block1
;;
;;                                 block1:
;; @0038                               return v28
;; }
