;;! target = "x86_64"
;;! test = "optimize"
;;! flags = [
;;!   "-Ccranelift-enable-heap-access-spectre-mitigation=false",
;;!   "-Ostatic-memory-maximum-size=0",
;;!   "-Odynamic-memory-guard-size=0xffff",
;;! ]

(module
  (memory (export "memory") 0)

  (func (export "loads") (param i32) (result i32 i32 i32)
    ;; Within the guard region.
    local.get 0
    i32.load offset=0
    ;; Also within the guard region, bounds check should GVN with previous.
    local.get 0
    i32.load offset=4
    ;; Outside the guard region, needs additional bounds checks.
    local.get 0
    i32.load offset=0x000fffff
  )

  ;; Same as above, but for stores.
  (func (export "stores") (param i32 i32 i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0
    local.get 0
    local.get 2
    i32.store offset=4
    local.get 0
    local.get 3
    i32.store offset=0x000fffff
  )
)

;; function u0:0(i64 vmctx, i64, i32) -> i32, i32, i32 tail {
;;     region0 = 8 "VMContext+0x8"
;;     region1 = 134217752 "VMStoreContext+0x18"
;;     region2 = 1207959552 "VMMemoryDefinition+0x0"
;;     region3 = 1207959560 "VMMemoryDefinition+0x8"
;;     region4 = 268435456 "PublicMemory"
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly can_move region0 gv0+8
;;     gv2 = load.i64 notrap aligned region1 gv1+24
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64, v2: i32):
;; @0047                               v4 = load.i64 notrap aligned region3 v0+64
;; @0047                               v3 = uextend.i64 v2
;; @0047                               v5 = icmp ugt v3, v4
;; @0047                               trapnz v5, heap_oob
;; @0047                               v6 = load.i64 notrap aligned can_move region2 v0+56
;; @0047                               v7 = iadd v6, v3
;; @0047                               v8 = load.i32 little region4 v7
;; @004c                               v14 = iconst.i64 4
;; @004c                               v15 = iadd v7, v14  ; v14 = 4
;; @004c                               v16 = load.i32 little region4 v15
;; @0051                               v18 = iconst.i64 0x0010_0003
;; @0051                               v19 = uadd_overflow_trap v3, v18, heap_oob  ; v18 = 0x0010_0003
;; @0051                               v21 = icmp ugt v19, v4
;; @0051                               trapnz v21, heap_oob
;; @0051                               v24 = iconst.i64 0x000f_ffff
;; @0051                               v25 = iadd v7, v24  ; v24 = 0x000f_ffff
;; @0051                               v26 = load.i32 little region4 v25
;; @0056                               jump block1
;;
;;                                 block1:
;; @0056                               return v8, v16, v26
;; }
;;
;; function u0:1(i64 vmctx, i64, i32, i32, i32, i32) tail {
;;     region0 = 8 "VMContext+0x8"
;;     region1 = 134217752 "VMStoreContext+0x18"
;;     region2 = 1207959552 "VMMemoryDefinition+0x0"
;;     region3 = 1207959560 "VMMemoryDefinition+0x8"
;;     region4 = 268435456 "PublicMemory"
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly can_move region0 gv0+8
;;     gv2 = load.i64 notrap aligned region1 gv1+24
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64, v2: i32, v3: i32, v4: i32, v5: i32):
;; @005d                               v7 = load.i64 notrap aligned region3 v0+64
;; @005d                               v6 = uextend.i64 v2
;; @005d                               v8 = icmp ugt v6, v7
;; @005d                               trapnz v8, heap_oob
;; @005d                               v9 = load.i64 notrap aligned can_move region2 v0+56
;; @005d                               v10 = iadd v9, v6
;; @005d                               store little region4 v3, v10
;; @0064                               v16 = iconst.i64 4
;; @0064                               v17 = iadd v10, v16  ; v16 = 4
;; @0064                               store little region4 v4, v17
;; @006b                               v19 = iconst.i64 0x0010_0003
;; @006b                               v20 = uadd_overflow_trap v6, v19, heap_oob  ; v19 = 0x0010_0003
;; @006b                               v22 = icmp ugt v20, v7
;; @006b                               trapnz v22, heap_oob
;; @006b                               v25 = iconst.i64 0x000f_ffff
;; @006b                               v26 = iadd v10, v25  ; v25 = 0x000f_ffff
;; @006b                               store little region4 v5, v26
;; @0070                               jump block1
;;
;;                                 block1:
;; @0070                               return
;; }
