;;! target = "x86_64"

(module
  ;; Imported and immutable: should become a vmctx load.
  (import "env" "a" (global $imp-imm i32))

  ;; Imported and mutable: should become a vmctx load.
  (import "env" "b" (global $imp-mut (mut i32)))

  ;; Defined and immutable: should become a constant.
  (global $def-imm i32 (i32.const 42))

  ;; Defined and mutable: should become a vmctx load.
  (global $def-mut (mut i32) (i32.const 36))

  (func $f0 (result i32)
    (global.get $imp-imm)
  )

  (func $f1 (result i32)
    (global.get $imp-mut)
  )

  (func $f2 (result i32)
    (global.get $def-imm)
  )

  (func $f3 (result i32)
    (global.get $def-mut)
  )
)

;; function u0:0(i64 vmctx, i64) -> i32 tail {
;;     region0 = 8 "VMContext+0x8"
;;     region1 = 134217752 "VMStoreContext+0x18"
;;     region2 = 2952790016 "VMGlobalImport+0x0"
;;     region3 = 805306368 "PublicGlobal"
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly can_move region0 gv0+8
;;     gv2 = load.i64 notrap aligned region1 gv1+24
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64):
;; @003d                               v2 = load.i64 notrap aligned readonly can_move region2 v0+48
;; @003d                               v3 = load.i32 notrap aligned region3 v2
;; @003f                               jump block1
;;
;;                                 block1:
;; @003f                               return v3
;; }
;;
;; function u0:1(i64 vmctx, i64) -> i32 tail {
;;     region0 = 8 "VMContext+0x8"
;;     region1 = 134217752 "VMStoreContext+0x18"
;;     region2 = 2952790016 "VMGlobalImport+0x0"
;;     region3 = 805306368 "PublicGlobal"
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly can_move region0 gv0+8
;;     gv2 = load.i64 notrap aligned region1 gv1+24
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64):
;; @0042                               v2 = load.i64 notrap aligned readonly can_move region2 v0+72
;; @0042                               v3 = load.i32 notrap aligned region3 v2
;; @0044                               jump block1
;;
;;                                 block1:
;; @0044                               return v3
;; }
;;
;; function u0:2(i64 vmctx, i64) -> i32 tail {
;;     region0 = 8 "VMContext+0x8"
;;     region1 = 134217752 "VMStoreContext+0x18"
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly can_move region0 gv0+8
;;     gv2 = load.i64 notrap aligned region1 gv1+24
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64):
;; @0047                               v2 = iconst.i32 42
;; @0049                               jump block1
;;
;;                                 block1:
;; @0049                               return v2  ; v2 = 42
;; }
;;
;; function u0:3(i64 vmctx, i64) -> i32 tail {
;;     region0 = 8 "VMContext+0x8"
;;     region1 = 134217752 "VMStoreContext+0x18"
;;     region2 = 939524097 "DefinedGlobal(StaticModuleIndex(0), DefinedGlobalIndex(1))"
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly can_move region0 gv0+8
;;     gv2 = load.i64 notrap aligned region1 gv1+24
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64):
;; @004c                               v2 = load.i32 notrap aligned region2 v0+112
;; @004e                               jump block1
;;
;;                                 block1:
;; @004e                               return v2
;; }
