;;! target = "aarch64"
;;! test = "winch"

(module
    (func (result i32)
        (local f32)  

        (local.get 0)
        (i32.trunc_f32_s)
    )
)
;; wasm[0]::function[0]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       str     x28, [sp, #-0x10]!
;;       mov     x28, sp
;;       ldur    x16, [x0, #8]
;;       ldur    x16, [x16, #0x18]
;;       mov     x17, #0
;;       movk    x17, #0x18
;;       add     x16, x16, x17
;;       cmp     sp, x16
;;       b.lo    #0x90
;;   2c: mov     x9, x0
;;       sub     x28, x28, #0x18
;;       mov     sp, x28
;;       stur    x0, [x28, #0x10]
;;       stur    x1, [x28, #8]
;;       mov     x16, #0
;;       stur    x16, [x28]
;;       ldur    s0, [x28, #4]
;;       sub     sp, x28, #8
;;       fcmp    s0, s0
;;       b.vs    #0x94
;;   58: ldr     s31, #0xa0
;;       fcmp    s0, s31
;;       b.le    #0x98
;;   64: ldr     s31, #0xa8
;;       fcmp    s0, s31
;;       b.ge    #0x9c
;;   70: fcvtzs  w0, s0
;;       mov     sp, x28
;;       add     x28, x28, #0x18
;;       mov     sp, x28
;;       mov     sp, x28
;;       ldr     x28, [sp], #0x10
;;       ldp     x29, x30, [sp], #0x10
;;       ret
;;   90: udf     #0xc11f
;;   94: udf     #0xc11f
;;   98: udf     #0xc11f
;;   9c: udf     #0xc11f
;;   a0: .byte   0x01, 0x00, 0x00, 0xcf
;;   a4: udf     #0
;;   a8: .byte   0x00, 0x00, 0x00, 0x4f
