;;! target = "x86_64"
;;! flags = "-W function-references,gc -C collector=null"
;;! test = "optimize"

(module
  (type $ty (array (mut i64)))

  (func (param i64 i64 i64) (result (ref $ty))
    (array.new_fixed $ty 3 (local.get 0) (local.get 1) (local.get 2))
  )
)
;; function u0:0(i64 vmctx, i64, i64, i64, i64) -> i32 tail {
;;     region0 = 123 ""
;;     region1 = 160 ""
;;     region2 = 65 ""
;;     region3 = 237 ""
;;     region4 = 206 ""
;;     region5 = 196 ""
;;     region6 = 130 ""
;;     region7 = 6 ""
;;     region8 = 239 ""
;;     region9 = 134 ""
;;     region10 = 108 ""
;;     region11 = 5 ""
;;     gv0 = vmctx
;;     gv1 = load.i64 notrap aligned readonly can_move region0 gv0+8
;;     gv2 = load.i64 notrap aligned region1 gv1+24
;;     sig0 = (i64 vmctx, i64) -> i8 tail
;;     fn0 = colocated u805306368:23 sig0
;;     stack_limit = gv2
;;
;;                                 block0(v0: i64, v1: i64, v2: i64, v3: i64, v4: i64):
;; @0025                               v17 = load.i64 notrap aligned readonly can_move region2 v0+32
;; @0025                               v18 = load.i32 notrap aligned region3 v17
;;                                     v142 = iconst.i32 7
;; @0025                               v21 = uadd_overflow_trap v18, v142, user18  ; v142 = 7
;;                                     v148 = iconst.i32 -8
;; @0025                               v23 = band v21, v148  ; v148 = -8
;;                                     v135 = iconst.i32 40
;; @0025                               v24 = uadd_overflow_trap v23, v135, user18  ; v135 = 40
;; @0025                               v26 = load.i64 notrap aligned readonly can_move region0 v0+8
;; @0025                               v27 = load.i64 notrap aligned region4 v26+40
;; @0025                               v25 = uextend.i64 v24
;; @0025                               v28 = icmp ule v25, v27
;; @0025                               brif v28, block2, block3
;;
;;                                 block2:
;;                                     v149 = iconst.i32 -1476394968
;; @0025                               v32 = load.i64 notrap aligned readonly can_move region5 v26+32
;;                                     v242 = band.i32 v21, v148  ; v148 = -8
;;                                     v243 = uextend.i64 v242
;; @0025                               v34 = iadd v32, v243
;; @0025                               store user2 region8 v149, v34  ; v149 = -1476394968
;; @0025                               v37 = load.i64 notrap aligned readonly can_move region6 v0+40
;; @0025                               v38 = load.i32 notrap aligned readonly can_move region7 v37
;; @0025                               store user2 region9 v38, v34+4
;; @0025                               store.i32 notrap aligned region3 v24, v17
;; @0025                               v5 = iconst.i32 3
;; @0025                               v8 = iconst.i64 8
;; @0025                               v40 = iadd v34, v8  ; v8 = 8
;; @0025                               store user2 region10 v5, v40  ; v5 = 3
;; @0025                               trapz v242, user16
;;                                     v244 = iconst.i32 40
;; @0025                               v61 = uadd_overflow_trap v242, v244, user2  ; v244 = 40
;; @0025                               v62 = uextend.i64 v61
;; @0025                               v65 = iadd v32, v62
;;                                     v126 = iconst.i64 24
;; @0025                               v68 = isub v65, v126  ; v126 = 24
;; @0025                               store.i64 user2 little region11 v2, v68
;;                                     v211 = iconst.i64 16
;; @0025                               v96 = isub v65, v211  ; v211 = 16
;; @0025                               store.i64 user2 little region11 v3, v96
;; @0025                               v124 = isub v65, v8  ; v8 = 8
;; @0025                               store.i64 user2 little region11 v4, v124
;; @0029                               jump block1
;;
;;                                 block3 cold:
;; @0025                               v29 = isub.i64 v25, v27
;; @0025                               v30 = call fn0(v0, v29)
;; @0025                               jump block2
;;
;;                                 block1:
;;                                     v245 = band.i32 v21, v148  ; v148 = -8
;; @0029                               return v245
;; }
