test compile
target x86_64 legacy

function u0:0(i128) -> i8 fast {
block0(v0: i128):
    brz v0, block2
    ; check: v0 = iconcat v3, v4
    ; nextln: v5 = icmp_imm eq v3, 0
    ; nextln: v6 = icmp_imm eq v4, 0
    ; nextln: v7 = band v5, v6
    ; nextln: brnz v7, block2
    jump block1

block1:
    v1 = iconst.i8 0
    return v1

block2:
    v2 = iconst.i8 1
    return v2
}

function u0:1(i128) -> i8 fast {
block0(v0: i128):
    brnz v0, block2
    ; check: v0 = iconcat v3, v4
    ; nextln: brnz v3, block2
    ; nextln: fallthrough block3

    ; check: block3:
    ; nextln: brnz.i64 v4, block2
    jump block1
    ; nextln: fallthrough block1

block1:
    v1 = iconst.i8 0
    return v1

block2:
    v2 = iconst.i8 1
    return v2
}
