test compile
target i686 legacy

function u0:0() -> b1 {
block0:
    v0 = iconst.i32 0xffff_ee00
    ; check: v0 = iconst.i32 0xffff_ee00
    ; nextln: v2 -> v0
    v1 = uextend.i64 v0
    ; nextln: v7 = iconst.i32 0
    ; nextln: v3 -> v7
    ; nextln: v1 = iconcat v0, v7

    v2, v3 = isplit v1
    v4 = icmp_imm eq v2, 0xffff_ee00
    v5 = icmp_imm eq v3, 0

    v6 = band v4, v5
    return v6
}

function u0:1() -> b1 {
block0:
    v0 = iconst.i32 0xffff_ee00
    ; check: v0 = iconst.i32 0xffff_ee00
    ; nextln: v2 -> v0
    v1 = sextend.i64 v0
    ; nextln: v10 = copy v0
    ; nextln: v7 = sshr_imm v10, 31
    ; nextln: v3 -> v7

    v2, v3 = isplit v1
    v4 = icmp_imm eq v2, 0xffff_ee00
    v5 = icmp_imm eq v3, 0xffff_ffff
    v6 = band v4, v5
    return v6
}
