test compile
target x86_64 legacy

function u0:0() -> b1 {
block0:
    v0 = iconst.i64 0xffff_ffff_eeee_0000
    ; check: v0 = iconst.i64 0xffff_ffff_eeee_0000
    ; nextln: v2 -> v0
    v1 = uextend.i128 v0
    ; nextln: v7 = iconst.i64 0
    ; nextln: v3 -> v7
    ; nextln: v1 = iconcat v0, v7

    v2, v3 = isplit v1
    v4 = icmp_imm eq v2, 0xffff_ffff_eeee_0000
    v5 = icmp_imm eq v3, 0

    v6 = band v4, v5
    return v6
}

function u0:1() -> b1 {
block0:
    v0 = iconst.i64 0xffff_ffff_eeee_0000
    ; check: v0 = iconst.i64 0xffff_ffff_eeee_0000
    ; nextln: v2 -> v0
    v1 = sextend.i128 v0
    ; nextln: v8 = copy v0
    ; nextln: v7 = sshr_imm v8, 63
    ; nextln: v3 -> v7

    v2, v3 = isplit v1
    v4 = icmp_imm eq v2, 0xffff_ffff_eeee_0000
    v5 = icmp_imm eq v3, 0xffff_ffff_ffff_ffff
    v6 = band v4, v5
    return v6
}
