test compile
set opt_level=speed_and_size
target x86_64 legacy
; regex: V=v\d+
; regex: BB=block\d+

function u0:0(i64) system_v {
    ss0 = explicit_slot 1
    jt0 = jump_table [block1]

block0(v0: i64):
    v1 = stack_addr.i64 ss0
    v2 = load.i8 v1
    br_table v2, block2, jt0
; check:     $(oob=$V) = ifcmp_imm $(idx=$V), 1
; block2 is replaced by block1 by fold_redundant_jump
; nextln:    brif uge $oob, block1
; nextln:    fallthrough $(inb=$BB)
; check:   $inb:
; nextln:    $(final_idx=$V) = uextend.i64 $idx
; nextln:    $(base=$V) = jump_table_base.i64 jt0
; nextln:    $(rel_addr=$V) = jump_table_entry $final_idx, $base, 4, jt0
; nextln:    $(addr=$V) = iadd $base, $rel_addr
; nextln:    indirect_jump_table_br $addr, jt0

block2:
    jump block1

block1:
    return
}
