test legalizer

target x86_64 legacy

function %br_icmp(i64) fast {
block0(v0: i64):
    v1 = iconst.i64 0
    br_icmp eq v0, v1, block1
    jump block1

block1:
    return
}

; sameln: function %br_icmp(i64 [%rdi]) fast {
; nextln:                                 block0(v0: i64):
; nextln: [RexOp1pu_id#b8]                    v1 = iconst.i64 0
; nextln: [RexOp1icscc#8039]                  v2 = icmp eq v0, v1
; nextln: [RexOp1t8jccb#75]                   brnz v2, block1
; nextln: [Op1jmpb#eb]                        jump block1
; nextln: 
; nextln:                                 block1:
; nextln: [Op1ret#c3]                         return
; nextln: }


function %br_icmp_args(i64) fast {
block0(v0: i64):
    v1 = iconst.i64 0
    br_icmp eq v0, v1, block1(v0)
    jump block1(v0)

block1(v2: i64):
    return
}

; sameln: function %br_icmp_args(i64 [%rdi]) fast {
; nextln:                                 block0(v0: i64):
; nextln: [RexOp1pu_id#b8]                    v1 = iconst.i64 0
; nextln: [RexOp1icscc#8039]                  v3 = icmp eq v0, v1
; nextln: [RexOp1t8jccb#75]                   brnz v3, block1(v0)
; nextln: [Op1jmpb#eb]                        jump block1(v0)
; nextln: 
; nextln:                                 block1(v2: i64):
; nextln: [Op1ret#c3]                         return
; nextln: }
