test compile
target x86_64 legacy

; regex: V=v\d+

function u0:0(i8) -> i8, i8 fast {
block0(v0: i8):
    v1 = clz v0
    ; check: v3 = uextend.i32 v0
    ; nextln: v6 = iconst.i32 -1
    ; nextln: v7 = iconst.i32 31
    ; nextln: v8, v9 = x86_bsr v3
    ; nextln: v10 = selectif.i32 eq v9, v6, v8
    ; nextln: v4 = isub v7, v10
    ; nextln: v5 = iadd_imm v4, -24
    ; nextln: v1 = ireduce.i8 v5
    v2 = ctz v0
    ; nextln: v11 = uextend.i32 v0
    ; nextln: v12 = bor_imm v11, 256
    ; nextln: v14 = iconst.i32 32
    ; nextln: v15, v16 = x86_bsf v12
    ; nextln: v13 = selectif.i32 eq v16, v14, v15
    ; nextln: v2 = ireduce.i8 v13
    return v1, v2
}
