test legalizer
set enable_simd
target x86_64 legacy skylake

function %icmp_ne_32x4(i32x4, i32x4) -> b32x4 {
; check: const0 = 0xffffffffffffffffffffffffffffffff
block0(v0: i32x4, v1: i32x4):
    v2 = icmp ne v0, v1
    ; check: v3 = icmp eq v0, v1
    ; nextln: v4 = vconst.b32x4 const0
    ; nextln: v2 = bxor v4, v3
    return v2
}

function %icmp_ugt_i32x4(i32x4, i32x4) -> b32x4 {
; check: const0 = 0xffffffffffffffffffffffffffffffff
block0(v0: i32x4, v1: i32x4):
    v2 = icmp ugt v0, v1
    ; check: v3 = x86_pmaxu v0, v1
    ; nextln: v4 = icmp eq v3, v1
    ; nextln: v5 = vconst.b32x4 const0
    ; nextln: v2 = bxor v5, v4
    return v2
}

function %icmp_sge_i16x8(i16x8, i16x8) -> b16x8 {
block0(v0: i16x8, v1: i16x8):
    v2 = icmp sge v0, v1
    ; check: v3 = x86_pmins v0, v1
    ; nextln: v2 = icmp eq v3, v1
    return v2
}

function %icmp_uge_i8x16(i8x16, i8x16) -> b8x16 {
block0(v0: i8x16, v1: i8x16):
    v2 = icmp uge v0, v1
    ; check: v3 = x86_pminu v0, v1
    ; nextln: v2 = icmp eq v3, v1
    return v2
}
