test legalizer
set enable_simd
target x86_64 legacy skylake

function %bnot_b32x4(b32x4) -> b32x4 {
; check: const0 = 0xffffffffffffffffffffffffffffffff
block0(v0: b32x4):
    v1 = bnot v0
    ; check: v2 = vconst.b32x4 const0
    ; nextln: v1 = bxor v2, v0
    return v1
}

function %vany_true_b32x4(b32x4) -> b1 {
block0(v0: b32x4):
    v1 = vany_true v0
    ; check: v2 = x86_ptest v0, v0
    ; nextln: v1 = trueif ne v2
    return v1
}

function %vall_true_i64x2(i64x2) -> b1 {
; check: const0 = 0x00000000000000000000000000000000
block0(v0: i64x2):
    v1 = vall_true v0
    ; check: v2 = vconst.i64x2 const0
    ; nextln: v3 = icmp eq v0, v2
    ; nextln: v4 = x86_ptest v3, v3
    ; nextln: v1 = trueif eq v4
    return v1
}
