;;! target = "aarch64"
;;! test = "winch"

(module
  (type (;0;) (func (result f64 f32 f64 f64 f64 f64 f64 f64 f64 f64 f64 f64 f64 i64 f64)))
  (global (;0;) (mut i32) i32.const 10)
  (export "main" (func 0))
  (func (;0;) (type 0) (result f64 f32 f64 f64 f64 f64 f64 f64 f64 f64 f64 f64 f64 i64 f64)
    call 1
    call 1
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    call 2
    br 0
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    drop
    f64.const 0x1.54e5e9c49a8a3p+224 (;=35900759953881640000000000000000000000000000000000000000000000000000;)
    f32.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    i64.const 0
    f64.const 0x0p+0 (;=0;)
  )
  (func (;1;) (type 0) (result f64 f32 f64 f64 f64 f64 f64 f64 f64 f64 f64 f64 f64 i64 f64)
    f64.const 0x0p+0 (;=0;)
    f32.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    i64.const 0
    f64.const 0x0p+0 (;=0;)
  )
  (func (;2;) (type 0) (result f64 f32 f64 f64 f64 f64 f64 f64 f64 f64 f64 f64 f64 i64 f64)
    f64.const 0x0p+0 (;=0;)
    f32.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    f64.const 0x0p+0 (;=0;)
    i64.const 0
    f64.const 0x0p+0 (;=0;)
  )
)
;; wasm[0]::function[0]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       str     x28, [sp, #-0x10]!
;;       mov     x28, sp
;;       ldur    x16, [x1, #8]
;;       ldur    x16, [x16, #0x18]
;;       mov     x17, #0
;;       movk    x17, #0xf10
;;       add     x16, x16, x17
;;       cmp     sp, x16
;;       b.lo    #0x8a8
;;   2c: mov     x9, x1
;;       sub     x28, x28, #0x18
;;       mov     sp, x28
;;       stur    x1, [x28, #0x10]
;;       stur    x2, [x28, #8]
;;       stur    x0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #0xc
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #0xc
;;       bl      #0x8c0
;;   64: add     x28, x28, #0xc
;;       mov     sp, x28
;;       ldur    x9, [x28, #0x7c]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #8
;;       bl      #0x8c0
;;   9c: add     x28, x28, #8
;;       mov     sp, x28
;;       ldur    x9, [x28, #0xf0]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #4
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #4
;;       bl      #0xaa0
;;   d4: add     x28, x28, #4
;;       mov     sp, x28
;;       mov     x16, #0x164
;;       ldr     x9, [x28, x16, sxtx]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #0
;;       bl      #0xaa0
;;  108: ldr     x9, [x28, #0x1d8]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #0xc
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #0xc
;;       bl      #0xaa0
;;  138: add     x28, x28, #0xc
;;       mov     sp, x28
;;       mov     x16, #0x24c
;;       ldr     x9, [x28, x16, sxtx]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #8
;;       bl      #0xaa0
;;  174: add     x28, x28, #8
;;       mov     sp, x28
;;       ldr     x9, [x28, #0x2c0]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #4
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #4
;;       bl      #0xaa0
;;  1ac: add     x28, x28, #4
;;       mov     sp, x28
;;       mov     x16, #0x334
;;       ldr     x9, [x28, x16, sxtx]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #0
;;       bl      #0xaa0
;;  1e0: ldr     x9, [x28, #0x3a8]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #0xc
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #0xc
;;       bl      #0xaa0
;;  210: add     x28, x28, #0xc
;;       mov     sp, x28
;;       mov     x16, #0x41c
;;       ldr     x9, [x28, x16, sxtx]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #8
;;       bl      #0xaa0
;;  24c: add     x28, x28, #8
;;       mov     sp, x28
;;       ldr     x9, [x28, #0x490]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #4
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #4
;;       bl      #0xaa0
;;  284: add     x28, x28, #4
;;       mov     sp, x28
;;       mov     x16, #0x504
;;       ldr     x9, [x28, x16, sxtx]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #0
;;       bl      #0xaa0
;;  2b8: ldr     x9, [x28, #0x578]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #0xc
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #0xc
;;       bl      #0xaa0
;;  2e8: add     x28, x28, #0xc
;;       mov     sp, x28
;;       mov     x16, #0x5ec
;;       ldr     x9, [x28, x16, sxtx]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #8
;;       bl      #0xaa0
;;  324: add     x28, x28, #8
;;       mov     sp, x28
;;       ldr     x9, [x28, #0x660]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #4
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #4
;;       bl      #0xaa0
;;  35c: add     x28, x28, #4
;;       mov     sp, x28
;;       mov     x16, #0x6d4
;;       ldr     x9, [x28, x16, sxtx]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #0
;;       bl      #0xaa0
;;  390: ldr     x9, [x28, #0x748]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #0xc
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #0xc
;;       bl      #0xaa0
;;  3c0: add     x28, x28, #0xc
;;       mov     sp, x28
;;       mov     x16, #0x7bc
;;       ldr     x9, [x28, x16, sxtx]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #8
;;       bl      #0xaa0
;;  3fc: add     x28, x28, #8
;;       mov     sp, x28
;;       ldr     x9, [x28, #0x830]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #4
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #4
;;       bl      #0xaa0
;;  434: add     x28, x28, #4
;;       mov     sp, x28
;;       mov     x16, #0x8a4
;;       ldr     x9, [x28, x16, sxtx]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #0
;;       bl      #0xaa0
;;  468: ldr     x9, [x28, #0x918]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #0xc
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #0xc
;;       bl      #0xaa0
;;  498: add     x28, x28, #0xc
;;       mov     sp, x28
;;       mov     x16, #0x98c
;;       ldr     x9, [x28, x16, sxtx]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #8
;;       bl      #0xaa0
;;  4d4: add     x28, x28, #8
;;       mov     sp, x28
;;       ldr     x9, [x28, #0xa00]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #4
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #4
;;       bl      #0xaa0
;;  50c: add     x28, x28, #4
;;       mov     sp, x28
;;       mov     x16, #0xa74
;;       ldr     x9, [x28, x16, sxtx]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #0
;;       bl      #0xaa0
;;  540: ldr     x9, [x28, #0xae8]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #0xc
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #0xc
;;       bl      #0xaa0
;;  570: add     x28, x28, #0xc
;;       mov     sp, x28
;;       mov     x16, #0xb5c
;;       ldr     x9, [x28, x16, sxtx]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #8
;;       bl      #0xaa0
;;  5ac: add     x28, x28, #8
;;       mov     sp, x28
;;       ldr     x9, [x28, #0xbd0]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #4
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #4
;;       bl      #0xaa0
;;  5e4: add     x28, x28, #4
;;       mov     sp, x28
;;       mov     x16, #0xc44
;;       ldr     x9, [x28, x16, sxtx]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #0
;;       bl      #0xaa0
;;  618: ldr     x9, [x28, #0xcb8]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #0xc
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #0xc
;;       bl      #0xaa0
;;  648: add     x28, x28, #0xc
;;       mov     sp, x28
;;       mov     x16, #0xd2c
;;       ldr     x9, [x28, x16, sxtx]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #8
;;       bl      #0xaa0
;;  684: add     x28, x28, #8
;;       mov     sp, x28
;;       ldr     x9, [x28, #0xda0]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #4
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #4
;;       bl      #0xaa0
;;  6bc: add     x28, x28, #4
;;       mov     sp, x28
;;       mov     x16, #0xe14
;;       ldr     x9, [x28, x16, sxtx]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #0
;;       bl      #0xaa0
;;  6f0: ldr     x9, [x28, #0xe88]
;;       sub     x28, x28, #8
;;       mov     sp, x28
;;       stur    d0, [x28]
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       sub     x28, x28, #0xc
;;       mov     sp, x28
;;       mov     x1, x9
;;       mov     x2, x9
;;       add     x0, x28, #0xc
;;       bl      #0xaa0
;;  720: add     x28, x28, #0xc
;;       mov     sp, x28
;;       mov     x16, #0xefc
;;       ldr     x9, [x28, x16, sxtx]
;;       ldur    x16, [x28, #0x64]
;;       mov     x17, #0xee4
;;       str     x16, [x28, x17, sxtx]
;;       ldur    w16, [x28, #0x60]
;;       str     w16, [x28, #0xee0]
;;       ldur    x16, [x28, #0x58]
;;       str     x16, [x28, #0xed8]
;;       ldur    x16, [x28, #0x50]
;;       str     x16, [x28, #0xed0]
;;       ldur    x16, [x28, #0x48]
;;       str     x16, [x28, #0xec8]
;;       ldur    x16, [x28, #0x40]
;;       str     x16, [x28, #0xec0]
;;       ldur    x16, [x28, #0x38]
;;       str     x16, [x28, #0xeb8]
;;       ldur    x16, [x28, #0x30]
;;       str     x16, [x28, #0xeb0]
;;       ldur    x16, [x28, #0x28]
;;       str     x16, [x28, #0xea8]
;;       ldur    x16, [x28, #0x20]
;;       str     x16, [x28, #0xea0]
;;       ldur    x16, [x28, #0x18]
;;       str     x16, [x28, #0xe98]
;;       ldur    x16, [x28, #0x10]
;;       str     x16, [x28, #0xe90]
;;       ldur    x16, [x28, #8]
;;       str     x16, [x28, #0xe88]
;;       ldur    x16, [x28]
;;       str     x16, [x28, #0xe80]
;;       add     x28, x28, #0xe80
;;       mov     sp, x28
;;       ldur    x0, [x28, #0x6c]
;;       ldur    x16, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    x16, [x0]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #8]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x10]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x18]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x20]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x28]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x30]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x38]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x40]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x48]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x50]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x58]
;;       ldur    s31, [x28]
;;       add     x28, x28, #4
;;       mov     sp, x28
;;       stur    s31, [x0, #0x60]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x64]
;;       add     x28, x28, #0x18
;;       mov     sp, x28
;;       mov     sp, x28
;;       ldr     x28, [sp], #0x10
;;       ldp     x29, x30, [sp], #0x10
;;       ret
;;  8a8: udf     #0xc11f
;;
;; wasm[0]::function[1]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       str     x28, [sp, #-0x10]!
;;       mov     x28, sp
;;       ldur    x16, [x1, #8]
;;       ldur    x16, [x16, #0x18]
;;       mov     x17, #0
;;       movk    x17, #0x84
;;       add     x16, x16, x17
;;       cmp     sp, x16
;;       b.lo    #0xa7c
;;  8ec: mov     x9, x1
;;       sub     x28, x28, #0x18
;;       mov     sp, x28
;;       stur    x1, [x28, #0x10]
;;       stur    x2, [x28, #8]
;;       stur    x0, [x28]
;;       ldr     d0, #0xa80
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       mov     x16, #0
;;       stur    x16, [x28]
;;       ldr     d31, #0xa80
;;       stur    d31, [x28, #8]
;;       ldr     d31, #0xa80
;;       stur    d31, [x28, #0x10]
;;       ldr     d31, #0xa80
;;       stur    d31, [x28, #0x18]
;;       ldr     d31, #0xa80
;;       stur    d31, [x28, #0x20]
;;       ldr     d31, #0xa80
;;       stur    d31, [x28, #0x28]
;;       ldr     d31, #0xa80
;;       stur    d31, [x28, #0x30]
;;       ldr     d31, #0xa80
;;       stur    d31, [x28, #0x38]
;;       ldr     d31, #0xa80
;;       stur    d31, [x28, #0x40]
;;       ldr     d31, #0xa80
;;       stur    d31, [x28, #0x48]
;;       ldr     d31, #0xa80
;;       stur    d31, [x28, #0x50]
;;       ldr     d31, #0xa80
;;       stur    d31, [x28, #0x58]
;;       ldr     s31, #0xa88
;;       stur    s31, [x28, #0x60]
;;       ldr     d31, #0xa80
;;       stur    d31, [x28, #0x64]
;;       ldur    x0, [x28, #0x6c]
;;       ldur    x16, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    x16, [x0]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #8]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x10]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x18]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x20]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x28]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x30]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x38]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x40]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x48]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x50]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x58]
;;       ldur    s31, [x28]
;;       add     x28, x28, #4
;;       mov     sp, x28
;;       stur    s31, [x0, #0x60]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x64]
;;       add     x28, x28, #0x18
;;       mov     sp, x28
;;       mov     sp, x28
;;       ldr     x28, [sp], #0x10
;;       ldp     x29, x30, [sp], #0x10
;;       ret
;;  a7c: udf     #0xc11f
;;  a80: udf     #0
;;  a84: udf     #0
;;  a88: udf     #0
;;
;; wasm[0]::function[2]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       str     x28, [sp, #-0x10]!
;;       mov     x28, sp
;;       ldur    x16, [x1, #8]
;;       ldur    x16, [x16, #0x18]
;;       mov     x17, #0
;;       movk    x17, #0x84
;;       add     x16, x16, x17
;;       cmp     sp, x16
;;       b.lo    #0xc5c
;;  acc: mov     x9, x1
;;       sub     x28, x28, #0x18
;;       mov     sp, x28
;;       stur    x1, [x28, #0x10]
;;       stur    x2, [x28, #8]
;;       stur    x0, [x28]
;;       ldr     d0, #0xc60
;;       sub     x28, x28, #0x6c
;;       mov     sp, x28
;;       mov     x16, #0
;;       stur    x16, [x28]
;;       ldr     d31, #0xc60
;;       stur    d31, [x28, #8]
;;       ldr     d31, #0xc60
;;       stur    d31, [x28, #0x10]
;;       ldr     d31, #0xc60
;;       stur    d31, [x28, #0x18]
;;       ldr     d31, #0xc60
;;       stur    d31, [x28, #0x20]
;;       ldr     d31, #0xc60
;;       stur    d31, [x28, #0x28]
;;       ldr     d31, #0xc60
;;       stur    d31, [x28, #0x30]
;;       ldr     d31, #0xc60
;;       stur    d31, [x28, #0x38]
;;       ldr     d31, #0xc60
;;       stur    d31, [x28, #0x40]
;;       ldr     d31, #0xc60
;;       stur    d31, [x28, #0x48]
;;       ldr     d31, #0xc60
;;       stur    d31, [x28, #0x50]
;;       ldr     d31, #0xc60
;;       stur    d31, [x28, #0x58]
;;       ldr     s31, #0xc68
;;       stur    s31, [x28, #0x60]
;;       ldr     d31, #0xc60
;;       stur    d31, [x28, #0x64]
;;       ldur    x0, [x28, #0x6c]
;;       ldur    x16, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    x16, [x0]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #8]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x10]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x18]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x20]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x28]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x30]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x38]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x40]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x48]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x50]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x58]
;;       ldur    s31, [x28]
;;       add     x28, x28, #4
;;       mov     sp, x28
;;       stur    s31, [x0, #0x60]
;;       ldur    d31, [x28]
;;       add     x28, x28, #8
;;       mov     sp, x28
;;       stur    d31, [x0, #0x64]
;;       add     x28, x28, #0x18
;;       mov     sp, x28
;;       mov     sp, x28
;;       ldr     x28, [sp], #0x10
;;       ldp     x29, x30, [sp], #0x10
;;       ret
;;  c5c: udf     #0xc11f
;;  c60: udf     #0
;;  c64: udf     #0
;;  c68: udf     #0
