; Test the legalization of i128 instructions on x86_64.
test legalizer
target x86_64 haswell

; regex: V=v\d+

function %imul(i128, i128) -> i128 {
ebb0(v1: i128, v2: i128):
    v10 = imul v1, v2
    ; check: v1 = iconcat $(v1_lsb=$V), $(v1_msb=$V)
    ; nextln: v2 = iconcat $(v2_lsb=$V), $(v2_msb=$V)
    ; nextln: $(v11=$V) = imul $v1_msb, $v2_lsb
    ; nextln: $(v12=$V) = imul $v1_lsb, $v2_msb
    ; nextln: $(v13=$V) = iadd $v11, $v12
    ; nextln: $(v99=$V), $(v14=$V) = x86_umulx $v1_lsb, $v2_lsb
    ; nextln: $(v10_msb=$V) = iadd $v13, $v14
    ; nextln: $(v10_lsb=$V) = imul $v1_lsb, $v2_lsb
    ; nextln: v10 = iconcat $v10_lsb, $v10_msb
    return v10
}
