test compile
set colocated_libcalls=1
set probestack_enabled=0
target x86_64

; Like %big in probestack.clif, but with probes disabled.

function %big() system_v {
    ss0 = explicit_slot 300000
ebb0:
    return
}
; check: function %big(i64 fp [%rbp]) -> i64 fp [%rbp] system_v {
; nextln:    ss0 = explicit_slot 300000, offset -300016
; nextln:    ss1 = incoming_arg 16, offset -16
; nextln: 
; nextln:                                 ebb0(v0: i64 [%rbp]):
; nextln: [RexOp1pushq#50]                    x86_push v0
; nextln: [RexOp1copysp#8089]                 copy_special %rsp -> %rbp
; nextln: [RexOp1adjustsp_id#d081]            adjust_sp_down_imm 0x0004_93e0
; nextln: [RexOp1adjustsp_id#8081]            adjust_sp_up_imm 0x0004_93e0
; nextln: [RexOp1popq#58,%rbp]                v1 = x86_pop.i64
; nextln: [Op1ret#c3]                         return v1
; nextln: }
