test compile precise-output
set opt_level=speed
target x86_64 has_bmi1

function %f1(i8, i8) -> i8 {
block0(v0: i8, v1: i8):
    v2 = band_not v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   andnl %edi, %esi, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   andnl %edi, %esi, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %reversed_operands(i8, i8) -> i8 {
block0(v0: i8, v1: i8):
    v2 = bnot v0
    v3 = band v2, v1
    return v3
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   andnl %esi, %edi, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   andnl %esi, %edi, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

