test compile precise-output
set enable_llvm_abi_extensions=true
target x86_64


function %clz(i128) -> i128 {
block0(v0: i128):
    v1 = clz v0
    return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rdi, %r8
;   movq $0xffffffffffffffff, %rcx
;   bsrq %rsi, %r9
;   cmovzq  %rcx, %r9, %r9
;   movl $0x3f, %edi
;   subq %r9, %rdi
;   movq $0xffffffffffffffff, %rdx
;   bsrq %r8, %r10
;   cmovzq  %rdx, %r10, %r10
;   movl $0x3f, %eax
;   subq %r10, %rax
;   addq $0x40, %rax
;   cmpq    $64, %rdi
;   cmovnzq %rdi, %rax, %rax
;   uninit  %rdx
;   xorq %rdx, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdi, %r8
;   movq $18446744073709551615, %rcx
;   bsrq %rsi, %r9
;   cmoveq %rcx, %r9
;   movl $0x3f, %edi
;   subq %r9, %rdi
;   movq $18446744073709551615, %rdx
;   bsrq %r8, %r10
;   cmoveq %rdx, %r10
;   movl $0x3f, %eax
;   subq %r10, %rax
;   addq $0x40, %rax
;   cmpq $0x40, %rdi
;   cmovneq %rdi, %rax
;   xorq %rdx, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %clz(i64) -> i64 {
block0(v0: i64):
    v1 = clz v0
    return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq $0xffffffffffffffff, %rax
;   bsrq %rdi, %r8
;   cmovzq  %rax, %r8, %r8
;   movl $0x3f, %eax
;   subq %r8, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq $18446744073709551615, %rax
;   bsrq %rdi, %r8
;   cmoveq %rax, %r8
;   movl $0x3f, %eax
;   subq %r8, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %clz(i32) -> i32 {
block0(v0: i32):
    v1 = clz v0
    return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq $0xffffffffffffffff, %rax
;   bsrl %edi, %r8d
;   cmovzl  %eax, %r8d, %r8d
;   movl $0x1f, %eax
;   subl %r8d, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq $18446744073709551615, %rax
;   bsrl %edi, %r8d
;   cmovel %eax, %r8d
;   movl $0x1f, %eax
;   subl %r8d, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %clz(i16) -> i16 {
block0(v0: i16):
    v1 = clz v0
    return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movzwq %di, %rax
;   movq $0xffffffffffffffff, %rdx
;   bsrq %rax, %r10
;   cmovzq  %rdx, %r10, %r10
;   movl $0x3f, %eax
;   subq %r10, %rax
;   subq $0x30, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movzwq %di, %rax
;   movq $18446744073709551615, %rdx
;   bsrq %rax, %r10
;   cmoveq %rdx, %r10
;   movl $0x3f, %eax
;   subq %r10, %rax
;   subq $0x30, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %clz(i8) -> i8 {
block0(v0: i8):
    v1 = clz v0
    return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movzbq %dil, %rax
;   movq $0xffffffffffffffff, %rdx
;   bsrq %rax, %r10
;   cmovzq  %rdx, %r10, %r10
;   movl $0x3f, %eax
;   subq %r10, %rax
;   subq $0x38, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movzbq %dil, %rax
;   movq $18446744073709551615, %rdx
;   bsrq %rax, %r10
;   cmoveq %rdx, %r10
;   movl $0x3f, %eax
;   subq %r10, %rax
;   subq $0x38, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

