test compile precise-output
target x86_64

function %f0(i64, i64) -> i64, i64 {
block0(v0: i64, v1: i64):
    v2 = load.i64 v1
    v3 = icmp eq v0, v2
    v4 = uextend.i64 v3
    v5 = select.i64 v3, v0, v1
    return v4, v5
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq (%rsi), %r8
;   cmpq %r8, %rdi
;   sete %r9b
;   movzbq %r9b, %rax
;   cmpq %r8, %rdi
;   movq %rsi, %rdx
;   cmoveq %rdi, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq (%rsi), %r8 ; trap: heap_oob
;   cmpq %r8, %rdi
;   sete %r9b
;   movzbq %r9b, %rax
;   cmpq %r8, %rdi
;   movq %rsi, %rdx
;   cmoveq %rdi, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f1(f64, i64) -> i64, f64 {
block0(v0: f64, v1: i64):
    v2 = load.f64 v1
    v3 = fcmp eq v0, v2
    v4 = uextend.i64 v3
    v5 = select.f64 v3, v0, v0
    return v4, v5
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movsd (%rdi), %xmm1
;   ucomisd %xmm1, %xmm0
;   setnp %r10b
;   sete %r11b
;   andl %r11d, %r10d
;   movzbq %r10b, %rax
;   ucomisd %xmm1, %xmm0
;   movdqa %xmm0, %xmm1
;   movsd %xmm0, %xmm0; jnp $next; movsd %xmm1, %xmm0; $next:
;   movsd %xmm0, %xmm0; jz $next; movsd %xmm1, %xmm0; $next:
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movsd (%rdi), %xmm1 ; trap: heap_oob
;   ucomisd %xmm1, %xmm0
;   setnp %r10b
;   sete %r11b
;   andl %r11d, %r10d
;   movzbq %r10b, %rax
;   ucomisd %xmm1, %xmm0
;   movdqa %xmm0, %xmm1
;   jnp 0x2c
;   movaps %xmm1, %xmm0
;   je 0x35
;   movaps %xmm1, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

