test compile precise-output
set enable_llvm_abi_extensions=true
target x86_64 has_bmi1


function %ctz(i128) -> i128 {
block0(v0: i128):
    v1 = ctz v0
    return v1
}

; VCode:
;   pushq %rbp
;   movq    %rsp, %rbp
; block0:
;   tzcntq %rdi, %rax
;   tzcntq %rsi, %r9
;   addq $0x40, %r9
;   cmpq    $64, %rax
;   cmovzq  %r9, %rax, %rax
;   uninit  %rdx
;   xorq %rdx, %rdx
;   movq    %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   tzcntq %rdi, %rax
;   tzcntq %rsi, %r9
;   addq $0x40, %r9
;   cmpq $0x40, %rax
;   cmoveq %r9, %rax
;   xorq %rdx, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ctz(i64) -> i64 {
block0(v0: i64):
    v1 = ctz v0
    return v1
}

; VCode:
;   pushq %rbp
;   movq    %rsp, %rbp
; block0:
;   tzcntq %rdi, %rax
;   movq    %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   tzcntq %rdi, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ctz(i32) -> i32 {
block0(v0: i32):
    v1 = ctz v0
    return v1
}

; VCode:
;   pushq %rbp
;   movq    %rsp, %rbp
; block0:
;   tzcntl %edi, %eax
;   movq    %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   tzcntl %edi, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ctz(i16) -> i16 {
block0(v0: i16):
    v1 = ctz v0
    return v1
}

; VCode:
;   pushq %rbp
;   movq    %rsp, %rbp
; block0:
;   movzwl %di, %ecx
;   orl $0x10000, %ecx
;   tzcntl %ecx, %eax
;   movq    %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movzwl %di, %ecx
;   orl $0x10000, %ecx
;   tzcntl %ecx, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ctz(i8) -> i8 {
block0(v0: i8):
    v1 = ctz v0
    return v1
}

; VCode:
;   pushq %rbp
;   movq    %rsp, %rbp
; block0:
;   movzbl %dil, %ecx
;   orl $0x100, %ecx
;   tzcntl %ecx, %eax
;   movq    %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movzbl %dil, %ecx
;   orl $0x100, %ecx
;   tzcntl %ecx, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

