test compile precise-output
target x86_64

;; We should get the checked-div/rem sequence (`srem` pseudoinst below).
;; The machine will SIGFPE in some
;; cases when `srem` is valid (specifically -INT_MIN % -1).

function %i8(i8, i8) -> i8 {
block0(v0: i8, v1: i8):
  v2 = srem.i8 v0, v1

  return v2
}

; VCode:
;   pushq   %rbp
;   movq    %rsp, %rbp
; block0:
;   movq    %rdi, %rax
;   cbtw  ;; implicit: %ax
;   checked_srem_seq %al, %sil, %al
;   shrq $0x8, %rax
;   movq    %rbp, %rsp
;   popq    %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdi, %rax
;   cbtw
;   cmpb $0xff, %sil
;   jne 0x1d
;   movl $0, %eax
;   jmp 0x20
;   idivb %sil ; trap: int_divz
;   shrq $8, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %i16(i16, i16) -> i16 {
block0(v0: i16, v1: i16):
  v2 = srem.i16 v0, v1

  return v2
}

; VCode:
;   pushq   %rbp
;   movq    %rsp, %rbp
; block0:
;   movq    %rdi, %rax
;   cwtd  ;; implicit: %dx, %ax
;   checked_srem_seq %ax, %dx, %si, %ax, %dx
;   movq    %rdx, %rax
;   movq    %rbp, %rsp
;   popq    %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdi, %rax
;   cwtd
;   cmpw $-1, %si
;   jne 0x1d
;   movl $0, %edx
;   jmp 0x20
;   idivw %si ; trap: int_divz
;   movq %rdx, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = srem.i32 v0, v1

  return v2
}

; VCode:
;   pushq   %rbp
;   movq    %rsp, %rbp
; block0:
;   movq    %rdi, %rax
;   cltd  ;; implicit: %edx, %eax
;   checked_srem_seq %eax, %edx, %esi, %eax, %edx
;   movq    %rdx, %rax
;   movq    %rbp, %rsp
;   popq    %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdi, %rax
;   cltd
;   cmpl $-1, %esi
;   jne 0x1b
;   movl $0, %edx
;   jmp 0x1d
;   idivl %esi ; trap: int_divz
;   movq %rdx, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
  v2 = srem.i64 v0, v1

  return v2
}

; VCode:
;   pushq   %rbp
;   movq    %rsp, %rbp
; block0:
;   movq    %rdi, %rax
;   cqto  ;; implicit: %rdx, %rax
;   checked_srem_seq %rax, %rdx, %rsi, %rax, %rdx
;   movq    %rdx, %rax
;   movq    %rbp, %rsp
;   popq    %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdi, %rax
;   cqto
;   cmpq $-1, %rsi
;   jne 0x1d
;   movl $0, %edx
;   jmp 0x20
;   idivq %rsi ; trap: int_divz
;   movq %rdx, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

