test compile precise-output
target x86_64 sse41

function %f1(i8) -> f32 {
block0(v0: i8):
  v1 = fcvt_from_sint.f32 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   uninit  %xmm0
;   xorps %xmm0, %xmm0
;   movsbl %dil, %r9d
;   cvtsi2ssl %r9d, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   xorps %xmm0, %xmm0
;   movsbl %dil, %r9d
;   cvtsi2ssl %r9d, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f2(i16) -> f32 {
block0(v0: i16):
  v1 = fcvt_from_sint.f32 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   uninit  %xmm0
;   xorps %xmm0, %xmm0
;   movswl %di, %r9d
;   cvtsi2ssl %r9d, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   xorps %xmm0, %xmm0
;   movswl %di, %r9d
;   cvtsi2ssl %r9d, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f3(i32) -> f32 {
block0(v0: i32):
  v1 = fcvt_from_sint.f32 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   uninit  %xmm0
;   xorps %xmm0, %xmm0
;   cvtsi2ssl %edi, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   xorps %xmm0, %xmm0
;   cvtsi2ssl %edi, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f4(i64) -> f32 {
block0(v0: i64):
  v1 = fcvt_from_sint.f32 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   uninit  %xmm0
;   xorps %xmm0, %xmm0
;   cvtsi2ssq %rdi, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   xorps %xmm0, %xmm0
;   cvtsi2ssq %rdi, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f5(i8) -> f64 {
block0(v0: i8):
  v1 = fcvt_from_sint.f64 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   uninit  %xmm0
;   xorpd %xmm0, %xmm0
;   movsbl %dil, %r9d
;   cvtsi2sdl %r9d, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   xorpd %xmm0, %xmm0
;   movsbl %dil, %r9d
;   cvtsi2sdl %r9d, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f6(i16) -> f64 {
block0(v0: i16):
  v1 = fcvt_from_sint.f64 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   uninit  %xmm0
;   xorpd %xmm0, %xmm0
;   movswl %di, %r9d
;   cvtsi2sdl %r9d, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   xorpd %xmm0, %xmm0
;   movswl %di, %r9d
;   cvtsi2sdl %r9d, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f7(i32) -> f64 {
block0(v0: i32):
  v1 = fcvt_from_sint.f64 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   uninit  %xmm0
;   xorpd %xmm0, %xmm0
;   cvtsi2sdl %edi, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   xorpd %xmm0, %xmm0
;   cvtsi2sdl %edi, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f8(i64) -> f64 {
block0(v0: i64):
  v1 = fcvt_from_sint.f64 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   uninit  %xmm0
;   xorpd %xmm0, %xmm0
;   cvtsi2sdq %rdi, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   xorpd %xmm0, %xmm0
;   cvtsi2sdq %rdi, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f9(i32x4) -> f64x2 {
block0(v0: i32x4):
  v1 = swiden_low v0
  v2 = fcvt_from_sint.f64x2 v1
  return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   cvtdq2pd %xmm0, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   cvtdq2pd %xmm0, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f10(i8, i16, i32, i64) -> f32 {
block0(v0: i8, v1: i16, v2: i32, v3: i64):
  v4 = fcvt_from_uint.f32 v0
  v5 = fcvt_from_uint.f32 v1
  v6 = fcvt_from_uint.f32 v2
  v7 = fcvt_from_uint.f32 v3
  v8 = fadd.f32 v4, v5
  v9 = fadd.f32 v8, v6
  v10 = fadd.f32 v9, v7
  return v10
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   uninit  %xmm0
;   xorps %xmm0, %xmm0
;   movzbq %dil, %r8
;   cvtsi2ssq %r8, %xmm0
;   uninit  %xmm6
;   xorps %xmm6, %xmm6
;   movzwq %si, %r8
;   cvtsi2ssq %r8, %xmm6
;   uninit  %xmm7
;   xorps %xmm7, %xmm7
;   movl %edx, %r8d
;   cvtsi2ssq %r8, %xmm7
;   u64_to_f32_seq %rcx, %xmm4, %r8, %rdx
;   addss %xmm6, %xmm0
;   addss %xmm7, %xmm0
;   addss %xmm4, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   xorps %xmm0, %xmm0
;   movzbq %dil, %r8
;   cvtsi2ssq %r8, %xmm0
;   xorps %xmm6, %xmm6
;   movzwq %si, %r8
;   cvtsi2ssq %r8, %xmm6
;   xorps %xmm7, %xmm7
;   movl %edx, %r8d
;   cvtsi2ssq %r8, %xmm7
;   cmpq $0, %rcx
;   jl 0x3b
;   cvtsi2ssq %rcx, %xmm4
;   jmp 0x55
;   movq %rcx, %r8
;   shrq $1, %r8
;   movq %rcx, %rdx
;   andq $1, %rdx
;   orq %r8, %rdx
;   cvtsi2ssq %rdx, %xmm4
;   addss %xmm4, %xmm4
;   addss %xmm6, %xmm0
;   addss %xmm7, %xmm0
;   addss %xmm4, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f11(i32x4) -> f64x2 {
block0(v0: i32x4):
  v1 = uwiden_low v0
  v2 = fcvt_from_uint.f64x2 v1
  return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   unpcklps (%rip), %xmm0
;   subpd (%rip), %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   unpcklps 0x15(%rip), %xmm0
;   subpd 0x1d(%rip), %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   xorb %al, (%rbx)
;   addb %dh, (%rax)
;   addb %al, (%r8)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   xorb %al, (%rbx)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %dh, (%rax)

function %f12(i32x4) -> f32x4 {
block0(v0: i32x4):
  v1 = fcvt_from_uint.f32x4 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movdqa %xmm0, %xmm3
;   pslld $0x10, %xmm3
;   psrld $0x10, %xmm3
;   psubd %xmm3, %xmm0
;   cvtdq2ps %xmm3, %xmm1
;   psrld $0x1, %xmm0
;   cvtdq2ps %xmm0, %xmm0
;   addps %xmm0, %xmm0
;   addps %xmm1, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movdqa %xmm0, %xmm3
;   pslld $0x10, %xmm3
;   psrld $0x10, %xmm3
;   psubd %xmm3, %xmm0
;   cvtdq2ps %xmm3, %xmm1
;   psrld $1, %xmm0
;   cvtdq2ps %xmm0, %xmm0
;   addps %xmm0, %xmm0
;   addps %xmm1, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f13(f32) -> i32 {
block0(v0: f32):
  v1 = fcvt_to_uint.i32 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   cvt_float32_to_uint32_seq %xmm0, %eax, %r8, %xmm3, %xmm4
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movl $0x4f000000, %r8d
;   movd %r8d, %xmm3
;   ucomiss %xmm3, %xmm0
;   jae 0x2d
;   jp 0x4c
;   cvttss2si %xmm0, %eax
;   cmpl $0, %eax
;   jge 0x47
;   ud2 ; trap: int_ovf
;   movaps %xmm0, %xmm4
;   subss %xmm3, %xmm4
;   cvttss2si %xmm4, %eax
;   cmpl $0, %eax
;   jl 0x4e
;   addl $0x80000000, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;   ud2 ; trap: bad_toint
;   ud2 ; trap: int_ovf

function %f14(f32) -> i64 {
block0(v0: f32):
  v1 = fcvt_to_uint.i64 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   cvt_float32_to_uint64_seq %xmm0, %rax, %r8, %xmm3, %xmm4
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movl $0x5f000000, %r8d
;   movd %r8d, %xmm3
;   ucomiss %xmm3, %xmm0
;   jae 0x2f
;   jp 0x57
;   cvttss2si %xmm0, %rax
;   cmpq $0, %rax
;   jge 0x52
;   ud2 ; trap: int_ovf
;   movaps %xmm0, %xmm4
;   subss %xmm3, %xmm4
;   cvttss2si %xmm4, %rax
;   cmpq $0, %rax
;   jl 0x59
;   movabsq $9223372036854775808, %r8
;   addq %r8, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;   ud2 ; trap: bad_toint
;   ud2 ; trap: int_ovf

function %f15(f64) -> i32 {
block0(v0: f64):
  v1 = fcvt_to_uint.i32 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   cvt_float64_to_uint32_seq %xmm0, %eax, %r8, %xmm3, %xmm4
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movabsq $0x41e0000000000000, %r8
;   movq %r8, %xmm3
;   ucomisd %xmm3, %xmm0
;   jae 0x32
;   jp 0x51
;   cvttsd2si %xmm0, %eax
;   cmpl $0, %eax
;   jge 0x4c
;   ud2 ; trap: int_ovf
;   movaps %xmm0, %xmm4
;   subsd %xmm3, %xmm4
;   cvttsd2si %xmm4, %eax
;   cmpl $0, %eax
;   jl 0x53
;   addl $0x80000000, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;   ud2 ; trap: bad_toint
;   ud2 ; trap: int_ovf

function %f16(f64) -> i64 {
block0(v0: f64):
  v1 = fcvt_to_uint.i64 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   cvt_float64_to_uint64_seq %xmm0, %rax, %r8, %xmm3, %xmm4
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movabsq $0x43e0000000000000, %r8
;   movq %r8, %xmm3
;   ucomisd %xmm3, %xmm0
;   jae 0x34
;   jp 0x5c
;   cvttsd2si %xmm0, %rax
;   cmpq $0, %rax
;   jge 0x57
;   ud2 ; trap: int_ovf
;   movaps %xmm0, %xmm4
;   subsd %xmm3, %xmm4
;   cvttsd2si %xmm4, %rax
;   cmpq $0, %rax
;   jl 0x5e
;   movabsq $9223372036854775808, %r8
;   addq %r8, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;   ud2 ; trap: bad_toint
;   ud2 ; trap: int_ovf

function %f17(f32) -> i32 {
block0(v0: f32):
  v1 = fcvt_to_uint_sat.i32 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   cvt_float32_to_uint32_sat_seq %xmm0, %eax, %r8, %xmm3, %xmm4
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movl $0x4f000000, %r8d
;   movd %r8d, %xmm3
;   ucomiss %xmm3, %xmm0
;   jae 0x39
;   jnp 0x25
;   xorl %eax, %eax
;   jmp 0x5d
;   cvttss2si %xmm0, %eax
;   cmpl $0, %eax
;   jge 0x5d
;   xorl %eax, %eax
;   jmp 0x5d
;   movaps %xmm0, %xmm4
;   subss %xmm3, %xmm4
;   cvttss2si %xmm4, %eax
;   cmpl $0, %eax
;   jge 0x57
;   movl $0xffffffff, %eax
;   jmp 0x5d
;   addl $0x80000000, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f18(f32) -> i64 {
block0(v0: f32):
  v1 = fcvt_to_uint_sat.i64 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   cvt_float32_to_uint64_sat_seq %xmm0, %rax, %r8, %xmm3, %xmm4
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movl $0x5f000000, %r8d
;   movd %r8d, %xmm3
;   ucomiss %xmm3, %xmm0
;   jae 0x3d
;   jnp 0x26
;   xorq %rax, %rax
;   jmp 0x6c
;   cvttss2si %xmm0, %rax
;   cmpq $0, %rax
;   jge 0x6c
;   xorq %rax, %rax
;   jmp 0x6c
;   movaps %xmm0, %xmm4
;   subss %xmm3, %xmm4
;   cvttss2si %xmm4, %rax
;   cmpq $0, %rax
;   jge 0x5f
;   movq $18446744073709551615, %rax
;   jmp 0x6c
;   movabsq $9223372036854775808, %r8
;   addq %r8, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f19(f64) -> i32 {
block0(v0: f64):
  v1 = fcvt_to_uint_sat.i32 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   cvt_float64_to_uint32_sat_seq %xmm0, %eax, %r8, %xmm3, %xmm4
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movabsq $0x41e0000000000000, %r8
;   movq %r8, %xmm3
;   ucomisd %xmm3, %xmm0
;   jae 0x3e
;   jnp 0x2a
;   xorl %eax, %eax
;   jmp 0x62
;   cvttsd2si %xmm0, %eax
;   cmpl $0, %eax
;   jge 0x62
;   xorl %eax, %eax
;   jmp 0x62
;   movaps %xmm0, %xmm4
;   subsd %xmm3, %xmm4
;   cvttsd2si %xmm4, %eax
;   cmpl $0, %eax
;   jge 0x5c
;   movl $0xffffffff, %eax
;   jmp 0x62
;   addl $0x80000000, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f20(f64) -> i64 {
block0(v0: f64):
  v1 = fcvt_to_uint_sat.i64 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   cvt_float64_to_uint64_sat_seq %xmm0, %rax, %r8, %xmm3, %xmm4
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movabsq $0x43e0000000000000, %r8
;   movq %r8, %xmm3
;   ucomisd %xmm3, %xmm0
;   jae 0x42
;   jnp 0x2b
;   xorq %rax, %rax
;   jmp 0x71
;   cvttsd2si %xmm0, %rax
;   cmpq $0, %rax
;   jge 0x71
;   xorq %rax, %rax
;   jmp 0x71
;   movaps %xmm0, %xmm4
;   subsd %xmm3, %xmm4
;   cvttsd2si %xmm4, %rax
;   cmpq $0, %rax
;   jge 0x64
;   movq $18446744073709551615, %rax
;   jmp 0x71
;   movabsq $9223372036854775808, %r8
;   addq %r8, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f21(f32) -> i32 {
block0(v0: f32):
  v1 = fcvt_to_sint.i32 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   cvt_float32_to_sint32_seq %xmm0, %eax, %rdx, %xmm3
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   cvttss2si %xmm0, %eax
;   cmpl $1, %eax
;   jno 0x39
;   ucomiss %xmm0, %xmm0
;   jp 0x3e
;   movl $0xcf000000, %edx
;   movd %edx, %xmm3
;   ucomiss %xmm3, %xmm0
;   jb 0x40
;   xorpd %xmm3, %xmm3
;   ucomiss %xmm0, %xmm3
;   jb 0x42
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;   ud2 ; trap: bad_toint
;   ud2 ; trap: int_ovf
;   ud2 ; trap: int_ovf

function %f22(f32) -> i64 {
block0(v0: f32):
  v1 = fcvt_to_sint.i64 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   cvt_float32_to_sint64_seq %xmm0, %rax, %rdx, %xmm3
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   cvttss2si %xmm0, %rax
;   cmpq $1, %rax
;   jno 0x3b
;   ucomiss %xmm0, %xmm0
;   jp 0x40
;   movl $0xdf000000, %edx
;   movd %edx, %xmm3
;   ucomiss %xmm3, %xmm0
;   jb 0x42
;   xorpd %xmm3, %xmm3
;   ucomiss %xmm0, %xmm3
;   jb 0x44
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;   ud2 ; trap: bad_toint
;   ud2 ; trap: int_ovf
;   ud2 ; trap: int_ovf

function %f23(f64) -> i32 {
block0(v0: f64):
  v1 = fcvt_to_sint.i32 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   cvt_float64_to_sint32_seq %xmm0, %eax, %rdx, %xmm3
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   cvttsd2si %xmm0, %eax
;   cmpl $1, %eax
;   jno 0x42
;   ucomisd %xmm0, %xmm0
;   jp 0x47
;   movabsq $13970166044105375744, %rdx
;   movq %rdx, %xmm3
;   ucomisd %xmm3, %xmm0
;   jbe 0x49
;   xorpd %xmm3, %xmm3
;   ucomisd %xmm0, %xmm3
;   jb 0x4b
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;   ud2 ; trap: bad_toint
;   ud2 ; trap: int_ovf
;   ud2 ; trap: int_ovf

function %f24(f64) -> i64 {
block0(v0: f64):
  v1 = fcvt_to_sint.i64 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   cvt_float64_to_sint64_seq %xmm0, %rax, %rdx, %xmm3
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   cvttsd2si %xmm0, %rax
;   cmpq $1, %rax
;   jno 0x44
;   ucomisd %xmm0, %xmm0
;   jp 0x49
;   movabsq $14114281232179134464, %rdx
;   movq %rdx, %xmm3
;   ucomisd %xmm3, %xmm0
;   jb 0x4b
;   xorpd %xmm3, %xmm3
;   ucomisd %xmm0, %xmm3
;   jb 0x4d
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;   ud2 ; trap: bad_toint
;   ud2 ; trap: int_ovf
;   ud2 ; trap: int_ovf

function %f25(f32) -> i32 {
block0(v0: f32):
  v1 = fcvt_to_sint_sat.i32 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   cvt_float32_to_sint32_sat_seq %xmm0, %eax, %rdx, %xmm3
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   cvttss2si %xmm0, %eax
;   cmpl $1, %eax
;   jno 0x33
;   ucomiss %xmm0, %xmm0
;   jnp 0x21
;   xorl %eax, %eax
;   jmp 0x33
;   xorpd %xmm3, %xmm3
;   ucomiss %xmm0, %xmm3
;   jae 0x33
;   movl $0x7fffffff, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f26(f32) -> i64 {
block0(v0: f32):
  v1 = fcvt_to_sint_sat.i64 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   cvt_float32_to_sint64_sat_seq %xmm0, %rax, %rdx, %xmm3
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   cvttss2si %xmm0, %rax
;   cmpq $1, %rax
;   jno 0x3b
;   ucomiss %xmm0, %xmm0
;   jnp 0x24
;   xorq %rax, %rax
;   jmp 0x3b
;   xorpd %xmm3, %xmm3
;   ucomiss %xmm0, %xmm3
;   jae 0x3b
;   movabsq $0x7fffffffffffffff, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f27(f64) -> i32 {
block0(v0: f64):
  v1 = fcvt_to_sint_sat.i32 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   cvt_float64_to_sint32_sat_seq %xmm0, %eax, %rdx, %xmm3
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   cvttsd2si %xmm0, %eax
;   cmpl $1, %eax
;   jno 0x35
;   ucomisd %xmm0, %xmm0
;   jnp 0x22
;   xorl %eax, %eax
;   jmp 0x35
;   xorpd %xmm3, %xmm3
;   ucomisd %xmm0, %xmm3
;   jae 0x35
;   movl $0x7fffffff, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f28(f64) -> i64 {
block0(v0: f64):
  v1 = fcvt_to_sint_sat.i64 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   cvt_float64_to_sint64_sat_seq %xmm0, %rax, %rdx, %xmm3
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   cvttsd2si %xmm0, %rax
;   cmpq $1, %rax
;   jno 0x3d
;   ucomisd %xmm0, %xmm0
;   jnp 0x25
;   xorq %rax, %rax
;   jmp 0x3d
;   xorpd %xmm3, %xmm3
;   ucomisd %xmm0, %xmm3
;   jae 0x3d
;   movabsq $0x7fffffffffffffff, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f29(f32x4) -> i32x4 {
block0(v0: f32x4):
  v1 = fcvt_to_uint_sat.i32x4 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   uninit  %xmm6
;   xorps %xmm6, %xmm6
;   maxps %xmm6, %xmm0
;   pcmpeqd %xmm6, %xmm6
;   psrld $0x1, %xmm6
;   cvtdq2ps %xmm6, %xmm7
;   cvttps2dq %xmm0, %xmm6
;   subps %xmm7, %xmm0
;   cmpleps %xmm0, %xmm7
;   cvttps2dq %xmm0, %xmm0
;   pxor %xmm7, %xmm0
;   uninit  %xmm1
;   pxor %xmm1, %xmm1
;   pmaxsd %xmm1, %xmm0
;   paddd %xmm6, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   xorps %xmm6, %xmm6
;   maxps %xmm6, %xmm0
;   pcmpeqd %xmm6, %xmm6
;   psrld $1, %xmm6
;   cvtdq2ps %xmm6, %xmm7
;   cvttps2dq %xmm0, %xmm6
;   subps %xmm7, %xmm0
;   cmpleps %xmm0, %xmm7
;   cvttps2dq %xmm0, %xmm0
;   pxor %xmm7, %xmm0
;   pxor %xmm1, %xmm1
;   pmaxsd %xmm1, %xmm0
;   paddd %xmm6, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f30(f32x4) -> i32x4 {
block0(v0: f32x4):
  v1 = fcvt_to_sint_sat.i32x4 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movdqa %xmm0, %xmm4
;   cmpeqps %xmm0, %xmm4
;   andps %xmm4, %xmm0
;   pxor %xmm0, %xmm4
;   cvttps2dq %xmm0, %xmm1
;   movdqa %xmm1, %xmm0
;   pand %xmm4, %xmm0
;   psrad $0x1f, %xmm0
;   pxor %xmm1, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movdqa %xmm0, %xmm4
;   cmpeqps %xmm0, %xmm4
;   andps %xmm4, %xmm0
;   pxor %xmm0, %xmm4
;   cvttps2dq %xmm0, %xmm1
;   movdqa %xmm1, %xmm0
;   pand %xmm4, %xmm0
;   psrad $0x1f, %xmm0
;   pxor %xmm1, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %u64x2_to_f64x2(i64x2) -> f64x2 {
block0(v0: i64x2):
  v1 = fcvt_from_uint.f64x2 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movdqa %xmm0, %xmm7
;   pand (%rip), %xmm7
;   movdqa %xmm7, %xmm1
;   por (%rip), %xmm1
;   movdqa %xmm1, %xmm7
;   psrlq $0x20, %xmm0
;   por (%rip), %xmm0
;   subpd (%rip), %xmm0
;   movdqa %xmm0, %xmm1
;   movdqa %xmm7, %xmm0
;   addpd %xmm1, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movdqa %xmm0, %xmm7
;   pand 0x40(%rip), %xmm7
;   movdqa %xmm7, %xmm1
;   por 0x44(%rip), %xmm1
;   movdqa %xmm1, %xmm7
;   psrlq $0x20, %xmm0
;   por 0x43(%rip), %xmm0
;   subpd 0x4b(%rip), %xmm0
;   movdqa %xmm0, %xmm1
;   movdqa %xmm7, %xmm0
;   addpd %xmm1, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)

function %i64x2_to_f64x2(i64x2) -> f64x2 {
block0(v0: i64x2):
  v1 = fcvt_from_sint.f64x2 v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   uninit  %xmm1
;   xorpd %xmm1, %xmm1
;   movdqa %xmm0, %xmm6
;   movq %xmm6, %r9
;   movdqa %xmm1, %xmm0
;   cvtsi2sdq %r9, %xmm0
;   pshufd $0xee, %xmm6, %xmm2
;   movq %xmm2, %rcx
;   cvtsi2sdq %rcx, %xmm1
;   unpcklpd %xmm1, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   xorpd %xmm1, %xmm1
;   movdqa %xmm0, %xmm6
;   movq %xmm6, %r9
;   movdqa %xmm1, %xmm0
;   cvtsi2sdq %r9, %xmm0
;   pshufd $0xee, %xmm6, %xmm2
;   movq %xmm2, %rcx
;   cvtsi2sdq %rcx, %xmm1
;   unpcklpd %xmm1, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

