test compile precise-output
set preserve_frame_pointers=true
target x86_64

function %fp() -> i64 {
block0:
    v0 = get_frame_pointer.i64
    return v0
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq    %rbp, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rbp, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sp() -> i64 {
block0:
    v0 = get_stack_pointer.i64
    return v0
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq    %rsp, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsp, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %return_address() -> i64 {
block0:
    v0 = get_return_address.i64
    return v0
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq    %rbp, %rsi
;   movq 8(%rsi), %rax
;   movq %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rbp, %rsi
;   movq 8(%rsi), %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

