test compile precise-output
set enable_simd
target x86_64 has_avx

function %sqrt_f32(f32) -> f32 {
block0(v0: f32):
    v1 = sqrt v0
    return v1
}

; VCode:
;   pushq   %rbp
;   movq    %rsp, %rbp
; block0:
;   vsqrtss %xmm0, %xmm0
;   movq    %rbp, %rsp
;   popq    %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vsqrtss %xmm0, %xmm0, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sqrt_f64(f64) -> f64 {
block0(v0: f64):
    v1 = sqrt v0
    return v1
}

; VCode:
;   pushq   %rbp
;   movq    %rsp, %rbp
; block0:
;   vsqrtsd %xmm0, %xmm0
;   movq    %rbp, %rsp
;   popq    %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vsqrtsd %xmm0, %xmm0, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

