test compile precise-output
target x86_64

function u1:6() system_v {
    sig0 = () tail
    fn0 = u1:7 sig0

block0:
    v5 = func_addr.i64 fn0
    call_indirect sig0, v5()
    call_indirect sig0, v5()
    return
}

; VCode:
;   pushq   %rbp
;   movq    %rsp, %rbp
;   subq $0x10, %rsp
;   movq    %rbx, 0(%rsp)
; block0:
;   load_ext_name userextname0+0, %rbx
;   call    *%rbx
;   call    *%rbx
;   movq (%rsp), %rbx
;   addq $0x10, %rsp
;   movq    %rbp, %rsp
;   popq    %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
;   subq $0x10, %rsp
;   movq %rbx, (%rsp)
; block1: ; offset 0xc
;   movabsq $0, %rbx ; reloc_external Abs8 u1:7 0
;   callq *%rbx
;   callq *%rbx
;   movq (%rsp), %rbx
;   addq $0x10, %rsp
;   movq %rbp, %rsp
;   popq %rbp
;   retq

