test compile precise-output
target x86_64

function %f0(i32) -> i32 {
block0(v0: i32):
    v1 = iconst.i32 127
    v2 = iadd_overflow_trap v0, v1, user0
    return v2
}

;   pushq   %rbp
;   movq    %rsp, %rbp
; block0:
;   movq    %rdi, %rax
;   addl    %eax, $127, %eax
;   jnb ; ud2 user0 ;
;   movq    %rbp, %rsp
;   popq    %rbp
;   ret

function %f1(i32) -> i32 {
block0(v0: i32):
    v1 = iconst.i32 127
    v2 = iadd_overflow_trap v1, v0, user0
    return v2
}

;   pushq   %rbp
;   movq    %rsp, %rbp
; block0:
;   movq    %rdi, %rax
;   addl    %eax, $127, %eax
;   jnb ; ud2 user0 ;
;   movq    %rbp, %rsp
;   popq    %rbp
;   ret

function %f2(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = iadd_overflow_trap v0, v1, user0
    return v2
}

;   pushq   %rbp
;   movq    %rsp, %rbp
; block0:
;   movq    %rdi, %rax
;   addl    %eax, %esi, %eax
;   jnb ; ud2 user0 ;
;   movq    %rbp, %rsp
;   popq    %rbp
;   ret

function %f3(i64) -> i64 {
block0(v0: i64):
    v1 = iconst.i64 127
    v2 = iadd_overflow_trap v0, v1, user0
    return v2
}

;   pushq   %rbp
;   movq    %rsp, %rbp
; block0:
;   movq    %rdi, %rax
;   addq    %rax, $127, %rax
;   jnb ; ud2 user0 ;
;   movq    %rbp, %rsp
;   popq    %rbp
;   ret

function %f3(i64) -> i64 {
block0(v0: i64):
    v1 = iconst.i64 127
    v2 = iadd_overflow_trap v1, v0, user0
    return v2
}

;   pushq   %rbp
;   movq    %rsp, %rbp
; block0:
;   movq    %rdi, %rax
;   addq    %rax, $127, %rax
;   jnb ; ud2 user0 ;
;   movq    %rbp, %rsp
;   popq    %rbp
;   ret

function %f4(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = iadd_overflow_trap v0, v1, user0
    return v2
}

;   pushq   %rbp
;   movq    %rsp, %rbp
; block0:
;   movq    %rdi, %rax
;   addq    %rax, %rsi, %rax
;   jnb ; ud2 user0 ;
;   movq    %rbp, %rsp
;   popq    %rbp
;   ret

