test compile precise-output
set enable_probestack=true
; Test with the larger size of 64k
set probestack_size_log2=16
set probestack_strategy=inline
target x86_64



; If the stack size is just one page, we can avoid the stack probe entirely
function %single_page() -> i64 system_v {
ss0 = explicit_slot 8192

block0:
  v1 = stack_addr.i64 ss0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
;   subq $0x2000, %rsp
; block0:
;   lea     rsp(0 + virtual offset), %rax
;   addq $0x2000, %rsp
;   movq %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
;   subq $0x2000, %rsp
; block1: ; offset 0xb
;   leaq (%rsp), %rax
;   addq $0x2000, %rsp
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %unrolled() -> i64 system_v {
ss0 = explicit_slot 196608

block0:
  v1 = stack_addr.i64 ss0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
;   subq $0x10000, %rsp
;   movl %esp, (%rsp)
;   subq $0x10000, %rsp
;   movl %esp, (%rsp)
;   subq $0x10000, %rsp
;   movl %esp, (%rsp)
;   addq $0x30000, %rsp
;   subq $0x30000, %rsp
; block0:
;   lea     rsp(0 + virtual offset), %rax
;   addq $0x30000, %rsp
;   movq %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
;   subq $0x10000, %rsp
;   movl %esp, (%rsp)
;   subq $0x10000, %rsp
;   movl %esp, (%rsp)
;   subq $0x10000, %rsp
;   movl %esp, (%rsp)
;   addq $0x30000, %rsp
;   subq $0x30000, %rsp
; block1: ; offset 0x30
;   leaq (%rsp), %rax
;   addq $0x30000, %rsp
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %large() -> i64 system_v {
ss0 = explicit_slot 2097152

block0:
  v1 = stack_addr.i64 ss0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
;   stack_probe_loop %r11, frame_size=2097152, guard_size=65536
;   subq $0x200000, %rsp
; block0:
;   lea     rsp(0 + virtual offset), %rax
;   addq $0x200000, %rsp
;   movq %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
;   movq %rsp, %r11
;   subq $0x200000, %r11
;   subq $0x10000, %rsp
;   movl %esp, (%rsp)
;   cmpq %rsp, %r11
;   jne 0xe
;   addq $0x200000, %rsp
;   subq $0x200000, %rsp
; block1: ; offset 0x2f
;   leaq (%rsp), %rax
;   addq $0x200000, %rsp
;   movq %rbp, %rsp
;   popq %rbp
;   retq

