test compile precise-output
set unwind_info=false
set opt_level=speed
target x86_64

function %imul_i16_const_unsigned_but_big(i32) -> i16 {
block0(v0: i32):
    v5 = iconst.i32 528657
    v3 = imul v0, v5
    v4 = ireduce.i16 v3
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   imulw $0x1111, %di, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   imulw $0x1111, %di, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

