test compile precise-output
set enable_nan_canonicalization=true
target x86_64 sse41

function %f0(f32x4, f32x4) -> f32x4 {
block0(v0: f32x4, v1: f32x4):
	v2 = fadd v0, v1
	return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   addps %xmm1, %xmm0
;   movl $0x7fc00000, %edi
;   movd %edi, %xmm7
;   shufps $0x0, (%rip), %xmm7
;   movdqa %xmm0, %xmm1
;   cmpunordps %xmm0, %xmm1
;   movdqa %xmm0, %xmm2
;   movdqa %xmm1, %xmm0
;   movdqa %xmm2, %xmm1
;   pblendvb %xmm0, %xmm7, %xmm1
;   movdqa %xmm1, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   addps %xmm1, %xmm0
;   movl $0x7fc00000, %edi
;   movd %edi, %xmm7
;   shufps $0, 0x28(%rip), %xmm7
;   movdqa %xmm0, %xmm1
;   cmpunordps %xmm0, %xmm1
;   movdqa %xmm0, %xmm2
;   movdqa %xmm1, %xmm0
;   movdqa %xmm2, %xmm1
;   pblendvb %xmm0, %xmm7, %xmm1
;   movdqa %xmm1, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   sarb $0, (%rdi)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)

function %f1(f64, f64) -> f64 {
block0(v0: f64, v1: f64):
	v2 = fadd v0, v1
	return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   addsd %xmm1, %xmm0
;   movdqa %xmm0, %xmm2
;   movabsq $0x7ff8000000000000, %rax
;   movq %rax, %xmm0
;   uninit  %xmm1
;   xorpd %xmm1, %xmm1
;   movsd %xmm0, %xmm1
;   uninit  %xmm0
;   xorpd %xmm0, %xmm0
;   movsd %xmm2, %xmm0
;   movdqa %xmm0, %xmm2
;   cmpunordpd %xmm0, %xmm2
;   movdqa %xmm0, %xmm3
;   movdqa %xmm2, %xmm0
;   movdqa %xmm3, %xmm2
;   pblendvb %xmm0, %xmm1, %xmm2
;   movdqa %xmm2, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   addsd %xmm1, %xmm0
;   movdqa %xmm0, %xmm2
;   movabsq $0x7ff8000000000000, %rax
;   movq %rax, %xmm0
;   xorpd %xmm1, %xmm1
;   movsd %xmm0, %xmm1
;   xorpd %xmm0, %xmm0
;   movsd %xmm2, %xmm0
;   movdqa %xmm0, %xmm2
;   cmpunordpd %xmm0, %xmm2
;   movdqa %xmm0, %xmm3
;   movdqa %xmm2, %xmm0
;   movdqa %xmm3, %xmm2
;   pblendvb %xmm0, %xmm1, %xmm2
;   movdqa %xmm2, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f1(f32, f32) -> f32 {
block0(v0: f32, v1: f32):
	v2 = fadd v0, v1
	return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   addss %xmm1, %xmm0
;   movdqa %xmm0, %xmm2
;   movl $0x7fc00000, %eax
;   movd %eax, %xmm0
;   uninit  %xmm1
;   xorps %xmm1, %xmm1
;   movss %xmm0, %xmm1
;   uninit  %xmm0
;   xorps %xmm0, %xmm0
;   movss %xmm2, %xmm0
;   movdqa %xmm0, %xmm2
;   cmpunordps %xmm0, %xmm2
;   movdqa %xmm0, %xmm3
;   movdqa %xmm2, %xmm0
;   movdqa %xmm3, %xmm2
;   pblendvb %xmm0, %xmm1, %xmm2
;   movdqa %xmm2, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   addss %xmm1, %xmm0
;   movdqa %xmm0, %xmm2
;   movl $0x7fc00000, %eax
;   movd %eax, %xmm0
;   xorps %xmm1, %xmm1
;   movss %xmm0, %xmm1
;   xorps %xmm0, %xmm0
;   movss %xmm2, %xmm0
;   movdqa %xmm0, %xmm2
;   cmpunordps %xmm0, %xmm2
;   movdqa %xmm0, %xmm3
;   movdqa %xmm2, %xmm0
;   movdqa %xmm3, %xmm2
;   pblendvb %xmm0, %xmm1, %xmm2
;   movdqa %xmm2, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

