test compile precise-output
set enable_nan_canonicalization=true 
target x86_64

function %f0(f32x4, f32x4) -> f32x4 {
block0(v0: f32x4, v1: f32x4):
	v2 = fadd v0, v1
	return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   addps %xmm1, %xmm0
;   movdqa %xmm0, %xmm1
;   movl $0x7fc00000, %esi
;   movd %esi, %xmm5
;   shufps  $0, %xmm5, const(0), %xmm5
;   cmpunordps %xmm1, %xmm0
;   andps %xmm0, %xmm5
;   andnps %xmm1, %xmm0
;   orps %xmm5, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   addps %xmm1, %xmm0
;   movdqa %xmm0, %xmm1
;   movl $0x7fc00000, %esi
;   movd %esi, %xmm5
;   shufps $0, 0x14(%rip), %xmm5
;   cmpunordps %xmm1, %xmm0
;   andps %xmm0, %xmm5
;   andnps %xmm1, %xmm0
;   orps %xmm5, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;   addb %al, (%rax)
;   addb %al, (%rax)
;   sarb $0, (%rdi)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)
;   addb %al, (%rax)

function %f1(f64, f64) -> f64 {
block0(v0: f64, v1: f64):
	v2 = fadd v0, v1
	return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   addsd %xmm1, %xmm0
;   movabsq $0x7ff8000000000000, %r8
;   movq %r8, %xmm1
;   uninit  %xmm6
;   xorpd %xmm6, %xmm6
;   movsd %xmm1, %xmm6
;   uninit  %xmm7
;   xorpd %xmm7, %xmm7
;   movsd %xmm0, %xmm7
;   movdqa %xmm7, %xmm0
;   cmpunordpd %xmm7, %xmm0
;   andpd %xmm0, %xmm6
;   andnpd %xmm7, %xmm0
;   orpd %xmm6, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   addsd %xmm1, %xmm0
;   movabsq $0x7ff8000000000000, %r8
;   movq %r8, %xmm1
;   xorpd %xmm6, %xmm6
;   movsd %xmm1, %xmm6
;   xorpd %xmm7, %xmm7
;   movsd %xmm0, %xmm7
;   movdqa %xmm7, %xmm0
;   cmpunordpd %xmm7, %xmm0
;   andpd %xmm0, %xmm6
;   andnpd %xmm7, %xmm0
;   orpd %xmm6, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f1(f32, f32) -> f32 {
block0(v0: f32, v1: f32):
	v2 = fadd v0, v1
	return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   addss %xmm1, %xmm0
;   movl $0x7fc00000, %r8d
;   movd %r8d, %xmm1
;   uninit  %xmm6
;   xorps %xmm6, %xmm6
;   movss %xmm1, %xmm6
;   uninit  %xmm7
;   xorps %xmm7, %xmm7
;   movss %xmm0, %xmm7
;   movdqa %xmm7, %xmm0
;   cmpunordps %xmm7, %xmm0
;   andps %xmm0, %xmm6
;   andnps %xmm7, %xmm0
;   orps %xmm6, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   addss %xmm1, %xmm0
;   movl $0x7fc00000, %r8d
;   movd %r8d, %xmm1
;   xorps %xmm6, %xmm6
;   movss %xmm1, %xmm6
;   xorps %xmm7, %xmm7
;   movss %xmm0, %xmm7
;   movdqa %xmm7, %xmm0
;   cmpunordps %xmm7, %xmm0
;   andps %xmm0, %xmm6
;   andnps %xmm7, %xmm0
;   orps %xmm6, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

