test compile precise-output
set enable_pinned_reg=true
target x86_64

function %f0() {
block0:
    v1 = get_pinned_reg.i64
    v2 = iadd_imm v1, 1
    set_pinned_reg v2
    return
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq    %r15, %rdi
;   lea     1(%rdi), %rdi
;   movq    %rdi, %r15
;   movq %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %r15, %rdi
;   addq $1, %rdi
;   movq %rdi, %r15
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f1() windows_fastcall {
block0:
    v1 = get_pinned_reg.i64
    v2 = iadd_imm v1, 1
    set_pinned_reg v2
    return
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
;   subq $0x10, %rsp
;   movq %rdi, (%rsp)
; block0:
;   movq    %r15, %rdi
;   lea     1(%rdi), %rdi
;   movq    %rdi, %r15
;   movq (%rsp), %rdi
;   addq $0x10, %rsp
;   movq %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
;   subq $0x10, %rsp
;   movq %rdi, (%rsp)
; block1: ; offset 0xc
;   movq %r15, %rdi
;   addq $1, %rdi
;   movq %rdi, %r15
;   movq (%rsp), %rdi
;   addq $0x10, %rsp
;   movq %rbp, %rsp
;   popq %rbp
;   retq

