test compile precise-output
target x86_64 has_popcnt has_sse42

function %popcnt(i64) -> i64 {
block0(v0: i64):
    v1 = popcnt v0
    return v1
}

; VCode:
;   pushq   %rbp
;   movq    %rsp, %rbp
; block0:
;   popcntq %rdi, %rax
;   movq    %rbp, %rsp
;   popq    %rbp
;   ret
; 
; Disassembled:
;   pushq %rbp
;   movq %rsp, %rbp
; block0: ; offset 0x4
;   popcntq %rdi, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %popcnt(i32) -> i32 {
block0(v0: i32):
    v1 = popcnt v0
    return v1
}

; VCode:
;   pushq   %rbp
;   movq    %rsp, %rbp
; block0:
;   popcntl %edi, %eax
;   movq    %rbp, %rsp
;   popq    %rbp
;   ret
; 
; Disassembled:
;   pushq %rbp
;   movq %rsp, %rbp
; block0: ; offset 0x4
;   popcntl %edi, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

