test compile precise-output
target x86_64

function %x64_shld_i32_20(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v6 = iconst.i32 12
    v2 = ushr v0, v6
    v5 = iconst.i32 20
    v3 = ishl v1, v5
    v4 = bor v2, v3
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rax
;   shldl $0x14, %edi, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rax
;   shldl $0x14, %edi, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %x64_shld_i32_20_swap(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v5 = iconst.i32 20
    v2 = ishl v0, v5
    v6 = iconst.i32 12
    v3 = ushr v1, v6
    v4 = bor v2, v3
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rdi, %rax
;   shldl $0x14, %esi, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdi, %rax
;   shldl $0x14, %esi, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %x64_shld_i32_28(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v6 = iconst.i32 4
    v2 = ushr v0, v6
    v5 = iconst.i32 28
    v3 = ishl v1, v5
    v4 = bor v2, v3
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rax
;   shldl $0x1c, %edi, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rax
;   shldl $0x1c, %edi, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %x64_shld_i32_28_swap(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v5 = iconst.i32 28
    v2 = ishl v0, v5
    v6 = iconst.i32 4
    v3 = ushr v1, v6
    v4 = bor v2, v3
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rdi, %rax
;   shldl $0x1c, %esi, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdi, %rax
;   shldl $0x1c, %esi, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %x64_shld_i64_52(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v6 = iconst.i64 12
    v2 = ushr v0, v6
    v5 = iconst.i64 52
    v3 = ishl v1, v5
    v4 = bor v2, v3
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rax
;   shldq $0x34, %rdi, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rax
;   shldq $0x34, %rdi, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %x64_shld_i64_52_swap(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v5 = iconst.i64 52
    v2 = ishl v0, v5
    v6 = iconst.i64 12
    v3 = ushr v1, v6
    v4 = bor v2, v3
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rdi, %rax
;   shldq $0x34, %rsi, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdi, %rax
;   shldq $0x34, %rsi, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %x64_shld_i16_3(i16, i16) -> i16 {
block0(v0: i16, v1: i16):
    v6 = iconst.i16 3
    v2 = ushr v0, v6
    v5 = iconst.i16 13
    v3 = ishl v1, v5
    v4 = bor v2, v3
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rax
;   shldw $0xd, %di, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rax
;   shldw $0xd, %di, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %x64_shld_i8_3(i8, i8) -> i8 {
block0(v0: i8, v1: i8):
    v6 = iconst.i8 3
    v2 = ushr v0, v6
    v5 = iconst.i8 5
    v3 = ishl v1, v5
    v4 = bor v2, v3
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   shrb $0x3, %dil
;   shlb $0x5, %sil
;   movq %rdi, %rax
;   orl %esi, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   shrb $3, %dil
;   shlb $5, %sil
;   movq %rdi, %rax
;   orl %esi, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %x64_shld_i32_32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v6 = iconst.i32 32
    v2 = ushr v0, v6
    v5 = iconst.i32 0
    v3 = ishl v1, v5
    v4 = bor v2, v3
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   shrl $0x0, %edi
;   shll $0x0, %esi
;   movq %rdi, %rax
;   orl %esi, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   shrl $0, %edi
;   shll $0, %esi
;   movq %rdi, %rax
;   orl %esi, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq


function %x64_shld_i32_32_swap(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v5 = iconst.i32 0
    v2 = ishl v1, v5
    v6 = iconst.i32 32
    v3 = ushr v0, v6
    v4 = bor v2, v3
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   shll $0x0, %esi
;   shrl $0x0, %edi
;   movq %rsi, %rax
;   orl %edi, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   shll $0, %esi
;   shrl $0, %edi
;   movq %rsi, %rax
;   orl %edi, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

