test compile precise-output
target x86_64 sse42 has_avx

function %vany_true_i32x4(i32x4) -> i8 {
block0(v0: i32x4):
    v1 = vany_true v0
    return v1
}

; VCode:
;   pushq %rbp
;   movq    %rsp, %rbp
; block0:
;   vptest  %xmm0, %xmm0
;   setnz   %al
;   movq    %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vptest %xmm0, %xmm0
;   setne %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %vall_true_i64x2(i64x2) -> i8 {
block0(v0: i64x2):
    v1 = vall_true v0
    return v1
}

; VCode:
;   pushq %rbp
;   movq    %rsp, %rbp
; block0:
;   uninit  %xmm2
;   vpxor   %xmm2, %xmm2, %xmm4
;   vpcmpeqq %xmm0, %xmm4, %xmm6
;   vptest  %xmm6, %xmm6
;   setz    %al
;   movq    %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   vpxor %xmm2, %xmm2, %xmm4
;   vpcmpeqq %xmm4, %xmm0, %xmm6
;   vptest %xmm6, %xmm6
;   sete %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq

