test compile precise-output
target x86_64 ssse3

function %f1(i16x8, i16x8) -> i16x8 {
block0(v0: i16x8, v1: i16x8):
  v2 = sqmul_round_sat v0, v1
  return v2
}

; VCode:
;   pushq   %rbp
;   movq    %rsp, %rbp
; block0:
;   pmulhrsw %xmm1, %xmm0
;   movdqa %xmm0, %xmm5
;   pcmpeqw %xmm5, const(0), %xmm5
;   pxor %xmm5, %xmm0
;   movq    %rbp, %rsp
;   popq    %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   pmulhrsw %xmm1, %xmm0
;   movdqa %xmm0, %xmm5
;   pcmpeqw 0xb(%rip), %xmm5
;   pxor %xmm5, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;   addb %al, (%rax)
;   addb %al, -0x7fff8000(%rax)
;   addb %al, -0x7fff8000(%rax)

