test compile precise-output
set enable_llvm_abi_extensions=true
target x86_64


function %sshr_i128_i128(i128, i8) -> i128 {
block0(v0: i128, v1: i8):
    v2 = uextend.i64 v1
    v3 = iconcat v2, v2

    v4 = sshr.i128 v0, v3

    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movzbq %dl, %rcx
;   shrq %cl, %rdi
;   movq %rsi, %r8
;   sarq %cl, %r8
;   movq %rcx, %rax
;   movl $0x40, %ecx
;   movq %rax, %r9
;   subq %r9, %rcx
;   movq %rsi, %rax
;   shlq %cl, %rax
;   uninit  %rdx
;   xorq %rdx, %rdx
;   testq $0x7f, %r9
;   cmoveq %rdx, %rax
;   orq %rax, %rdi
;   sarq $0x3f, %rsi
;   testq $0x40, %r9
;   movq %r8, %rax
;   cmoveq %rdi, %rax
;   movq %rsi, %rdx
;   cmoveq %r8, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movzbq %dl, %rcx
;   shrq %cl, %rdi
;   movq %rsi, %r8
;   sarq %cl, %r8
;   movq %rcx, %rax
;   movl $0x40, %ecx
;   movq %rax, %r9
;   subq %r9, %rcx
;   movq %rsi, %rax
;   shlq %cl, %rax
;   xorq %rdx, %rdx
;   testq $0x7f, %r9
;   cmoveq %rdx, %rax
;   orq %rax, %rdi
;   sarq $0x3f, %rsi
;   testq $0x40, %r9
;   movq %r8, %rax
;   cmoveq %rdi, %rax
;   movq %rsi, %rdx
;   cmoveq %r8, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i128_i64(i128, i64) -> i128 {
block0(v0: i128, v1: i64):
    v2 = sshr.i128 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rdx, %rax
;   movq %rdx, %rcx
;   shrq %cl, %rdi
;   movq %rsi, %r8
;   sarq %cl, %r8
;   movq %rcx, %rax
;   movl $0x40, %ecx
;   movq %rax, %r9
;   subq %r9, %rcx
;   movq %rsi, %rax
;   shlq %cl, %rax
;   uninit  %rdx
;   xorq %rdx, %rdx
;   testq $0x7f, %r9
;   cmoveq %rdx, %rax
;   orq %rax, %rdi
;   sarq $0x3f, %rsi
;   testq $0x40, %r9
;   movq %r8, %rax
;   cmoveq %rdi, %rax
;   movq %rsi, %rdx
;   cmoveq %r8, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdx, %rax
;   movq %rdx, %rcx
;   shrq %cl, %rdi
;   movq %rsi, %r8
;   sarq %cl, %r8
;   movq %rcx, %rax
;   movl $0x40, %ecx
;   movq %rax, %r9
;   subq %r9, %rcx
;   movq %rsi, %rax
;   shlq %cl, %rax
;   xorq %rdx, %rdx
;   testq $0x7f, %r9
;   cmoveq %rdx, %rax
;   orq %rax, %rdi
;   sarq $0x3f, %rsi
;   testq $0x40, %r9
;   movq %r8, %rax
;   cmoveq %rdi, %rax
;   movq %rsi, %rdx
;   cmoveq %r8, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i128_i32(i128, i32) -> i128 {
block0(v0: i128, v1: i32):
    v2 = sshr.i128 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rdx, %rax
;   movq %rdx, %rcx
;   shrq %cl, %rdi
;   movq %rsi, %r8
;   sarq %cl, %r8
;   movq %rcx, %rax
;   movl $0x40, %ecx
;   movq %rax, %r9
;   subq %r9, %rcx
;   movq %rsi, %rax
;   shlq %cl, %rax
;   uninit  %rdx
;   xorq %rdx, %rdx
;   testq $0x7f, %r9
;   cmoveq %rdx, %rax
;   orq %rax, %rdi
;   sarq $0x3f, %rsi
;   testq $0x40, %r9
;   movq %r8, %rax
;   cmoveq %rdi, %rax
;   movq %rsi, %rdx
;   cmoveq %r8, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdx, %rax
;   movq %rdx, %rcx
;   shrq %cl, %rdi
;   movq %rsi, %r8
;   sarq %cl, %r8
;   movq %rcx, %rax
;   movl $0x40, %ecx
;   movq %rax, %r9
;   subq %r9, %rcx
;   movq %rsi, %rax
;   shlq %cl, %rax
;   xorq %rdx, %rdx
;   testq $0x7f, %r9
;   cmoveq %rdx, %rax
;   orq %rax, %rdi
;   sarq $0x3f, %rsi
;   testq $0x40, %r9
;   movq %r8, %rax
;   cmoveq %rdi, %rax
;   movq %rsi, %rdx
;   cmoveq %r8, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i128_i16(i128, i16) -> i128 {
block0(v0: i128, v1: i16):
    v2 = sshr.i128 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rdx, %rax
;   movq %rdx, %rcx
;   shrq %cl, %rdi
;   movq %rsi, %r8
;   sarq %cl, %r8
;   movq %rcx, %rax
;   movl $0x40, %ecx
;   movq %rax, %r9
;   subq %r9, %rcx
;   movq %rsi, %rax
;   shlq %cl, %rax
;   uninit  %rdx
;   xorq %rdx, %rdx
;   testq $0x7f, %r9
;   cmoveq %rdx, %rax
;   orq %rax, %rdi
;   sarq $0x3f, %rsi
;   testq $0x40, %r9
;   movq %r8, %rax
;   cmoveq %rdi, %rax
;   movq %rsi, %rdx
;   cmoveq %r8, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdx, %rax
;   movq %rdx, %rcx
;   shrq %cl, %rdi
;   movq %rsi, %r8
;   sarq %cl, %r8
;   movq %rcx, %rax
;   movl $0x40, %ecx
;   movq %rax, %r9
;   subq %r9, %rcx
;   movq %rsi, %rax
;   shlq %cl, %rax
;   xorq %rdx, %rdx
;   testq $0x7f, %r9
;   cmoveq %rdx, %rax
;   orq %rax, %rdi
;   sarq $0x3f, %rsi
;   testq $0x40, %r9
;   movq %r8, %rax
;   cmoveq %rdi, %rax
;   movq %rsi, %rdx
;   cmoveq %r8, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i128_i8(i128, i8) -> i128 {
block0(v0: i128, v1: i8):
    v2 = sshr.i128 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rdx, %rax
;   movq %rdx, %rcx
;   shrq %cl, %rdi
;   movq %rsi, %r8
;   sarq %cl, %r8
;   movq %rcx, %rax
;   movl $0x40, %ecx
;   movq %rax, %r9
;   subq %r9, %rcx
;   movq %rsi, %rax
;   shlq %cl, %rax
;   uninit  %rdx
;   xorq %rdx, %rdx
;   testq $0x7f, %r9
;   cmoveq %rdx, %rax
;   orq %rax, %rdi
;   sarq $0x3f, %rsi
;   testq $0x40, %r9
;   movq %r8, %rax
;   cmoveq %rdi, %rax
;   movq %rsi, %rdx
;   cmoveq %r8, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdx, %rax
;   movq %rdx, %rcx
;   shrq %cl, %rdi
;   movq %rsi, %r8
;   sarq %cl, %r8
;   movq %rcx, %rax
;   movl $0x40, %ecx
;   movq %rax, %r9
;   subq %r9, %rcx
;   movq %rsi, %rax
;   shlq %cl, %rax
;   xorq %rdx, %rdx
;   testq $0x7f, %r9
;   cmoveq %rdx, %rax
;   orq %rax, %rdi
;   sarq $0x3f, %rsi
;   testq $0x40, %r9
;   movq %r8, %rax
;   cmoveq %rdi, %rax
;   movq %rsi, %rdx
;   cmoveq %r8, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i64_i128(i64, i128) -> i64 {
block0(v0: i64, v1: i128):
    v2 = sshr.i64 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   sarq %cl, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   sarq %cl, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i32_i128(i32, i128) -> i32 {
block0(v0: i32, v1: i128):
    v2 = sshr.i32 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   sarl %cl, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   sarl %cl, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i16_i128(i16, i128) -> i16 {
block0(v0: i16, v1: i128):
    v2 = sshr.i16 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   andq $0xf, %rcx
;   movq %rdi, %rax
;   sarw %cl, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   andq $0xf, %rcx
;   movq %rdi, %rax
;   sarw %cl, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i8_i128(i8, i128) -> i8 {
block0(v0: i8, v1: i128):
    v2 = sshr.i8 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   andq $0x7, %rcx
;   movq %rdi, %rax
;   sarb %cl, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   andq $7, %rcx
;   movq %rdi, %rax
;   sarb %cl, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i64_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = sshr.i64 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   sarq %cl, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   sarq %cl, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i64_i32(i64, i32) -> i64 {
block0(v0: i64, v1: i32):
    v2 = sshr.i64 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   sarq %cl, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   sarq %cl, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i64_i16(i64, i16) -> i64 {
block0(v0: i64, v1: i16):
    v2 = sshr.i64 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   sarq %cl, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   sarq %cl, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i64_i8(i64, i8) -> i64 {
block0(v0: i64, v1: i8):
    v2 = sshr.i64 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   sarq %cl, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   sarq %cl, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i32_i64(i32, i64) -> i32 {
block0(v0: i32, v1: i64):
    v2 = sshr.i32 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   sarl %cl, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   sarl %cl, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i32_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = sshr.i32 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   sarl %cl, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   sarl %cl, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i32_i16(i32, i16) -> i32 {
block0(v0: i32, v1: i16):
    v2 = sshr.i32 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   sarl %cl, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   sarl %cl, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i32_i8(i32, i8) -> i32 {
block0(v0: i32, v1: i8):
    v2 = sshr.i32 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   sarl %cl, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   sarl %cl, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i16_i64(i16, i64) -> i16 {
block0(v0: i16, v1: i64):
    v2 = sshr.i16 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   andq $0xf, %rcx
;   movq %rdi, %rax
;   sarw %cl, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   andq $0xf, %rcx
;   movq %rdi, %rax
;   sarw %cl, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i16_i32(i16, i32) -> i16 {
block0(v0: i16, v1: i32):
    v2 = sshr.i16 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   andq $0xf, %rcx
;   movq %rdi, %rax
;   sarw %cl, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   andq $0xf, %rcx
;   movq %rdi, %rax
;   sarw %cl, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i16_i16(i16, i16) -> i16 {
block0(v0: i16, v1: i16):
    v2 = sshr.i16 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   andq $0xf, %rcx
;   movq %rdi, %rax
;   sarw %cl, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   andq $0xf, %rcx
;   movq %rdi, %rax
;   sarw %cl, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i16_i8(i16, i8) -> i16 {
block0(v0: i16, v1: i8):
    v2 = sshr.i16 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   andq $0xf, %rcx
;   movq %rdi, %rax
;   sarw %cl, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   andq $0xf, %rcx
;   movq %rdi, %rax
;   sarw %cl, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i8_i64(i8, i64) -> i8 {
block0(v0: i8, v1: i64):
    v2 = sshr.i8 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   andq $0x7, %rcx
;   movq %rdi, %rax
;   sarb %cl, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   andq $7, %rcx
;   movq %rdi, %rax
;   sarb %cl, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i8_i32(i8, i32) -> i8 {
block0(v0: i8, v1: i32):
    v2 = sshr.i8 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   andq $0x7, %rcx
;   movq %rdi, %rax
;   sarb %cl, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   andq $7, %rcx
;   movq %rdi, %rax
;   sarb %cl, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i8_i16(i8, i16) -> i8 {
block0(v0: i8, v1: i16):
    v2 = sshr.i8 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   andq $0x7, %rcx
;   movq %rdi, %rax
;   sarb %cl, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   andq $7, %rcx
;   movq %rdi, %rax
;   sarb %cl, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i8_i8(i8, i8) -> i8 {
block0(v0: i8, v1: i8):
    v2 = sshr.i8 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   andq $0x7, %rcx
;   movq %rdi, %rax
;   sarb %cl, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   andq $7, %rcx
;   movq %rdi, %rax
;   sarb %cl, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i64_const(i64) -> i64 {
block0(v0: i64):
    v2 = iconst.i64 65
    v1 = sshr v0, v2
    return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rdi, %rax
;   sarq $1, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdi, %rax
;   sarq $1, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i32_const(i32) -> i32 {
block0(v0: i32):
    v2 = iconst.i32 33
    v1 = sshr v0, v2
    return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rdi, %rax
;   sarl $1, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdi, %rax
;   sarl $1, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i16_const(i16) -> i16 {
block0(v0: i16):
    v2 = iconst.i16 17
    v1 = sshr v0, v2
    return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rdi, %rax
;   sarw $1, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdi, %rax
;   sarw $1, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %sshr_i8_const(i8) -> i8 {
block0(v0: i8):
    v2 = iconst.i8 9
    v1 = sshr v0, v2
    return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rdi, %rax
;   sarb $1, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdi, %rax
;   sarb $1, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq

