test compile precise-output
target x86_64

function %store_i8x2(i8x2, i64) {
block0(v0: i8x2, v1: i64):
    store.i8x2 v0, v1
    return
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   pextrw $0x0, %xmm0, %esi
;   movw %si, (%rdi)
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   pextrw $0, %xmm0, %esi
;   movw %si, (%rdi) ; trap: heap_oob
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %store_i16x2(i16x2, i64) {
block0(v0: i16x2, v1: i64):
    store.i16x2 v0, v1
    return
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movss %xmm0, (%rdi)
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movss %xmm0, (%rdi) ; trap: heap_oob
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %store_i32x2(i32x2, i64) {
block0(v0: i32x2, v1: i64):
    store.i32x2 v0, v1
    return
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movsd %xmm0, (%rdi)
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movsd %xmm0, (%rdi) ; trap: heap_oob
;   movq %rbp, %rsp
;   popq %rbp
;   retq

