test compile precise-output
target x86_64

function %store_f16(f16, i64) {
block0(v0: f16, v1: i64):
    store.f16 v0, v1
    return
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   pextrw $0x0, %xmm0, %ecx
;   movw %cx, (%rdi)
;   movq %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   pextrw $0, %xmm0, %ecx
;   movw %cx, (%rdi) ; trap: heap_oob
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %store_f128(f128, i64) {
block0(v0: f128, v1: i64):
    store.f128 v0, v1
    return
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movdqu %xmm0, (%rdi)
;   movq %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movdqu %xmm0, (%rdi) ; trap: heap_oob
;   movq %rbp, %rsp
;   popq %rbp
;   retq

