test compile precise-output
set tls_model=coff
target x86_64


function u0:0(i32) -> i64 {
gv0 = symbol colocated tls u1:0

block0(v0: i32):
    v1 = global_value.i64 gv0
    return v1
}

; VCode:
;   pushq   %rbp
;   movq    %rsp, %rbp
; block0:
;   %rax = coff_tls_get_addr User(userextname0)
;   movq    %rbp, %rsp
;   popq    %rbp
;   ret
; 
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movl (%rip), %eax ; reloc_external PCRel4 %CoffTlsIndex -4
;   movq %gs:0x58, %rcx
;   movq (%rcx, %rax, 8), %rax
;   leaq (%rax), %rax ; reloc_external SecRel u1:0 0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

