test compile precise-output
set tls_model=elf_gd
target x86_64

function u0:0(i32) -> i64 {
gv0 = symbol colocated tls u1:0

block0(v0: i32):
    v1 = tls_value.i64 gv0
    return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   %rax = elf_tls_get_addr User(userextname0)
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   leaq (%rip), %rdi ; reloc_external ElfX86_64TlsGd u1:0 -4
;   callq 0x14 ; reloc_external CallPLTRel4 %ElfTlsGetAddr -4
;   movq %rbp, %rsp
;   popq %rbp
;   retq

