test compile precise-output
set tls_model=macho
target x86_64

function u0:0(i32) -> i64 {
gv0 = symbol colocated tls u1:0

block0(v0: i32):
    v1 = tls_value.i64 gv0
    return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   %rax = macho_tls_get_addr User(userextname0)
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq (%rip), %rdi ; reloc_external MachOX86_64Tlv u1:0 -4
;   callq *(%rdi)
;   movq %rbp, %rsp
;   popq %rbp
;   retq

