test compile precise-output
target x86_64

function %f1(f32) -> f32 {
block0(v0: f32):
  v1 = trunc v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   load_ext_name %TruncF32+0, %rcx
;   call    *%rcx
;   movq %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movabsq $0, %rcx ; reloc_external Abs8 %TruncF32 0
;   callq *%rcx
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %f2(f64) -> f64 {
block0(v0: f64):
  v1 = trunc v0
  return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   load_ext_name %TruncF64+0, %rcx
;   call    *%rcx
;   movq %rbp, %rsp
;   popq %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movabsq $0, %rcx ; reloc_external Abs8 %TruncF64 0
;   callq *%rcx
;   movq %rbp, %rsp
;   popq %rbp
;   retq

