test compile
target x86_64

; The x86_64 system_v call conv respects uext and sext
function u0:0(i8) system_v {
    sig0 = (i8 uext) system_v
    fn0 = u0:0 sig0

block0(v0: i8):
    call fn0(v0)
    return
}

; check:  pushq %rbp
; nextln: movq    %rsp, %rbp
; nextln: block0:
; nextln: movzbq %dil, %rdi
; nextln: load_ext_name userextname0+0, %rdx
; nextln: call    *%rdx

; The x86_64 windows_fastcall call conv respects uext and sext
function u0:0(i8) windows_fastcall {
    sig0 = (i8 uext) windows_fastcall
    fn0 = u0:0 sig0

block0(v0: i8):
    call fn0(v0)
    return
}

; check: pushq %rbp
; nextln: movq    %rsp, %rbp
; nextln: subq $$0x20, %rsp
; nextln: block0:
; nextln: movzbq %cl, %rcx
; nextln: load_ext_name userextname0+0, %rdx
; nextln: call    *%rdx
