test compile precise-output
target x86_64

function u0:0(i32, i64) -> i32 fast {
block0(v1: i32, v2: i64):
    v3 = load.i32 notrap aligned v2
    v4 = umax v1, v3
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movl (%rsi), %edx
;   cmpl    %edi, %edx
;   movq %rdi, %rax
;   cmovnbl %edx, %eax, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movl (%rsi), %edx
;   cmpl %edi, %edx
;   movq %rdi, %rax
;   cmovael %edx, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

