test compile precise-output
set enable_llvm_abi_extensions=true
target x86_64


function %ushr_i128_i128(i128, i8) -> i128 {
block0(v0: i128, v1: i8):
    v2 = uextend.i64 v1
    v3 = iconcat v2, v2

    v4 = ushr.i128 v0, v3
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movzbq %dl, %rcx
;   shrq %cl, %rdi
;   movq %rsi, %r10
;   shrq %cl, %r10
;   movq %rcx, %r11
;   movl $0x40, %ecx
;   movq %r11, %rax
;   subq %rax, %rcx
;   shlq %cl, %rsi
;   uninit  %rdx
;   xorq %rdx, %rdx
;   testq $0x7f, %rax
;   cmovzq  %rdx, %rsi, %rsi
;   orq %rdi, %rsi
;   testq $0x40, %rax
;   movq %r10, %rax
;   cmovzq  %rsi, %rax, %rax
;   cmovzq  %r10, %rdx, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movzbq %dl, %rcx
;   shrq %cl, %rdi
;   movq %rsi, %r10
;   shrq %cl, %r10
;   movq %rcx, %r11
;   movl $0x40, %ecx
;   movq %r11, %rax
;   subq %rax, %rcx
;   shlq %cl, %rsi
;   xorq %rdx, %rdx
;   testq $0x7f, %rax
;   cmoveq %rdx, %rsi
;   orq %rdi, %rsi
;   testq $0x40, %rax
;   movq %r10, %rax
;   cmoveq %rsi, %rax
;   cmoveq %r10, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i128_i64(i128, i64) -> i128 {
block0(v0: i128, v1: i64):
    v2 = ushr.i128 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rdx, %rcx
;   movq %rdx, %r10
;   shrq %cl, %rdi
;   movq %rsi, %r9
;   shrq %cl, %r9
;   movq %rcx, %r10
;   movl $0x40, %ecx
;   movq %r10, %rax
;   subq %rax, %rcx
;   shlq %cl, %rsi
;   uninit  %rdx
;   xorq %rdx, %rdx
;   testq $0x7f, %rax
;   cmovzq  %rdx, %rsi, %rsi
;   orq %rdi, %rsi
;   testq $0x40, %rax
;   movq %r9, %rax
;   cmovzq  %rsi, %rax, %rax
;   cmovzq  %r9, %rdx, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdx, %rcx
;   movq %rdx, %r10
;   shrq %cl, %rdi
;   movq %rsi, %r9
;   shrq %cl, %r9
;   movq %rcx, %r10
;   movl $0x40, %ecx
;   movq %r10, %rax
;   subq %rax, %rcx
;   shlq %cl, %rsi
;   xorq %rdx, %rdx
;   testq $0x7f, %rax
;   cmoveq %rdx, %rsi
;   orq %rdi, %rsi
;   testq $0x40, %rax
;   movq %r9, %rax
;   cmoveq %rsi, %rax
;   cmoveq %r9, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i128_i32(i128, i32) -> i128 {
block0(v0: i128, v1: i32):
    v2 = ushr.i128 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rdx, %rcx
;   movq %rdx, %r10
;   shrq %cl, %rdi
;   movq %rsi, %r9
;   shrq %cl, %r9
;   movq %rcx, %r10
;   movl $0x40, %ecx
;   movq %r10, %rax
;   subq %rax, %rcx
;   shlq %cl, %rsi
;   uninit  %rdx
;   xorq %rdx, %rdx
;   testq $0x7f, %rax
;   cmovzq  %rdx, %rsi, %rsi
;   orq %rdi, %rsi
;   testq $0x40, %rax
;   movq %r9, %rax
;   cmovzq  %rsi, %rax, %rax
;   cmovzq  %r9, %rdx, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdx, %rcx
;   movq %rdx, %r10
;   shrq %cl, %rdi
;   movq %rsi, %r9
;   shrq %cl, %r9
;   movq %rcx, %r10
;   movl $0x40, %ecx
;   movq %r10, %rax
;   subq %rax, %rcx
;   shlq %cl, %rsi
;   xorq %rdx, %rdx
;   testq $0x7f, %rax
;   cmoveq %rdx, %rsi
;   orq %rdi, %rsi
;   testq $0x40, %rax
;   movq %r9, %rax
;   cmoveq %rsi, %rax
;   cmoveq %r9, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i128_i16(i128, i16) -> i128 {
block0(v0: i128, v1: i16):
    v2 = ushr.i128 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rdx, %rcx
;   movq %rdx, %r10
;   shrq %cl, %rdi
;   movq %rsi, %r9
;   shrq %cl, %r9
;   movq %rcx, %r10
;   movl $0x40, %ecx
;   movq %r10, %rax
;   subq %rax, %rcx
;   shlq %cl, %rsi
;   uninit  %rdx
;   xorq %rdx, %rdx
;   testq $0x7f, %rax
;   cmovzq  %rdx, %rsi, %rsi
;   orq %rdi, %rsi
;   testq $0x40, %rax
;   movq %r9, %rax
;   cmovzq  %rsi, %rax, %rax
;   cmovzq  %r9, %rdx, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdx, %rcx
;   movq %rdx, %r10
;   shrq %cl, %rdi
;   movq %rsi, %r9
;   shrq %cl, %r9
;   movq %rcx, %r10
;   movl $0x40, %ecx
;   movq %r10, %rax
;   subq %rax, %rcx
;   shlq %cl, %rsi
;   xorq %rdx, %rdx
;   testq $0x7f, %rax
;   cmoveq %rdx, %rsi
;   orq %rdi, %rsi
;   testq $0x40, %rax
;   movq %r9, %rax
;   cmoveq %rsi, %rax
;   cmoveq %r9, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i128_i8(i128, i8) -> i128 {
block0(v0: i128, v1: i8):
    v2 = ushr.i128 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rdx, %rcx
;   movq %rdx, %r10
;   shrq %cl, %rdi
;   movq %rsi, %r9
;   shrq %cl, %r9
;   movq %rcx, %r10
;   movl $0x40, %ecx
;   movq %r10, %rax
;   subq %rax, %rcx
;   shlq %cl, %rsi
;   uninit  %rdx
;   xorq %rdx, %rdx
;   testq $0x7f, %rax
;   cmovzq  %rdx, %rsi, %rsi
;   orq %rdi, %rsi
;   testq $0x40, %rax
;   movq %r9, %rax
;   cmovzq  %rsi, %rax, %rax
;   cmovzq  %r9, %rdx, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdx, %rcx
;   movq %rdx, %r10
;   shrq %cl, %rdi
;   movq %rsi, %r9
;   shrq %cl, %r9
;   movq %rcx, %r10
;   movl $0x40, %ecx
;   movq %r10, %rax
;   subq %rax, %rcx
;   shlq %cl, %rsi
;   xorq %rdx, %rdx
;   testq $0x7f, %rax
;   cmoveq %rdx, %rsi
;   orq %rdi, %rsi
;   testq $0x40, %rax
;   movq %r9, %rax
;   cmoveq %rsi, %rax
;   cmoveq %r9, %rdx
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i64_i128(i64, i128) -> i64 {
block0(v0: i64, v1: i128):
    v2 = ushr.i64 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   shrq %cl, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   shrq %cl, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i32_i128(i32, i64, i64) -> i32 {
block0(v0: i32, v1: i64, v2: i64):
    v3 = iconcat v1, v2
    v4 = ushr.i32 v0, v3
    return v4
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   shrl %cl, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   shrl %cl, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i16_i128(i16, i128) -> i16 {
block0(v0: i16, v1: i128):
    v2 = ushr.i16 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   andq $0xf, %rcx
;   movq %rdi, %rax
;   shrw %cl, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   andq $0xf, %rcx
;   movq %rdi, %rax
;   shrw %cl, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i8_i128(i8, i128) -> i8 {
block0(v0: i8, v1: i128):
    v2 = ushr.i8 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   andq $0x7, %rcx
;   movq %rdi, %rax
;   shrb %cl, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   andq $7, %rcx
;   movq %rdi, %rax
;   shrb %cl, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i64_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = ushr.i64 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   shrq %cl, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   shrq %cl, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i64_i32(i64, i32) -> i64 {
block0(v0: i64, v1: i32):
    v2 = ushr.i64 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   shrq %cl, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   shrq %cl, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i64_i16(i64, i16) -> i64 {
block0(v0: i64, v1: i16):
    v2 = ushr.i64 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   shrq %cl, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   shrq %cl, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i64_i8(i64, i8) -> i64 {
block0(v0: i64, v1: i8):
    v2 = ushr.i64 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   shrq %cl, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   shrq %cl, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i32_i64(i32, i64) -> i32 {
block0(v0: i32, v1: i64):
    v2 = ushr.i32 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   shrl %cl, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   shrl %cl, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i32_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = ushr.i32 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   shrl %cl, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   shrl %cl, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i32_i16(i32, i16) -> i32 {
block0(v0: i32, v1: i16):
    v2 = ushr.i32 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   shrl %cl, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   shrl %cl, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i32_i8(i32, i8) -> i32 {
block0(v0: i32, v1: i8):
    v2 = ushr.i32 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   shrl %cl, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   movq %rdi, %rax
;   shrl %cl, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i16_i64(i16, i64) -> i16 {
block0(v0: i16, v1: i64):
    v2 = ushr.i16 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   andq $0xf, %rcx
;   movq %rdi, %rax
;   shrw %cl, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   andq $0xf, %rcx
;   movq %rdi, %rax
;   shrw %cl, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i16_i32(i16, i32) -> i16 {
block0(v0: i16, v1: i32):
    v2 = ushr.i16 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   andq $0xf, %rcx
;   movq %rdi, %rax
;   shrw %cl, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   andq $0xf, %rcx
;   movq %rdi, %rax
;   shrw %cl, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i16_i16(i16, i16) -> i16 {
block0(v0: i16, v1: i16):
    v2 = ushr.i16 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   andq $0xf, %rcx
;   movq %rdi, %rax
;   shrw %cl, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   andq $0xf, %rcx
;   movq %rdi, %rax
;   shrw %cl, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i16_i8(i16, i8) -> i16 {
block0(v0: i16, v1: i8):
    v2 = ushr.i16 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   andq $0xf, %rcx
;   movq %rdi, %rax
;   shrw %cl, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   andq $0xf, %rcx
;   movq %rdi, %rax
;   shrw %cl, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i8_i64(i8, i64) -> i8 {
block0(v0: i8, v1: i64):
    v2 = ushr.i8 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   andq $0x7, %rcx
;   movq %rdi, %rax
;   shrb %cl, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   andq $7, %rcx
;   movq %rdi, %rax
;   shrb %cl, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i8_i32(i8, i32) -> i8 {
block0(v0: i8, v1: i32):
    v2 = ushr.i8 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   andq $0x7, %rcx
;   movq %rdi, %rax
;   shrb %cl, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   andq $7, %rcx
;   movq %rdi, %rax
;   shrb %cl, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i8_i16(i8, i16) -> i8 {
block0(v0: i8, v1: i16):
    v2 = ushr.i8 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   andq $0x7, %rcx
;   movq %rdi, %rax
;   shrb %cl, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   andq $7, %rcx
;   movq %rdi, %rax
;   shrb %cl, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i8_i8(i8, i8) -> i8 {
block0(v0: i8, v1: i8):
    v2 = ushr.i8 v0, v1
    return v2
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rsi, %rcx
;   andq $0x7, %rcx
;   movq %rdi, %rax
;   shrb %cl, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rsi, %rcx
;   andq $7, %rcx
;   movq %rdi, %rax
;   shrb %cl, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i64_const(i64) -> i64 {
block0(v0: i64):
    v1 = ushr_imm.i64 v0, 65
    return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rdi, %rax
;   shrq $0x1, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdi, %rax
;   shrq $1, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i32_const(i32) -> i32 {
block0(v0: i32):
    v1 = ushr_imm.i32 v0, 33
    return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rdi, %rax
;   shrl $0x1, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdi, %rax
;   shrl $1, %eax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i16_const(i16) -> i16 {
block0(v0: i16):
    v1 = ushr_imm.i16 v0, 17
    return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rdi, %rax
;   shrw $0x1, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdi, %rax
;   shrw $1, %ax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

function %ushr_i8_const(i8) -> i8 {
block0(v0: i8):
    v1 = ushr_imm.i8 v0, 9
    return v1
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movq %rdi, %rax
;   shrb $0x1, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movq %rdi, %rax
;   shrb $1, %al
;   movq %rbp, %rsp
;   popq %rbp
;   retq

