test compile precise-output
target x86_64 sse41

function u0:0(i64 vmctx, i8x16) -> i16x8 fast {
block0(v0: i64, v2: i8x16):
    v5 = load.i8x16 notrap aligned table v0+80
    v6 = uwiden_high v5
    return v6
}

; VCode:
;   pushq %rbp
;   movq %rsp, %rbp
; block0:
;   movdqu 0x50(%rdi), %xmm0
;   uninit  %xmm4
;   pxor %xmm4, %xmm4
;   punpckhbw %xmm4, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   movdqu 0x50(%rdi), %xmm0
;   pxor %xmm4, %xmm4
;   punpckhbw %xmm4, %xmm0
;   movq %rbp, %rsp
;   popq %rbp
;   retq

