;;! target = "s390x"
;;!
;;! settings = ['enable_heap_access_spectre_mitigation=false']
;;!
;;! compile = true
;;!
;;! [globals.vmctx]
;;! type = "i64"
;;! vmctx = true
;;!
;;! [globals.heap_base]
;;! type = "i64"
;;! load = { base = "vmctx", offset = 0, readonly = true }
;;!
;;! [globals.heap_bound]
;;! type = "i64"
;;! load = { base = "vmctx", offset = 8, readonly = true }
;;!
;;! [[heaps]]
;;! base = "heap_base"
;;! min_size = 0x10000
;;! offset_guard_size = 0xffffffff
;;! index_type = "i64"
;;! style = { kind = "dynamic", bound = "heap_bound" }

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0x1000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load8_u offset=0x1000))

;; function u0:0:
;;   unwind DefineNewFrame { offset_upward_to_caller_sp: 160, offset_downward_to_clobbers: 0 }
;;   unwind StackAlloc { size: 0 }
;; block0:
;;   lghi %r5, -4097
;;   ag %r5, 8(%r4)
;;   clgr %r2, %r5
;;   jgnh label1 ; jg label3
;; block1:
;;   lgr %r5, %r2
;;   ag %r5, 0(%r4)
;;   lghi %r4, 4096
;;   stc %r3, 0(%r4,%r5)
;;   jg label2
;; block2:
;;   br %r14
;; block3:
;;   trap
;;
;; function u0:1:
;;   unwind DefineNewFrame { offset_upward_to_caller_sp: 160, offset_downward_to_clobbers: 0 }
;;   unwind StackAlloc { size: 0 }
;; block0:
;;   lghi %r5, -4097
;;   ag %r5, 8(%r3)
;;   clgr %r2, %r5
;;   jgnh label1 ; jg label3
;; block1:
;;   lgr %r4, %r2
;;   ag %r4, 0(%r3)
;;   lghi %r2, 4096
;;   llc %r2, 0(%r2,%r4)
;;   jg label2
;; block2:
;;   br %r14
;; block3:
;;   trap