;;! target = "aarch64"
;;! test = "winch"

(module
  (func
    i64.const 1
    i64.const 1
    i64.rotl
    i64.const 2
    i64.ne
    if
      unreachable
    end
  )
  (export "a" (func 0))
)
;; wasm[0]::function[0]:
;;       stp     x29, x30, [sp, #-0x10]!
;;       mov     x29, sp
;;       str     x28, [sp, #-0x10]!
;;       mov     x28, sp
;;       ldur    x16, [x0, #8]
;;       ldur    x16, [x16, #0x18]
;;       mov     x17, #0
;;       movk    x17, #0x10
;;       add     x16, x16, x17
;;       cmp     sp, x16
;;       b.lo    #0x78
;;   2c: mov     x9, x0
;;       sub     x28, x28, #0x10
;;       mov     sp, x28
;;       stur    x0, [x28, #8]
;;       stur    x1, [x28]
;;       mov     x0, #1
;;       ror     x0, x0, #0x3f
;;       cmp     x0, #2
;;       cset    x0, ne
;;       tst     w0, w0
;;       b.eq    #0x60
;;       b       #0x5c
;;   5c: udf     #0xc11f
;;       add     x28, x28, #0x10
;;       mov     sp, x28
;;       mov     sp, x28
;;       ldr     x28, [sp], #0x10
;;       ldp     x29, x30, [sp], #0x10
;;       ret
;;   78: udf     #0xc11f
