;;! target = "riscv64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -W memory64 -O static-memory-forced -O static-memory-guard-size=4294967295 -O dynamic-memory-guard-size=4294967295"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load8_u offset=0))

;; wasm[0]::function[0]:
;;    0: addi    sp, sp, -0x10
;;    4: sd      ra, 8(sp)
;;    8: sd      s0, 0(sp)
;;    c: mv      s0, sp
;;   10: auipc   a5, 0
;;   14: ld      a5, 0x38(a5)
;;   18: sltu    a5, a5, a2
;;   1c: ld      a0, 0x50(a0)
;;   20: add     a0, a0, a2
;;   24: neg     a4, a5
;;   28: not     a5, a4
;;   2c: and     a1, a0, a5
;;   30: sb      a3, 0(a1)
;;   34: ld      ra, 8(sp)
;;   38: ld      s0, 0(sp)
;;   3c: addi    sp, sp, 0x10
;;   40: ret
;;   44: .byte   0x00, 0x00, 0x00, 0x00
;;   48: .byte   0xff, 0xff, 0xff, 0xff
;;   4c: .byte   0x00, 0x00, 0x00, 0x00
;;
;; wasm[0]::function[1]:
;;   50: addi    sp, sp, -0x10
;;   54: sd      ra, 8(sp)
;;   58: sd      s0, 0(sp)
;;   5c: mv      s0, sp
;;   60: auipc   a5, 0
;;   64: ld      a5, 0x38(a5)
;;   68: sltu    a5, a5, a2
;;   6c: ld      a0, 0x50(a0)
;;   70: add     a0, a0, a2
;;   74: neg     a3, a5
;;   78: not     a5, a3
;;   7c: and     a1, a0, a5
;;   80: lbu     a0, 0(a1)
;;   84: ld      ra, 8(sp)
;;   88: ld      s0, 0(sp)
;;   8c: addi    sp, sp, 0x10
;;   90: ret
;;   94: .byte   0x00, 0x00, 0x00, 0x00
;;   98: .byte   0xff, 0xff, 0xff, 0xff
;;   9c: .byte   0x00, 0x00, 0x00, 0x00
