;;! target = "riscv64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0xffff0000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0xffff0000))

;; wasm[0]::function[0]:
;;       addi    sp, sp, -0x10
;;       sd      ra, 8(sp)
;;       sd      s0, 0(sp)
;;       mv      s0, sp
;;       slli    a1, a2, 0x20
;;       srli    a2, a1, 0x20
;;       lui     a5, 0x3fffc
;;       addi    a1, a5, 1
;;       slli    a4, a1, 2
;;       add     a1, a2, a4
;;       bgeu    a1, a2, 8
;;       .byte   0x00, 0x00, 0x00, 0x00
;;       ld      a4, 0x58(a0)
;;       ld      a5, 0x50(a0)
;;       sltu    a4, a4, a1
;;       add     a2, a5, a2
;;       lui     a1, 0xffff
;;       slli    a5, a1, 4
;;       add     a2, a2, a5
;;       neg     a0, a4
;;       not     a4, a0
;;       and     a4, a2, a4
;;       sw      a3, 0(a4)
;;       ld      ra, 8(sp)
;;       ld      s0, 0(sp)
;;       addi    sp, sp, 0x10
;;       ret
;;
;; wasm[0]::function[1]:
;;       addi    sp, sp, -0x10
;;       sd      ra, 8(sp)
;;       sd      s0, 0(sp)
;;       mv      s0, sp
;;       slli    a1, a2, 0x20
;;       srli    a2, a1, 0x20
;;       lui     a5, 0x3fffc
;;       addi    a1, a5, 1
;;       slli    a3, a1, 2
;;       add     a1, a2, a3
;;       bgeu    a1, a2, 8
;;       .byte   0x00, 0x00, 0x00, 0x00
;;       ld      a3, 0x58(a0)
;;       ld      a4, 0x50(a0)
;;       sltu    a3, a3, a1
;;       add     a2, a4, a2
;;       lui     a1, 0xffff
;;       slli    a4, a1, 4
;;       add     a2, a2, a4
;;       neg     a0, a3
;;       not     a3, a0
;;       and     a4, a2, a3
;;       lw      a0, 0(a4)
;;       ld      ra, 8(sp)
;;       ld      s0, 0(sp)
;;       addi    sp, sp, 0x10
;;       ret
