;;! target = "riscv64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0x1000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load8_u offset=0x1000))

;; wasm[0]::function[0]:
;;       addi    sp, sp, -0x10
;;       sd      ra, 8(sp)
;;       sd      s0, 0(sp)
;;       mv      s0, sp
;;       ld      a1, 0x40(a0)
;;       ld      a0, 0x38(a0)
;;       slli    a2, a2, 0x20
;;       srli    a2, a2, 0x20
;;       lui     a4, 1
;;       addi    a4, a4, 1
;;       sub     a1, a1, a4
;;       sltu    a1, a1, a2
;;       add     a0, a0, a2
;;       lui     a2, 1
;;       add     a0, a0, a2
;;       neg     a5, a1
;;       not     a1, a5
;;       and     a0, a0, a1
;;       sb      a3, 0(a0)
;;       ld      ra, 8(sp)
;;       ld      s0, 0(sp)
;;       addi    sp, sp, 0x10
;;       ret
;;
;; wasm[0]::function[1]:
;;       addi    sp, sp, -0x10
;;       sd      ra, 8(sp)
;;       sd      s0, 0(sp)
;;       mv      s0, sp
;;       ld      a1, 0x40(a0)
;;       ld      a0, 0x38(a0)
;;       slli    a2, a2, 0x20
;;       srli    a2, a2, 0x20
;;       lui     a3, 1
;;       addi    a3, a3, 1
;;       sub     a1, a1, a3
;;       sltu    a1, a1, a2
;;       add     a0, a0, a2
;;       lui     a2, 1
;;       add     a0, a0, a2
;;       neg     a5, a1
;;       not     a1, a5
;;       and     a0, a0, a1
;;       lbu     a0, 0(a0)
;;       ld      ra, 8(sp)
;;       ld      s0, 0(sp)
;;       addi    sp, sp, 0x10
;;       ret
