;;! target = "riscv64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -W memory64 -O static-memory-maximum-size=0 -O static-memory-guard-size=4294967295 -O dynamic-memory-guard-size=4294967295"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load8_u offset=0))

;; wasm[0]::function[0]:
;;    0: addi    sp, sp, -0x10
;;    4: sd      ra, 8(sp)
;;    8: sd      s0, 0(sp)
;;    c: mv      s0, sp
;;   10: ld      a1, 0x58(a0)
;;   14: ld      a0, 0x50(a0)
;;   18: sltu    a5, a2, a1
;;   1c: xori    a1, a5, 1
;;   20: add     a0, a0, a2
;;   24: neg     a4, a1
;;   28: not     a1, a4
;;   2c: and     a2, a0, a1
;;   30: sb      a3, 0(a2)
;;   34: ld      ra, 8(sp)
;;   38: ld      s0, 0(sp)
;;   3c: addi    sp, sp, 0x10
;;   40: ret
;;
;; wasm[0]::function[1]:
;;   44: addi    sp, sp, -0x10
;;   48: sd      ra, 8(sp)
;;   4c: sd      s0, 0(sp)
;;   50: mv      s0, sp
;;   54: ld      a1, 0x58(a0)
;;   58: ld      a0, 0x50(a0)
;;   5c: sltu    a5, a2, a1
;;   60: xori    a1, a5, 1
;;   64: add     a0, a0, a2
;;   68: neg     a4, a1
;;   6c: not     a1, a4
;;   70: and     a2, a0, a1
;;   74: lbu     a0, 0(a2)
;;   78: ld      ra, 8(sp)
;;   7c: ld      s0, 0(sp)
;;   80: addi    sp, sp, 0x10
;;   84: ret
