;;! target = "riscv64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -W memory64 -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0x1000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load8_u offset=0x1000))

;; wasm[0]::function[0]:
;;       addi    sp, sp, -0x10
;;       sd      ra, 8(sp)
;;       sd      s0, 0(sp)
;;       mv      s0, sp
;;       ld      a1, 0x40(a0)
;;       ld      a5, 0x38(a0)
;;       lui     a4, 1
;;       addi    a0, a4, 1
;;       sub     a0, a1, a0
;;       sltu    a0, a0, a2
;;       add     a5, a5, a2
;;       lui     a1, 1
;;       add     a5, a5, a1
;;       neg     a4, a0
;;       not     a0, a4
;;       and     a0, a5, a0
;;       sb      a3, 0(a0)
;;       ld      ra, 8(sp)
;;       ld      s0, 0(sp)
;;       addi    sp, sp, 0x10
;;       ret
;;
;; wasm[0]::function[1]:
;;       addi    sp, sp, -0x10
;;       sd      ra, 8(sp)
;;       sd      s0, 0(sp)
;;       mv      s0, sp
;;       ld      a1, 0x40(a0)
;;       ld      a5, 0x38(a0)
;;       lui     a4, 1
;;       addi    a0, a4, 1
;;       sub     a0, a1, a0
;;       sltu    a0, a0, a2
;;       add     a5, a5, a2
;;       lui     a1, 1
;;       add     a5, a5, a1
;;       neg     a3, a0
;;       not     a0, a3
;;       and     a0, a5, a0
;;       lbu     a0, 0(a0)
;;       ld      ra, 8(sp)
;;       ld      s0, 0(sp)
;;       addi    sp, sp, 0x10
;;       ret
