;;! target = "riscv64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -W memory64 -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store offset=0xffff0000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load offset=0xffff0000))

;; wasm[0]::function[0]:
;;       addi    sp, sp, -0x10
;;       sd      ra, 8(sp)
;;       sd      s0, 0(sp)
;;       mv      s0, sp
;;       lui     a5, 0x3fffc
;;       addi    a1, a5, 1
;;       slli    a1, a1, 2
;;       add     a1, a2, a1
;;       bgeu    a1, a2, 8
;;       .byte   0x00, 0x00, 0x00, 0x00
;;       ld      a4, 0x40(a0)
;;       ld      a5, 0x38(a0)
;;       sltu    a0, a4, a1
;;       add     a1, a5, a2
;;       lui     a2, 0xffff
;;       slli    a2, a2, 4
;;       add     a1, a1, a2
;;       neg     a0, a0
;;       not     a0, a0
;;       and     a0, a1, a0
;;       sw      a3, 0(a0)
;;       ld      ra, 8(sp)
;;       ld      s0, 0(sp)
;;       addi    sp, sp, 0x10
;;       ret
;;
;; wasm[0]::function[1]:
;;       addi    sp, sp, -0x10
;;       sd      ra, 8(sp)
;;       sd      s0, 0(sp)
;;       mv      s0, sp
;;       lui     a5, 0x3fffc
;;       addi    a1, a5, 1
;;       slli    a1, a1, 2
;;       add     a1, a2, a1
;;       bgeu    a1, a2, 8
;;       .byte   0x00, 0x00, 0x00, 0x00
;;       ld      a3, 0x40(a0)
;;       ld      a4, 0x38(a0)
;;       sltu    a0, a3, a1
;;       add     a1, a4, a2
;;       lui     a2, 0xffff
;;       slli    a2, a2, 4
;;       add     a1, a1, a2
;;       neg     a0, a0
;;       not     a0, a0
;;       and     a0, a1, a0
;;       lw      a0, 0(a0)
;;       ld      ra, 8(sp)
;;       ld      s0, 0(sp)
;;       addi    sp, sp, 0x10
;;       ret
