;;! target = "riscv64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-forced -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0x1000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load8_u offset=0x1000))

;; wasm[0]::function[0]:
;;       addi    sp, sp, -0x10
;;       sd      ra, 8(sp)
;;       sd      s0, 0(sp)
;;       mv      s0, sp
;;       slli    a2, a2, 0x20
;;       srli    a5, a2, 0x20
;;       auipc   a4, 0
;;       ld      a4, 0x40(a4)
;;       sltu    a4, a4, a5
;;       ld      a0, 0x50(a0)
;;       add     a5, a0, a5
;;       lui     a0, 1
;;       add     a5, a5, a0
;;       neg     a1, a4
;;       not     a4, a1
;;       and     a5, a5, a4
;;       sb      a3, 0(a5)
;;       ld      ra, 8(sp)
;;       ld      s0, 0(sp)
;;       addi    sp, sp, 0x10
;;       ret
;;       .byte   0x00, 0x00, 0x00, 0x00
;;       .byte   0xff, 0xef, 0xff, 0xff
;;       .byte   0x00, 0x00, 0x00, 0x00
;;
;; wasm[0]::function[1]:
;;       addi    sp, sp, -0x10
;;       sd      ra, 8(sp)
;;       sd      s0, 0(sp)
;;       mv      s0, sp
;;       slli    a2, a2, 0x20
;;       srli    a4, a2, 0x20
;;       auipc   a3, 0
;;       ld      a3, 0x40(a3)
;;       sltu    a3, a3, a4
;;       ld      a5, 0x50(a0)
;;       add     a4, a5, a4
;;       lui     a5, 1
;;       add     a4, a4, a5
;;       neg     a1, a3
;;       not     a3, a1
;;       and     a5, a4, a3
;;       lbu     a0, 0(a5)
;;       ld      ra, 8(sp)
;;       ld      s0, 0(sp)
;;       addi    sp, sp, 0x10
;;       ret
;;       .byte   0x00, 0x00, 0x00, 0x00
;;       .byte   0xff, 0xef, 0xff, 0xff
;;       .byte   0x00, 0x00, 0x00, 0x00
