;;! target = "riscv64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-forced -O static-memory-guard-size=4294967295 -O dynamic-memory-guard-size=4294967295"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0x1000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0x1000))

;; wasm[0]::function[0]:
;;    0: addi    sp, sp, -0x10
;;    4: sd      ra, 8(sp)
;;    8: sd      s0, 0(sp)
;;    c: mv      s0, sp
;;   10: ld      a4, 0x50(a0)
;;   14: slli    a1, a2, 0x20
;;   18: srli    a5, a1, 0x20
;;   1c: add     a2, a4, a5
;;   20: lui     t6, 1
;;   24: add     t6, t6, a2
;;   28: sw      a3, 0(t6)
;;   2c: ld      ra, 8(sp)
;;   30: ld      s0, 0(sp)
;;   34: addi    sp, sp, 0x10
;;   38: ret
;;
;; wasm[0]::function[1]:
;;   3c: addi    sp, sp, -0x10
;;   40: sd      ra, 8(sp)
;;   44: sd      s0, 0(sp)
;;   48: mv      s0, sp
;;   4c: ld      a3, 0x50(a0)
;;   50: slli    a1, a2, 0x20
;;   54: srli    a4, a1, 0x20
;;   58: add     a2, a3, a4
;;   5c: lui     t6, 1
;;   60: add     t6, t6, a2
;;   64: lw      a0, 0(t6)
;;   68: ld      ra, 8(sp)
;;   6c: ld      s0, 0(sp)
;;   70: addi    sp, sp, 0x10
;;   74: ret
