test compile precise-output
target pulley32

function %brif_i8(i8) -> i8 {
block0(v0: i8):
  brif v0, block1, block2

block1:
  v1 = iconst.i8 1
  return v1

block2:
  v2 = iconst.i8 0
  return v2
}

; VCode:
; block0:
;   zext8 x4, x0
;   br_if32 x4, label2; jump label1
; block1:
;   xzero x0
;   ret
; block2:
;   xone x0
;   ret
;
; Disassembled:
; zext8 x4, x0
; br_if32 x4, 0x9    // target = 0xc
; xzero x0
; ret
; xone x0
; ret

function %brif_i16(i16) -> i8 {
block0(v0: i16):
  brif v0, block1, block2

block1:
  v1 = iconst.i8 1
  return v1

block2:
  v2 = iconst.i8 0
  return v2
}

; VCode:
; block0:
;   zext16 x4, x0
;   br_if32 x4, label2; jump label1
; block1:
;   xzero x0
;   ret
; block2:
;   xone x0
;   ret
;
; Disassembled:
; zext16 x4, x0
; br_if32 x4, 0x9    // target = 0xc
; xzero x0
; ret
; xone x0
; ret

function %brif_i32(i32) -> i8 {
block0(v0: i32):
  brif v0, block1, block2

block1:
  v1 = iconst.i8 1
  return v1

block2:
  v2 = iconst.i8 0
  return v2
}

; VCode:
; block0:
;   br_if32 x0, label2; jump label1
; block1:
;   xzero x0
;   ret
; block2:
;   xone x0
;   ret
;
; Disassembled:
; br_if32 x0, 0x9    // target = 0x9
; xzero x0
; ret
; xone x0
; ret

function %brif_i64(i64) -> i8 {
block0(v0: i64):
  brif v0, block1, block2

block1:
  v1 = iconst.i8 1
  return v1

block2:
  v2 = iconst.i8 0
  return v2
}

; VCode:
; block0:
;   br_if_xneq64_i32 x0, 0, label2; jump label1
; block1:
;   xzero x0
;   ret
; block2:
;   xone x0
;   ret
;
; Disassembled:
; br_if_xneq64_i8 x0, 0, 0xa    // target = 0xa
; xzero x0
; ret
; xone x0
; ret

function %brif_icmp_i8(i8, i8) -> i8 {
block0(v0: i8, v1: i8):
  v2 = icmp eq v0, v1
  brif v2, block1, block2

block1:
  v3 = iconst.i8 1
  return v3

block2:
  v4 = iconst.i8 0
  return v4
}

; VCode:
; block0:
;   zext8 x6, x0
;   zext8 x8, x1
;   xeq32 x10, x6, x8
;   zext8 x8, x10
;   br_if32 x8, label2; jump label1
; block1:
;   xzero x0
;   ret
; block2:
;   xone x0
;   ret
;
; Disassembled:
; zext8 x6, x0
; zext8 x8, x1
; xeq32 x10, x6, x8
; zext8 x8, x10
; br_if32 x8, 0x9    // target = 0x15
; xzero x0
; ret
; xone x0
; ret

function %brif_icmp_i16(i16, i16) -> i8 {
block0(v0: i16, v1: i16):
  v2 = icmp ne v0, v1
  brif v2, block1, block2

block1:
  v3 = iconst.i8 1
  return v3

block2:
  v4 = iconst.i8 0
  return v4
}

; VCode:
; block0:
;   zext16 x6, x0
;   zext16 x8, x1
;   xneq32 x10, x6, x8
;   zext8 x8, x10
;   br_if32 x8, label2; jump label1
; block1:
;   xzero x0
;   ret
; block2:
;   xone x0
;   ret
;
; Disassembled:
; zext16 x6, x0
; zext16 x8, x1
; xneq32 x10, x6, x8
; zext8 x8, x10
; br_if32 x8, 0x9    // target = 0x15
; xzero x0
; ret
; xone x0
; ret

function %brif_icmp_i32(i32, i32) -> i8 {
block0(v0: i32, v1: i32):
  v2 = icmp slt v0, v1
  brif v2, block1, block2

block1:
  v3 = iconst.i8 1
  return v3

block2:
  v4 = iconst.i8 0
  return v4
}

; VCode:
; block0:
;   br_if_xslt32 x0, x1, label2; jump label1
; block1:
;   xzero x0
;   ret
; block2:
;   xone x0
;   ret
;
; Disassembled:
; br_if_xslt32 x0, x1, 0xa    // target = 0xa
; xzero x0
; ret
; xone x0
; ret

function %brif_icmp_i64(i64, i64) -> i8 {
block0(v0: i64, v1: i64):
  v2 = icmp uge v0, v1
  brif v2, block1, block2

block1:
  v3 = iconst.i8 1
  return v3

block2:
  v4 = iconst.i8 0
  return v4
}

; VCode:
; block0:
;   br_if_xulteq64 x1, x0, label2; jump label1
; block1:
;   xzero x0
;   ret
; block2:
;   xone x0
;   ret
;
; Disassembled:
; br_if_xulteq64 x1, x0, 0xa    // target = 0xa
; xzero x0
; ret
; xone x0
; ret

function %brif_icmp_i32_imm(i32) -> i8 {
block0(v0: i32):
  v5 = iconst.i32 10
  v2 = icmp slt v0, v5
  brif v2, block1, block2

block1:
  v3 = iconst.i8 1
  return v3

block2:
  v4 = iconst.i8 0
  return v4
}

; VCode:
; block0:
;   br_if_xslt32_i32 x0, 10, label2; jump label1
; block1:
;   xzero x0
;   ret
; block2:
;   xone x0
;   ret
;
; Disassembled:
; br_if_xslt32_i8 x0, 10, 0xa    // target = 0xa
; xzero x0
; ret
; xone x0
; ret

function %brif_icmp_i32_imm_big(i32) -> i8 {
block0(v0: i32):
  v5 = iconst.i32 88888
  v2 = icmp slt v0, v5
  brif v2, block1, block2

block1:
  v3 = iconst.i8 1
  return v3

block2:
  v4 = iconst.i8 0
  return v4
}

; VCode:
; block0:
;   br_if_xslt32_i32 x0, 88888, label2; jump label1
; block1:
;   xzero x0
;   ret
; block2:
;   xone x0
;   ret
;
; Disassembled:
; br_if_xslt32_i32 x0, 88888, 0xd    // target = 0xd
; xzero x0
; ret
; xone x0
; ret

function %brif_icmp_i64_imm(i64) -> i8 {
block0(v0: i64):
  v5 = iconst.i64 10
  v2 = icmp slt v0, v5
  brif v2, block1, block2

block1:
  v3 = iconst.i8 1
  return v3

block2:
  v4 = iconst.i8 0
  return v4
}

; VCode:
; block0:
;   br_if_xslt64_i32 x0, 10, label2; jump label1
; block1:
;   xzero x0
;   ret
; block2:
;   xone x0
;   ret
;
; Disassembled:
; br_if_xslt64_i8 x0, 10, 0xa    // target = 0xa
; xzero x0
; ret
; xone x0
; ret

function %brif_icmp_i64_imm_big(i64) -> i8 {
block0(v0: i64):
  v5 = iconst.i64 88888
  v2 = icmp slt v0, v5
  brif v2, block1, block2

block1:
  v3 = iconst.i8 1
  return v3

block2:
  v4 = iconst.i8 0
  return v4
}

; VCode:
; block0:
;   br_if_xslt64_i32 x0, 88888, label2; jump label1
; block1:
;   xzero x0
;   ret
; block2:
;   xone x0
;   ret
;
; Disassembled:
; br_if_xslt64_i32 x0, 88888, 0xd    // target = 0xd
; xzero x0
; ret
; xone x0
; ret

