test compile precise-output
target pulley32

function %load_i32(i32) -> i32 {
block0(v0: i32):
    v1 = load.i32 v0
    return v1
}

; VCode:
; block0:
;   x0 = xload32 x0+0 // flags =
;   ret
;
; Disassembled:
; xload32le_offset8 x0, x0, 0
; ret

function %load_i64(i32) -> i64 {
block0(v0: i32):
    v1 = load.i64 v0
    return v1
}

; VCode:
; block0:
;   x0 = xload64 x0+0 // flags =
;   ret
;
; Disassembled:
; xload64le_offset8 x0, x0, 0
; ret

function %load_i32_with_offset(i32) -> i32 {
block0(v0: i32):
    v1 = load.i32 v0+4
    return v1
}

; VCode:
; block0:
;   x0 = xload32 x0+4 // flags =
;   ret
;
; Disassembled:
; xload32le_offset8 x0, x0, 4
; ret

function %load_i64_with_offset(i32) -> i64 {
block0(v0: i32):
    v1 = load.i64 v0+8
    return v1
}

; VCode:
; block0:
;   x0 = xload64 x0+8 // flags =
;   ret
;
; Disassembled:
; xload64le_offset8 x0, x0, 8
; ret

