test compile precise-output
target pulley32

function %ret_stack() -> i32 {
    ss0 = explicit_slot 4
block0():
    v0 = stack_addr.i32 ss0
    return v0
}

; VCode:
;   x30 = xconst8 -16
;   x27 = xadd32 x27, x30
;   store64 sp+8, x28 // flags =  notrap aligned
;   store64 sp+0, x29 // flags =  notrap aligned
;   x29 = xmov x27
;   x30 = xconst8 -16
;   x27 = xadd32 x27, x30
; block0:
;   x0 = load_addr Slot(0)
;   x30 = xconst8 16
;   x27 = xadd32 x27, x30
;   x28 = load64_u sp+8 // flags = notrap aligned
;   x29 = load64_u sp+0 // flags = notrap aligned
;   x30 = xconst8 16
;   x27 = xadd32 x27, x30
;   ret
;
; Disassembled:
; xconst8 spilltmp0, -16
; xadd32 sp, sp, spilltmp0
; store64_offset8 sp, 8, lr
; store64 sp, fp
; xmov fp, sp
; xconst8 spilltmp0, -16
; xadd32 sp, sp, spilltmp0
; xmov x0, sp
; xconst8 spilltmp0, 16
; xadd32 sp, sp, spilltmp0
; load64_offset8 lr, sp, 8
; load64 fp, sp
; xconst8 spilltmp0, 16
; xadd32 sp, sp, spilltmp0
; ret

