test optimize precise-output
set opt_level=speed
target x86_64

function %fold_sub_add1(i8, i8) -> i8 {
block0(v0: i8, v1: i8):
    v2 = iadd v0, v1
    v3 = isub v2, v1
    return v3
}

; function %fold_sub_add1(i8, i8) -> i8 fast {
; block0(v0: i8, v1: i8):
;     return v0
; }



function %fold_sub_add2(i16, i16) -> i16 {
block0(v0: i16, v1: i16):
    v2 = iadd v0, v1
    v3 = isub v2, v1
    return v3
}

; function %fold_sub_add2(i16, i16) -> i16 fast {
; block0(v0: i16, v1: i16):
;     return v0
; }



function %fold_sub_add3(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = iadd v0, v1
    v3 = isub v2, v1
    return v3
}

; function %fold_sub_add3(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     return v0
; }



function %fold_sub_add4(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = iadd v0, v1
    v3 = isub v2, v1
    return v3
}

; function %fold_sub_add4(i64, i64) -> i64 fast {
; block0(v0: i64, v1: i64):
;     return v0
; }



