test optimize precise-output
set opt_level=speed
target x86_64

function %test1(i8, i8, i8) -> i8 {
block0(v0: i8, v1: i8, v3: i8):
    v2 = ishl v0, v1
    v4 = ishl v3, v1
    v5 = band v2, v4
    return v5
}

; function %test1(i8, i8, i8) -> i8 fast {
; block0(v0: i8, v1: i8, v3: i8):
;     v6 = band v0, v3
;     v7 = ishl v6, v1
;     return v7
; }

function %test2(i16, i16, i16) -> i16 {
block0(v0: i16, v1: i16, v3: i16):
    v2 = ishl v0, v1
    v4 = ishl v3, v1
    v5 = band v2, v4
    return v5
}

; function %test2(i16, i16, i16) -> i16 fast {
; block0(v0: i16, v1: i16, v3: i16):
;     v6 = band v0, v3
;     v7 = ishl v6, v1
;     return v7
; }

function %test3(i32, i32, i32) -> i32 {
block0(v0: i32, v1: i32, v3: i32):
    v2 = ishl v0, v1
    v4 = ishl v3, v1
    v5 = band v2, v4
    return v5
}

; function %test3(i32, i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32, v3: i32):
;     v6 = band v0, v3
;     v7 = ishl v6, v1
;     return v7
; }

function %test4(i64, i64, i64) -> i64 {
block0(v0: i64, v1: i64, v3: i64):
    v2 = ishl v0, v1
    v4 = ishl v3, v1
    v5 = band v2, v4
    return v5
}

; function %test4(i64, i64, i64) -> i64 fast {
; block0(v0: i64, v1: i64, v3: i64):
;     v6 = band v0, v3
;     v7 = ishl v6, v1
;     return v7
; }

