test optimize precise-output
set opt_level=speed
target x86_64

;; (rule (simplify (bor ty x (bor ty x y))) (bor ty x y))
function %simplify_bor_xxy(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = bor v0, v1
    v3 = bor v0, v2
    return v3
}

; function %simplify_bor_xxy(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v2 = bor v0, v1
;     return v2
; }

;; (rule (simplify (bor ty y (bor ty x y))) (bor ty x y))
function %simplify_bor_yxy(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v3 = bor v0, v1
    v4 = bor v1, v3
    return v4
}

; function %simplify_bor_yxy(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v3 = bor v0, v1
;     return v3
; }

;; (rule (simplify (bor ty (bor ty x y) x)) (bor ty x y))
function %simplify_bor_xyx(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = bor v0, v1
    v3 = bor v2, v0
    return v3
}

; function %simplify_bor_xyx(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v2 = bor v0, v1
;     return v2
; }

;; (rule (simplify (bor ty (bor ty x y) y)) (bor ty x y))
function %simplify_bor_xyy(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = bor v0, v1
    v3 = bor v2, v1
    return v3
}

; function %simplify_bor_xyy(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v2 = bor v0, v1
;     return v2
; }

;; (bxor ty (band ty z x) (band ty z y)) -> (band ty z (bxor ty x y))
function %test_bxor_band_band(i32, i32, i32) -> i32 fast {
block0(v0: i32, v1: i32, v2: i32):
    v3 = band v0, v1  
    v4 = band v0, v2 
    v5 = bxor v3, v4
    return v5
}

; function %test_bxor_band_band(i32, i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32, v2: i32):
;     v6 = bxor v1, v2
;     v7 = band v0, v6
;     return v7
; }

;; (bor ty (band ty x y) (bnot ty (bxor ty x y))) -> (bnot ty (bxor ty x y))
function %test_bor_band_bnot_bxor(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = band v0, v1
    v3 = bxor v0, v1
    v4 = bnot v3
    v5 = bor v2, v4
    return v5
}

; function %test_bor_band_bnot_bxor(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v6 = bxor v1, v0
;     v7 = bnot v6
;     return v7
; }

;; (iadd ty (bor ty x y) (ineg ty y)) -> (band ty x (bnot ty y))
function %test_iadd_bor_ineg(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = bor v0, v1
    v3 = ineg v1
    v4 = iadd v2, v3
    return v4
}

; function %test_iadd_bor_ineg(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v2 = bor v0, v1
;     v7 = isub v2, v1
;     return v7
; }

;; (band ty (bor ty x y) x) -> x
function %test_band_bor_absorb_x(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = bor v0, v1
    v3 = band v2, v0
    return v3
}

; function %test_band_bor_absorb_x(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     return v0
; }

;; (band ty (bor ty x z) (bor ty y z)) -> (bor ty (band ty x y) z)
function %test_band_bor_bor(i32, i32, i32) -> i32 fast {
block0(v0: i32, v1: i32, v2: i32):
    v3 = bor v0, v2
    v4 = bor v1, v2
    v5 = band v3, v4
    return v5
}

; function %test_band_bor_bor(i32, i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32, v2: i32):
;     v8 = band v1, v0
;     v9 = bor v8, v2
;     return v9
; }

;; (bor ty (band ty x z) (band ty y z)) -> (band ty (bor ty x y) z)
function %test_bor_band_band(i32, i32, i32) -> i32 fast {
block0(v0: i32, v1: i32, v2: i32):
    v3 = band v0, v2
    v4 = band v1, v2
    v5 = bor v3, v4
    return v5
}

; function %test_bor_band_band(i32, i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32, v2: i32):
;     v8 = bor v1, v0
;     v9 = band v8, v2
;     return v9
; }

;; (bxor ty (bor ty x y) (bor ty x (bnot ty y))) -> (bnot ty x)
function %test_bxor_bor_bor_bnot(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = bor v0, v1
    v3 = bnot v1
    v4 = bor v0, v3
    v5 = bxor v2, v4
    return v5
}

; function %test_bxor_bor_bor_bnot(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v6 = bnot v0
;     return v6
; }

;; (band ty (bnot ty x) (bnot ty y)) -> (bnot ty (bor ty x y))
function %test_band_bnot_bnot(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = bnot v0
    v3 = bnot v1
    v4 = band v2, v3
    return v4
}

; function %test_band_bnot_bnot(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v7 = bor v1, v0
;     v8 = bnot v7
;     return v8
; }

;; (bor ty (bnot ty x) (bnot ty y)) -> (bnot ty (band ty x y))
function %test_bor_bnot_bnot(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = bnot v0
    v3 = bnot v1
    v4 = bor v2, v3
    return v4
}

; function %test_bor_bnot_bnot(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v7 = band v1, v0
;     v8 = bnot v7
;     return v8
; }


;; ((x & ~y) - (x & y)) --> ((x ^ y) - y)
function %test_isub_band_band_bnot(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = bnot v1
    v3 = band v0, v2
    v4 = band v0, v1
    v5 = isub v3, v4
    return v5
}

; function %test_isub_band_band_bnot(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v2 = bnot v1
;     v3 = band v0, v2
;     v4 = band v0, v1
;     v5 = isub v3, v4
;     return v5
; }

;; (x & ~y) | (~x & y) --> (x ^ y)
function %test_bor_band_bnot_to_bxor(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = bnot v1
    v3 = band v0, v2
    v4 = bnot v0
    v5 = band v4, v1
    v6 = bor v3, v5
    return v6
}

; function %test_bor_band_bnot_to_bxor(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v2 = bnot v1
;     v3 = band v0, v2
;     v4 = bnot v0
;     v5 = band v4, v1
;     v6 = bor v3, v5
;     return v6
; }

;; (x & ~y) | (x ^ y) --> (x ^ y)
function %test_bor_band_bnot_bxor_absorb(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = bnot v1
    v3 = band v0, v2
    v4 = bxor v0, v1
    v5 = bor v3, v4
    return v5
}

; function %test_bor_band_bnot_bxor_absorb(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v2 = bnot v1
;     v3 = band v0, v2
;     v4 = bxor v0, v1
;     v5 = bor v3, v4
;     return v5
; }

;; (x & ~y) ^ ~x --> ~(x & y)
function %test_bxor_band_bnot_to_bnot_band(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = bnot v1
    v3 = band v0, v2
    v4 = bnot v0
    v5 = bxor v3, v4
    return v5
}

; function %test_bxor_band_bnot_to_bnot_band(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v6 = band v1, v0
;     v10 = bnot v6
;     return v10
; }

;; (~x & y) ^ x --> x | y
function %test_bxor_band_bnot_x(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = bnot v0
    v3 = band v2, v1
    v4 = bxor v3, v0
    return v4
}

; function %test_bxor_band_bnot_x(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v5 = bor v0, v1
;     return v5
; }

;; (x | y) & ~(x ^ y) --> x & y
function %test_band_bor_bnot_bxor(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = bor v0, v1
    v3 = bxor v0, v1
    v4 = bnot v3
    v5 = band v2, v4
    return v5
}

; function %test_band_bor_bnot_bxor(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v7 = band v1, v0
;     return v7
; }

;; x | ~(x ^ y) --> x | ~y
function %test_bor_bnot_bxor(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = bxor v0, v1
    v3 = bnot v2
    v4 = bor v0, v3
    return v4
}

; function %test_bor_bnot_bxor(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v5 = bnot v1
;     v6 = bor v0, v5
;     return v6
; }

;; x | ((~x) ^ y) --> x | ~y
function %test_bor_bxor_bnot_x(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = bnot v0
    v3 = bxor v2, v1
    v4 = bor v0, v3
    return v4
}

; function %test_bor_bxor_bnot_x(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v5 = bnot v1
;     v6 = bor v0, v5
;     return v6
; }

;; x & ~(x ^ y) --> x & y
function %test_band_bnot_bxor(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = bxor v0, v1
    v3 = bnot v2
    v4 = band v0, v3
    return v4
}

; function %test_band_bnot_bxor(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v5 = band v0, v1
;     return v5
; }

;; x & ((~x) ^ y) --> x & y
function %test_band_bxor_bnot_x(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = bnot v0
    v3 = bxor v2, v1
    v4 = band v0, v3
    return v4
}

; function %test_band_bxor_bnot_x(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v5 = band v0, v1
;     return v5
; }

;; (x | y) | (x ^ y) --> (x | y)
function %test_bor_bor_bxor_same(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = bor v0, v1
    v3 = bxor v0, v1
    v4 = bor v2, v3
    return v4
}

; function %test_bor_bor_bxor_same(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v5 = bor v1, v0
;     return v5
; }

;; (x ^ y) & ((y ^ z) ^ x) --> (x ^ y) & ~z
function %test_band_bxor_bxor_bnot(i32, i32, i32) -> i32 fast {
block0(v0: i32, v1: i32, v2: i32):
    v3 = bxor v0, v1
    v4 = bxor v1, v2
    v5 = bxor v4, v0
    v6 = band v3, v5
    return v6
}

; function %test_band_bxor_bxor_bnot(i32, i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32, v2: i32):
;     v3 = bxor v0, v1
;     v7 = bnot v2
;     v8 = band v3, v7
;     return v8
; }

;; (~x & y) ^ z --> (x & y) ^ (z ^ y)
function %test_bxor_band_bnot_general(i32, i32, i32) -> i32 fast {
block0(v0: i32, v1: i32, v2: i32):
    v3 = bnot v0
    v4 = band v3, v1
    v5 = bxor v4, v2
    return v5
}

; function %test_bxor_band_bnot_general(i32, i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32, v2: i32):
;     v6 = band v0, v1
;     v7 = bxor v2, v1
;     v8 = bxor v6, v7
;     return v8
; }

;; ~x - ~y --> y - x
function %test_isub_bnot_bnot(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = bnot v0
    v3 = bnot v1
    v4 = isub v2, v3
    return v4
}

; function %test_isub_bnot_bnot(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v5 = isub v1, v0
;     return v5
; }

;; (~x & y) | ~(x | y) --> ~x
function %test_bor_band_bnot_bor_to_bnot(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = bnot v0
    v3 = band v2, v1
    v4 = bor v0, v1
    v5 = bnot v4
    v6 = bor v3, v5
    return v6
}

; function %test_bor_band_bnot_bor_to_bnot(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v2 = bnot v0
;     return v2
; }

;; (~x | y) & ~(x & y) --> ~x
function %test_band_bor_bnot_band_to_bnot(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = bnot v0
    v3 = bor v2, v1
    v4 = band v0, v1
    v5 = bnot v4
    v6 = band v3, v5
    return v6
}

; function %test_band_bor_bnot_band_to_bnot(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v2 = bnot v0
;     return v2
; }

;; (x & y) | ~(x | y) --> ~(x ^ y)
function %test_bor_band_bnot_bor_to_bnot_bxor(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = band v0, v1
    v3 = bor v0, v1
    v4 = bnot v3
    v5 = bor v2, v4
    return v5
}

; function %test_bor_band_bnot_bor_to_bnot_bxor(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v8 = bxor v1, v0
;     v9 = bnot v8
;     return v9
; }

;; (~x | y) ^ (x ^ y) --> x | ~y
function %test_bxor_bor_bnot_bxor(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = bnot v0
    v3 = bor v2, v1
    v4 = bxor v0, v1
    v5 = bxor v3, v4
    return v5
}

; function %test_bxor_bor_bnot_bxor(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v6 = bnot v1
;     v7 = bor v0, v6
;     return v7
; }

;; (x & ~y) == ~y --> (x | y) == -1
function %test_eq_band_bnot_fullmask(i32, i32) -> i8 fast {
block0(v0: i32, v1: i32):
    v2 = bnot v1
    v3 = band v0, v2
    v4 = icmp eq v3, v2
    return v4
}

; function %test_eq_band_bnot_fullmask(i32, i32) -> i8 fast {
; block0(v0: i32, v1: i32):
;     v5 = bor v1, v0
;     v6 = iconst.i32 -1
;     v7 = icmp eq v5, v6  ; v6 = -1
;     return v7
; }

;; x >=_u (x & y) --> true
function %test_uge_x_band(i32, i32) -> i8 fast {
block0(v0: i32, v1: i32):
    v2 = band v0, v1
    v3 = icmp uge v0, v2
    return v3
}

; function %test_uge_x_band(i32, i32) -> i8 fast {
; block0(v0: i32, v1: i32):
;     v2 = band v0, v1
;     v3 = icmp uge v0, v2
;     return v3
; }

;; (x & y) <=_u x --> true
function %test_ule_band_x(i32, i32) -> i8 fast {
block0(v0: i32, v1: i32):
    v2 = band v0, v1
    v3 = icmp ule v2, v0
    return v3
}

; function %test_ule_band_x(i32, i32) -> i8 fast {
; block0(v0: i32, v1: i32):
;     v2 = band v0, v1
;     v3 = icmp ule v2, v0
;     return v3
; }

;; (x | y) >=_u x --> true
function %test_uge_bor_x(i32, i32) -> i8 fast {
block0(v0: i32, v1: i32):
    v2 = bor v0, v1
    v3 = icmp uge v2, v0
    return v3
}

; function %test_uge_bor_x(i32, i32) -> i8 fast {
; block0(v0: i32, v1: i32):
;     v2 = bor v0, v1
;     v3 = icmp uge v2, v0
;     return v3
; }

;; x <=_u (x | y) --> true
function %test_ule_x_bor(i32, i32) -> i8 fast {
block0(v0: i32, v1: i32):
    v2 = bor v0, v1
    v3 = icmp ule v0, v2
    return v3
}

; function %test_ule_x_bor(i32, i32) -> i8 fast {
; block0(v0: i32, v1: i32):
;     v2 = bor v0, v1
;     v3 = icmp ule v0, v2
;     return v3
; }

