test compile precise-output
set opt_level=speed
target x86_64

;; `atomic_rmw` is not a load, but it reports `true` to `.can_load()`. We want
;; to make sure the alias analysis machinery doesn't break when we have these odd
;; memory ops in the IR.

function u0:1302(i64) -> i64 system_v {
  block0(v0: i64):
    v9 = atomic_rmw.i64 add v0, v0
    return v0
}

; VCode:
;   pushq   %rbp
;   movq    %rsp, %rbp
; block0:
;   lock addq %rdi, (%rdi)
;   movq    %rdi, %rax
;   movq    %rbp, %rsp
;   popq    %rbp
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   pushq %rbp
;   movq %rsp, %rbp
; block1: ; offset 0x4
;   lock addq %rdi, (%rdi) ; trap: heap_oob
;   movq %rdi, %rax
;   movq %rbp, %rsp
;   popq %rbp
;   retq

