test optimize
set opt_level=none
set use_egraphs=true
target x86_64

function %f(i32) -> i32 {
block0(v0: i32):
    v1 = iconst.i32 42
    v2 = iadd.i32 v0, v1
    brnz v2, block1
    jump block2

block1:
    v3 = iconst.i32 84
    v4 = iadd.i32 v2, v3
    return v4

block2:
    return v2
}

; check:  block0(v0: i32):
; check:      v1 = iconst.i32 42
; check:      v2 = iadd v0, v1
; check:      brnz v2, block1
; check:      jump block2
; check:   block1:
; check:      v11 = iconst.i32 126
; check:      v13 = iadd.i32 v0, v11
; check:      return v13
; check:   block2:
; check:      v15 = iconst.i32 42
; check:      v16 = iadd.i32 v0, v15
; check:      return v16

