test optimize precise-output
set opt_level=speed
target x86_64

;; (iadd ty (select ty c x y) z) -> (select ty c (x + z) (y + z))
function %simplify_iadd_select_const_i32(i8) -> i32 fast {
block0(v0: i8):
    v1 = iconst.i32 5
    v2 = iconst.i32 10
    v3 = select v0, v1, v2
    v4 = iconst.i32 3
    v5 = iadd v3, v4
    return v5
}

; function %simplify_iadd_select_const_i32(i8) -> i32 fast {
; block0(v0: i8):
;     v6 = iconst.i32 8
;     v7 = iconst.i32 13
;     v8 = select v0, v6, v7  ; v6 = 8, v7 = 13
;     return v8
; }


;; (iadd ty (select ty c x y) z) -> (select ty c (x + z) (y + z))
function %simplify_iadd_select_const_i32_big_constants(i8) -> i8 fast {
block0(v0: i8):
    v1 = iconst.i8 100
    v2 = iconst.i8 200
    v3 = select v0, v1, v2
    v4 = iconst.i8 200
    v5 = iadd v3, v4
    return v5
}

; function %simplify_iadd_select_const_i32_big_constants(i8) -> i8 fast {
; block0(v0: i8):
;     v6 = iconst.i8 44
;     v7 = iconst.i8 -112
;     v8 = select v0, v6, v7  ; v6 = 44, v7 = -112
;     return v8
; }


;; (iadd ty (select ty c x y) z) -> (select ty c (x + z) (y + z))
function %simplify_iadd_select_const_i64_big_constants(i8) -> i64 fast {
block0(v0: i8):
    v1 = iconst.i64 0xa000_0000_0000_0000
    v2 = iconst.i64 0xb000_0000_0000_0000
    v3 = select v0, v1, v2
    v4 = iconst.i64 0xc000_0000_0000_0000
    v5 = iadd v3, v4
    return v5
}

; function %simplify_iadd_select_const_i64_big_constants(i8) -> i64 fast {
; block0(v0: i8):
;     v6 = iconst.i64 0x6000_0000_0000_0000
;     v7 = iconst.i64 0x7000_0000_0000_0000
;     v8 = select v0, v6, v7  ; v6 = 0x6000_0000_0000_0000, v7 = 0x7000_0000_0000_0000
;     return v8
; }

function %test_sgt_select_slt_min(i32, i32) -> i8 fast {
block0(v0: i32, v1: i32):
    v2 = icmp slt v1, v0  
    v3 = select v2, v1, v0 
    v4 = icmp sgt v3, v0   
    return v4
}

; function %test_sgt_select_slt_min(i32, i32) -> i8 fast {
; block0(v0: i32, v1: i32):
;     v7 = iconst.i8 0
;     return v7  ; v7 = 0
; }

function %test_ugt_select_ult_min(i32, i32) -> i8 fast {
block0(v0: i32, v1: i32):
    v2 = icmp ult v1, v0  
    v3 = select v2, v1, v0 
    v4 = icmp ugt v3, v0   
    return v4
}

; function %test_ugt_select_ult_min(i32, i32) -> i8 fast {
; block0(v0: i32, v1: i32):
;     v7 = iconst.i8 0
;     return v7  ; v7 = 0
; }

function %select_eq_xy_xy_to_y(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = icmp eq v0, v1
    v3 = select v2, v0, v1
    return v3
}

; function %select_eq_xy_xy_to_y(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     return v1
; }

;; (x | (y != z)) ? y : z  ==> y
function %select_bor_ne_to_y(i8, i8, i8) -> i8 fast {
block0(v0: i8, v1: i8, v2: i8):
    v3 = icmp ne v1, v2
    v4 = bor v0, v3
    v5 = select v4, v1, v2
    return v5
}

; function %select_bor_ne_to_y(i8, i8, i8) -> i8 fast {
; block0(v0: i8, v1: i8, v2: i8):
;     return v1
; }

;; (x == y) ? x : (x | y)  ==> (x | y)
function %select_eq_xy_x_borxy_to_borxy(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = icmp eq v0, v1
    v3 = bor v0, v1
    v4 = select v2, v0, v3
    return v4
}

; function %select_eq_xy_x_borxy_to_borxy(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v3 = bor v0, v1
;     return v3
; }

;; (x != y) ? (x & y) : y  ==> (x & y)
function %select_ne_xy_bandxy_y_to_bandxy(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = icmp ne v0, v1
    v3 = band v0, v1
    v4 = select v2, v3, v1
    return v4
}

; function %select_ne_xy_bandxy_y_to_bandxy(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v3 = band v0, v1
;     return v3
; }

;; (x <_u y) ? 1 : (x == y)  ==> (x <=_u y)
function %select_ult_one_eq_to_ule(i8, i8) -> i8 fast {
block0(v0: i8, v1: i8):
    v2 = icmp ult v0, v1
    v3 = iconst.i8 1
    v4 = icmp eq v0, v1
    v5 = select v2, v3, v4
    return v5
}

; function %select_ult_one_eq_to_ule(i8, i8) -> i8 fast {
; block0(v0: i8, v1: i8):
;     v6 = icmp ule v0, v1
;     return v6
; }

;; (x < y) ? 1 : (x > y)  ==> (x != y)
function %select_slt_one_sgt_to_ne(i8, i8) -> i8 fast {
block0(v0: i8, v1: i8):
    v2 = icmp slt v0, v1
    v3 = iconst.i8 1
    v4 = icmp sgt v0, v1
    v5 = select v2, v3, v4
    return v5
}

; function %select_slt_one_sgt_to_ne(i8, i8) -> i8 fast {
; block0(v0: i8, v1: i8):
;     v6 = icmp ne v0, v1
;     return v6
; }

;; (x ? 1 : (x | y))  ==>  (x ? 1 : y)
function %select_x_one_borxy_to_select_x_one_y(i8, i8) -> i8 fast {
block0(v0: i8, v1: i8):
    v2 = iconst.i8 1
    v3 = bor v0, v1
    v4 = select v0, v2, v3
    return v4
}

; function %select_x_one_borxy_to_select_x_one_y(i8, i8) -> i8 fast {
; block0(v0: i8, v1: i8):
;     v2 = iconst.i8 1
;     v5 = select v0, v2, v1  ; v2 = 1
;     return v5
; }

;; if x == n then (y - n) else (y - x)  ==>  (y - x)
function %select_eq_xn_yminusn_yminusx_to_yminusx(i32, i32) -> i32 fast {
block0(v0: i32, v1: i32):
    v2 = iconst.i32 7
    v3 = icmp eq v0, v2
    v4 = isub v1, v2
    v5 = isub v1, v0
    v6 = select v3, v4, v5
    return v6
}

; function %select_eq_xn_yminusn_yminusx_to_yminusx(i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32):
;     v5 = isub v1, v0
;     return v5
; }

;; select(cond, eq(z, y), eq(p, y))  ==>  eq(y, select(cond, z, p))
function %select_eq_eq_to_eq_select(i8, i32, i32) -> i8 fast {
block0(v0: i8, v1: i32, v2: i32):
    v3 = icmp eq v2, v1
    v4 = iconst.i32 7
    v5 = icmp eq v4, v1
    v6 = select v0, v3, v5
    return v6
}

; function %select_eq_eq_to_eq_select(i8, i32, i32) -> i8 fast {
; block0(v0: i8, v1: i32, v2: i32):
;     v4 = iconst.i32 7
;     v9 = select v0, v2, v4  ; v4 = 7
;     v10 = icmp eq v1, v9
;     return v10
; }

