test optimize precise-output
set opt_level=speed
target x86_64

function %fold_shifts_over_and1(i32, i32, i32) -> i32 {
block0(v0: i32, v1: i32, v3: i32):
    v2 = ishl v0, v1
    v4 = band v2, v3
    v5 = ushr v4, v1
    return v5
}

; function %fold_shifts_over_and1(i32, i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32, v3: i32):
;     v6 = ushr v3, v1
;     v7 = band v0, v6
;     return v7
; }

function %fold_shifts_over_and2(i64, i64, i64) -> i64 {
block0(v0: i64, v1: i64, v3: i64):
    v2 = ishl v0, v1
    v4 = band v2, v3
    v5 = ushr v4, v1
    return v5
}

; function %fold_shifts_over_and2(i64, i64, i64) -> i64 fast {
; block0(v0: i64, v1: i64, v3: i64):
;     v6 = ushr v3, v1
;     v7 = band v0, v6
;     return v7
; }

