test optimize
set opt_level=speed
target x86_64

function %f1(i32) -> f64x2 {
block0(v0: i32):
  v1 = splat.i32x2 v0
  v2 = fcvt_from_uint.f64x2 v1
  return v2
  ; check: v3 = fcvt_from_uint.f64 v0
  ; check: v4 = splat.f64x2 v3
  ; check: return v4
}

function %f2(i32) -> f64x2 {
block0(v0: i32):
  v1 = uextend.i64 v0
  v2 = splat.i64x2 v1
  v3 = fcvt_from_uint.f64x2 v2
  return v3
  ; check: v1 = uextend.i64 v0
  ; check: v4 = fcvt_from_uint.f64 v1
  ; check: v5 = splat.f64x2 v4
  ; check: return v5
}

function %f3(i32) -> f64x2 {
block0(v0: i32):
  v1 = splat.i32x2 v0
  v2 = fcvt_from_sint.f64x2 v1
  return v2
  ; check: v3 = fcvt_from_sint.f64 v0
  ; check: v4 = splat.f64x2 v3
  ; check: return v4
}
