;;! component_model_threading = true

(component definition $Tester
  (core module $Memory
    (table (export "t") 1 funcref)
  )
  (core instance $memory (instantiate $Memory))

  (core type $ft (func (param i32)))
  (core func $thread.new-indirect (canon thread.new-indirect $ft (table $memory "t")))
  (core func $thread.switch-to (canon thread.switch-to))
  (core func $thread.suspend (canon thread.suspend))
  (core func $thread.resume-later (canon thread.resume-later))
  (core func $thread.yield-to (canon thread.yield-to))

  (core module $DM
    (import "" "thread.new-indirect" (func $thread.new-indirect (param i32 i32) (result i32)))
    (import "" "thread.switch-to" (func $thread.switch-to (param i32) (result i32)))
    (import "" "thread.suspend" (func $thread.suspend (result i32)))
    (import "" "thread.resume-later" (func $thread.resume-later (param i32)))
    (import "" "thread.yield-to" (func $thread.yield-to (param i32) (result i32)))

    (func (export "noop"))
    (func (export "trap-calling-thread-new-indirect") (call $thread.new-indirect (i32.const 0) (i32.const 0)) drop)
    (func (export "trap-calling-thread-switch-to") (call $thread.switch-to (i32.const 0)) drop)
    (func (export "trap-calling-thread-suspend") (call $thread.suspend) drop)
    (func (export "trap-calling-thread-resume-later") (call $thread.resume-later (i32.const 0)))
    (func (export "trap-calling-thread-yield-to") (call $thread.yield-to (i32.const 0)) drop)
  )
  (core instance $dm (instantiate $DM (with "" (instance
    (export "thread.new-indirect" (func $thread.new-indirect))
    (export "thread.switch-to" (func $thread.switch-to))
    (export "thread.suspend" (func $thread.suspend))
    (export "thread.resume-later" (func $thread.resume-later))
    (export "thread.yield-to" (func $thread.yield-to))
  ))))
  (func (export "trap-calling-thread-new-indirect")
    (canon lift (core func $dm "noop")
      (post-return (func $dm "trap-calling-thread-new-indirect"))))
  (func (export "trap-calling-thread-switch-to")
    (canon lift (core func $dm "noop")
      (post-return (func $dm "trap-calling-thread-switch-to"))))
  (func (export "trap-calling-thread-suspend")
    (canon lift (core func $dm "noop")
      (post-return (func $dm "trap-calling-thread-suspend"))))
  (func (export "trap-calling-thread-resume-later")
    (canon lift (core func $dm "noop")
      (post-return (func $dm "trap-calling-thread-resume-later"))))
  (func (export "trap-calling-thread-yield-to")
    (canon lift (core func $dm "noop")
      (post-return (func $dm "trap-calling-thread-yield-to"))))
)

(component instance $i0 $Tester)
(assert_trap (invoke "trap-calling-thread-new-indirect") "cannot leave component instance")
(component instance $i1 $Tester)
(assert_trap (invoke "trap-calling-thread-switch-to") "cannot leave component instance")
(component instance $i2 $Tester)
(assert_trap (invoke "trap-calling-thread-suspend") "cannot leave component instance")
(component instance $i3 $Tester)
(assert_trap (invoke "trap-calling-thread-resume-later") "cannot leave component instance")
(component instance $i4 $Tester)
(assert_trap (invoke "trap-calling-thread-yield-to") "cannot leave component instance")
