//! A Cranelift-specific x64 assembler; see the `README.md` for more
//! information.

// All of the generated struct names use snake case.
#![allow(non_camel_case_types)]

mod api;
pub mod fuzz;
mod imm;
pub mod isle;
mod mem;
mod reg;
mod rex;

pub use api::{
    AsReg, CodeSink, Constant, KnownOffsetTable, Label, RegisterVisitor, Registers, TrapCode,
};
pub use imm::{Extension, Imm16, Imm32, Imm8, Simm32, Simm32PlusKnownOffset};
pub use mem::{Amode, DeferredTarget, GprMem, Scale};
pub use reg::{Gpr, NonRspGpr, Size};
pub use rex::RexFlags;

// Include code generated by the `meta` crate.
use mem::emit_modrm_sib_disp;
use rex::emit_simm;
include!(concat!(env!("OUT_DIR"), "/assembler.rs"));

/// Helper function to make code generation simpler.
fn emit_modrm(buffer: &mut impl CodeSink, enc_reg_g: u8, rm_e: u8) {
    let modrm = rex::encode_modrm(0b11, enc_reg_g & 7, rm_e & 7);
    buffer.put1(modrm);
}

/// List the files generated to create this assembler.
pub fn generated_files() -> Vec<std::path::PathBuf> {
    env!("ASSEMBLER_BUILT_FILES")
        .split(':')
        .map(std::path::PathBuf::from)
        .collect()
}
