/// `wasi-nn` API
///
/// `wasi-nn` is a WASI API for performing machine learning (ML) inference. The
/// API is not (yet) capable of performing ML training. WebAssembly programs
/// that want to use a host's ML capabilities can access these capabilities
/// through `wasi-nn`'s core abstractions: _backends_, _graphs_, and _tensors_.
/// A user selects a _backend_ for inference and `load`s a model, instantiated
/// as a _graph_, to use in the _backend_. Then, the user passes _tensor_ inputs
/// to the _graph_, computes the inference, and retrieves the _tensor_ outputs.
///
/// This module draws inspiration from the inference side of
/// [WebNN](https://webmachinelearning.github.io/webnn/#api). See the
/// [README](https://github.com/WebAssembly/wasi-nn/blob/main/README.md) for
/// more context about the design and goals of this API.

package wasi:nn

world ml {
    import inference
}
