;; Test the legalizations of `trap[n]z`.

test legalizer
target aarch64
target x86_64
target riscv64
target s390x

function %trapnz(i32) -> i32 {
block0(v0: i32):
    trapnz v0, heap_oob
    return v0
}

; check:  block0(v0: i32):
; nextln:     brif v0, block1, block2
; nextln: 
; nextln: block1 cold:
; nextln:     trap heap_oob
; nextln: 
; nextln: block2:
; nextln:     return v0

function %trapz(i32) -> i32 {
block0(v0: i32):
    trapz v0, heap_oob
    return v0
}

; check:  block0(v0: i32):
; nextln:     brif v0, block2, block1
; nextln: 
; nextln: block1 cold:
; nextln:     trap heap_oob
; nextln: 
; nextln: block2:
; nextln:     return v0

