default world command {
  import wall-clock: clocks.wall-clock
  import monotonic-clock: clocks.monotonic-clock
  import timezone: clocks.timezone
  import filesystem: filesystem.filesystem
  import instance-network: sockets.instance-network
  import ip-name-lookup: sockets.ip-name-lookup
  import network: sockets.network
  import tcp-create-socket: sockets.tcp-create-socket
  import tcp: sockets.tcp
  import udp-create-socket: sockets.udp-create-socket
  import udp: sockets.udp
  import random: random.random
  import insecure-random: random.insecure
  import insecure-random-seed: random.insecure-seed
  import poll: poll.poll
  import streams: io.streams
  import environment: wasi-cli-base.environment
  import preopens: wasi-cli-base.preopens
  import stdin: wasi-cli-base.stdio.stdin
  import stdout: wasi-cli-base.stdio.stdout
  import stderr: wasi-cli-base.stdio.stderr
  import exit: wasi-cli-base.exit

  export run: func() -> result
}
