test compile precise-output
set unwind_info=false
target riscv64

function %atomic_load_i64(i64) -> i64 {
block0(v0: i64):
  v1 = atomic_load.i64 v0
  return v1
}

; VCode:
; block0:
;   atomic_load.i64 a0,(a0)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   fence rw, rw
;   ld a0, 0(a0) ; trap: heap_oob
;   fence r, rw
;   ret

function %atomic_load_i32(i64) -> i32 {
block0(v0: i64):
  v1 = atomic_load.i32 v0
  return v1
}

; VCode:
; block0:
;   atomic_load.i32 a0,(a0)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   fence rw, rw
;   lw a0, 0(a0) ; trap: heap_oob
;   fence r, rw
;   ret

function %atomic_load_i32_i64(i64) -> i64 {
block0(v0: i64):
  v1 = atomic_load.i32 v0
  v2 = uextend.i64 v1
  return v2
}

; VCode:
; block0:
;   atomic_load.i32 a0,(a0)
;   slli a0,a0,32
;   srli a0,a0,32
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   fence rw, rw
;   lw a0, 0(a0) ; trap: heap_oob
;   fence r, rw
;   slli a0, a0, 0x20
;   srli a0, a0, 0x20
;   ret

