test compile precise-output
set opt_level=speed
target riscv64 has_zbb

function %band_not_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v3 = bnot v1
  v2 = band v0, v3
  return v2
}

; VCode:
; block0:
;   andn a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x33, 0x75, 0xb5, 0x40
;   ret

function %band_not_i32_reversed(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = bnot v0
  v3 = band v2, v1
  return v3
}

; VCode:
; block0:
;   andn a0,a1,a0
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x33, 0xf5, 0xa5, 0x40
;   ret

function %bor_not_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v3 = bnot v1
  v2 = bor v0, v3
  return v2
}

; VCode:
; block0:
;   orn a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x33, 0x65, 0xb5, 0x40
;   ret

function %bor_not_i32_reversed(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = bnot v0
  v3 = bor v2, v1
  return v3
}

; VCode:
; block0:
;   orn a0,a1,a0
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x33, 0xe5, 0xa5, 0x40
;   ret

