test compile precise-output
set unwind_info=false
target riscv64


function %ceil_f32(f32) -> f32 {
block0(v0: f32):
  v1 = ceil v0
  return v1
}

; VCode:
; block0:
;   lui a0,307200
;   fmv.w.x fa1,a0
;   fabs.s fa2,fa0
;   flt.s a0,fa2,fa1
;   fcvt.w.s a1,fa0,rup
;   fcvt.s.w fa2,a1,rup
;   fsgnj.s fa4,fa2,fa0
;   fmv.w.x fa1,zero
;   fadd.s fa0,fa0,fa1,rne
;   select fa0,fa0,fa4##condition=(a0 eq zero)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   lui a0, 0x4b000
;   fmv.w.x fa1, a0
;   fabs.s fa2, fa0
;   flt.s a0, fa2, fa1
;   fcvt.w.s a1, fa0, rup ; trap: bad_toint
;   fcvt.s.w fa2, a1, rup
;   fsgnj.s fa4, fa2, fa0
;   fmv.w.x fa1, zero
;   fadd.s fa0, fa0, fa1, rne
;   beqz a0, 8
;   fmv.d fa0, fa4
;   ret

function %ceil_f64(f64) -> f64 {
block0(v0: f64):
  v1 = ceil v0
  return v1
}

; VCode:
; block0:
;   lui a0,1075
;   slli a0,a0,40
;   fmv.d.x fa1,a0
;   fabs.d fa2,fa0
;   flt.d a0,fa2,fa1
;   fcvt.l.d a2,fa0,rup
;   fcvt.d.l fa4,a2,rup
;   fsgnj.d fa1,fa4,fa0
;   fmv.d.x fa2,zero
;   fadd.d fa0,fa0,fa2,rne
;   select fa0,fa0,fa1##condition=(a0 eq zero)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   lui a0, 0x433
;   slli a0, a0, 0x28
;   fmv.d.x fa1, a0
;   fabs.d fa2, fa0
;   flt.d a0, fa2, fa1
;   fcvt.l.d a2, fa0, rup ; trap: bad_toint
;   fcvt.d.l fa4, a2, rup
;   fsgnj.d fa1, fa4, fa0
;   fmv.d.x fa2, zero
;   fadd.d fa0, fa0, fa2, rne
;   beqz a0, 8
;   fmv.d fa0, fa1
;   ret

