test compile precise-output

target riscv64

function %no_cold_annotation(i32) -> i32 {
block0(v0: i32):
    brif v0, block1(v0), block2

block1(v1: i32):
    return v1

block2:
    v2 = iconst.i32 97
    jump block1(v2)
}

; VCode:
; block0:
;   sext.w a1,a0
;   bne a1,zero,taken(label1),not_taken(label2)
; block1:
;   j label3
; block2:
;   li a0,97
;   j label3
; block3:
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   sext.w a1, a0
;   bnez a1, 8
; block1: ; offset 0x8
;   addi a0, zero, 0x61
; block2: ; offset 0xc
;   ret

function %cold_annotation(i32) -> i32 {
block0(v0: i32):
    brif v0, block1(v0), block2

block1(v1: i32):
    return v1

block2 cold:
    v2 = iconst.i32 97
    jump block1(v2)
}

; VCode:
; block0:
;   sext.w a1,a0
;   bne a1,zero,taken(label1),not_taken(label2)
; block1:
;   j label3
; block3:
;   ret
; block2:
;   li a0,97
;   j label3
;
; Disassembled:
; block0: ; offset 0x0
;   sext.w a1, a0
;   beqz a1, 8
; block1: ; offset 0x8
;   ret
; block2: ; offset 0xc
;   addi a0, zero, 0x61
;   j -8

