test compile precise-output
target riscv64 has_zfh

function %bitcast_i16_f16(i16) -> f16 fast {
block0(v0: i16):
    v1 = bitcast.f16 v0
    return v1
}

; VCode:
; block0:
;   fmv.h.x fa0,a0
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x53, 0x05, 0x05, 0xf4
;   ret

function %bitcast_f16_i16(f16) -> i16 fast {
block0(v0: f16):
    v1 = bitcast.i16 v0
    return v1
}

; VCode:
; block0:
;   fmv.x.h a0,fa0
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x53, 0x05, 0x05, 0xe4
;   ret

