test compile precise-output
set unwind_info=false
target riscv64

function %fmax_f32(f32, f32) -> f32 {
block0(v0: f32, v1: f32):
    v2 = fmax v0, v1
    return v2
}

; VCode:
; block0:
;   feq.s a0,fa0,fa0
;   feq.s a1,fa1,fa1
;   and a0,a0,a1
;   fadd.s fa2,fa0,fa1,rne
;   fmax.s fa1,fa0,fa1
;   select fa0,fa1,fa2##condition=(a0 ne zero)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   feq.s a0, fa0, fa0
;   feq.s a1, fa1, fa1
;   and a0, a0, a1
;   fadd.s fa2, fa0, fa1, rne
;   fmax.s fa1, fa0, fa1
;   fmv.d fa0, fa1
;   bnez a0, 8
;   fmv.d fa0, fa2
;   ret

function %fmax_f64(f64, f64) -> f64 {
block0(v0: f64, v1: f64):
    v2 = fmax v0, v1
    return v2
}

; VCode:
; block0:
;   feq.d a0,fa0,fa0
;   feq.d a1,fa1,fa1
;   and a0,a0,a1
;   fadd.d fa2,fa0,fa1,rne
;   fmax.d fa1,fa0,fa1
;   select fa0,fa1,fa2##condition=(a0 ne zero)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   feq.d a0, fa0, fa0
;   feq.d a1, fa1, fa1
;   and a0, a0, a1
;   fadd.d fa2, fa0, fa1, rne
;   fmax.d fa1, fa0, fa1
;   fmv.d fa0, fa1
;   bnez a0, 8
;   fmv.d fa0, fa2
;   ret

