test compile precise-output
target riscv64

function u1:6() system_v {
    sig0 = () tail
    fn0 = u1:7 sig0

block0:
    v5 = func_addr.i64 fn0
    call_indirect sig0, v5()
    call_indirect sig0, v5()
    return
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-16
;   sd s1,8(sp)
; block0:
;   load_sym s1,userextname0+0
;   callind s1
;   callind s1
;   ld s1,8(sp)
;   addi sp,sp,16
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
;   addi sp, sp, -0x10
;   sd s1, 8(sp)
; block1: ; offset 0x18
;   auipc s1, 0
;   ld s1, 0xc(s1)
;   j 0xc
;   .byte 0x00, 0x00, 0x00, 0x00 ; reloc_external Abs8 u1:7 0
;   .byte 0x00, 0x00, 0x00, 0x00
;   jalr s1
;   jalr s1
;   ld s1, 8(sp)
;   addi sp, sp, 0x10
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

