test compile precise-output
set opt_level=speed
target riscv64

function %mul_uextend_i64(i64, i64) -> i128 {
block0(v0: i64, v1: i64):
    v2 = uextend.i128 v0
    v3 = uextend.i128 v1
    v4 = imul v2, v3
    return v4
}

; VCode:
; block0:
;   mul a2,a0,a1
;   mulhu a1,a0,a1
;   mv a0,a2
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mul a2, a0, a1
;   mulhu a1, a0, a1
;   mv a0, a2
;   ret

function %mul_sextend_i64(i64, i64) -> i128 {
block0(v0: i64, v1: i64):
    v2 = sextend.i128 v0
    v3 = sextend.i128 v1
    v4 = imul v2, v3
    return v4
}

; VCode:
; block0:
;   mul a2,a0,a1
;   mulh a1,a0,a1
;   mv a0,a2
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mul a2, a0, a1
;   mulh a1, a0, a1
;   mv a0, a2
;   ret

function %smul_high_i64_pattern(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = sextend.i128 v0
    v3 = sextend.i128 v1
    v4 = imul v2, v3
    v5 = sshr_imm v4, 64
    v6 = ireduce.i64 v5
    return v6
}

; VCode:
; block0:
;   mulh a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mulh a0, a0, a1
;   ret

function %smul_high_i64_isplit(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = sextend.i128 v0
    v3 = sextend.i128 v1
    v4 = imul v2, v3
    v5, v6 = isplit v4
    return v6
}

; VCode:
; block0:
;   mulh a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mulh a0, a0, a1
;   ret

function %umul_high_i64_pattern(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = uextend.i128 v0
    v3 = uextend.i128 v1
    v4 = imul v2, v3
    v5 = ushr_imm v4, 64
    v6 = ireduce.i64 v5
    return v6
}

; VCode:
; block0:
;   mulhu a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mulhu a0, a0, a1
;   ret

function %umul_high_i64_isplit(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = uextend.i128 v0
    v3 = uextend.i128 v1
    v4 = imul v2, v3
    v5, v6 = isplit v4
    return v6
}

; VCode:
; block0:
;   mulhu a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mulhu a0, a0, a1
;   ret

