test compile precise-output
target riscv64 has_zbb=true

function %iabs_i8(i8) -> i8 {
block0(v0: i8):
    v1 = iabs v0
    return v1
}

; VCode:
; block0:
;   sext.b t2,a0
;   sub a1,zero,t2
;   max a0,t2,a1
;   ret
; 
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x93, 0x13, 0x45, 0x60
;   neg a1, t2
;   .byte 0x33, 0xe5, 0xb3, 0x0a
;   ret

function %iabs_i16(i16) -> i16 {
block0(v0: i16):
    v1 = iabs v0
    return v1
}

; VCode:
; block0:
;   sext.h t2,a0
;   sub a1,zero,t2
;   max a0,t2,a1
;   ret
; 
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x93, 0x13, 0x55, 0x60
;   neg a1, t2
;   .byte 0x33, 0xe5, 0xb3, 0x0a
;   ret

function %iabs_i32(i32) -> i32 {
block0(v0: i32):
    v1 = iabs v0
    return v1
}

; VCode:
; block0:
;   sext.w t2,a0
;   sub a1,zero,t2
;   max a0,t2,a1
;   ret
; 
; Disassembled:
; block0: ; offset 0x0
;   sext.w t2, a0
;   neg a1, t2
;   .byte 0x33, 0xe5, 0xb3, 0x0a
;   ret

function %iabs_i64(i64) -> i64 {
block0(v0: i64):
    v1 = iabs v0
    return v1
}

; VCode:
; block0:
;   sub t2,zero,a0
;   max a0,a0,t2
;   ret
; 
; Disassembled:
; block0: ; offset 0x0
;   neg t2, a0
;   .byte 0x33, 0x65, 0x75, 0x0a
;   ret

