test compile precise-output
target riscv64

function %f0(i32) -> i32 {
block0(v0: i32):
    v1 = iconst.i32 127
    v2 = iadd_overflow_trap v0, v1, user0
    return v2
}

; block0:
;   mv a6,a0
;   li a0,127
;   uext.w a2,a6
;   uext.w a4,a0
;   add a0,a2,a4
;   srli t3,a0,32
;   trap_if t3,user0
;   ret

function %f1(i32) -> i32 {
block0(v0: i32):
    v1 = iconst.i32 127
    v2 = iadd_overflow_trap v1, v0, user0
    return v2
}

; block0:
;   li a1,127
;   uext.w a2,a1
;   uext.w a4,a0
;   add a0,a2,a4
;   srli t3,a0,32
;   trap_if t3,user0
;   ret

function %f2(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = iadd_overflow_trap v0, v1, user0
    return v2
}

; block0:
;   mv a6,a1
;   uext.w a1,a0
;   uext.w a3,a6
;   add a0,a1,a3
;   srli a7,a0,32
;   trap_if a7,user0
;   ret

function %f3(i64) -> i64 {
block0(v0: i64):
    v1 = iconst.i64 127
    v2 = iadd_overflow_trap v0, v1, user0
    return v2
}

; block0:
;   li a1,127
;   add a2,a0,a1
;   mv a5,a2
;   ult a4,a5,a0##ty=i64
;   mv a2,a5
;   trap_if a4,user0
;   mv a0,a2
;   ret

function %f3(i64) -> i64 {
block0(v0: i64):
    v1 = iconst.i64 127
    v2 = iadd_overflow_trap v1, v0, user0
    return v2
}

; block0:
;   li a1,127
;   add a0,a1,a0
;   ult a4,a0,a1##ty=i64
;   trap_if a4,user0
;   ret

function %f4(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = iadd_overflow_trap v0, v1, user0
    return v2
}

; block0:
;   add a1,a0,a1
;   mv a4,a1
;   ult a3,a4,a0##ty=i64
;   mv a1,a4
;   trap_if a3,user0
;   mv a0,a1
;   ret

