test compile precise-output
set enable_probestack=true
set probestack_strategy=inline
; This is the default and is equivalent to a page size of 4096
set probestack_size_log2=12
target riscv64


; If the stack size is just one page, we can avoid the stack probe entirely
function %single_page() -> i64 system_v {
ss0 = explicit_slot 2048

block0:
  v1 = stack_addr.i64 ss0
  return v1
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-2048
; block0:
;   load_addr a0,0(nominal_sp)
;   lui t6,1
;   addi t6,t6,-2048
;   add sp,sp,t6
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
;   addi sp, sp, -0x800
; block1: ; offset 0x14
;   mv a0, sp
;   lui t6, 1
;   addi t6, t6, -0x800
;   add sp, sp, t6
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

function %unrolled() -> i64 system_v {
ss0 = explicit_slot 12288

block0:
  v1 = stack_addr.i64 ss0
  return v1
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   lui t3,-1
;   add sp,sp,t3
;   sw zero,0(sp)
;   add sp,sp,t3
;   sw zero,0(sp)
;   add sp,sp,t3
;   sw zero,0(sp)
;   lui t6,3
;   add sp,sp,t6
;   lui t6,-3
;   add sp,sp,t6
; block0:
;   load_addr a0,0(nominal_sp)
;   lui t6,3
;   add sp,sp,t6
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
;   lui t3, 0xfffff
;   add sp, sp, t3
;   sw zero, 0(sp)
;   add sp, sp, t3
;   sw zero, 0(sp)
;   add sp, sp, t3
;   sw zero, 0(sp)
;   lui t6, 3
;   add sp, sp, t6
;   lui t6, 0xffffd
;   add sp, sp, t6
; block1: ; offset 0x3c
;   mv a0, sp
;   lui t6, 3
;   add sp, sp, t6
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

function %large() -> i64 system_v {
ss0 = explicit_slot 100000

block0:
  v1 = stack_addr.i64 ss0
  return v1
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   inline_stack_probe##guard_size=4096 probe_count=25 tmp=t3
;   lui t6,-24
;   addi t6,t6,-1696
;   add sp,sp,t6
; block0:
;   load_addr a0,0(nominal_sp)
;   lui t6,24
;   addi t6,t6,1696
;   add sp,sp,t6
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
;   lui t6, 0x19
;   lui t3, 1
;   bgeu t3, t6, 0x14
;   sub t5, sp, t6
;   sb zero, 0(t5) ; trap: heap_oob
;   sub t6, t6, t3
;   j -0x10
;   lui t6, 0xfffe8
;   addi t6, t6, -0x6a0
;   add sp, sp, t6
; block1: ; offset 0x38
;   mv a0, sp
;   lui t6, 0x18
;   addi t6, t6, 0x6a0
;   add sp, sp, t6
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

