test compile precise-output
set unwind_info=false
target riscv64


function %ishl_i8_i8(i8, i8) -> i8 {
block0(v0: i8, v1: i8):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   andi a1,a1,7
;   sllw a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a1, a1, 7
;   sllw a0, a0, a1
;   ret

function %ishl_i8_i16(i8, i16) -> i8 {
block0(v0: i8, v1: i16):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   andi a1,a1,7
;   sllw a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a1, a1, 7
;   sllw a0, a0, a1
;   ret

function %ishl_i8_i32(i8, i32) -> i8 {
block0(v0: i8, v1: i32):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   andi a1,a1,7
;   sllw a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a1, a1, 7
;   sllw a0, a0, a1
;   ret

function %ishl_i8_i64(i8, i64) -> i8 {
block0(v0: i8, v1: i64):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   andi a1,a1,7
;   sllw a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a1, a1, 7
;   sllw a0, a0, a1
;   ret

function %ishl_i8_i128(i8, i128) -> i8 {
block0(v0: i8, v1: i128):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   andi a1,a1,7
;   sllw a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a1, a1, 7
;   sllw a0, a0, a1
;   ret

function %ishl_i16_i8(i16, i8) -> i16 {
block0(v0: i16, v1: i8):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   andi a1,a1,15
;   sllw a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a1, a1, 0xf
;   sllw a0, a0, a1
;   ret

function %ishl_i16_i16(i16, i16) -> i16 {
block0(v0: i16, v1: i16):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   andi a1,a1,15
;   sllw a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a1, a1, 0xf
;   sllw a0, a0, a1
;   ret

function %ishl_i16_i32(i16, i32) -> i16 {
block0(v0: i16, v1: i32):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   andi a1,a1,15
;   sllw a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a1, a1, 0xf
;   sllw a0, a0, a1
;   ret

function %ishl_i16_i64(i16, i64) -> i16 {
block0(v0: i16, v1: i64):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   andi a1,a1,15
;   sllw a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a1, a1, 0xf
;   sllw a0, a0, a1
;   ret

function %ishl_i16_i128(i16, i128) -> i16 {
block0(v0: i16, v1: i128):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   andi a1,a1,15
;   sllw a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a1, a1, 0xf
;   sllw a0, a0, a1
;   ret

function %ishl_i32_i8(i32, i8) -> i32 {
block0(v0: i32, v1: i8):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   sllw a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   sllw a0, a0, a1
;   ret

function %ishl_i32_i16(i32, i16) -> i32 {
block0(v0: i32, v1: i16):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   sllw a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   sllw a0, a0, a1
;   ret

function %ishl_i32_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   sllw a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   sllw a0, a0, a1
;   ret

function %ishl_i32_i64(i32, i64) -> i32 {
block0(v0: i32, v1: i64):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   sllw a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   sllw a0, a0, a1
;   ret

function %ishl_i32_i128(i32, i128) -> i32 {
block0(v0: i32, v1: i128):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   sllw a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   sllw a0, a0, a1
;   ret

function %ishl_i64_i8(i64, i8) -> i64 {
block0(v0: i64, v1: i8):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   sll a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   sll a0, a0, a1
;   ret

function %ishl_i64_i16(i64, i16) -> i64 {
block0(v0: i64, v1: i16):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   sll a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   sll a0, a0, a1
;   ret

function %ishl_i64_i32(i64, i32) -> i64 {
block0(v0: i64, v1: i32):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   sll a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   sll a0, a0, a1
;   ret

function %ishl_i64_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   sll a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   sll a0, a0, a1
;   ret

function %ishl_i64_i128(i64, i128) -> i64 {
block0(v0: i64, v1: i128):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   sll a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   sll a0, a0, a1
;   ret

function %ishl_i128_i8(i128, i8) -> i128 {
block0(v0: i128, v1: i8):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   andi a3,a2,63
;   li a4,64
;   sub a5,a4,a3
;   sll a7,a0,a3
;   srl t4,a0,a5
;   select_reg t1,zero,t4##condition=(a3 eq zero)
;   sll a0,a1,a3
;   or a3,t1,a0
;   li a4,64
;   andi a6,a2,127
;   select_reg a0,zero,a7##condition=(a6 uge a4)
;   select_reg a1,a7,a3##condition=(a6 uge a4)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a3, a2, 0x3f
;   addi a4, zero, 0x40
;   sub a5, a4, a3
;   sll a7, a0, a3
;   srl t4, a0, a5
;   beqz a3, 0xc
;   mv t1, t4
;   j 8
;   mv t1, zero
;   sll a0, a1, a3
;   or a3, t1, a0
;   addi a4, zero, 0x40
;   andi a6, a2, 0x7f
;   bgeu a6, a4, 0xc
;   mv a0, a7
;   j 8
;   mv a0, zero
;   bgeu a6, a4, 0xc
;   mv a1, a3
;   j 8
;   mv a1, a7
;   ret

function %ishl_i128_i16(i128, i16) -> i128 {
block0(v0: i128, v1: i16):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   andi a3,a2,63
;   li a4,64
;   sub a5,a4,a3
;   sll a7,a0,a3
;   srl t4,a0,a5
;   select_reg t1,zero,t4##condition=(a3 eq zero)
;   sll a0,a1,a3
;   or a3,t1,a0
;   li a4,64
;   andi a6,a2,127
;   select_reg a0,zero,a7##condition=(a6 uge a4)
;   select_reg a1,a7,a3##condition=(a6 uge a4)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a3, a2, 0x3f
;   addi a4, zero, 0x40
;   sub a5, a4, a3
;   sll a7, a0, a3
;   srl t4, a0, a5
;   beqz a3, 0xc
;   mv t1, t4
;   j 8
;   mv t1, zero
;   sll a0, a1, a3
;   or a3, t1, a0
;   addi a4, zero, 0x40
;   andi a6, a2, 0x7f
;   bgeu a6, a4, 0xc
;   mv a0, a7
;   j 8
;   mv a0, zero
;   bgeu a6, a4, 0xc
;   mv a1, a3
;   j 8
;   mv a1, a7
;   ret

function %ishl_i128_i32(i128, i32) -> i128 {
block0(v0: i128, v1: i32):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   andi a3,a2,63
;   li a4,64
;   sub a5,a4,a3
;   sll a7,a0,a3
;   srl t4,a0,a5
;   select_reg t1,zero,t4##condition=(a3 eq zero)
;   sll a0,a1,a3
;   or a3,t1,a0
;   li a4,64
;   andi a6,a2,127
;   select_reg a0,zero,a7##condition=(a6 uge a4)
;   select_reg a1,a7,a3##condition=(a6 uge a4)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a3, a2, 0x3f
;   addi a4, zero, 0x40
;   sub a5, a4, a3
;   sll a7, a0, a3
;   srl t4, a0, a5
;   beqz a3, 0xc
;   mv t1, t4
;   j 8
;   mv t1, zero
;   sll a0, a1, a3
;   or a3, t1, a0
;   addi a4, zero, 0x40
;   andi a6, a2, 0x7f
;   bgeu a6, a4, 0xc
;   mv a0, a7
;   j 8
;   mv a0, zero
;   bgeu a6, a4, 0xc
;   mv a1, a3
;   j 8
;   mv a1, a7
;   ret

function %ishl_i128_i64(i128, i64) -> i128 {
block0(v0: i128, v1: i64):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   andi a3,a2,63
;   li a4,64
;   sub a5,a4,a3
;   sll a7,a0,a3
;   srl t4,a0,a5
;   select_reg t1,zero,t4##condition=(a3 eq zero)
;   sll a0,a1,a3
;   or a3,t1,a0
;   li a4,64
;   andi a6,a2,127
;   select_reg a0,zero,a7##condition=(a6 uge a4)
;   select_reg a1,a7,a3##condition=(a6 uge a4)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a3, a2, 0x3f
;   addi a4, zero, 0x40
;   sub a5, a4, a3
;   sll a7, a0, a3
;   srl t4, a0, a5
;   beqz a3, 0xc
;   mv t1, t4
;   j 8
;   mv t1, zero
;   sll a0, a1, a3
;   or a3, t1, a0
;   addi a4, zero, 0x40
;   andi a6, a2, 0x7f
;   bgeu a6, a4, 0xc
;   mv a0, a7
;   j 8
;   mv a0, zero
;   bgeu a6, a4, 0xc
;   mv a1, a3
;   j 8
;   mv a1, a7
;   ret

function %ishl_i128_i128(i128, i128) -> i128 {
block0(v0: i128, v1: i128):
    v2 = ishl v0, v1
    return v2
}

; VCode:
; block0:
;   andi a3,a2,63
;   li a4,64
;   sub a6,a4,a3
;   sll t3,a0,a3
;   srl t0,a0,a6
;   select_reg t2,zero,t0##condition=(a3 eq zero)
;   sll a1,a1,a3
;   or a3,t2,a1
;   li a5,64
;   andi a7,a2,127
;   select_reg a0,zero,t3##condition=(a7 uge a5)
;   select_reg a1,t3,a3##condition=(a7 uge a5)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a3, a2, 0x3f
;   addi a4, zero, 0x40
;   sub a6, a4, a3
;   sll t3, a0, a3
;   srl t0, a0, a6
;   beqz a3, 0xc
;   mv t2, t0
;   j 8
;   mv t2, zero
;   sll a1, a1, a3
;   or a3, t2, a1
;   addi a5, zero, 0x40
;   andi a7, a2, 0x7f
;   bgeu a7, a5, 0xc
;   mv a0, t3
;   j 8
;   mv a0, zero
;   bgeu a7, a5, 0xc
;   mv a1, a3
;   j 8
;   mv a1, t3
;   ret

