test compile precise-output
set unwind_info=false
target riscv64

function %atomic_rmw_add_i8(i64, i8) {
block0(v0: i64, v1: i8):
    v2 = atomic_rmw.i8 add v0, v1
    return
}

; VCode:
; block0:
;   andi a2,a0,3
;   slli a2,a2,3
;   andi a0,a0,-4
;   atomic_rmw.i8 add a4,a1,(a0)##t0=a3 offset=a2
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a2, a0, 3
;   slli a2, a2, 3
;   andi a0, a0, -4
;   lr.w.aqrl a4, (a0) ; trap: heap_oob
;   mv t5, a4
;   srl a4, a4, a2
;   andi a4, a4, 0xff
;   add a3, a4, a1
;   addi t6, zero, 0xff
;   sll t6, t6, a2
;   not t6, t6
;   and t5, t5, t6
;   andi t6, a3, 0xff
;   sll t6, t6, a2
;   or t5, t5, t6
;   sc.w.aqrl a3, t5, (a0) ; trap: heap_oob
;   bnez a3, -0x34
;   ret

function %atomic_rmw_sub_i16(i64, i16) {
block0(v0: i64, v1: i16):
    v2 = atomic_rmw.i16 sub v0, v1
    return
}

; VCode:
; block0:
;   andi a2,a0,3
;   slli a2,a2,3
;   andi a0,a0,-4
;   atomic_rmw.i16 sub a4,a1,(a0)##t0=a3 offset=a2
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a2, a0, 3
;   slli a2, a2, 3
;   andi a0, a0, -4
;   lr.w.aqrl a4, (a0) ; trap: heap_oob
;   mv t5, a4
;   srl a4, a4, a2
;   slli a4, a4, 0x30
;   srli a4, a4, 0x30
;   sub a3, a4, a1
;   addi t6, zero, -1
;   slli t6, t6, 0x30
;   srli t6, t6, 0x30
;   sll t6, t6, a2
;   not t6, t6
;   and t5, t5, t6
;   slli t6, a3, 0x30
;   srli t6, t6, 0x30
;   sll t6, t6, a2
;   or t5, t5, t6
;   sc.w.aqrl a3, t5, (a0) ; trap: heap_oob
;   bnez a3, -0x44
;   ret

function %atomic_rmw_xchg_i8(i64, i8) {
block0(v0: i64, v1: i8):
    v2 = atomic_rmw.i8 xchg v0, v1
    return
}

; VCode:
; block0:
;   andi a2,a0,3
;   slli a2,a2,3
;   andi a0,a0,-4
;   atomic_rmw.i8 xchg a4,a1,(a0)##t0=a3 offset=a2
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a2, a0, 3
;   slli a2, a2, 3
;   andi a0, a0, -4
;   lr.w.aqrl a4, (a0) ; trap: heap_oob
;   mv t5, a4
;   srl a4, a4, a2
;   andi a4, a4, 0xff
;   addi t6, zero, 0xff
;   sll t6, t6, a2
;   not t6, t6
;   and t5, t5, t6
;   andi t6, a1, 0xff
;   sll t6, t6, a2
;   or t5, t5, t6
;   sc.w.aqrl a3, t5, (a0) ; trap: heap_oob
;   bnez a3, -0x30
;   ret

function %atomic_rmw_nand_i8(i64, i8) {
block0(v0: i64, v1: i8):
    v2 = atomic_rmw.i8 nand v0, v1
    return
}

; VCode:
; block0:
;   andi a2,a0,3
;   slli a2,a2,3
;   andi a0,a0,-4
;   atomic_rmw.i8 nand a4,a1,(a0)##t0=a3 offset=a2
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a2, a0, 3
;   slli a2, a2, 3
;   andi a0, a0, -4
;   lr.w.aqrl a4, (a0) ; trap: heap_oob
;   mv t5, a4
;   srl a4, a4, a2
;   andi a4, a4, 0xff
;   and a3, a1, a4
;   not a3, a3
;   addi t6, zero, 0xff
;   sll t6, t6, a2
;   not t6, t6
;   and t5, t5, t6
;   andi t6, a3, 0xff
;   sll t6, t6, a2
;   or t5, t5, t6
;   sc.w.aqrl a3, t5, (a0) ; trap: heap_oob
;   bnez a3, -0x38
;   ret

function %atomic_rmw_umin_i16(i64, i16) {
block0(v0: i64, v1: i16):
    v2 = atomic_rmw.i16 umin v0, v1
    return
}

; VCode:
; block0:
;   slli a1,a1,48
;   srli a1,a1,48
;   andi a2,a0,3
;   slli a2,a2,3
;   andi a3,a0,-4
;   atomic_rmw.i16 umin a0,a1,(a3)##t0=a4 offset=a2
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a1, a1, 0x30
;   srli a1, a1, 0x30
;   andi a2, a0, 3
;   slli a2, a2, 3
;   andi a3, a0, -4
;   lr.w.aqrl a0, (a3) ; trap: heap_oob
;   mv t5, a0
;   srl a0, a0, a2
;   slli a0, a0, 0x30
;   srli a0, a0, 0x30
;   bltu a0, a1, 0xc
;   mv a4, a1
;   j 8
;   mv a4, a0
;   addi t6, zero, -1
;   slli t6, t6, 0x30
;   srli t6, t6, 0x30
;   sll t6, t6, a2
;   not t6, t6
;   and t5, t5, t6
;   slli t6, a4, 0x30
;   srli t6, t6, 0x30
;   sll t6, t6, a2
;   or t5, t5, t6
;   sc.w.aqrl a4, t5, (a3) ; trap: heap_oob
;   bnez a4, -0x50
;   ret

