test compile precise-output
set enable_multi_ret_implicit_sret
set enable_nan_canonicalization=true
target riscv64

function %f1(f64, f64) -> f64 {
block0(v0: f64, v1: f64):
	v2 = fadd v0, v1
	return v2
}

; VCode:
; block0:
;   fadd.d fa0,fa0,fa1,rne
;   lui a0,4095
;   slli a0,a0,39
;   fmv.d.x fa2,a0
;   feq.d a0,fa0,fa0
;   feq.d a1,fa0,fa0
;   and a1,a0,a1
;   select fa0,fa2,fa0##condition=(a1 eq zero)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   fadd.d fa0, fa0, fa1, rne
;   lui a0, 0xfff
;   slli a0, a0, 0x27
;   fmv.d.x fa2, a0
;   feq.d a0, fa0, fa0
;   feq.d a1, fa0, fa0
;   and a1, a0, a1
;   bnez a1, 8
;   fmv.d fa0, fa2
;   ret

function %f1(f32, f32) -> f32 {
block0(v0: f32, v1: f32):
	v2 = fadd v0, v1
	return v2
}

; VCode:
; block0:
;   fadd.s fa0,fa0,fa1,rne
;   lui a0,523264
;   fmv.w.x fa1,a0
;   feq.s a0,fa0,fa0
;   feq.s a1,fa0,fa0
;   and a0,a0,a1
;   select fa0,fa1,fa0##condition=(a0 eq zero)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   fadd.s fa0, fa0, fa1, rne
;   lui a0, 0x7fc00
;   fmv.w.x fa1, a0
;   feq.s a0, fa0, fa0
;   feq.s a1, fa0, fa0
;   and a0, a0, a1
;   bnez a0, 8
;   fmv.d fa0, fa1
;   ret

