test compile precise-output
set unwind_info=false
target riscv64

function %ireduce_128_64(i128) -> i64 {
block0(v0: i128):
  v1 = ireduce.i64 v0
  return v1
}

; VCode:
; block0:
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   ret

function %ireduce_128_32(i128) -> i32 {
block0(v0: i128):
  v1 = ireduce.i32 v0
  return v1
}

; VCode:
; block0:
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   ret

function %ireduce_128_16(i128) -> i16 {
block0(v0: i128):
  v1 = ireduce.i16 v0
  return v1
}

; VCode:
; block0:
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   ret

function %ireduce_128_8(i128) -> i8 {
block0(v0: i128):
  v1 = ireduce.i8 v0
  return v1
}

; VCode:
; block0:
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   ret

