test compile precise-output
set unwind_info=false
target riscv64

function %f0(r64) -> r64 {
block0(v0: r64):
  return v0
}

; VCode:
; block0:
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   ret

function %f1(r64) -> i8 {
block0(v0: r64):
  v1 = is_null v0
  return v1
}

; VCode:
; block0:
;   seqz a0,a0
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   seqz a0, a0
;   ret

function %f2(r64) -> i8 {
block0(v0: r64):
  v1 = is_invalid v0
  return v1
}

; VCode:
; block0:
;   addi a2,a0,1
;   seqz a0,a2
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi a2, a0, 1
;   seqz a0, a2
;   ret

function %f3() -> r64 {
block0:
  v0 = null.r64
  return v0
}

; VCode:
; block0:
;   li a0,0
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mv a0, zero
;   ret

function %f4(r64, r64) -> r64, r64, r64 {
    fn0 = %f(r64) -> i8
    ss0 = explicit_slot 8

block0(v0: r64, v1: r64):
    v2 = call fn0(v0)
    stack_store.r64 v0, ss0
    brif v2, block2(v0, v1), block1(v1, v0)

block1(v3: r64, v4: r64):
    jump block3(v3, v4)

block2(v5: r64, v6: r64):
    jump block3(v5, v6)

block3(v7: r64, v8: r64):
    v9 = stack_load.r64 ss0
    return v7, v8, v9
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-48
;   sd s5,40(sp)
;   sd s9,32(sp)
; block0:
;   mv a3,a0
;   mv s5,a2
;   sd a1,16(slot)
;   mv a0,a3
;   mv s9,a3
;   load_sym a5,%f+0
;   sd s9,8(slot)
;   callind a5
;   mv a3,s9
;   sd a3,0(slot)
;   andi a5,a0,255
;   bne a5,zero,taken(label2),not_taken(label1)
; block1:
;   ld a0,16(slot)
;   mv a1,s9
;   j label3
; block2:
;   mv a0,s9
;   ld a1,16(slot)
;   j label3
; block3:
;   ld a2,0(slot)
;   mv a3,s5
;   sd a2,0(a3)
;   ld s5,40(sp)
;   ld s9,32(sp)
;   addi sp,sp,48
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
;   addi sp, sp, -0x30
;   sd s5, 0x28(sp)
;   sd s9, 0x20(sp)
; block1: ; offset 0x1c
;   mv a3, a0
;   mv s5, a2
;   sd a1, 0x10(sp)
;   mv a0, a3
;   mv s9, a3
;   auipc a5, 0
;   ld a5, 0xc(a5)
;   j 0xc
;   .byte 0x00, 0x00, 0x00, 0x00 ; reloc_external Abs8 %f 0
;   .byte 0x00, 0x00, 0x00, 0x00
;   sd s9, 8(sp)
;   jalr a5
;   mv a3, s9
;   sd a3, 0(sp)
;   andi a5, a0, 0xff
;   bnez a5, 0x10
; block2: ; offset 0x5c
;   ld a0, 0x10(sp)
;   mv a1, s9
;   j 0xc
; block3: ; offset 0x68
;   mv a0, s9
;   ld a1, 0x10(sp)
; block4: ; offset 0x70
;   ld a2, 0(sp)
;   mv a3, s5
;   sd a2, 0(a3)
;   ld s5, 0x28(sp)
;   ld s9, 0x20(sp)
;   addi sp, sp, 0x30
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

