test compile precise-output

target riscv64

;;;; Test passing `i64`s ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

function %callee_i64(i64) -> i64 tail {
block0(v0: i64):
    v1 = iadd_imm.i64 v0, 10
    return v1
}

; VCode:
; block0:
;   addi a0,a0,10
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi a0, a0, 0xa
;   ret

function %call_i64(i64) -> i64 tail {
    sig0 = (i64) -> i64 tail
    fn0 = %callee_i64(i64) -> i64 tail

block0(v0: i64):
    v1 = func_addr.i64 fn0
    return_call_indirect sig0, v1(v0)
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   load_sym t0,%callee_i64+0
;   return_call_ind t0 new_stack_arg_size:0 a0=a0
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
; block1: ; offset 0x10
;   auipc t0, 0
;   ld t0, 0xc(t0)
;   j 0xc
;   .byte 0x00, 0x00, 0x00, 0x00 ; reloc_external Abs8 %callee_i64 0
;   .byte 0x00, 0x00, 0x00, 0x00
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   jr t0

;;;; Test colocated tail calls ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

function %colocated_i64(i64) -> i64 tail {
    sig0 = (i64) -> i64 tail
    fn0 = colocated %callee_i64(i64) -> i64 tail

block0(v0: i64):
    v1 = func_addr.i64 fn0
    return_call_indirect sig0, v1(v0)
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   load_sym t0,%callee_i64+0
;   return_call_ind t0 new_stack_arg_size:0 a0=a0
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
; block1: ; offset 0x10
;   auipc t0, 0
;   ld t0, 0xc(t0)
;   j 0xc
;   .byte 0x00, 0x00, 0x00, 0x00 ; reloc_external Abs8 %callee_i64 0
;   .byte 0x00, 0x00, 0x00, 0x00
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   jr t0

;;;; Test passing `f64`s ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

function %callee_f64(f64) -> f64 tail {
block0(v0: f64):
    v1 = f64const 0x10.0
    v2 = fadd.f64 v0, v1
    return v2
}

; VCode:
; block0:
;   lui a3,1027
;   slli a5,a3,40
;   fmv.d.x fa1,a5
;   fadd.d fa0,fa0,fa1,rne
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   lui a3, 0x403
;   slli a5, a3, 0x28
;   fmv.d.x fa1, a5
;   fadd.d fa0, fa0, fa1, rne
;   ret

function %call_f64(f64) -> f64 tail {
    sig0 = (f64) -> f64 tail
    fn0 = %callee_f64(f64) -> f64 tail

block0(v0: f64):
    v1 = func_addr.i64 fn0
    return_call_indirect sig0, v1(v0)
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   load_sym t0,%callee_f64+0
;   return_call_ind t0 new_stack_arg_size:0 fa0=fa0
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
; block1: ; offset 0x10
;   auipc t0, 0
;   ld t0, 0xc(t0)
;   j 0xc
;   .byte 0x00, 0x00, 0x00, 0x00 ; reloc_external Abs8 %callee_f64 0
;   .byte 0x00, 0x00, 0x00, 0x00
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   jr t0

;;;; Test passing `i8`s ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

function %callee_i8(i8) -> i8 tail {
block0(v0: i8):
    v1 = iconst.i8 0
    v2 = icmp eq v0, v1
    return v2
}

; VCode:
; block0:
;   andi a2,a0,255
;   seqz a0,a2
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a2, a0, 0xff
;   seqz a0, a2
;   ret

function %call_i8(i8) -> i8 tail {
    sig0 = (i8) -> i8 tail
    fn0 = %callee_i8(i8) -> i8 tail

block0(v0: i8):
    v1 = func_addr.i64 fn0
    return_call_indirect sig0, v1(v0)
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   load_sym t0,%callee_i8+0
;   return_call_ind t0 new_stack_arg_size:0 a0=a0
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
; block1: ; offset 0x10
;   auipc t0, 0
;   ld t0, 0xc(t0)
;   j 0xc
;   .byte 0x00, 0x00, 0x00, 0x00 ; reloc_external Abs8 %callee_i8 0
;   .byte 0x00, 0x00, 0x00, 0x00
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   jr t0

;;;; Test passing many arguments on stack ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

function %tail_caller_stack_args() -> i64 tail {
    fn0 = %tail_callee_stack_args(i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64) -> i64 tail

block0:
    v0 = iconst.i64 10
    v1 = iconst.i64 15
    v2 = iconst.i64 20
    v3 = iconst.i64 25
    v4 = iconst.i64 30
    v5 = iconst.i64 35
    v6 = iconst.i64 40
    v7 = iconst.i64 45
    v8 = iconst.i64 50
    v9 = iconst.i64 55
    v10 = iconst.i64 60
    v11 = iconst.i64 65
    v12 = iconst.i64 70
    v13 = iconst.i64 75
    v14 = iconst.i64 80
    v15 = iconst.i64 85
    v16 = iconst.i64 90
    v17 = iconst.i64 95
    v18 = iconst.i64 100
    v19 = iconst.i64 105
    v20 = iconst.i64 110
    v21 = iconst.i64 115
    v22 = iconst.i64 120
    v23 = iconst.i64 125
    v24 = iconst.i64 130
    v25 = iconst.i64 135
    v26 = func_addr.i64 fn0
    return_call_indirect sig0, v26(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25)
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-144
;   sd ra,8(sp)
;   ld fp,144(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-128
;   sd s1,120(sp)
;   sd s2,112(sp)
;   sd s3,104(sp)
;   sd s4,96(sp)
;   sd s5,88(sp)
;   sd s6,80(sp)
;   sd s7,72(sp)
;   sd s8,64(sp)
;   sd s9,56(sp)
;   sd s10,48(sp)
;   sd s11,40(sp)
; block0:
;   li a1,10
;   sd a1,16(slot)
;   li a2,15
;   sd a2,8(slot)
;   li a3,20
;   sd a3,0(slot)
;   li a3,25
;   li a4,30
;   li a5,35
;   li a6,40
;   li a7,45
;   li s2,50
;   li s3,55
;   li s4,60
;   li s5,65
;   li s6,70
;   li s7,75
;   li s8,80
;   li s9,85
;   li s10,90
;   li s11,95
;   li t0,100
;   li t1,105
;   li t2,110
;   li t3,115
;   li t4,120
;   li s1,125
;   li a0,130
;   li a1,135
;   load_sym a2,%tail_callee_stack_args+0
;   sd s2,-144(incoming_arg)
;   sd s3,-136(incoming_arg)
;   sd s4,-128(incoming_arg)
;   sd s5,-120(incoming_arg)
;   sd s6,-112(incoming_arg)
;   sd s7,-104(incoming_arg)
;   sd s8,-96(incoming_arg)
;   sd s9,-88(incoming_arg)
;   sd s10,-80(incoming_arg)
;   sd s11,-72(incoming_arg)
;   sd t0,-64(incoming_arg)
;   sd t1,-56(incoming_arg)
;   sd t2,-48(incoming_arg)
;   sd t3,-40(incoming_arg)
;   sd t4,-32(incoming_arg)
;   sd s1,-24(incoming_arg)
;   sd a0,-16(incoming_arg)
;   sd a1,-8(incoming_arg)
;   ld a1,8(slot)
;   ld a0,16(slot)
;   mv t0,a2
;   ld a2,0(slot)
;   return_call_ind t0 new_stack_arg_size:144 a0=a0 a1=a1 a2=a2 a3=a3 a4=a4 a5=a5 a6=a6 a7=a7
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
;   addi sp, sp, -0x90
;   sd ra, 8(sp)
;   ld s0, 0x90(sp)
;   sd s0, 0(sp)
;   mv s0, sp
;   addi sp, sp, -0x80
;   sd s1, 0x78(sp)
;   sd s2, 0x70(sp)
;   sd s3, 0x68(sp)
;   sd s4, 0x60(sp)
;   sd s5, 0x58(sp)
;   sd s6, 0x50(sp)
;   sd s7, 0x48(sp)
;   sd s8, 0x40(sp)
;   sd s9, 0x38(sp)
;   sd s10, 0x30(sp)
;   sd s11, 0x28(sp)
; block1: ; offset 0x54
;   addi a1, zero, 0xa
;   sd a1, 0x10(sp)
;   addi a2, zero, 0xf
;   sd a2, 8(sp)
;   addi a3, zero, 0x14
;   sd a3, 0(sp)
;   addi a3, zero, 0x19
;   addi a4, zero, 0x1e
;   addi a5, zero, 0x23
;   addi a6, zero, 0x28
;   addi a7, zero, 0x2d
;   addi s2, zero, 0x32
;   addi s3, zero, 0x37
;   addi s4, zero, 0x3c
;   addi s5, zero, 0x41
;   addi s6, zero, 0x46
;   addi s7, zero, 0x4b
;   addi s8, zero, 0x50
;   addi s9, zero, 0x55
;   addi s10, zero, 0x5a
;   addi s11, zero, 0x5f
;   addi t0, zero, 0x64
;   addi t1, zero, 0x69
;   addi t2, zero, 0x6e
;   addi t3, zero, 0x73
;   addi t4, zero, 0x78
;   addi s1, zero, 0x7d
;   addi a0, zero, 0x82
;   addi a1, zero, 0x87
;   auipc a2, 0
;   ld a2, 0xc(a2)
;   j 0xc
;   .byte 0x00, 0x00, 0x00, 0x00 ; reloc_external Abs8 %tail_callee_stack_args 0
;   .byte 0x00, 0x00, 0x00, 0x00
;   sd s2, 0x90(sp)
;   sd s3, 0x98(sp)
;   sd s4, 0xa0(sp)
;   sd s5, 0xa8(sp)
;   sd s6, 0xb0(sp)
;   sd s7, 0xb8(sp)
;   sd s8, 0xc0(sp)
;   sd s9, 0xc8(sp)
;   sd s10, 0xd0(sp)
;   sd s11, 0xd8(sp)
;   sd t0, 0xe0(sp)
;   sd t1, 0xe8(sp)
;   sd t2, 0xf0(sp)
;   sd t3, 0xf8(sp)
;   sd t4, 0x100(sp)
;   sd s1, 0x108(sp)
;   sd a0, 0x110(sp)
;   sd a1, 0x118(sp)
;   ld a1, 8(sp)
;   ld a0, 0x10(sp)
;   mv t0, a2
;   ld a2, 0(sp)
;   ld s1, 0x78(sp)
;   ld s2, 0x70(sp)
;   ld s3, 0x68(sp)
;   ld s4, 0x60(sp)
;   ld s5, 0x58(sp)
;   ld s6, 0x50(sp)
;   ld s7, 0x48(sp)
;   ld s8, 0x40(sp)
;   ld s9, 0x38(sp)
;   ld s10, 0x30(sp)
;   ld s11, 0x28(sp)
;   ld ra, 0x88(sp)
;   ld s0, 0x80(sp)
;   addi sp, sp, 0x90
;   jr t0

