test compile precise-output
set unwind_info=false
target riscv64

function %f(i64) -> i64 {
block0(v0: i64):
  v1 = iconst.i64 3
  v2 = ishl.i64 v0, v1
  v3 = iadd.i64 v0, v2
  return v3
}

; VCode:
; block0:
;   slli a1,a0,3
;   add a0,a0,a1
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a1, a0, 3
;   add a0, a0, a1
;   ret

function %f(i32) -> i32 {
block0(v0: i32):
  v1 = iconst.i32 53
  v2 = ishl.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   slliw a0,a0,53
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slliw a0, a0, 0x15
;   ret

