test compile precise-output
set unwind_info=false
target riscv64 has_v


function %trunc_f32x4(f32x4) -> f32x4 {
block0(v0: f32x4):
    v1 = trunc v0
    return v1
}

; VCode:
;   add sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   vle8.v v1,16(fp) #avl=16, #vtype=(e8, m1, ta, ma)
;   vfabs.v v4,v1 #avl=4, #vtype=(e32, m1, ta, ma)
;   lui a3,307200
;   fmv.w.x fa0,a3
;   vmflt.vf v0,v4,fa0 #avl=4, #vtype=(e32, m1, ta, ma)
;   vfcvt.rtz.x.f.v v12,v1 #avl=4, #vtype=(e32, m1, ta, ma)
;   vfcvt.f.x.v v14,v12 #avl=4, #vtype=(e32, m1, ta, ma)
;   vfsgnj.vv v16,v14,v1 #avl=4, #vtype=(e32, m1, ta, ma)
;   fmv.w.x ft10,zero
;   vfadd.vf v20,v1,ft10 #avl=4, #vtype=(e32, m1, ta, ma)
;   vmerge.vvm v22,v20,v16,v0.t #avl=4, #vtype=(e32, m1, ta, ma)
;   vse8.v v22,0(a0) #avl=16, #vtype=(e8, m1, ta, ma)
;   ld ra,8(sp)
;   ld fp,0(sp)
;   add sp,+16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   ori s0, sp, 0
; block1: ; offset 0x10
;   .byte 0x57, 0x70, 0x08, 0xcc
;   addi t6, s0, 0x10
;   .byte 0x87, 0x80, 0x0f, 0x02
;   .byte 0x57, 0x70, 0x02, 0xcd
;   .byte 0x57, 0x92, 0x10, 0x2a
;   lui a3, 0x4b000
;   fmv.w.x fa0, a3
;   .byte 0x57, 0x50, 0x45, 0x6e
;   .byte 0x57, 0x96, 0x13, 0x4a
;   .byte 0x57, 0x97, 0xc1, 0x4a
;   .byte 0x57, 0x98, 0xe0, 0x22
;   fmv.w.x ft10, zero
;   .byte 0x57, 0x5a, 0x1f, 0x02
;   .byte 0x57, 0x0b, 0x48, 0x5d
;   .byte 0x57, 0x70, 0x08, 0xcc
;   .byte 0x27, 0x0b, 0x05, 0x02
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

function %trunc_f64x2(f64x2) -> f64x2 {
block0(v0: f64x2):
    v1 = trunc v0
    return v1
}

; VCode:
;   add sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   vle8.v v1,16(fp) #avl=16, #vtype=(e8, m1, ta, ma)
;   vfabs.v v4,v1 #avl=2, #vtype=(e64, m1, ta, ma)
;   ld a3,[const(0)]
;   fmv.d.x fa0,a3
;   vmflt.vf v0,v4,fa0 #avl=2, #vtype=(e64, m1, ta, ma)
;   vfcvt.rtz.x.f.v v12,v1 #avl=2, #vtype=(e64, m1, ta, ma)
;   vfcvt.f.x.v v14,v12 #avl=2, #vtype=(e64, m1, ta, ma)
;   vfsgnj.vv v16,v14,v1 #avl=2, #vtype=(e64, m1, ta, ma)
;   fmv.d.x ft10,zero
;   vfadd.vf v20,v1,ft10 #avl=2, #vtype=(e64, m1, ta, ma)
;   vmerge.vvm v22,v20,v16,v0.t #avl=2, #vtype=(e64, m1, ta, ma)
;   vse8.v v22,0(a0) #avl=16, #vtype=(e8, m1, ta, ma)
;   ld ra,8(sp)
;   ld fp,0(sp)
;   add sp,+16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   ori s0, sp, 0
; block1: ; offset 0x10
;   .byte 0x57, 0x70, 0x08, 0xcc
;   addi t6, s0, 0x10
;   .byte 0x87, 0x80, 0x0f, 0x02
;   .byte 0x57, 0x70, 0x81, 0xcd
;   .byte 0x57, 0x92, 0x10, 0x2a
;   auipc a3, 0
;   ld a3, 0x44(a3)
;   fmv.d.x fa0, a3
;   .byte 0x57, 0x50, 0x45, 0x6e
;   .byte 0x57, 0x96, 0x13, 0x4a
;   .byte 0x57, 0x97, 0xc1, 0x4a
;   .byte 0x57, 0x98, 0xe0, 0x22
;   fmv.d.x ft10, zero
;   .byte 0x57, 0x5a, 0x1f, 0x02
;   .byte 0x57, 0x0b, 0x48, 0x5d
;   .byte 0x57, 0x70, 0x08, 0xcc
;   .byte 0x27, 0x0b, 0x05, 0x02
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret
;   .byte 0x00, 0x00, 0x00, 0x00
;   .byte 0x00, 0x00, 0x00, 0x00
;   .byte 0x00, 0x00, 0x30, 0x43

