test compile precise-output
set enable_multi_ret_implicit_sret
set unwind_info=false
target riscv64 has_v


function %iadd_const_i8x16(i8x16) -> i8x16 {
block0(v0: i8x16):
    v2 = vconst.i8x16 0x01010101_01010101_01010101_01010101
    v3 = iadd v0, v2

    v4 = vconst.i8x16 0x00010001_00010001_00010001_00010001
    v5 = iadd v3, v4

    v6 = vconst.i8x16 0x00000001_00000001_00000001_00000001
    v7 = iadd v5, v6

    v8 = vconst.i8x16 0x00000000_00000001_00000000_00000001
    v9 = iadd v7, v8

    return v9
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   vle8.v v8,-16(incoming_arg) #avl=16, #vtype=(e8, m1, ta, ma)
;   vadd.vi v10,v8,1 #avl=16, #vtype=(e8, m1, ta, ma)
;   vle8.v v11,[const(2)] #avl=16, #vtype=(e8, m1, ta, ma)
;   vadd.vv v10,v10,v11 #avl=16, #vtype=(e8, m1, ta, ma)
;   vle8.v v11,[const(1)] #avl=16, #vtype=(e8, m1, ta, ma)
;   vadd.vv v10,v10,v11 #avl=16, #vtype=(e8, m1, ta, ma)
;   vle8.v v11,[const(0)] #avl=16, #vtype=(e8, m1, ta, ma)
;   vadd.vv v10,v10,v11 #avl=16, #vtype=(e8, m1, ta, ma)
;   vse8.v v10,0(a0) #avl=16, #vtype=(e8, m1, ta, ma)
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
; block1: ; offset 0x10
;   .byte 0x57, 0x70, 0x08, 0xcc
;   addi t6, sp, 0x10
;   .byte 0x07, 0x84, 0x0f, 0x02
;   .byte 0x57, 0xb5, 0x80, 0x02
;   auipc t6, 0
;   addi t6, t6, 0x50
;   .byte 0x87, 0x85, 0x0f, 0x02
;   .byte 0x57, 0x85, 0xa5, 0x02
;   auipc t6, 0
;   addi t6, t6, 0x50
;   .byte 0x87, 0x85, 0x0f, 0x02
;   .byte 0x57, 0x85, 0xa5, 0x02
;   auipc t6, 0
;   addi t6, t6, 0x50
;   .byte 0x87, 0x85, 0x0f, 0x02
;   .byte 0x57, 0x85, 0xa5, 0x02
;   .byte 0x27, 0x05, 0x05, 0x02
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret
;   .byte 0x00, 0x00, 0x00, 0x00
;   .byte 0x00, 0x00, 0x00, 0x00
;   .byte 0x00, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x00, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x00, 0x00, 0x00, 0x00

function %iadd_const_i16x8(i16x8) -> i16x8 {
block0(v0: i16x8):
    v2 = vconst.i16x8 0x01010101_01010101_01010101_01010101
    v3 = iadd v0, v2

    v4 = vconst.i16x8 0x00010001_00010001_00010001_00010001
    v5 = iadd v3, v4

    v6 = vconst.i16x8 0x00000001_00000001_00000001_00000001
    v7 = iadd v5, v6

    v8 = vconst.i16x8 0x00000000_00000001_00000000_00000001
    v9 = iadd v7, v8

    return v9
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   vle8.v v8,-16(incoming_arg) #avl=16, #vtype=(e8, m1, ta, ma)
;   vle16.v v10,[const(2)] #avl=8, #vtype=(e16, m1, ta, ma)
;   vadd.vv v10,v8,v10 #avl=8, #vtype=(e16, m1, ta, ma)
;   vadd.vi v10,v10,1 #avl=8, #vtype=(e16, m1, ta, ma)
;   vle16.v v11,[const(1)] #avl=8, #vtype=(e16, m1, ta, ma)
;   vadd.vv v10,v10,v11 #avl=8, #vtype=(e16, m1, ta, ma)
;   vle16.v v11,[const(0)] #avl=8, #vtype=(e16, m1, ta, ma)
;   vadd.vv v10,v10,v11 #avl=8, #vtype=(e16, m1, ta, ma)
;   vse8.v v10,0(a0) #avl=16, #vtype=(e8, m1, ta, ma)
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
; block1: ; offset 0x10
;   .byte 0x57, 0x70, 0x08, 0xcc
;   addi t6, sp, 0x10
;   .byte 0x07, 0x84, 0x0f, 0x02
;   .byte 0x57, 0x70, 0x84, 0xcc
;   auipc t6, 0
;   addi t6, t6, 0x50
;   .byte 0x07, 0xd5, 0x0f, 0x02
;   .byte 0x57, 0x05, 0x85, 0x02
;   .byte 0x57, 0xb5, 0xa0, 0x02
;   auipc t6, 0
;   addi t6, t6, 0x4c
;   .byte 0x87, 0xd5, 0x0f, 0x02
;   .byte 0x57, 0x85, 0xa5, 0x02
;   auipc t6, 0
;   addi t6, t6, 0x4c
;   .byte 0x87, 0xd5, 0x0f, 0x02
;   .byte 0x57, 0x85, 0xa5, 0x02
;   .byte 0x57, 0x70, 0x08, 0xcc
;   .byte 0x27, 0x05, 0x05, 0x02
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret
;   .byte 0x00, 0x00, 0x00, 0x00
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x00, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x00, 0x00, 0x00, 0x00

function %iadd_const_i32x4(i32x4) -> i32x4 {
block0(v0: i32x4):
    v2 = vconst.i32x4 0x01010101_01010101_01010101_01010101
    v3 = iadd v0, v2

    v4 = vconst.i32x4 0x00010001_00010001_00010001_00010001
    v5 = iadd v3, v4

    v6 = vconst.i32x4 0x00000001_00000001_00000001_00000001
    v7 = iadd v5, v6

    v8 = vconst.i32x4 0x00000000_00000001_00000000_00000001
    v9 = iadd v7, v8

    return v9
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   vle8.v v8,-16(incoming_arg) #avl=16, #vtype=(e8, m1, ta, ma)
;   vle32.v v10,[const(2)] #avl=4, #vtype=(e32, m1, ta, ma)
;   vadd.vv v10,v8,v10 #avl=4, #vtype=(e32, m1, ta, ma)
;   vle32.v v11,[const(1)] #avl=4, #vtype=(e32, m1, ta, ma)
;   vadd.vv v10,v10,v11 #avl=4, #vtype=(e32, m1, ta, ma)
;   vadd.vi v10,v10,1 #avl=4, #vtype=(e32, m1, ta, ma)
;   vle32.v v11,[const(0)] #avl=4, #vtype=(e32, m1, ta, ma)
;   vadd.vv v10,v10,v11 #avl=4, #vtype=(e32, m1, ta, ma)
;   vse8.v v10,0(a0) #avl=16, #vtype=(e8, m1, ta, ma)
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
; block1: ; offset 0x10
;   .byte 0x57, 0x70, 0x08, 0xcc
;   addi t6, sp, 0x10
;   .byte 0x07, 0x84, 0x0f, 0x02
;   .byte 0x57, 0x70, 0x02, 0xcd
;   auipc t6, 0
;   addi t6, t6, 0x50
;   .byte 0x07, 0xe5, 0x0f, 0x02
;   .byte 0x57, 0x05, 0x85, 0x02
;   auipc t6, 0
;   addi t6, t6, 0x50
;   .byte 0x87, 0xe5, 0x0f, 0x02
;   .byte 0x57, 0x85, 0xa5, 0x02
;   .byte 0x57, 0xb5, 0xa0, 0x02
;   auipc t6, 0
;   addi t6, t6, 0x4c
;   .byte 0x87, 0xe5, 0x0f, 0x02
;   .byte 0x57, 0x85, 0xa5, 0x02
;   .byte 0x57, 0x70, 0x08, 0xcc
;   .byte 0x27, 0x05, 0x05, 0x02
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret
;   .byte 0x00, 0x00, 0x00, 0x00
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x00, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x00, 0x00, 0x00, 0x00

function %iadd_const_i64x2(i64x2) -> i64x2 {
block0(v0: i64x2):
    v2 = vconst.i64x2 0x01010101_01010101_01010101_01010101
    v3 = iadd v0, v2

    v4 = vconst.i64x2 0x00010001_00010001_00010001_00010001
    v5 = iadd v3, v4

    v6 = vconst.i64x2 0x00000001_00000001_00000001_00000001
    v7 = iadd v5, v6

    v8 = vconst.i64x2 0x00000000_00000001_00000000_00000001
    v9 = iadd v7, v8

    return v9
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   vle8.v v8,-16(incoming_arg) #avl=16, #vtype=(e8, m1, ta, ma)
;   vle64.v v10,[const(2)] #avl=2, #vtype=(e64, m1, ta, ma)
;   vadd.vv v10,v8,v10 #avl=2, #vtype=(e64, m1, ta, ma)
;   vle64.v v11,[const(1)] #avl=2, #vtype=(e64, m1, ta, ma)
;   vadd.vv v10,v10,v11 #avl=2, #vtype=(e64, m1, ta, ma)
;   vle64.v v11,[const(0)] #avl=2, #vtype=(e64, m1, ta, ma)
;   vadd.vv v10,v10,v11 #avl=2, #vtype=(e64, m1, ta, ma)
;   vadd.vi v10,v10,1 #avl=2, #vtype=(e64, m1, ta, ma)
;   vse8.v v10,0(a0) #avl=16, #vtype=(e8, m1, ta, ma)
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
; block1: ; offset 0x10
;   .byte 0x57, 0x70, 0x08, 0xcc
;   addi t6, sp, 0x10
;   .byte 0x07, 0x84, 0x0f, 0x02
;   .byte 0x57, 0x70, 0x81, 0xcd
;   auipc t6, 0
;   addi t6, t6, 0x50
;   .byte 0x07, 0xf5, 0x0f, 0x02
;   .byte 0x57, 0x05, 0x85, 0x02
;   auipc t6, 0
;   addi t6, t6, 0x50
;   .byte 0x87, 0xf5, 0x0f, 0x02
;   .byte 0x57, 0x85, 0xa5, 0x02
;   auipc t6, 0
;   addi t6, t6, 0x50
;   .byte 0x87, 0xf5, 0x0f, 0x02
;   .byte 0x57, 0x85, 0xa5, 0x02
;   .byte 0x57, 0xb5, 0xa0, 0x02
;   .byte 0x57, 0x70, 0x08, 0xcc
;   .byte 0x27, 0x05, 0x05, 0x02
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret
;   .byte 0x00, 0x00, 0x00, 0x00
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00

function %isub_const_i8x16(i8x16) -> i8x16 {
block0(v0: i8x16):
    v2 = vconst.i8x16 0x01010101_01010101_01010101_01010101
    v3 = isub v0, v2

    v4 = vconst.i8x16 0x00010001_00010001_00010001_00010001
    v5 = isub v3, v4

    v6 = vconst.i8x16 0x00000001_00000001_00000001_00000001
    v7 = isub v5, v6

    v8 = vconst.i8x16 0x00000000_00000001_00000000_00000001
    v9 = isub v7, v8

    return v9
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   vle8.v v8,-16(incoming_arg) #avl=16, #vtype=(e8, m1, ta, ma)
;   vadd.vi v10,v8,-1 #avl=16, #vtype=(e8, m1, ta, ma)
;   vle8.v v11,[const(2)] #avl=16, #vtype=(e8, m1, ta, ma)
;   vsub.vv v10,v10,v11 #avl=16, #vtype=(e8, m1, ta, ma)
;   vle8.v v11,[const(1)] #avl=16, #vtype=(e8, m1, ta, ma)
;   vsub.vv v10,v10,v11 #avl=16, #vtype=(e8, m1, ta, ma)
;   vle8.v v11,[const(0)] #avl=16, #vtype=(e8, m1, ta, ma)
;   vsub.vv v10,v10,v11 #avl=16, #vtype=(e8, m1, ta, ma)
;   vse8.v v10,0(a0) #avl=16, #vtype=(e8, m1, ta, ma)
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
; block1: ; offset 0x10
;   .byte 0x57, 0x70, 0x08, 0xcc
;   addi t6, sp, 0x10
;   .byte 0x07, 0x84, 0x0f, 0x02
;   .byte 0x57, 0xb5, 0x8f, 0x02
;   auipc t6, 0
;   addi t6, t6, 0x50
;   .byte 0x87, 0x85, 0x0f, 0x02
;   .byte 0x57, 0x85, 0xa5, 0x0a
;   auipc t6, 0
;   addi t6, t6, 0x50
;   .byte 0x87, 0x85, 0x0f, 0x02
;   .byte 0x57, 0x85, 0xa5, 0x0a
;   auipc t6, 0
;   addi t6, t6, 0x50
;   .byte 0x87, 0x85, 0x0f, 0x02
;   .byte 0x57, 0x85, 0xa5, 0x0a
;   .byte 0x27, 0x05, 0x05, 0x02
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret
;   .byte 0x00, 0x00, 0x00, 0x00
;   .byte 0x00, 0x00, 0x00, 0x00
;   .byte 0x00, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x00, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x00, 0x00, 0x00, 0x00

function %isub_const_i16x8(i16x8) -> i16x8 {
block0(v0: i16x8):
    v2 = vconst.i16x8 0x01010101_01010101_01010101_01010101
    v3 = isub v0, v2

    v4 = vconst.i16x8 0x00010001_00010001_00010001_00010001
    v5 = isub v3, v4

    v6 = vconst.i16x8 0x00000001_00000001_00000001_00000001
    v7 = isub v5, v6

    v8 = vconst.i16x8 0x00000000_00000001_00000000_00000001
    v9 = isub v7, v8

    return v9
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   vle8.v v8,-16(incoming_arg) #avl=16, #vtype=(e8, m1, ta, ma)
;   vle16.v v10,[const(2)] #avl=8, #vtype=(e16, m1, ta, ma)
;   vsub.vv v10,v8,v10 #avl=8, #vtype=(e16, m1, ta, ma)
;   vadd.vi v10,v10,-1 #avl=8, #vtype=(e16, m1, ta, ma)
;   vle16.v v11,[const(1)] #avl=8, #vtype=(e16, m1, ta, ma)
;   vsub.vv v10,v10,v11 #avl=8, #vtype=(e16, m1, ta, ma)
;   vle16.v v11,[const(0)] #avl=8, #vtype=(e16, m1, ta, ma)
;   vsub.vv v10,v10,v11 #avl=8, #vtype=(e16, m1, ta, ma)
;   vse8.v v10,0(a0) #avl=16, #vtype=(e8, m1, ta, ma)
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
; block1: ; offset 0x10
;   .byte 0x57, 0x70, 0x08, 0xcc
;   addi t6, sp, 0x10
;   .byte 0x07, 0x84, 0x0f, 0x02
;   .byte 0x57, 0x70, 0x84, 0xcc
;   auipc t6, 0
;   addi t6, t6, 0x50
;   .byte 0x07, 0xd5, 0x0f, 0x02
;   .byte 0x57, 0x05, 0x85, 0x0a
;   .byte 0x57, 0xb5, 0xaf, 0x02
;   auipc t6, 0
;   addi t6, t6, 0x4c
;   .byte 0x87, 0xd5, 0x0f, 0x02
;   .byte 0x57, 0x85, 0xa5, 0x0a
;   auipc t6, 0
;   addi t6, t6, 0x4c
;   .byte 0x87, 0xd5, 0x0f, 0x02
;   .byte 0x57, 0x85, 0xa5, 0x0a
;   .byte 0x57, 0x70, 0x08, 0xcc
;   .byte 0x27, 0x05, 0x05, 0x02
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret
;   .byte 0x00, 0x00, 0x00, 0x00
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x00, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x00, 0x00, 0x00, 0x00

function %isub_const_i32x4(i32x4) -> i32x4 {
block0(v0: i32x4):
    v2 = vconst.i32x4 0x01010101_01010101_01010101_01010101
    v3 = isub v0, v2

    v4 = vconst.i32x4 0x00010001_00010001_00010001_00010001
    v5 = isub v3, v4

    v6 = vconst.i32x4 0x00000001_00000001_00000001_00000001
    v7 = isub v5, v6

    v8 = vconst.i32x4 0x00000000_00000001_00000000_00000001
    v9 = isub v7, v8

    return v9
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   vle8.v v8,-16(incoming_arg) #avl=16, #vtype=(e8, m1, ta, ma)
;   vle32.v v10,[const(2)] #avl=4, #vtype=(e32, m1, ta, ma)
;   vsub.vv v10,v8,v10 #avl=4, #vtype=(e32, m1, ta, ma)
;   vle32.v v11,[const(1)] #avl=4, #vtype=(e32, m1, ta, ma)
;   vsub.vv v10,v10,v11 #avl=4, #vtype=(e32, m1, ta, ma)
;   vadd.vi v10,v10,-1 #avl=4, #vtype=(e32, m1, ta, ma)
;   vle32.v v11,[const(0)] #avl=4, #vtype=(e32, m1, ta, ma)
;   vsub.vv v10,v10,v11 #avl=4, #vtype=(e32, m1, ta, ma)
;   vse8.v v10,0(a0) #avl=16, #vtype=(e8, m1, ta, ma)
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
; block1: ; offset 0x10
;   .byte 0x57, 0x70, 0x08, 0xcc
;   addi t6, sp, 0x10
;   .byte 0x07, 0x84, 0x0f, 0x02
;   .byte 0x57, 0x70, 0x02, 0xcd
;   auipc t6, 0
;   addi t6, t6, 0x50
;   .byte 0x07, 0xe5, 0x0f, 0x02
;   .byte 0x57, 0x05, 0x85, 0x0a
;   auipc t6, 0
;   addi t6, t6, 0x50
;   .byte 0x87, 0xe5, 0x0f, 0x02
;   .byte 0x57, 0x85, 0xa5, 0x0a
;   .byte 0x57, 0xb5, 0xaf, 0x02
;   auipc t6, 0
;   addi t6, t6, 0x4c
;   .byte 0x87, 0xe5, 0x0f, 0x02
;   .byte 0x57, 0x85, 0xa5, 0x0a
;   .byte 0x57, 0x70, 0x08, 0xcc
;   .byte 0x27, 0x05, 0x05, 0x02
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret
;   .byte 0x00, 0x00, 0x00, 0x00
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x00, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x00, 0x00, 0x00, 0x00

function %isub_const_i64x2(i64x2) -> i64x2 {
block0(v0: i64x2):
    v2 = vconst.i64x2 0x01010101_01010101_01010101_01010101
    v3 = isub v0, v2

    v4 = vconst.i64x2 0x00010001_00010001_00010001_00010001
    v5 = isub v3, v4

    v6 = vconst.i64x2 0x00000001_00000001_00000001_00000001
    v7 = isub v5, v6

    v8 = vconst.i64x2 0x00000000_00000001_00000000_00000001
    v9 = isub v7, v8

    return v9
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   vle8.v v8,-16(incoming_arg) #avl=16, #vtype=(e8, m1, ta, ma)
;   vle64.v v10,[const(2)] #avl=2, #vtype=(e64, m1, ta, ma)
;   vsub.vv v10,v8,v10 #avl=2, #vtype=(e64, m1, ta, ma)
;   vle64.v v11,[const(1)] #avl=2, #vtype=(e64, m1, ta, ma)
;   vsub.vv v10,v10,v11 #avl=2, #vtype=(e64, m1, ta, ma)
;   vle64.v v11,[const(0)] #avl=2, #vtype=(e64, m1, ta, ma)
;   vsub.vv v10,v10,v11 #avl=2, #vtype=(e64, m1, ta, ma)
;   vadd.vi v10,v10,-1 #avl=2, #vtype=(e64, m1, ta, ma)
;   vse8.v v10,0(a0) #avl=16, #vtype=(e8, m1, ta, ma)
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
; block1: ; offset 0x10
;   .byte 0x57, 0x70, 0x08, 0xcc
;   addi t6, sp, 0x10
;   .byte 0x07, 0x84, 0x0f, 0x02
;   .byte 0x57, 0x70, 0x81, 0xcd
;   auipc t6, 0
;   addi t6, t6, 0x50
;   .byte 0x07, 0xf5, 0x0f, 0x02
;   .byte 0x57, 0x05, 0x85, 0x0a
;   auipc t6, 0
;   addi t6, t6, 0x50
;   .byte 0x87, 0xf5, 0x0f, 0x02
;   .byte 0x57, 0x85, 0xa5, 0x0a
;   auipc t6, 0
;   addi t6, t6, 0x50
;   .byte 0x87, 0xf5, 0x0f, 0x02
;   .byte 0x57, 0x85, 0xa5, 0x0a
;   .byte 0x57, 0xb5, 0xaf, 0x02
;   .byte 0x57, 0x70, 0x08, 0xcc
;   .byte 0x27, 0x05, 0x05, 0x02
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret
;   .byte 0x00, 0x00, 0x00, 0x00
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x01, 0x01, 0x01
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x01, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00
;   .byte 0x01, 0x00, 0x00, 0x00

