test compile precise-output
set enable_multi_ret_implicit_sret
set unwind_info=false
target riscv64 has_v

function %unarrow_i16x8(i16x8, i16x8) -> i8x16 {
block0(v0: i16x8, v1: i16x8):
    v2 = unarrow v0, v1
    return v2
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   vle8.v v9,-32(incoming_arg) #avl=16, #vtype=(e8, m1, ta, ma)
;   vle8.v v11,-16(incoming_arg) #avl=16, #vtype=(e8, m1, ta, ma)
;   vmax.vx v14,v9,zero #avl=8, #vtype=(e16, m1, ta, ma)
;   vmax.vx v8,v11,zero #avl=8, #vtype=(e16, m1, ta, ma)
;   vnclipu.wi v12,v14,0 #avl=8, #vtype=(e8, mf2, ta, ma)
;   vnclipu.wi v13,v8,0 #avl=8, #vtype=(e8, mf2, ta, ma)
;   vslideup.vi v12,v13,8 #avl=16, #vtype=(e8, m1, ta, ma)
;   vse8.v v12,0(a0) #avl=16, #vtype=(e8, m1, ta, ma)
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
; block1: ; offset 0x10
;   .byte 0x57, 0x70, 0x08, 0xcc
;   addi t6, sp, 0x10
;   .byte 0x87, 0x84, 0x0f, 0x02
;   addi t6, sp, 0x20
;   .byte 0x87, 0x85, 0x0f, 0x02
;   .byte 0x57, 0x70, 0x84, 0xcc
;   .byte 0x57, 0x47, 0x90, 0x1e
;   .byte 0x57, 0x44, 0xb0, 0x1e
;   .byte 0x57, 0x70, 0x74, 0xcc
;   .byte 0x57, 0x36, 0xe0, 0xba
;   .byte 0xd7, 0x36, 0x80, 0xba
;   .byte 0x57, 0x70, 0x08, 0xcc
;   .byte 0x57, 0x36, 0xd4, 0x3a
;   .byte 0x27, 0x06, 0x05, 0x02
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

function %unarrow_i32x4(i32x4, i32x4) -> i16x8 {
block0(v0: i32x4, v1: i32x4):
    v2 = unarrow v0, v1
    return v2
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   vle8.v v9,-32(incoming_arg) #avl=16, #vtype=(e8, m1, ta, ma)
;   vle8.v v11,-16(incoming_arg) #avl=16, #vtype=(e8, m1, ta, ma)
;   vmax.vx v14,v9,zero #avl=4, #vtype=(e32, m1, ta, ma)
;   vmax.vx v8,v11,zero #avl=4, #vtype=(e32, m1, ta, ma)
;   vnclipu.wi v12,v14,0 #avl=4, #vtype=(e16, mf2, ta, ma)
;   vnclipu.wi v13,v8,0 #avl=4, #vtype=(e16, mf2, ta, ma)
;   vslideup.vi v12,v13,4 #avl=8, #vtype=(e16, m1, ta, ma)
;   vse8.v v12,0(a0) #avl=16, #vtype=(e8, m1, ta, ma)
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
; block1: ; offset 0x10
;   .byte 0x57, 0x70, 0x08, 0xcc
;   addi t6, sp, 0x10
;   .byte 0x87, 0x84, 0x0f, 0x02
;   addi t6, sp, 0x20
;   .byte 0x87, 0x85, 0x0f, 0x02
;   .byte 0x57, 0x70, 0x02, 0xcd
;   .byte 0x57, 0x47, 0x90, 0x1e
;   .byte 0x57, 0x44, 0xb0, 0x1e
;   .byte 0x57, 0x70, 0xf2, 0xcc
;   .byte 0x57, 0x36, 0xe0, 0xba
;   .byte 0xd7, 0x36, 0x80, 0xba
;   .byte 0x57, 0x70, 0x84, 0xcc
;   .byte 0x57, 0x36, 0xd2, 0x3a
;   .byte 0x57, 0x70, 0x08, 0xcc
;   .byte 0x27, 0x06, 0x05, 0x02
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

function %unarrow_i64x2(i64x2, i64x2) -> i32x4 {
block0(v0: i64x2, v1: i64x2):
    v2 = unarrow v0, v1
    return v2
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   vle8.v v9,-32(incoming_arg) #avl=16, #vtype=(e8, m1, ta, ma)
;   vle8.v v11,-16(incoming_arg) #avl=16, #vtype=(e8, m1, ta, ma)
;   vmax.vx v14,v9,zero #avl=2, #vtype=(e64, m1, ta, ma)
;   vmax.vx v8,v11,zero #avl=2, #vtype=(e64, m1, ta, ma)
;   vnclipu.wi v12,v14,0 #avl=2, #vtype=(e32, mf2, ta, ma)
;   vnclipu.wi v13,v8,0 #avl=2, #vtype=(e32, mf2, ta, ma)
;   vslideup.vi v12,v13,2 #avl=4, #vtype=(e32, m1, ta, ma)
;   vse8.v v12,0(a0) #avl=16, #vtype=(e8, m1, ta, ma)
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
; block1: ; offset 0x10
;   .byte 0x57, 0x70, 0x08, 0xcc
;   addi t6, sp, 0x10
;   .byte 0x87, 0x84, 0x0f, 0x02
;   addi t6, sp, 0x20
;   .byte 0x87, 0x85, 0x0f, 0x02
;   .byte 0x57, 0x70, 0x81, 0xcd
;   .byte 0x57, 0x47, 0x90, 0x1e
;   .byte 0x57, 0x44, 0xb0, 0x1e
;   .byte 0x57, 0x70, 0x71, 0xcd
;   .byte 0x57, 0x36, 0xe0, 0xba
;   .byte 0xd7, 0x36, 0x80, 0xba
;   .byte 0x57, 0x70, 0x02, 0xcd
;   .byte 0x57, 0x36, 0xd1, 0x3a
;   .byte 0x57, 0x70, 0x08, 0xcc
;   .byte 0x27, 0x06, 0x05, 0x02
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

