test compile precise-output
set enable_multi_ret_implicit_sret
set unwind_info=false
target riscv64 has_v


function %vhighbits_i8x16(i8x16) -> i16 {
block0(v0: i8x16):
    v1 = vhigh_bits.i16 v0
    return v1
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   vle8.v v8,-16(incoming_arg) #avl=16, #vtype=(e8, m1, ta, ma)
;   vmslt.vx v10,v8,zero #avl=16, #vtype=(e8, m1, ta, ma)
;   vmv.x.s a4,v10 #avl=2, #vtype=(e64, m1, ta, ma)
;   lui a0,16
;   addi a2,a0,-1
;   and a0,a4,a2
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
; block1: ; offset 0x10
;   .byte 0x57, 0x70, 0x08, 0xcc
;   addi t6, sp, 0x10
;   .byte 0x07, 0x84, 0x0f, 0x02
;   .byte 0x57, 0x45, 0x80, 0x6e
;   .byte 0x57, 0x70, 0x81, 0xcd
;   .byte 0x57, 0x27, 0xa0, 0x42
;   lui a0, 0x10
;   addi a2, a0, -1
;   and a0, a4, a2
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

function %vhighbits_i16x8(i16x8) -> i8 {
block0(v0: i16x8):
    v1 = vhigh_bits.i8 v0
    return v1
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   vle8.v v8,-16(incoming_arg) #avl=16, #vtype=(e8, m1, ta, ma)
;   vmslt.vx v10,v8,zero #avl=8, #vtype=(e16, m1, ta, ma)
;   vmv.x.s a4,v10 #avl=2, #vtype=(e64, m1, ta, ma)
;   andi a0,a4,255
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
; block1: ; offset 0x10
;   .byte 0x57, 0x70, 0x08, 0xcc
;   addi t6, sp, 0x10
;   .byte 0x07, 0x84, 0x0f, 0x02
;   .byte 0x57, 0x70, 0x84, 0xcc
;   .byte 0x57, 0x45, 0x80, 0x6e
;   .byte 0x57, 0x70, 0x81, 0xcd
;   .byte 0x57, 0x27, 0xa0, 0x42
;   andi a0, a4, 0xff
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

function %vhighbits_i32x4(i32x4) -> i8 {
block0(v0: i32x4):
    v1 = vhigh_bits.i8 v0
    return v1
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   vle8.v v8,-16(incoming_arg) #avl=16, #vtype=(e8, m1, ta, ma)
;   vmslt.vx v10,v8,zero #avl=4, #vtype=(e32, m1, ta, ma)
;   vmv.x.s a4,v10 #avl=2, #vtype=(e64, m1, ta, ma)
;   andi a0,a4,15
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
; block1: ; offset 0x10
;   .byte 0x57, 0x70, 0x08, 0xcc
;   addi t6, sp, 0x10
;   .byte 0x07, 0x84, 0x0f, 0x02
;   .byte 0x57, 0x70, 0x02, 0xcd
;   .byte 0x57, 0x45, 0x80, 0x6e
;   .byte 0x57, 0x70, 0x81, 0xcd
;   .byte 0x57, 0x27, 0xa0, 0x42
;   andi a0, a4, 0xf
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

function %vhighbits_i64x2(i64x2) -> i8 {
block0(v0: i64x2):
    v1 = vhigh_bits.i8 v0
    return v1
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   vle8.v v8,-16(incoming_arg) #avl=16, #vtype=(e8, m1, ta, ma)
;   vmslt.vx v10,v8,zero #avl=2, #vtype=(e64, m1, ta, ma)
;   vmv.x.s a4,v10 #avl=2, #vtype=(e64, m1, ta, ma)
;   andi a0,a4,3
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
; block1: ; offset 0x10
;   .byte 0x57, 0x70, 0x08, 0xcc
;   addi t6, sp, 0x10
;   .byte 0x07, 0x84, 0x0f, 0x02
;   .byte 0x57, 0x70, 0x81, 0xcd
;   .byte 0x57, 0x45, 0x80, 0x6e
;   .byte 0x57, 0x27, 0xa0, 0x42
;   andi a0, a4, 3
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

