test compile precise-output
set unwind_info=false
target riscv64 has_v

function %fvdemote(f64x2) -> f32x4 {
block0(v0: f64x2):
    v1 = fvdemote v0
    return v1
}

; VCode:
;   add sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   vle8.v v1,16(fp) #avl=16, #vtype=(e8, m1, ta, ma)
;   vfncvt.f.f.w v4,v1 #avl=4, #vtype=(e32, mf2, ta, ma)
;   vmv.v.i v0,12 #avl=2, #vtype=(e64, m1, ta, ma)
;   vmerge.vim v8,v4,0,v0.t #avl=4, #vtype=(e32, m1, ta, ma)
;   vse8.v v8,0(a0) #avl=16, #vtype=(e8, m1, ta, ma)
;   ld ra,8(sp)
;   ld fp,0(sp)
;   add sp,+16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
; block1: ; offset 0x10
;   .byte 0x57, 0x70, 0x08, 0xcc
;   addi t6, s0, 0x10
;   .byte 0x87, 0x80, 0x0f, 0x02
;   .byte 0x57, 0x70, 0x72, 0xcd
;   .byte 0x57, 0x12, 0x1a, 0x4a
;   .byte 0x57, 0x70, 0x81, 0xcd
;   .byte 0x57, 0x30, 0x06, 0x5e
;   .byte 0x57, 0x70, 0x02, 0xcd
;   .byte 0x57, 0x34, 0x40, 0x5c
;   .byte 0x57, 0x70, 0x08, 0xcc
;   .byte 0x27, 0x04, 0x05, 0x02
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

