test compile precise-output
set unwind_info=false
target riscv64

function %store_f16(f16, i64) {
block0(v0: f16, v1: i64):
    store.f16 v0, v1
    return
}

; VCode:
; block0:
;   fmv.x.w a3,fa0
;   sh a3,0(a0)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   fmv.x.w a3, fa0
;   sh a3, 0(a0) ; trap: heap_oob
;   ret

function %store_f128(f128, i64) {
block0(v0: f128, v1: i64):
    store.f128 v0, v1
    return
}

; VCode:
; block0:
;   sd a0,0(a2)
;   sd a1,8(a2)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   sd a0, 0(a2) ; trap: heap_oob
;   sd a1, 8(a2) ; trap: heap_oob
;   ret

