test compile precise-output
set tls_model=elf_gd
target riscv64

function u0:0(i32) -> i32, i64 {
gv0 = symbol colocated tls u1:0

block0(v0: i32):
    v1 = tls_value.i64 gv0
    return v0, v1
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-16
;   sd s1,8(sp)
; block0:
;   mv s1,a0
;   elf_tls_get_addr a0,userextname0
;   mv a1,a0
;   mv a0,s1
;   ld s1,8(sp)
;   addi sp,sp,16
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
;   addi sp, sp, -0x10
;   sd s1, 8(sp)
; block1: ; offset 0x18
;   mv s1, a0
;   auipc a0, 0 ; reloc_external RiscvTlsGdHi20 u1:0 0
;   mv a0, a0 ; reloc_external RiscvPCRelLo12I func+28 0
;   auipc ra, 0 ; reloc_external RiscvCallPlt %ElfTlsGetAddr 0
;   jalr ra
;   mv a1, a0
;   mv a0, s1
;   ld s1, 8(sp)
;   addi sp, sp, 0x10
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

function u0:1(i64) -> i64 system_v {
gv0 = symbol colocated tls u1:0

block0(v0: i64):
    v1 = tls_value.i64 gv0
    v2 = iconst.i8 0
    store notrap v2, v1
    v3 = iconst.i64 0
    return v3
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
; block0:
;   elf_tls_get_addr a0,userextname0
;   sb zero,0(a0)
;   li a0,0
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
; block1: ; offset 0x10
;   auipc a0, 0 ; reloc_external RiscvTlsGdHi20 u1:0 0
;   mv a0, a0 ; reloc_external RiscvPCRelLo12I func+16 0
;   auipc ra, 0 ; reloc_external RiscvCallPlt %ElfTlsGetAddr 0
;   jalr ra
;   sb zero, 0(a0)
;   mv a0, zero
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

