test compile precise-output
target riscv64

function u0:0(i32) -> i32, i64 {
gv0 = symbol colocated tls u1:0

block0(v0: i32):
    v1 = global_value.i64 gv0
    return v0, v1
}

;   stp fp, lr, [sp, #-16]!
;   mov fp, sp
;   str x25, [sp, #-16]!
;   stp d14, d15, [sp, #-16]!
;   stp d12, d13, [sp, #-16]!
;   stp d10, d11, [sp, #-16]!
;   stp d8, d9, [sp, #-16]!
; block0:
;   mov x25, x0
;   elf_tls_get_addr u1:0
;   mov x1, x0
;   mov x0, x25
;   ldp d8, d9, [sp], #16
;   ldp d10, d11, [sp], #16
;   ldp d12, d13, [sp], #16
;   ldp d14, d15, [sp], #16
;   ldr x25, [sp], #16
;   ldp fp, lr, [sp], #16
;   ret

