test compile precise-output
target riscv64

function %f(i64, i64) {
block0(v0: i64, v1: i64):
    v2 = load.i32 notrap aligned readonly v0
    v3 = ireduce.i32 v1
    v4 = icmp ult v2, v3
    trapz v4, user15
    return
}

; VCode:
; block0:
;   lw a0,0(a0)
;   slli a0,a0,32
;   srli a0,a0,32
;   slli a1,a1,32
;   srli a1,a1,32
;   trap_if user15##(a0 uge a1)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   lw a0, 0(a0)
;   slli a0, a0, 0x20
;   srli a0, a0, 0x20
;   slli a1, a1, 0x20
;   srli a1, a1, 0x20
;   bgeu a0, a1, 8
;   ret
;   .byte 0x00, 0x00, 0x00, 0x00 ; trap: user15

