test compile precise-output
set unwind_info=false
target riscv64 has_v

function %umin_i8(i8, i8) -> i8{
block0(v0: i8, v1: i8):
    v2 = umin v0, v1
    return v2
}

; VCode:
; block0:
;   andi a3,a0,255
;   andi a5,a1,255
;   select a0,a3,a5##condition=(a3 ult a5)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a3, a0, 0xff
;   andi a5, a1, 0xff
;   bgeu a3, a5, 0xc
;   mv a0, a3
;   j 8
;   mv a0, a5
;   ret

function %umin_i16(i16, i16) -> i16{
block0(v0: i16, v1: i16):
    v2 = umin v0, v1
    return v2
}

; VCode:
; block0:
;   slli a3,a0,48
;   srli a5,a3,48
;   slli a1,a1,48
;   srli a3,a1,48
;   select a0,a5,a3##condition=(a5 ult a3)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a3, a0, 0x30
;   srli a5, a3, 0x30
;   slli a1, a1, 0x30
;   srli a3, a1, 0x30
;   bgeu a5, a3, 0xc
;   mv a0, a5
;   j 8
;   mv a0, a3
;   ret

function %umin_i32(i32, i32) -> i32{
block0(v0: i32, v1: i32):
    v2 = umin v0, v1
    return v2
}

; VCode:
; block0:
;   slli a3,a0,32
;   srli a5,a3,32
;   slli a1,a1,32
;   srli a3,a1,32
;   select a0,a5,a3##condition=(a5 ult a3)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a3, a0, 0x20
;   srli a5, a3, 0x20
;   slli a1, a1, 0x20
;   srli a3, a1, 0x20
;   bgeu a5, a3, 0xc
;   mv a0, a5
;   j 8
;   mv a0, a3
;   ret

function %umin_i64(i64, i64) -> i64{
block0(v0: i64, v1: i64):
    v2 = umin v0, v1
    return v2
}

; VCode:
; block0:
;   select a0,a0,a1##condition=(a0 ult a1)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   bltu a0, a1, 8
;   mv a0, a1
;   ret

function %umin_i128(i128, i128) -> i128{
block0(v0: i128, v1: i128):
    v2 = umin v0, v1
    return v2
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-16
;   sd s7,8(sp)
;   sd s9,0(sp)
; block0:
;   sltu a5,a1,a3
;   sltu a4,a0,a2
;   mv s7,a0
;   xor a0,a1,a3
;   mv s9,a1
;   select a5,a4,a5##condition=(a0 eq zero)
;   mv a4,s7
;   select [a0,a1],[a4,s9],[a2,a3]##condition=(a5 ne zero)
;   ld s7,8(sp)
;   ld s9,0(sp)
;   addi sp,sp,16
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
;   addi sp, sp, -0x10
;   sd s7, 8(sp)
;   sd s9, 0(sp)
; block1: ; offset 0x1c
;   sltu a5, a1, a3
;   sltu a4, a0, a2
;   mv s7, a0
;   xor a0, a1, a3
;   mv s9, a1
;   bnez a0, 8
;   mv a5, a4
;   mv a4, s7
;   beqz a5, 0x10
;   mv a0, a4
;   mv a1, s9
;   j 0xc
;   mv a0, a2
;   mv a1, a3
;   ld s7, 8(sp)
;   ld s9, 0(sp)
;   addi sp, sp, 0x10
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

