test compile precise-output
set unwind_info=false
target riscv64


function %ushr_i8_const_i8(i8) -> i8 {
block0(v0: i8):
    v1 = iconst.i8 5
    v2 = ushr v0, v1
    return v2
}

; VCode:
; block0:
;   andi a0,a0,255
;   srliw a0,a0,5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a0, a0, 0xff
;   srliw a0, a0, 5
;   ret

function %ushr_i8_const_i16(i8) -> i8 {
block0(v0: i8):
    v1 = iconst.i16 5
    v2 = ushr v0, v1
    return v2
}

; VCode:
; block0:
;   andi a0,a0,255
;   srliw a0,a0,5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a0, a0, 0xff
;   srliw a0, a0, 5
;   ret

function %ushr_i8_const_i32(i8) -> i8 {
block0(v0: i8):
    v1 = iconst.i32 5
    v2 = ushr v0, v1
    return v2
}

; VCode:
; block0:
;   andi a0,a0,255
;   srliw a0,a0,5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a0, a0, 0xff
;   srliw a0, a0, 5
;   ret

function %ushr_i8_const_i64(i8) -> i8 {
block0(v0: i8):
    v1 = iconst.i64 5
    v2 = ushr v0, v1
    return v2
}

; VCode:
; block0:
;   andi a0,a0,255
;   srliw a0,a0,5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a0, a0, 0xff
;   srliw a0, a0, 5
;   ret

function %ushr_i8_const_i128(i8) -> i8 {
block0(v0: i8):
    v1 = iconst.i64 5
    v2 = uextend.i128 v1
    v3 = ushr v0, v2
    return v3
}

; VCode:
; block0:
;   andi a0,a0,255
;   srliw a0,a0,5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   andi a0, a0, 0xff
;   srliw a0, a0, 5
;   ret

function %ushr_i16_const_i8(i16) -> i16 {
block0(v0: i16):
    v1 = iconst.i8 5
    v2 = ushr v0, v1
    return v2
}

; VCode:
; block0:
;   slli a0,a0,48
;   srli a0,a0,48
;   srliw a0,a0,5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a0, a0, 0x30
;   srli a0, a0, 0x30
;   srliw a0, a0, 5
;   ret

function %ushr_i16_const_i16(i16) -> i16 {
block0(v0: i16):
    v1 = iconst.i16 5
    v2 = ushr v0, v1
    return v2
}

; VCode:
; block0:
;   slli a0,a0,48
;   srli a0,a0,48
;   srliw a0,a0,5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a0, a0, 0x30
;   srli a0, a0, 0x30
;   srliw a0, a0, 5
;   ret

function %ushr_i16_const_i32(i16) -> i16 {
block0(v0: i16):
    v1 = iconst.i32 5
    v2 = ushr v0, v1
    return v2
}

; VCode:
; block0:
;   slli a0,a0,48
;   srli a0,a0,48
;   srliw a0,a0,5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a0, a0, 0x30
;   srli a0, a0, 0x30
;   srliw a0, a0, 5
;   ret

function %ushr_i16_const_i64(i16) -> i16 {
block0(v0: i16):
    v1 = iconst.i64 5
    v2 = ushr v0, v1
    return v2
}

; VCode:
; block0:
;   slli a0,a0,48
;   srli a0,a0,48
;   srliw a0,a0,5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a0, a0, 0x30
;   srli a0, a0, 0x30
;   srliw a0, a0, 5
;   ret

function %ushr_i16_const_i128(i16) -> i16 {
block0(v0: i16):
    v1 = iconst.i64 5
    v2 = uextend.i128 v1
    v3 = ushr v0, v2
    return v3
}

; VCode:
; block0:
;   slli a0,a0,48
;   srli a0,a0,48
;   srliw a0,a0,5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   slli a0, a0, 0x30
;   srli a0, a0, 0x30
;   srliw a0, a0, 5
;   ret

function %ushr_i32_const_i8(i32) -> i32 {
block0(v0: i32):
    v1 = iconst.i8 5
    v2 = ushr v0, v1
    return v2
}

; VCode:
; block0:
;   srliw a0,a0,5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   srliw a0, a0, 5
;   ret

function %ushr_i32_const_i16(i32) -> i32 {
block0(v0: i32):
    v1 = iconst.i16 5
    v2 = ushr v0, v1
    return v2
}

; VCode:
; block0:
;   srliw a0,a0,5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   srliw a0, a0, 5
;   ret

function %ushr_i32_const_i32(i32) -> i32 {
block0(v0: i32):
    v1 = iconst.i32 5
    v2 = ushr v0, v1
    return v2
}

; VCode:
; block0:
;   srliw a0,a0,5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   srliw a0, a0, 5
;   ret

function %ushr_i32_const_i64(i32) -> i32 {
block0(v0: i32):
    v1 = iconst.i64 5
    v2 = ushr v0, v1
    return v2
}

; VCode:
; block0:
;   srliw a0,a0,5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   srliw a0, a0, 5
;   ret

function %ushr_i32_const_i128(i32) -> i32 {
block0(v0: i32):
    v1 = iconst.i64 5
    v2 = uextend.i128 v1
    v3 = ushr v0, v2
    return v3
}

; VCode:
; block0:
;   srliw a0,a0,5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   srliw a0, a0, 5
;   ret

function %ushr_i64_const_i8(i64) -> i64 {
block0(v0: i64):
    v1 = iconst.i8 5
    v2 = ushr v0, v1
    return v2
}

; VCode:
; block0:
;   srli a0,a0,5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   srli a0, a0, 5
;   ret

function %ushr_i64_const_i16(i64) -> i64 {
block0(v0: i64):
    v1 = iconst.i16 5
    v2 = ushr v0, v1
    return v2
}

; VCode:
; block0:
;   srli a0,a0,5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   srli a0, a0, 5
;   ret

function %ushr_i64_const_i32(i64) -> i64 {
block0(v0: i64):
    v1 = iconst.i32 5
    v2 = ushr v0, v1
    return v2
}

; VCode:
; block0:
;   srli a0,a0,5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   srli a0, a0, 5
;   ret

function %ushr_i64_const_i64(i64) -> i64 {
block0(v0: i64):
    v1 = iconst.i64 5
    v2 = ushr v0, v1
    return v2
}

; VCode:
; block0:
;   srli a0,a0,5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   srli a0, a0, 5
;   ret

function %ushr_i64_const_i128(i64) -> i64 {
block0(v0: i64):
    v1 = iconst.i64 5
    v2 = uextend.i128 v1
    v3 = ushr v0, v2
    return v3
}

; VCode:
; block0:
;   srli a0,a0,5
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   srli a0, a0, 5
;   ret

function %ushr_i128_const_i8(i128) -> i128 {
block0(v0: i128):
    v1 = iconst.i8 5
    v2 = ushr v0, v1
    return v2
}

; VCode:
; block0:
;   mv a3,a0
;   li a5,5
;   andi a0,a5,63
;   li a2,64
;   sub a2,a2,a0
;   sll a2,a1,a2
;   select a2,zero,a2##condition=(a0 eq zero)
;   srl a4,a3,a0
;   or a3,a2,a4
;   li a2,64
;   srl a4,a1,a0
;   andi a5,a5,127
;   select [a0,a1],[a4,zero],[a3,a4]##condition=(a5 uge a2)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mv a3, a0
;   addi a5, zero, 5
;   andi a0, a5, 0x3f
;   addi a2, zero, 0x40
;   sub a2, a2, a0
;   sll a2, a1, a2
;   bnez a0, 8
;   mv a2, zero
;   srl a4, a3, a0
;   or a3, a2, a4
;   addi a2, zero, 0x40
;   srl a4, a1, a0
;   andi a5, a5, 0x7f
;   mv a0, a4
;   mv a1, zero
;   bgeu a5, a2, 0xc
;   mv a0, a3
;   mv a1, a4
;   ret

function %ushr_i128_const_i16(i128) -> i128 {
block0(v0: i128):
    v1 = iconst.i16 5
    v2 = ushr v0, v1
    return v2
}

; VCode:
; block0:
;   mv a3,a0
;   li a5,5
;   andi a0,a5,63
;   li a2,64
;   sub a2,a2,a0
;   sll a2,a1,a2
;   select a2,zero,a2##condition=(a0 eq zero)
;   srl a4,a3,a0
;   or a3,a2,a4
;   li a2,64
;   srl a4,a1,a0
;   andi a5,a5,127
;   select [a0,a1],[a4,zero],[a3,a4]##condition=(a5 uge a2)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mv a3, a0
;   addi a5, zero, 5
;   andi a0, a5, 0x3f
;   addi a2, zero, 0x40
;   sub a2, a2, a0
;   sll a2, a1, a2
;   bnez a0, 8
;   mv a2, zero
;   srl a4, a3, a0
;   or a3, a2, a4
;   addi a2, zero, 0x40
;   srl a4, a1, a0
;   andi a5, a5, 0x7f
;   mv a0, a4
;   mv a1, zero
;   bgeu a5, a2, 0xc
;   mv a0, a3
;   mv a1, a4
;   ret

function %ushr_i128_const_i32(i128) -> i128 {
block0(v0: i128):
    v1 = iconst.i32 5
    v2 = ushr v0, v1
    return v2
}

; VCode:
; block0:
;   mv a3,a0
;   li a5,5
;   andi a0,a5,63
;   li a2,64
;   sub a2,a2,a0
;   sll a2,a1,a2
;   select a2,zero,a2##condition=(a0 eq zero)
;   srl a4,a3,a0
;   or a3,a2,a4
;   li a2,64
;   srl a4,a1,a0
;   andi a5,a5,127
;   select [a0,a1],[a4,zero],[a3,a4]##condition=(a5 uge a2)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mv a3, a0
;   addi a5, zero, 5
;   andi a0, a5, 0x3f
;   addi a2, zero, 0x40
;   sub a2, a2, a0
;   sll a2, a1, a2
;   bnez a0, 8
;   mv a2, zero
;   srl a4, a3, a0
;   or a3, a2, a4
;   addi a2, zero, 0x40
;   srl a4, a1, a0
;   andi a5, a5, 0x7f
;   mv a0, a4
;   mv a1, zero
;   bgeu a5, a2, 0xc
;   mv a0, a3
;   mv a1, a4
;   ret

function %ushr_i128_const_i64(i128) -> i128 {
block0(v0: i128):
    v1 = iconst.i64 5
    v2 = ushr v0, v1
    return v2
}

; VCode:
; block0:
;   mv a3,a0
;   li a5,5
;   andi a0,a5,63
;   li a2,64
;   sub a2,a2,a0
;   sll a2,a1,a2
;   select a2,zero,a2##condition=(a0 eq zero)
;   srl a4,a3,a0
;   or a3,a2,a4
;   li a2,64
;   srl a4,a1,a0
;   andi a5,a5,127
;   select [a0,a1],[a4,zero],[a3,a4]##condition=(a5 uge a2)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mv a3, a0
;   addi a5, zero, 5
;   andi a0, a5, 0x3f
;   addi a2, zero, 0x40
;   sub a2, a2, a0
;   sll a2, a1, a2
;   bnez a0, 8
;   mv a2, zero
;   srl a4, a3, a0
;   or a3, a2, a4
;   addi a2, zero, 0x40
;   srl a4, a1, a0
;   andi a5, a5, 0x7f
;   mv a0, a4
;   mv a1, zero
;   bgeu a5, a2, 0xc
;   mv a0, a3
;   mv a1, a4
;   ret

function %ushr_i128_const_i128(i128) -> i128 {
block0(v0: i128):
    v1 = iconst.i64 5
    v2 = uextend.i128 v1
    v3 = ushr v0, v2
    return v3
}

; VCode:
; block0:
;   mv a4,a0
;   li a0,5
;   li a2,0
;   andi a2,a0,63
;   li a3,64
;   sub a3,a3,a2
;   sll a3,a1,a3
;   select a3,zero,a3##condition=(a2 eq zero)
;   srl a5,a4,a2
;   or a4,a3,a5
;   li a3,64
;   srl a2,a1,a2
;   andi a5,a0,127
;   select [a0,a1],[a2,zero],[a4,a2]##condition=(a5 uge a3)
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   mv a4, a0
;   addi a0, zero, 5
;   mv a2, zero
;   andi a2, a0, 0x3f
;   addi a3, zero, 0x40
;   sub a3, a3, a2
;   sll a3, a1, a3
;   bnez a2, 8
;   mv a3, zero
;   srl a5, a4, a2
;   or a4, a3, a5
;   addi a3, zero, 0x40
;   srl a2, a1, a2
;   andi a5, a0, 0x7f
;   mv a0, a2
;   mv a1, zero
;   bgeu a5, a3, 0xc
;   mv a0, a4
;   mv a1, a2
;   ret

