test compile precise-output
set enable_multi_ret_implicit_sret
set unwind_info=false
target riscv64 has_zfa has_zfhmin has_zfh


function %fminm_s(f32, f32) -> f32 {
block0(v0: f32, v1: f32):
  v2 = fmin.f32 v0, v1
  return v2
}

; VCode:
; block0:
;   fminm.s fa0,fa0,fa1,rdn
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x53, 0x25, 0xb5, 0x28
;   ret


function %fminm_d(f64, f64) -> f64 {
block0(v0: f64, v1: f64):
  v2 = fmin.f64 v0, v1
  return v2
}

; VCode:
; block0:
;   fminm.d fa0,fa0,fa1,rdn
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x53, 0x25, 0xb5, 0x2a
;   ret

function %fmaxm_s(f32, f32) -> f32 {
block0(v0: f32, v1: f32):
  v2 = fmax.f32 v0, v1
  return v2
}

; VCode:
; block0:
;   fmaxm.s fa0,fa0,fa1,rup
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x53, 0x35, 0xb5, 0x28
;   ret

function %fmaxm_d(f64, f64) -> f64 {
block0(v0: f64, v1: f64):
  v2 = fmax.f64 v0, v1
  return v2
}

; VCode:
; block0:
;   fmaxm.d fa0,fa0,fa1,rup
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x53, 0x35, 0xb5, 0x2a
;   ret



function %ceil_f32(f32) -> f32 {
block0(v0: f32):
  v1 = ceil v0
  return v1
}

; VCode:
; block0:
;   fround.s fa0,fa0,rup
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x53, 0x35, 0x45, 0x40
;   ret


function %ceil_f64(f64) -> f64 {
block0(v0: f64):
  v1 = ceil v0
  return v1
}

; VCode:
; block0:
;   fround.d fa0,fa0,rup
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x53, 0x35, 0x45, 0x42
;   ret


function %floor_f32(f32) -> f32 {
block0(v0: f32):
  v1 = floor v0
  return v1
}

; VCode:
; block0:
;   fround.s fa0,fa0,rdn
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x53, 0x25, 0x45, 0x40
;   ret


function %floor_f64(f64) -> f64 {
block0(v0: f64):
  v1 = floor v0
  return v1
}

; VCode:
; block0:
;   fround.d fa0,fa0,rdn
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x53, 0x25, 0x45, 0x42
;   ret


function %trunc_f32(f32) -> f32 {
block0(v0: f32):
  v1 = trunc v0
  return v1
}

; VCode:
; block0:
;   fround.s fa0,fa0,rtz
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x53, 0x15, 0x45, 0x40
;   ret


function %trunc_f64(f64) -> f64 {
block0(v0: f64):
  v1 = trunc v0
  return v1
}

; VCode:
; block0:
;   fround.d fa0,fa0,rtz
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x53, 0x15, 0x45, 0x42
;   ret


function %nearest_f32(f32) -> f32 {
block0(v0: f32):
  v1 = nearest v0
  return v1
}

; VCode:
; block0:
;   fround.s fa0,fa0,rne
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x53, 0x05, 0x45, 0x40
;   ret


function %nearest_f64(f64) -> f64 {
block0(v0: f64):
  v1 = nearest v0
  return v1
}

; VCode:
; block0:
;   fround.d fa0,fa0,rne
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x53, 0x05, 0x45, 0x42
;   ret


function %fli_h() -> f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16 {
block0:
    v0 = f16const -0x1.p0
    v1 = f16const 0x1.p-14
    v2 = f16const 0x1.p-16
    v3 = f16const 0x1.p-15
    v4 = f16const 0x1.p-8
    v5 = f16const 0x1.p-7
    v6 = f16const 0x1.p-4
    v7 = f16const 0x1.p-3
    v8 = f16const 0x1.p-2
    v9 = f16const 0x1.4p-2
    v10 = f16const 0x1.8p-2
    v11 = f16const 0x1.cp-2
    v12 = f16const 0x1.p-1
    v13 = f16const 0x1.4p-1
    v14 = f16const 0x1.8p-1
    v15 = f16const 0x1.cp-1
    v16 = f16const 0x1.p0
    v17 = f16const 0x1.4p0
    v18 = f16const 0x1.8p0
    v19 = f16const 0x1.cp0
    v20 = f16const 0x1.p1
    v21 = f16const 0x1.4p1
    v22 = f16const 0x1.8p1
    v23 = f16const 0x1.p2
    v24 = f16const 0x1.p3
    v25 = f16const 0x1.p4
    v26 = f16const 0x1.p7
    v27 = f16const 0x1.p8
    v28 = f16const 0x1.p15
    v29 = f16const +Inf
    v30 = f16const +NaN

    return v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, v27, v28, v29, v30
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-96
;   fsd fs0,88(sp)
;   fsd fs2,80(sp)
;   fsd fs3,72(sp)
;   fsd fs4,64(sp)
;   fsd fs5,56(sp)
;   fsd fs6,48(sp)
;   fsd fs7,40(sp)
;   fsd fs8,32(sp)
;   fsd fs9,24(sp)
;   fsd fs10,16(sp)
;   fsd fs11,8(sp)
; block0:
;   fli.h fa0,-1.0
;   fli.h fa1,min
;   fli.h fa2,2^-16
;   fli.h fa3,2^-15
;   fli.h fa4,2^-8
;   fli.h fa5,2^-7
;   fli.h ft0,0.0625
;   fli.h ft1,0.125
;   fli.h ft2,0.25
;   fli.h ft3,0.3125
;   fli.h ft4,0.375
;   fli.h ft5,0.4375
;   fli.h ft6,0.5
;   fli.h ft7,0.625
;   fli.h fs0,0.75
;   fli.h fs1,0.875
;   fli.h fa6,1.0
;   fli.h fa7,1.25
;   fli.h fs2,1.5
;   fli.h fs3,1.75
;   fli.h fs4,2.0
;   fli.h fs5,2.5
;   fli.h fs6,3.0
;   fli.h fs7,4.0
;   fli.h fs8,8.0
;   fli.h fs9,16.0
;   fli.h fs10,128.0
;   fli.h fs11,256.0
;   fli.h ft8,32768.0
;   fli.h ft9,inf
;   fli.h ft10,nan
;   fsh fa2,0(a0)
;   fsh fa3,8(a0)
;   fsh fa4,16(a0)
;   fsh fa5,24(a0)
;   fsh ft0,32(a0)
;   fsh ft1,40(a0)
;   fsh ft2,48(a0)
;   fsh ft3,56(a0)
;   fsh ft4,64(a0)
;   fsh ft5,72(a0)
;   fsh ft6,80(a0)
;   fsh ft7,88(a0)
;   fsh fs0,96(a0)
;   fsh fs1,104(a0)
;   fsh fa6,112(a0)
;   fsh fa7,120(a0)
;   fsh fs2,128(a0)
;   fsh fs3,136(a0)
;   fsh fs4,144(a0)
;   fsh fs5,152(a0)
;   fsh fs6,160(a0)
;   fsh fs7,168(a0)
;   fsh fs8,176(a0)
;   fsh fs9,184(a0)
;   fsh fs10,192(a0)
;   fsh fs11,200(a0)
;   fsh ft8,208(a0)
;   fsh ft9,216(a0)
;   fsh ft10,224(a0)
;   fld fs0,88(sp)
;   fld fs2,80(sp)
;   fld fs3,72(sp)
;   fld fs4,64(sp)
;   fld fs5,56(sp)
;   fld fs6,48(sp)
;   fld fs7,40(sp)
;   fld fs8,32(sp)
;   fld fs9,24(sp)
;   fld fs10,16(sp)
;   fld fs11,8(sp)
;   addi sp,sp,96
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
;   addi sp, sp, -0x60
;   fsd fs0, 0x58(sp)
;   fsd fs2, 0x50(sp)
;   fsd fs3, 0x48(sp)
;   fsd fs4, 0x40(sp)
;   fsd fs5, 0x38(sp)
;   fsd fs6, 0x30(sp)
;   fsd fs7, 0x28(sp)
;   fsd fs8, 0x20(sp)
;   fsd fs9, 0x18(sp)
;   fsd fs10, 0x10(sp)
;   fsd fs11, 8(sp)
; block1: ; offset 0x40
;   .byte 0x53, 0x05, 0x10, 0xf4
;   .byte 0xd3, 0x85, 0x10, 0xf4
;   .byte 0x53, 0x06, 0x11, 0xf4
;   .byte 0xd3, 0x86, 0x11, 0xf4
;   .byte 0x53, 0x07, 0x12, 0xf4
;   .byte 0xd3, 0x87, 0x12, 0xf4
;   .byte 0x53, 0x00, 0x13, 0xf4
;   .byte 0xd3, 0x80, 0x13, 0xf4
;   .byte 0x53, 0x01, 0x14, 0xf4
;   .byte 0xd3, 0x81, 0x14, 0xf4
;   .byte 0x53, 0x02, 0x15, 0xf4
;   .byte 0xd3, 0x82, 0x15, 0xf4
;   .byte 0x53, 0x03, 0x16, 0xf4
;   .byte 0xd3, 0x83, 0x16, 0xf4
;   .byte 0x53, 0x04, 0x17, 0xf4
;   .byte 0xd3, 0x84, 0x17, 0xf4
;   .byte 0x53, 0x08, 0x18, 0xf4
;   .byte 0xd3, 0x88, 0x18, 0xf4
;   .byte 0x53, 0x09, 0x19, 0xf4
;   .byte 0xd3, 0x89, 0x19, 0xf4
;   .byte 0x53, 0x0a, 0x1a, 0xf4
;   .byte 0xd3, 0x8a, 0x1a, 0xf4
;   .byte 0x53, 0x0b, 0x1b, 0xf4
;   .byte 0xd3, 0x8b, 0x1b, 0xf4
;   .byte 0x53, 0x0c, 0x1c, 0xf4
;   .byte 0xd3, 0x8c, 0x1c, 0xf4
;   .byte 0x53, 0x0d, 0x1d, 0xf4
;   .byte 0xd3, 0x8d, 0x1d, 0xf4
;   .byte 0x53, 0x0e, 0x1e, 0xf4
;   .byte 0xd3, 0x0e, 0x1f, 0xf4
;   .byte 0x53, 0x8f, 0x1f, 0xf4
;   .byte 0x27, 0x10, 0xc5, 0x00
;   .byte 0x27, 0x14, 0xd5, 0x00
;   .byte 0x27, 0x18, 0xe5, 0x00
;   .byte 0x27, 0x1c, 0xf5, 0x00
;   .byte 0x27, 0x10, 0x05, 0x02
;   .byte 0x27, 0x14, 0x15, 0x02
;   .byte 0x27, 0x18, 0x25, 0x02
;   .byte 0x27, 0x1c, 0x35, 0x02
;   .byte 0x27, 0x10, 0x45, 0x04
;   .byte 0x27, 0x14, 0x55, 0x04
;   .byte 0x27, 0x18, 0x65, 0x04
;   .byte 0x27, 0x1c, 0x75, 0x04
;   .byte 0x27, 0x10, 0x85, 0x06
;   .byte 0x27, 0x14, 0x95, 0x06
;   .byte 0x27, 0x18, 0x05, 0x07
;   .byte 0x27, 0x1c, 0x15, 0x07
;   .byte 0x27, 0x10, 0x25, 0x09
;   .byte 0x27, 0x14, 0x35, 0x09
;   .byte 0x27, 0x18, 0x45, 0x09
;   .byte 0x27, 0x1c, 0x55, 0x09
;   .byte 0x27, 0x10, 0x65, 0x0b
;   .byte 0x27, 0x14, 0x75, 0x0b
;   .byte 0x27, 0x18, 0x85, 0x0b
;   .byte 0x27, 0x1c, 0x95, 0x0b
;   .byte 0x27, 0x10, 0xa5, 0x0d
;   .byte 0x27, 0x14, 0xb5, 0x0d
;   .byte 0x27, 0x18, 0xc5, 0x0d
;   .byte 0x27, 0x1c, 0xd5, 0x0d
;   .byte 0x27, 0x10, 0xe5, 0x0f
;   fld fs0, 0x58(sp)
;   fld fs2, 0x50(sp)
;   fld fs3, 0x48(sp)
;   fld fs4, 0x40(sp)
;   fld fs5, 0x38(sp)
;   fld fs6, 0x30(sp)
;   fld fs7, 0x28(sp)
;   fld fs8, 0x20(sp)
;   fld fs9, 0x18(sp)
;   fld fs10, 0x10(sp)
;   fld fs11, 8(sp)
;   addi sp, sp, 0x60
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

function %fli_s() -> f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32 {
block0:
    v0 = f32const -0x1.p0
    v1 = f32const 0x1.p-126
    v2 = f32const 0x1.p-16
    v3 = f32const 0x1.p-15
    v4 = f32const 0x1.p-8
    v5 = f32const 0x1.p-7
    v6 = f32const 0x1.p-4
    v7 = f32const 0x1.p-3
    v8 = f32const 0x1.p-2
    v9 = f32const 0x1.4p-2
    v10 = f32const 0x1.8p-2
    v11 = f32const 0x1.cp-2
    v12 = f32const 0x1.p-1
    v13 = f32const 0x1.4p-1
    v14 = f32const 0x1.8p-1
    v15 = f32const 0x1.cp-1
    v16 = f32const 0x1.p0
    v17 = f32const 0x1.4p0
    v18 = f32const 0x1.8p0
    v19 = f32const 0x1.cp0
    v20 = f32const 0x1.p1
    v21 = f32const 0x1.4p1
    v22 = f32const 0x1.8p1
    v23 = f32const 0x1.p2
    v24 = f32const 0x1.p3
    v25 = f32const 0x1.p4
    v26 = f32const 0x1.p7
    v27 = f32const 0x1.p8
    v28 = f32const 0x1.p15
    v29 = f32const 0x1.p16
    v30 = f32const +Inf
    v31 = f32const +NaN

    return v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, v27, v28, v29, v30, v31
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-96
;   fsd fs0,88(sp)
;   fsd fs2,80(sp)
;   fsd fs3,72(sp)
;   fsd fs4,64(sp)
;   fsd fs5,56(sp)
;   fsd fs6,48(sp)
;   fsd fs7,40(sp)
;   fsd fs8,32(sp)
;   fsd fs9,24(sp)
;   fsd fs10,16(sp)
;   fsd fs11,8(sp)
; block0:
;   fli.s fa0,-1.0
;   fli.s fa1,min
;   fli.s fa2,2^-16
;   fli.s fa3,2^-15
;   fli.s fa4,2^-8
;   fli.s fa5,2^-7
;   fli.s ft0,0.0625
;   fli.s ft1,0.125
;   fli.s ft2,0.25
;   fli.s ft3,0.3125
;   fli.s ft4,0.375
;   fli.s ft5,0.4375
;   fli.s ft6,0.5
;   fli.s ft7,0.625
;   fli.s fs0,0.75
;   fli.s fs1,0.875
;   fli.s fa6,1.0
;   fli.s fa7,1.25
;   fli.s fs2,1.5
;   fli.s fs3,1.75
;   fli.s fs4,2.0
;   fli.s fs5,2.5
;   fli.s fs6,3.0
;   fli.s fs7,4.0
;   fli.s fs8,8.0
;   fli.s fs9,16.0
;   fli.s fs10,128.0
;   fli.s fs11,256.0
;   fli.s ft8,32768.0
;   fli.s ft9,65536.0
;   fli.s ft10,inf
;   fli.s ft11,nan
;   fsw fa2,0(a0)
;   fsw fa3,8(a0)
;   fsw fa4,16(a0)
;   fsw fa5,24(a0)
;   fsw ft0,32(a0)
;   fsw ft1,40(a0)
;   fsw ft2,48(a0)
;   fsw ft3,56(a0)
;   fsw ft4,64(a0)
;   fsw ft5,72(a0)
;   fsw ft6,80(a0)
;   fsw ft7,88(a0)
;   fsw fs0,96(a0)
;   fsw fs1,104(a0)
;   fsw fa6,112(a0)
;   fsw fa7,120(a0)
;   fsw fs2,128(a0)
;   fsw fs3,136(a0)
;   fsw fs4,144(a0)
;   fsw fs5,152(a0)
;   fsw fs6,160(a0)
;   fsw fs7,168(a0)
;   fsw fs8,176(a0)
;   fsw fs9,184(a0)
;   fsw fs10,192(a0)
;   fsw fs11,200(a0)
;   fsw ft8,208(a0)
;   fsw ft9,216(a0)
;   fsw ft10,224(a0)
;   fsw ft11,232(a0)
;   fld fs0,88(sp)
;   fld fs2,80(sp)
;   fld fs3,72(sp)
;   fld fs4,64(sp)
;   fld fs5,56(sp)
;   fld fs6,48(sp)
;   fld fs7,40(sp)
;   fld fs8,32(sp)
;   fld fs9,24(sp)
;   fld fs10,16(sp)
;   fld fs11,8(sp)
;   addi sp,sp,96
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
;   addi sp, sp, -0x60
;   fsd fs0, 0x58(sp)
;   fsd fs2, 0x50(sp)
;   fsd fs3, 0x48(sp)
;   fsd fs4, 0x40(sp)
;   fsd fs5, 0x38(sp)
;   fsd fs6, 0x30(sp)
;   fsd fs7, 0x28(sp)
;   fsd fs8, 0x20(sp)
;   fsd fs9, 0x18(sp)
;   fsd fs10, 0x10(sp)
;   fsd fs11, 8(sp)
; block1: ; offset 0x40
;   .byte 0x53, 0x05, 0x10, 0xf0
;   .byte 0xd3, 0x85, 0x10, 0xf0
;   .byte 0x53, 0x06, 0x11, 0xf0
;   .byte 0xd3, 0x86, 0x11, 0xf0
;   .byte 0x53, 0x07, 0x12, 0xf0
;   .byte 0xd3, 0x87, 0x12, 0xf0
;   .byte 0x53, 0x00, 0x13, 0xf0
;   .byte 0xd3, 0x80, 0x13, 0xf0
;   .byte 0x53, 0x01, 0x14, 0xf0
;   .byte 0xd3, 0x81, 0x14, 0xf0
;   .byte 0x53, 0x02, 0x15, 0xf0
;   .byte 0xd3, 0x82, 0x15, 0xf0
;   .byte 0x53, 0x03, 0x16, 0xf0
;   .byte 0xd3, 0x83, 0x16, 0xf0
;   .byte 0x53, 0x04, 0x17, 0xf0
;   .byte 0xd3, 0x84, 0x17, 0xf0
;   .byte 0x53, 0x08, 0x18, 0xf0
;   .byte 0xd3, 0x88, 0x18, 0xf0
;   .byte 0x53, 0x09, 0x19, 0xf0
;   .byte 0xd3, 0x89, 0x19, 0xf0
;   .byte 0x53, 0x0a, 0x1a, 0xf0
;   .byte 0xd3, 0x8a, 0x1a, 0xf0
;   .byte 0x53, 0x0b, 0x1b, 0xf0
;   .byte 0xd3, 0x8b, 0x1b, 0xf0
;   .byte 0x53, 0x0c, 0x1c, 0xf0
;   .byte 0xd3, 0x8c, 0x1c, 0xf0
;   .byte 0x53, 0x0d, 0x1d, 0xf0
;   .byte 0xd3, 0x8d, 0x1d, 0xf0
;   .byte 0x53, 0x0e, 0x1e, 0xf0
;   .byte 0xd3, 0x8e, 0x1e, 0xf0
;   .byte 0x53, 0x0f, 0x1f, 0xf0
;   .byte 0xd3, 0x8f, 0x1f, 0xf0
;   fsw fa2, 0(a0)
;   fsw fa3, 8(a0)
;   fsw fa4, 0x10(a0)
;   fsw fa5, 0x18(a0)
;   fsw ft0, 0x20(a0)
;   fsw ft1, 0x28(a0)
;   fsw ft2, 0x30(a0)
;   fsw ft3, 0x38(a0)
;   fsw ft4, 0x40(a0)
;   fsw ft5, 0x48(a0)
;   fsw ft6, 0x50(a0)
;   fsw ft7, 0x58(a0)
;   fsw fs0, 0x60(a0)
;   fsw fs1, 0x68(a0)
;   fsw fa6, 0x70(a0)
;   fsw fa7, 0x78(a0)
;   fsw fs2, 0x80(a0)
;   fsw fs3, 0x88(a0)
;   fsw fs4, 0x90(a0)
;   fsw fs5, 0x98(a0)
;   fsw fs6, 0xa0(a0)
;   fsw fs7, 0xa8(a0)
;   fsw fs8, 0xb0(a0)
;   fsw fs9, 0xb8(a0)
;   fsw fs10, 0xc0(a0)
;   fsw fs11, 0xc8(a0)
;   fsw ft8, 0xd0(a0)
;   fsw ft9, 0xd8(a0)
;   fsw ft10, 0xe0(a0)
;   fsw ft11, 0xe8(a0)
;   fld fs0, 0x58(sp)
;   fld fs2, 0x50(sp)
;   fld fs3, 0x48(sp)
;   fld fs4, 0x40(sp)
;   fld fs5, 0x38(sp)
;   fld fs6, 0x30(sp)
;   fld fs7, 0x28(sp)
;   fld fs8, 0x20(sp)
;   fld fs9, 0x18(sp)
;   fld fs10, 0x10(sp)
;   fld fs11, 8(sp)
;   addi sp, sp, 0x60
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

function %fli_d() -> f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 {
block0:
    v0 = f64const -0x1.p0
    v1 = f64const 0x1.p-1022
    v2 = f64const 0x1.p-16
    v3 = f64const 0x1.p-15
    v4 = f64const 0x1.p-8
    v5 = f64const 0x1.p-7
    v6 = f64const 0x1.p-4
    v7 = f64const 0x1.p-3
    v8 = f64const 0x1.p-2
    v9 = f64const 0x1.4p-2
    v10 = f64const 0x1.8p-2
    v11 = f64const 0x1.cp-2
    v12 = f64const 0x1.p-1
    v13 = f64const 0x1.4p-1
    v14 = f64const 0x1.8p-1
    v15 = f64const 0x1.cp-1
    v16 = f64const 0x1.p0
    v17 = f64const 0x1.4p0
    v18 = f64const 0x1.8p0
    v19 = f64const 0x1.cp0
    v20 = f64const 0x1.p1
    v21 = f64const 0x1.4p1
    v22 = f64const 0x1.8p1
    v23 = f64const 0x1.p2
    v24 = f64const 0x1.p3
    v25 = f64const 0x1.p4
    v26 = f64const 0x1.p7
    v27 = f64const 0x1.p8
    v28 = f64const 0x1.p15
    v29 = f64const 0x1.p16
    v30 = f64const +Inf
    v31 = f64const +NaN
    return v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, v27, v28, v29, v30, v31
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-96
;   fsd fs0,88(sp)
;   fsd fs2,80(sp)
;   fsd fs3,72(sp)
;   fsd fs4,64(sp)
;   fsd fs5,56(sp)
;   fsd fs6,48(sp)
;   fsd fs7,40(sp)
;   fsd fs8,32(sp)
;   fsd fs9,24(sp)
;   fsd fs10,16(sp)
;   fsd fs11,8(sp)
; block0:
;   fli.d fa0,-1.0
;   fli.d fa1,min
;   fli.d fa2,2^-16
;   fli.d fa3,2^-15
;   fli.d fa4,2^-8
;   fli.d fa5,2^-7
;   fli.d ft0,0.0625
;   fli.d ft1,0.125
;   fli.d ft2,0.25
;   fli.d ft3,0.3125
;   fli.d ft4,0.375
;   fli.d ft5,0.4375
;   fli.d ft6,0.5
;   fli.d ft7,0.625
;   fli.d fs0,0.75
;   fli.d fs1,0.875
;   fli.d fa6,1.0
;   fli.d fa7,1.25
;   fli.d fs2,1.5
;   fli.d fs3,1.75
;   fli.d fs4,2.0
;   fli.d fs5,2.5
;   fli.d fs6,3.0
;   fli.d fs7,4.0
;   fli.d fs8,8.0
;   fli.d fs9,16.0
;   fli.d fs10,128.0
;   fli.d fs11,256.0
;   fli.d ft8,32768.0
;   fli.d ft9,65536.0
;   fli.d ft10,inf
;   fli.d ft11,nan
;   fsd fa2,0(a0)
;   fsd fa3,8(a0)
;   fsd fa4,16(a0)
;   fsd fa5,24(a0)
;   fsd ft0,32(a0)
;   fsd ft1,40(a0)
;   fsd ft2,48(a0)
;   fsd ft3,56(a0)
;   fsd ft4,64(a0)
;   fsd ft5,72(a0)
;   fsd ft6,80(a0)
;   fsd ft7,88(a0)
;   fsd fs0,96(a0)
;   fsd fs1,104(a0)
;   fsd fa6,112(a0)
;   fsd fa7,120(a0)
;   fsd fs2,128(a0)
;   fsd fs3,136(a0)
;   fsd fs4,144(a0)
;   fsd fs5,152(a0)
;   fsd fs6,160(a0)
;   fsd fs7,168(a0)
;   fsd fs8,176(a0)
;   fsd fs9,184(a0)
;   fsd fs10,192(a0)
;   fsd fs11,200(a0)
;   fsd ft8,208(a0)
;   fsd ft9,216(a0)
;   fsd ft10,224(a0)
;   fsd ft11,232(a0)
;   fld fs0,88(sp)
;   fld fs2,80(sp)
;   fld fs3,72(sp)
;   fld fs4,64(sp)
;   fld fs5,56(sp)
;   fld fs6,48(sp)
;   fld fs7,40(sp)
;   fld fs8,32(sp)
;   fld fs9,24(sp)
;   fld fs10,16(sp)
;   fld fs11,8(sp)
;   addi sp,sp,96
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
;   addi sp, sp, -0x60
;   fsd fs0, 0x58(sp)
;   fsd fs2, 0x50(sp)
;   fsd fs3, 0x48(sp)
;   fsd fs4, 0x40(sp)
;   fsd fs5, 0x38(sp)
;   fsd fs6, 0x30(sp)
;   fsd fs7, 0x28(sp)
;   fsd fs8, 0x20(sp)
;   fsd fs9, 0x18(sp)
;   fsd fs10, 0x10(sp)
;   fsd fs11, 8(sp)
; block1: ; offset 0x40
;   .byte 0x53, 0x05, 0x10, 0xf2
;   .byte 0xd3, 0x85, 0x10, 0xf2
;   .byte 0x53, 0x06, 0x11, 0xf2
;   .byte 0xd3, 0x86, 0x11, 0xf2
;   .byte 0x53, 0x07, 0x12, 0xf2
;   .byte 0xd3, 0x87, 0x12, 0xf2
;   .byte 0x53, 0x00, 0x13, 0xf2
;   .byte 0xd3, 0x80, 0x13, 0xf2
;   .byte 0x53, 0x01, 0x14, 0xf2
;   .byte 0xd3, 0x81, 0x14, 0xf2
;   .byte 0x53, 0x02, 0x15, 0xf2
;   .byte 0xd3, 0x82, 0x15, 0xf2
;   .byte 0x53, 0x03, 0x16, 0xf2
;   .byte 0xd3, 0x83, 0x16, 0xf2
;   .byte 0x53, 0x04, 0x17, 0xf2
;   .byte 0xd3, 0x84, 0x17, 0xf2
;   .byte 0x53, 0x08, 0x18, 0xf2
;   .byte 0xd3, 0x88, 0x18, 0xf2
;   .byte 0x53, 0x09, 0x19, 0xf2
;   .byte 0xd3, 0x89, 0x19, 0xf2
;   .byte 0x53, 0x0a, 0x1a, 0xf2
;   .byte 0xd3, 0x8a, 0x1a, 0xf2
;   .byte 0x53, 0x0b, 0x1b, 0xf2
;   .byte 0xd3, 0x8b, 0x1b, 0xf2
;   .byte 0x53, 0x0c, 0x1c, 0xf2
;   .byte 0xd3, 0x8c, 0x1c, 0xf2
;   .byte 0x53, 0x0d, 0x1d, 0xf2
;   .byte 0xd3, 0x8d, 0x1d, 0xf2
;   .byte 0x53, 0x0e, 0x1e, 0xf2
;   .byte 0xd3, 0x8e, 0x1e, 0xf2
;   .byte 0x53, 0x0f, 0x1f, 0xf2
;   .byte 0xd3, 0x8f, 0x1f, 0xf2
;   fsd fa2, 0(a0)
;   fsd fa3, 8(a0)
;   fsd fa4, 0x10(a0)
;   fsd fa5, 0x18(a0)
;   fsd ft0, 0x20(a0)
;   fsd ft1, 0x28(a0)
;   fsd ft2, 0x30(a0)
;   fsd ft3, 0x38(a0)
;   fsd ft4, 0x40(a0)
;   fsd ft5, 0x48(a0)
;   fsd ft6, 0x50(a0)
;   fsd ft7, 0x58(a0)
;   fsd fs0, 0x60(a0)
;   fsd fs1, 0x68(a0)
;   fsd fa6, 0x70(a0)
;   fsd fa7, 0x78(a0)
;   fsd fs2, 0x80(a0)
;   fsd fs3, 0x88(a0)
;   fsd fs4, 0x90(a0)
;   fsd fs5, 0x98(a0)
;   fsd fs6, 0xa0(a0)
;   fsd fs7, 0xa8(a0)
;   fsd fs8, 0xb0(a0)
;   fsd fs9, 0xb8(a0)
;   fsd fs10, 0xc0(a0)
;   fsd fs11, 0xc8(a0)
;   fsd ft8, 0xd0(a0)
;   fsd ft9, 0xd8(a0)
;   fsd ft10, 0xe0(a0)
;   fsd ft11, 0xe8(a0)
;   fld fs0, 0x58(sp)
;   fld fs2, 0x50(sp)
;   fld fs3, 0x48(sp)
;   fld fs4, 0x40(sp)
;   fld fs5, 0x38(sp)
;   fld fs6, 0x30(sp)
;   fld fs7, 0x28(sp)
;   fld fs8, 0x20(sp)
;   fld fs9, 0x18(sp)
;   fld fs10, 0x10(sp)
;   fld fs11, 8(sp)
;   addi sp, sp, 0x60
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

function %fli_h_neg() -> f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16, f16 {
block0:
    v0 = f16const 0x1.p0
    v1 = f16const -0x1.p-14
    v2 = f16const -0x1.p-16
    v3 = f16const -0x1.p-15
    v4 = f16const -0x1.p-8
    v5 = f16const -0x1.p-7
    v6 = f16const -0x1.p-4
    v7 = f16const -0x1.p-3
    v8 = f16const -0x1.p-2
    v9 = f16const -0x1.4p-2
    v10 = f16const -0x1.8p-2
    v11 = f16const -0x1.cp-2
    v12 = f16const -0x1.p-1
    v13 = f16const -0x1.4p-1
    v14 = f16const -0x1.8p-1
    v15 = f16const -0x1.cp-1
    v16 = f16const -0x1.p0
    v17 = f16const -0x1.4p0
    v18 = f16const -0x1.8p0
    v19 = f16const -0x1.cp0
    v20 = f16const -0x1.p1
    v21 = f16const -0x1.4p1
    v22 = f16const -0x1.8p1
    v23 = f16const -0x1.p2
    v24 = f16const -0x1.p3
    v25 = f16const -0x1.p4
    v26 = f16const -0x1.p7
    v27 = f16const -0x1.p8
    v28 = f16const -0x1.p15
    v29 = f16const -Inf
    v30 = f16const -NaN

    return v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, v27, v28, v29, v30
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-96
;   fsd fs0,88(sp)
;   fsd fs2,80(sp)
;   fsd fs3,72(sp)
;   fsd fs4,64(sp)
;   fsd fs5,56(sp)
;   fsd fs6,48(sp)
;   fsd fs7,40(sp)
;   fsd fs8,32(sp)
;   fsd fs9,24(sp)
;   fsd fs10,16(sp)
;   fsd fs11,8(sp)
; block0:
;   fli.h fa0,1.0
;   fli.h fa1,min
;   fneg.h fa1,fa1
;   fli.h fa2,2^-16
;   fneg.h fa2,fa2
;   fli.h fa3,2^-15
;   fneg.h fa3,fa3
;   fli.h fa4,2^-8
;   fneg.h fa4,fa4
;   fli.h fa5,2^-7
;   fneg.h fa5,fa5
;   fli.h ft0,0.0625
;   fneg.h ft0,ft0
;   fli.h ft1,0.125
;   fneg.h ft1,ft1
;   fli.h ft2,0.25
;   fneg.h ft2,ft2
;   fli.h ft3,0.3125
;   fneg.h ft3,ft3
;   fli.h ft4,0.375
;   fneg.h ft4,ft4
;   fli.h ft5,0.4375
;   fneg.h ft5,ft5
;   fli.h ft6,0.5
;   fneg.h ft6,ft6
;   fli.h ft7,0.625
;   fneg.h ft7,ft7
;   fli.h fs0,0.75
;   fneg.h fs0,fs0
;   fli.h fs1,0.875
;   fneg.h fs1,fs1
;   fli.h fa6,-1.0
;   fli.h fa7,1.25
;   fneg.h fa7,fa7
;   fli.h fs2,1.5
;   fneg.h fs2,fs2
;   fli.h fs3,1.75
;   fneg.h fs3,fs3
;   fli.h fs4,2.0
;   fneg.h fs4,fs4
;   fli.h fs5,2.5
;   fneg.h fs5,fs5
;   fli.h fs6,3.0
;   fneg.h fs6,fs6
;   fli.h fs7,4.0
;   fneg.h fs7,fs7
;   fli.h fs8,8.0
;   fneg.h fs8,fs8
;   fli.h fs9,16.0
;   fneg.h fs9,fs9
;   fli.h fs10,128.0
;   fneg.h fs10,fs10
;   fli.h fs11,256.0
;   fneg.h fs11,fs11
;   fli.h ft8,32768.0
;   fneg.h ft8,ft8
;   fli.h ft9,inf
;   fneg.h ft9,ft9
;   fli.h ft10,nan
;   fneg.h ft10,ft10
;   fsh fa2,0(a0)
;   fsh fa3,8(a0)
;   fsh fa4,16(a0)
;   fsh fa5,24(a0)
;   fsh ft0,32(a0)
;   fsh ft1,40(a0)
;   fsh ft2,48(a0)
;   fsh ft3,56(a0)
;   fsh ft4,64(a0)
;   fsh ft5,72(a0)
;   fsh ft6,80(a0)
;   fsh ft7,88(a0)
;   fsh fs0,96(a0)
;   fsh fs1,104(a0)
;   fsh fa6,112(a0)
;   fsh fa7,120(a0)
;   fsh fs2,128(a0)
;   fsh fs3,136(a0)
;   fsh fs4,144(a0)
;   fsh fs5,152(a0)
;   fsh fs6,160(a0)
;   fsh fs7,168(a0)
;   fsh fs8,176(a0)
;   fsh fs9,184(a0)
;   fsh fs10,192(a0)
;   fsh fs11,200(a0)
;   fsh ft8,208(a0)
;   fsh ft9,216(a0)
;   fsh ft10,224(a0)
;   fld fs0,88(sp)
;   fld fs2,80(sp)
;   fld fs3,72(sp)
;   fld fs4,64(sp)
;   fld fs5,56(sp)
;   fld fs6,48(sp)
;   fld fs7,40(sp)
;   fld fs8,32(sp)
;   fld fs9,24(sp)
;   fld fs10,16(sp)
;   fld fs11,8(sp)
;   addi sp,sp,96
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
;   addi sp, sp, -0x60
;   fsd fs0, 0x58(sp)
;   fsd fs2, 0x50(sp)
;   fsd fs3, 0x48(sp)
;   fsd fs4, 0x40(sp)
;   fsd fs5, 0x38(sp)
;   fsd fs6, 0x30(sp)
;   fsd fs7, 0x28(sp)
;   fsd fs8, 0x20(sp)
;   fsd fs9, 0x18(sp)
;   fsd fs10, 0x10(sp)
;   fsd fs11, 8(sp)
; block1: ; offset 0x40
;   .byte 0x53, 0x05, 0x18, 0xf4
;   .byte 0xd3, 0x85, 0x10, 0xf4
;   .byte 0xd3, 0x95, 0xb5, 0x24
;   .byte 0x53, 0x06, 0x11, 0xf4
;   .byte 0x53, 0x16, 0xc6, 0x24
;   .byte 0xd3, 0x86, 0x11, 0xf4
;   .byte 0xd3, 0x96, 0xd6, 0x24
;   .byte 0x53, 0x07, 0x12, 0xf4
;   .byte 0x53, 0x17, 0xe7, 0x24
;   .byte 0xd3, 0x87, 0x12, 0xf4
;   .byte 0xd3, 0x97, 0xf7, 0x24
;   .byte 0x53, 0x00, 0x13, 0xf4
;   .byte 0x53, 0x10, 0x00, 0x24
;   .byte 0xd3, 0x80, 0x13, 0xf4
;   .byte 0xd3, 0x90, 0x10, 0x24
;   .byte 0x53, 0x01, 0x14, 0xf4
;   .byte 0x53, 0x11, 0x21, 0x24
;   .byte 0xd3, 0x81, 0x14, 0xf4
;   .byte 0xd3, 0x91, 0x31, 0x24
;   .byte 0x53, 0x02, 0x15, 0xf4
;   .byte 0x53, 0x12, 0x42, 0x24
;   .byte 0xd3, 0x82, 0x15, 0xf4
;   .byte 0xd3, 0x92, 0x52, 0x24
;   .byte 0x53, 0x03, 0x16, 0xf4
;   .byte 0x53, 0x13, 0x63, 0x24
;   .byte 0xd3, 0x83, 0x16, 0xf4
;   .byte 0xd3, 0x93, 0x73, 0x24
;   .byte 0x53, 0x04, 0x17, 0xf4
;   .byte 0x53, 0x14, 0x84, 0x24
;   .byte 0xd3, 0x84, 0x17, 0xf4
;   .byte 0xd3, 0x94, 0x94, 0x24
;   .byte 0x53, 0x08, 0x10, 0xf4
;   .byte 0xd3, 0x88, 0x18, 0xf4
;   .byte 0xd3, 0x98, 0x18, 0x25
;   .byte 0x53, 0x09, 0x19, 0xf4
;   .byte 0x53, 0x19, 0x29, 0x25
;   .byte 0xd3, 0x89, 0x19, 0xf4
;   .byte 0xd3, 0x99, 0x39, 0x25
;   .byte 0x53, 0x0a, 0x1a, 0xf4
;   .byte 0x53, 0x1a, 0x4a, 0x25
;   .byte 0xd3, 0x8a, 0x1a, 0xf4
;   .byte 0xd3, 0x9a, 0x5a, 0x25
;   .byte 0x53, 0x0b, 0x1b, 0xf4
;   .byte 0x53, 0x1b, 0x6b, 0x25
;   .byte 0xd3, 0x8b, 0x1b, 0xf4
;   .byte 0xd3, 0x9b, 0x7b, 0x25
;   .byte 0x53, 0x0c, 0x1c, 0xf4
;   .byte 0x53, 0x1c, 0x8c, 0x25
;   .byte 0xd3, 0x8c, 0x1c, 0xf4
;   .byte 0xd3, 0x9c, 0x9c, 0x25
;   .byte 0x53, 0x0d, 0x1d, 0xf4
;   .byte 0x53, 0x1d, 0xad, 0x25
;   .byte 0xd3, 0x8d, 0x1d, 0xf4
;   .byte 0xd3, 0x9d, 0xbd, 0x25
;   .byte 0x53, 0x0e, 0x1e, 0xf4
;   .byte 0x53, 0x1e, 0xce, 0x25
;   .byte 0xd3, 0x0e, 0x1f, 0xf4
;   .byte 0xd3, 0x9e, 0xde, 0x25
;   .byte 0x53, 0x8f, 0x1f, 0xf4
;   .byte 0x53, 0x1f, 0xef, 0x25
;   .byte 0x27, 0x10, 0xc5, 0x00
;   .byte 0x27, 0x14, 0xd5, 0x00
;   .byte 0x27, 0x18, 0xe5, 0x00
;   .byte 0x27, 0x1c, 0xf5, 0x00
;   .byte 0x27, 0x10, 0x05, 0x02
;   .byte 0x27, 0x14, 0x15, 0x02
;   .byte 0x27, 0x18, 0x25, 0x02
;   .byte 0x27, 0x1c, 0x35, 0x02
;   .byte 0x27, 0x10, 0x45, 0x04
;   .byte 0x27, 0x14, 0x55, 0x04
;   .byte 0x27, 0x18, 0x65, 0x04
;   .byte 0x27, 0x1c, 0x75, 0x04
;   .byte 0x27, 0x10, 0x85, 0x06
;   .byte 0x27, 0x14, 0x95, 0x06
;   .byte 0x27, 0x18, 0x05, 0x07
;   .byte 0x27, 0x1c, 0x15, 0x07
;   .byte 0x27, 0x10, 0x25, 0x09
;   .byte 0x27, 0x14, 0x35, 0x09
;   .byte 0x27, 0x18, 0x45, 0x09
;   .byte 0x27, 0x1c, 0x55, 0x09
;   .byte 0x27, 0x10, 0x65, 0x0b
;   .byte 0x27, 0x14, 0x75, 0x0b
;   .byte 0x27, 0x18, 0x85, 0x0b
;   .byte 0x27, 0x1c, 0x95, 0x0b
;   .byte 0x27, 0x10, 0xa5, 0x0d
;   .byte 0x27, 0x14, 0xb5, 0x0d
;   .byte 0x27, 0x18, 0xc5, 0x0d
;   .byte 0x27, 0x1c, 0xd5, 0x0d
;   .byte 0x27, 0x10, 0xe5, 0x0f
;   fld fs0, 0x58(sp)
;   fld fs2, 0x50(sp)
;   fld fs3, 0x48(sp)
;   fld fs4, 0x40(sp)
;   fld fs5, 0x38(sp)
;   fld fs6, 0x30(sp)
;   fld fs7, 0x28(sp)
;   fld fs8, 0x20(sp)
;   fld fs9, 0x18(sp)
;   fld fs10, 0x10(sp)
;   fld fs11, 8(sp)
;   addi sp, sp, 0x60
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

function %fli_s_neg() -> f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32, f32 {
block0:
    v0 = f32const 0x1.p0
    v1 = f32const -0x1.p-126
    v2 = f32const -0x1.p-16
    v3 = f32const -0x1.p-15
    v4 = f32const -0x1.p-8
    v5 = f32const -0x1.p-7
    v6 = f32const -0x1.p-4
    v7 = f32const -0x1.p-3
    v8 = f32const -0x1.p-2
    v9 = f32const -0x1.4p-2
    v10 = f32const -0x1.8p-2
    v11 = f32const -0x1.cp-2
    v12 = f32const -0x1.p-1
    v13 = f32const -0x1.4p-1
    v14 = f32const -0x1.8p-1
    v15 = f32const -0x1.cp-1
    v16 = f32const -0x1.p0
    v17 = f32const -0x1.4p0
    v18 = f32const -0x1.8p0
    v19 = f32const -0x1.cp0
    v20 = f32const -0x1.p1
    v21 = f32const -0x1.4p1
    v22 = f32const -0x1.8p1
    v23 = f32const -0x1.p2
    v24 = f32const -0x1.p3
    v25 = f32const -0x1.p4
    v26 = f32const -0x1.p7
    v27 = f32const -0x1.p8
    v28 = f32const -0x1.p15
    v29 = f32const -0x1.p16
    v30 = f32const -Inf
    v31 = f32const -NaN

    return v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, v27, v28, v29, v30, v31
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-96
;   fsd fs0,88(sp)
;   fsd fs2,80(sp)
;   fsd fs3,72(sp)
;   fsd fs4,64(sp)
;   fsd fs5,56(sp)
;   fsd fs6,48(sp)
;   fsd fs7,40(sp)
;   fsd fs8,32(sp)
;   fsd fs9,24(sp)
;   fsd fs10,16(sp)
;   fsd fs11,8(sp)
; block0:
;   fli.s fa0,1.0
;   fli.s fa1,min
;   fneg.s fa1,fa1
;   fli.s fa2,2^-16
;   fneg.s fa2,fa2
;   fli.s fa3,2^-15
;   fneg.s fa3,fa3
;   fli.s fa4,2^-8
;   fneg.s fa4,fa4
;   fli.s fa5,2^-7
;   fneg.s fa5,fa5
;   fli.s ft0,0.0625
;   fneg.s ft1,ft0
;   fli.s ft0,0.125
;   fneg.s ft2,ft0
;   fli.s ft0,0.25
;   fneg.s ft3,ft0
;   fli.s ft0,0.3125
;   fneg.s ft4,ft0
;   fli.s ft0,0.375
;   fneg.s ft5,ft0
;   fli.s ft0,0.4375
;   fneg.s ft6,ft0
;   fli.s ft0,0.5
;   fneg.s ft7,ft0
;   fli.s ft0,0.625
;   fneg.s fs0,ft0
;   fli.s ft0,0.75
;   fneg.s fs1,ft0
;   fli.s ft0,0.875
;   fneg.s fa6,ft0
;   fli.s ft0,-1.0
;   fli.s fa7,1.25
;   fneg.s fa7,fa7
;   fli.s fs2,1.5
;   fneg.s fs2,fs2
;   fli.s fs3,1.75
;   fneg.s fs3,fs3
;   fli.s fs4,2.0
;   fneg.s fs4,fs4
;   fli.s fs5,2.5
;   fneg.s fs5,fs5
;   fli.s fs6,3.0
;   fneg.s fs6,fs6
;   fli.s fs7,4.0
;   fneg.s fs7,fs7
;   fli.s fs8,8.0
;   fneg.s fs8,fs8
;   fli.s fs9,16.0
;   fneg.s fs9,fs9
;   fli.s fs10,128.0
;   fneg.s fs10,fs10
;   fli.s fs11,256.0
;   fneg.s fs11,fs11
;   fli.s ft8,32768.0
;   fneg.s ft8,ft8
;   fli.s ft9,65536.0
;   fneg.s ft9,ft9
;   fli.s ft10,inf
;   fneg.s ft10,ft10
;   fli.s ft11,nan
;   fneg.s ft11,ft11
;   fsw fa2,0(a0)
;   fsw fa3,8(a0)
;   fsw fa4,16(a0)
;   fsw fa5,24(a0)
;   fsw ft1,32(a0)
;   fsw ft2,40(a0)
;   fsw ft3,48(a0)
;   fsw ft4,56(a0)
;   fsw ft5,64(a0)
;   fsw ft6,72(a0)
;   fsw ft7,80(a0)
;   fsw fs0,88(a0)
;   fsw fs1,96(a0)
;   fsw fa6,104(a0)
;   fsw ft0,112(a0)
;   fsw fa7,120(a0)
;   fsw fs2,128(a0)
;   fsw fs3,136(a0)
;   fsw fs4,144(a0)
;   fsw fs5,152(a0)
;   fsw fs6,160(a0)
;   fsw fs7,168(a0)
;   fsw fs8,176(a0)
;   fsw fs9,184(a0)
;   fsw fs10,192(a0)
;   fsw fs11,200(a0)
;   fsw ft8,208(a0)
;   fsw ft9,216(a0)
;   fsw ft10,224(a0)
;   fsw ft11,232(a0)
;   fld fs0,88(sp)
;   fld fs2,80(sp)
;   fld fs3,72(sp)
;   fld fs4,64(sp)
;   fld fs5,56(sp)
;   fld fs6,48(sp)
;   fld fs7,40(sp)
;   fld fs8,32(sp)
;   fld fs9,24(sp)
;   fld fs10,16(sp)
;   fld fs11,8(sp)
;   addi sp,sp,96
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
;   addi sp, sp, -0x60
;   fsd fs0, 0x58(sp)
;   fsd fs2, 0x50(sp)
;   fsd fs3, 0x48(sp)
;   fsd fs4, 0x40(sp)
;   fsd fs5, 0x38(sp)
;   fsd fs6, 0x30(sp)
;   fsd fs7, 0x28(sp)
;   fsd fs8, 0x20(sp)
;   fsd fs9, 0x18(sp)
;   fsd fs10, 0x10(sp)
;   fsd fs11, 8(sp)
; block1: ; offset 0x40
;   .byte 0x53, 0x05, 0x18, 0xf0
;   .byte 0xd3, 0x85, 0x10, 0xf0
;   fneg.s fa1, fa1
;   .byte 0x53, 0x06, 0x11, 0xf0
;   fneg.s fa2, fa2
;   .byte 0xd3, 0x86, 0x11, 0xf0
;   fneg.s fa3, fa3
;   .byte 0x53, 0x07, 0x12, 0xf0
;   fneg.s fa4, fa4
;   .byte 0xd3, 0x87, 0x12, 0xf0
;   fneg.s fa5, fa5
;   .byte 0x53, 0x00, 0x13, 0xf0
;   fneg.s ft1, ft0
;   .byte 0x53, 0x80, 0x13, 0xf0
;   fneg.s ft2, ft0
;   .byte 0x53, 0x00, 0x14, 0xf0
;   fneg.s ft3, ft0
;   .byte 0x53, 0x80, 0x14, 0xf0
;   fneg.s ft4, ft0
;   .byte 0x53, 0x00, 0x15, 0xf0
;   fneg.s ft5, ft0
;   .byte 0x53, 0x80, 0x15, 0xf0
;   fneg.s ft6, ft0
;   .byte 0x53, 0x00, 0x16, 0xf0
;   fneg.s ft7, ft0
;   .byte 0x53, 0x80, 0x16, 0xf0
;   fneg.s fs0, ft0
;   .byte 0x53, 0x00, 0x17, 0xf0
;   fneg.s fs1, ft0
;   .byte 0x53, 0x80, 0x17, 0xf0
;   fneg.s fa6, ft0
;   .byte 0x53, 0x00, 0x10, 0xf0
;   .byte 0xd3, 0x88, 0x18, 0xf0
;   fneg.s fa7, fa7
;   .byte 0x53, 0x09, 0x19, 0xf0
;   fneg.s fs2, fs2
;   .byte 0xd3, 0x89, 0x19, 0xf0
;   fneg.s fs3, fs3
;   .byte 0x53, 0x0a, 0x1a, 0xf0
;   fneg.s fs4, fs4
;   .byte 0xd3, 0x8a, 0x1a, 0xf0
;   fneg.s fs5, fs5
;   .byte 0x53, 0x0b, 0x1b, 0xf0
;   fneg.s fs6, fs6
;   .byte 0xd3, 0x8b, 0x1b, 0xf0
;   fneg.s fs7, fs7
;   .byte 0x53, 0x0c, 0x1c, 0xf0
;   fneg.s fs8, fs8
;   .byte 0xd3, 0x8c, 0x1c, 0xf0
;   fneg.s fs9, fs9
;   .byte 0x53, 0x0d, 0x1d, 0xf0
;   fneg.s fs10, fs10
;   .byte 0xd3, 0x8d, 0x1d, 0xf0
;   fneg.s fs11, fs11
;   .byte 0x53, 0x0e, 0x1e, 0xf0
;   fneg.s ft8, ft8
;   .byte 0xd3, 0x8e, 0x1e, 0xf0
;   fneg.s ft9, ft9
;   .byte 0x53, 0x0f, 0x1f, 0xf0
;   fneg.s ft10, ft10
;   .byte 0xd3, 0x8f, 0x1f, 0xf0
;   fneg.s ft11, ft11
;   fsw fa2, 0(a0)
;   fsw fa3, 8(a0)
;   fsw fa4, 0x10(a0)
;   fsw fa5, 0x18(a0)
;   fsw ft1, 0x20(a0)
;   fsw ft2, 0x28(a0)
;   fsw ft3, 0x30(a0)
;   fsw ft4, 0x38(a0)
;   fsw ft5, 0x40(a0)
;   fsw ft6, 0x48(a0)
;   fsw ft7, 0x50(a0)
;   fsw fs0, 0x58(a0)
;   fsw fs1, 0x60(a0)
;   fsw fa6, 0x68(a0)
;   fsw ft0, 0x70(a0)
;   fsw fa7, 0x78(a0)
;   fsw fs2, 0x80(a0)
;   fsw fs3, 0x88(a0)
;   fsw fs4, 0x90(a0)
;   fsw fs5, 0x98(a0)
;   fsw fs6, 0xa0(a0)
;   fsw fs7, 0xa8(a0)
;   fsw fs8, 0xb0(a0)
;   fsw fs9, 0xb8(a0)
;   fsw fs10, 0xc0(a0)
;   fsw fs11, 0xc8(a0)
;   fsw ft8, 0xd0(a0)
;   fsw ft9, 0xd8(a0)
;   fsw ft10, 0xe0(a0)
;   fsw ft11, 0xe8(a0)
;   fld fs0, 0x58(sp)
;   fld fs2, 0x50(sp)
;   fld fs3, 0x48(sp)
;   fld fs4, 0x40(sp)
;   fld fs5, 0x38(sp)
;   fld fs6, 0x30(sp)
;   fld fs7, 0x28(sp)
;   fld fs8, 0x20(sp)
;   fld fs9, 0x18(sp)
;   fld fs10, 0x10(sp)
;   fld fs11, 8(sp)
;   addi sp, sp, 0x60
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

function %fli_d_neg() -> f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64, f64 {
block0:
    v0 = f64const 0x1.p0
    v1 = f64const -0x1.p-1022
    v2 = f64const -0x1.p-16
    v3 = f64const -0x1.p-15
    v4 = f64const -0x1.p-8
    v5 = f64const -0x1.p-7
    v6 = f64const -0x1.p-4
    v7 = f64const -0x1.p-3
    v8 = f64const -0x1.p-2
    v9 = f64const -0x1.4p-2
    v10 = f64const -0x1.8p-2
    v11 = f64const -0x1.cp-2
    v12 = f64const -0x1.p-1
    v13 = f64const -0x1.4p-1
    v14 = f64const -0x1.8p-1
    v15 = f64const -0x1.cp-1
    v16 = f64const -0x1.p0
    v17 = f64const -0x1.4p0
    v18 = f64const -0x1.8p0
    v19 = f64const -0x1.cp0
    v20 = f64const -0x1.p1
    v21 = f64const -0x1.4p1
    v22 = f64const -0x1.8p1
    v23 = f64const -0x1.p2
    v24 = f64const -0x1.p3
    v25 = f64const -0x1.p4
    v26 = f64const -0x1.p7
    v27 = f64const -0x1.p8
    v28 = f64const -0x1.p15
    v29 = f64const -0x1.p16
    v30 = f64const -Inf
    v31 = f64const -NaN

    return v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25, v26, v27, v28, v29, v30, v31
}

; VCode:
;   addi sp,sp,-16
;   sd ra,8(sp)
;   sd fp,0(sp)
;   mv fp,sp
;   addi sp,sp,-96
;   fsd fs0,88(sp)
;   fsd fs2,80(sp)
;   fsd fs3,72(sp)
;   fsd fs4,64(sp)
;   fsd fs5,56(sp)
;   fsd fs6,48(sp)
;   fsd fs7,40(sp)
;   fsd fs8,32(sp)
;   fsd fs9,24(sp)
;   fsd fs10,16(sp)
;   fsd fs11,8(sp)
; block0:
;   fli.d fa0,1.0
;   fli.d fa1,min
;   fneg.d fa1,fa1
;   fli.d fa2,2^-16
;   fneg.d fa2,fa2
;   fli.d fa3,2^-15
;   fneg.d fa3,fa3
;   fli.d fa4,2^-8
;   fneg.d fa4,fa4
;   fli.d fa5,2^-7
;   fneg.d fa5,fa5
;   fli.d ft0,0.0625
;   fneg.d ft1,ft0
;   fli.d ft0,0.125
;   fneg.d ft2,ft0
;   fli.d ft0,0.25
;   fneg.d ft3,ft0
;   fli.d ft0,0.3125
;   fneg.d ft4,ft0
;   fli.d ft0,0.375
;   fneg.d ft5,ft0
;   fli.d ft0,0.4375
;   fneg.d ft6,ft0
;   fli.d ft0,0.5
;   fneg.d ft7,ft0
;   fli.d ft0,0.625
;   fneg.d fs0,ft0
;   fli.d ft0,0.75
;   fneg.d fs1,ft0
;   fli.d ft0,0.875
;   fneg.d fa6,ft0
;   fli.d ft0,-1.0
;   fli.d fa7,1.25
;   fneg.d fa7,fa7
;   fli.d fs2,1.5
;   fneg.d fs2,fs2
;   fli.d fs3,1.75
;   fneg.d fs3,fs3
;   fli.d fs4,2.0
;   fneg.d fs4,fs4
;   fli.d fs5,2.5
;   fneg.d fs5,fs5
;   fli.d fs6,3.0
;   fneg.d fs6,fs6
;   fli.d fs7,4.0
;   fneg.d fs7,fs7
;   fli.d fs8,8.0
;   fneg.d fs8,fs8
;   fli.d fs9,16.0
;   fneg.d fs9,fs9
;   fli.d fs10,128.0
;   fneg.d fs10,fs10
;   fli.d fs11,256.0
;   fneg.d fs11,fs11
;   fli.d ft8,32768.0
;   fneg.d ft8,ft8
;   fli.d ft9,65536.0
;   fneg.d ft9,ft9
;   fli.d ft10,inf
;   fneg.d ft10,ft10
;   fli.d ft11,nan
;   fneg.d ft11,ft11
;   fsd fa2,0(a0)
;   fsd fa3,8(a0)
;   fsd fa4,16(a0)
;   fsd fa5,24(a0)
;   fsd ft1,32(a0)
;   fsd ft2,40(a0)
;   fsd ft3,48(a0)
;   fsd ft4,56(a0)
;   fsd ft5,64(a0)
;   fsd ft6,72(a0)
;   fsd ft7,80(a0)
;   fsd fs0,88(a0)
;   fsd fs1,96(a0)
;   fsd fa6,104(a0)
;   fsd ft0,112(a0)
;   fsd fa7,120(a0)
;   fsd fs2,128(a0)
;   fsd fs3,136(a0)
;   fsd fs4,144(a0)
;   fsd fs5,152(a0)
;   fsd fs6,160(a0)
;   fsd fs7,168(a0)
;   fsd fs8,176(a0)
;   fsd fs9,184(a0)
;   fsd fs10,192(a0)
;   fsd fs11,200(a0)
;   fsd ft8,208(a0)
;   fsd ft9,216(a0)
;   fsd ft10,224(a0)
;   fsd ft11,232(a0)
;   fld fs0,88(sp)
;   fld fs2,80(sp)
;   fld fs3,72(sp)
;   fld fs4,64(sp)
;   fld fs5,56(sp)
;   fld fs6,48(sp)
;   fld fs7,40(sp)
;   fld fs8,32(sp)
;   fld fs9,24(sp)
;   fld fs10,16(sp)
;   fld fs11,8(sp)
;   addi sp,sp,96
;   ld ra,8(sp)
;   ld fp,0(sp)
;   addi sp,sp,16
;   ret
;
; Disassembled:
; block0: ; offset 0x0
;   addi sp, sp, -0x10
;   sd ra, 8(sp)
;   sd s0, 0(sp)
;   mv s0, sp
;   addi sp, sp, -0x60
;   fsd fs0, 0x58(sp)
;   fsd fs2, 0x50(sp)
;   fsd fs3, 0x48(sp)
;   fsd fs4, 0x40(sp)
;   fsd fs5, 0x38(sp)
;   fsd fs6, 0x30(sp)
;   fsd fs7, 0x28(sp)
;   fsd fs8, 0x20(sp)
;   fsd fs9, 0x18(sp)
;   fsd fs10, 0x10(sp)
;   fsd fs11, 8(sp)
; block1: ; offset 0x40
;   .byte 0x53, 0x05, 0x18, 0xf2
;   .byte 0xd3, 0x85, 0x10, 0xf2
;   fneg.d fa1, fa1
;   .byte 0x53, 0x06, 0x11, 0xf2
;   fneg.d fa2, fa2
;   .byte 0xd3, 0x86, 0x11, 0xf2
;   fneg.d fa3, fa3
;   .byte 0x53, 0x07, 0x12, 0xf2
;   fneg.d fa4, fa4
;   .byte 0xd3, 0x87, 0x12, 0xf2
;   fneg.d fa5, fa5
;   .byte 0x53, 0x00, 0x13, 0xf2
;   fneg.d ft1, ft0
;   .byte 0x53, 0x80, 0x13, 0xf2
;   fneg.d ft2, ft0
;   .byte 0x53, 0x00, 0x14, 0xf2
;   fneg.d ft3, ft0
;   .byte 0x53, 0x80, 0x14, 0xf2
;   fneg.d ft4, ft0
;   .byte 0x53, 0x00, 0x15, 0xf2
;   fneg.d ft5, ft0
;   .byte 0x53, 0x80, 0x15, 0xf2
;   fneg.d ft6, ft0
;   .byte 0x53, 0x00, 0x16, 0xf2
;   fneg.d ft7, ft0
;   .byte 0x53, 0x80, 0x16, 0xf2
;   fneg.d fs0, ft0
;   .byte 0x53, 0x00, 0x17, 0xf2
;   fneg.d fs1, ft0
;   .byte 0x53, 0x80, 0x17, 0xf2
;   fneg.d fa6, ft0
;   .byte 0x53, 0x00, 0x10, 0xf2
;   .byte 0xd3, 0x88, 0x18, 0xf2
;   fneg.d fa7, fa7
;   .byte 0x53, 0x09, 0x19, 0xf2
;   fneg.d fs2, fs2
;   .byte 0xd3, 0x89, 0x19, 0xf2
;   fneg.d fs3, fs3
;   .byte 0x53, 0x0a, 0x1a, 0xf2
;   fneg.d fs4, fs4
;   .byte 0xd3, 0x8a, 0x1a, 0xf2
;   fneg.d fs5, fs5
;   .byte 0x53, 0x0b, 0x1b, 0xf2
;   fneg.d fs6, fs6
;   .byte 0xd3, 0x8b, 0x1b, 0xf2
;   fneg.d fs7, fs7
;   .byte 0x53, 0x0c, 0x1c, 0xf2
;   fneg.d fs8, fs8
;   .byte 0xd3, 0x8c, 0x1c, 0xf2
;   fneg.d fs9, fs9
;   .byte 0x53, 0x0d, 0x1d, 0xf2
;   fneg.d fs10, fs10
;   .byte 0xd3, 0x8d, 0x1d, 0xf2
;   fneg.d fs11, fs11
;   .byte 0x53, 0x0e, 0x1e, 0xf2
;   fneg.d ft8, ft8
;   .byte 0xd3, 0x8e, 0x1e, 0xf2
;   fneg.d ft9, ft9
;   .byte 0x53, 0x0f, 0x1f, 0xf2
;   fneg.d ft10, ft10
;   .byte 0xd3, 0x8f, 0x1f, 0xf2
;   fneg.d ft11, ft11
;   fsd fa2, 0(a0)
;   fsd fa3, 8(a0)
;   fsd fa4, 0x10(a0)
;   fsd fa5, 0x18(a0)
;   fsd ft1, 0x20(a0)
;   fsd ft2, 0x28(a0)
;   fsd ft3, 0x30(a0)
;   fsd ft4, 0x38(a0)
;   fsd ft5, 0x40(a0)
;   fsd ft6, 0x48(a0)
;   fsd ft7, 0x50(a0)
;   fsd fs0, 0x58(a0)
;   fsd fs1, 0x60(a0)
;   fsd fa6, 0x68(a0)
;   fsd ft0, 0x70(a0)
;   fsd fa7, 0x78(a0)
;   fsd fs2, 0x80(a0)
;   fsd fs3, 0x88(a0)
;   fsd fs4, 0x90(a0)
;   fsd fs5, 0x98(a0)
;   fsd fs6, 0xa0(a0)
;   fsd fs7, 0xa8(a0)
;   fsd fs8, 0xb0(a0)
;   fsd fs9, 0xb8(a0)
;   fsd fs10, 0xc0(a0)
;   fsd fs11, 0xc8(a0)
;   fsd ft8, 0xd0(a0)
;   fsd ft9, 0xd8(a0)
;   fsd ft10, 0xe0(a0)
;   fsd ft11, 0xe8(a0)
;   fld fs0, 0x58(sp)
;   fld fs2, 0x50(sp)
;   fld fs3, 0x48(sp)
;   fld fs4, 0x40(sp)
;   fld fs5, 0x38(sp)
;   fld fs6, 0x30(sp)
;   fld fs7, 0x28(sp)
;   fld fs8, 0x20(sp)
;   fld fs9, 0x18(sp)
;   fld fs10, 0x10(sp)
;   fld fs11, 8(sp)
;   addi sp, sp, 0x60
;   ld ra, 8(sp)
;   ld s0, 0(sp)
;   addi sp, sp, 0x10
;   ret

