;;! target = "x86_64"
;;! test = "winch"
(module
  (func (export "large") (param i32) (result i32)
    (block
      (block
        (br_table
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          (local.get 0)
        )
        (return (i32.const -1))
      )
      (return (i32.const 0))
    )
    (return (i32.const 1))
  )
)
;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    8(%rdi), %r11
;;       movq    0x18(%r11), %r11
;;       addq    $0x20, %r11
;;       cmpq    %rsp, %r11
;;       ja      0x1810b
;;   1c: movq    %rdi, %r14
;;       subq    $0x20, %rsp
;;       movq    %rdi, 0x18(%rsp)
;;       movq    %rsi, 0x10(%rsp)
;;       movl    %edx, 0xc(%rsp)
;;       movl    0xc(%rsp), %eax
;;       movl    $0x6027, %ecx
;;       cmpl    %eax, %ecx
;;       cmovbl  %ecx, %eax
;;       leaq    0xa(%rip), %r11
;;       movslq  (%r11, %rax, 4), %rcx
;;       addq    %rcx, %r11
;;       jmpq    *%r11
;;   53: movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movabsb 0xa0000180aa000180, %al
;;       addb    $0, (%rcx)
;;       stosb   %al, (%rdi)
;;       addb    $0, (%rcx)
;;       movl    $0, %eax
;;       jmp     0x18102
;; 180fd: movl    $1, %eax
;;       addq    $0x20, %rsp
;;       popq    %rbp
;;       retq
;; 1810b: ud2
