;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -W memory64 -O static-memory-maximum-size=0 -O static-memory-guard-size=4294967295 -O dynamic-memory-guard-size=4294967295"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store offset=0)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load offset=0))

;; wasm[0]::function[0]:
;;    0: pushq   %rbp
;;    1: movq    %rsp, %rbp
;;    4: movq    0x58(%rdi), %rsi
;;    8: xorq    %r11, %r11
;;    b: movq    %rdx, %r10
;;    e: addq    0x50(%rdi), %r10
;;   12: cmpq    %rsi, %rdx
;;   15: cmovaq  %r11, %r10
;;   19: movl    %ecx, (%r10)
;;   1c: movq    %rbp, %rsp
;;   1f: popq    %rbp
;;   20: retq
;;
;; wasm[0]::function[1]:
;;   30: pushq   %rbp
;;   31: movq    %rsp, %rbp
;;   34: movq    0x58(%rdi), %rsi
;;   38: xorq    %r11, %r11
;;   3b: movq    %rdx, %r10
;;   3e: addq    0x50(%rdi), %r10
;;   42: cmpq    %rsi, %rdx
;;   45: cmovaq  %r11, %r10
;;   49: movl    (%r10), %eax
;;   4c: movq    %rbp, %rsp
;;   4f: popq    %rbp
;;   50: retq
