;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-maximum-size=0 -O static-memory-guard-size=4294967295 -O dynamic-memory-guard-size=4294967295"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0x1000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load8_u offset=0x1000))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    0x40(%rdi), %r10
;;       movq    0x38(%rdi), %rax
;;       movl    %edx, %edx
;;       xorq    %r11, %r11
;;       leaq    0x1000(%rax, %rdx), %r9
;;       cmpq    %r10, %rdx
;;       cmovaq  %r11, %r9
;;       movb    %cl, (%r9)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    0x40(%rdi), %r10
;;       movq    0x38(%rdi), %rax
;;       movl    %edx, %ecx
;;       xorq    %r11, %r11
;;       leaq    0x1000(%rax, %rcx), %r9
;;       cmpq    %r10, %rcx
;;       cmovaq  %r11, %r9
;;       movzbq  (%r9), %rax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
