;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-maximum-size=0 -O static-memory-guard-size=4294967295 -O dynamic-memory-guard-size=4294967295"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0xffff0000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0xffff0000))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    0x48(%rdi), %rax
;;       movl    %edx, %r8d
;;       xorq    %rdx, %rdx
;;       movq    %r8, %r9
;;       addq    0x40(%rdi), %r9
;;       movl    $0xffff0000, %r10d
;;       leaq    (%r9, %r10), %rdi
;;       cmpq    %rax, %r8
;;       cmovaq  %rdx, %rdi
;;       movl    %ecx, (%rdi)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    0x48(%rdi), %rax
;;       movl    %edx, %edx
;;       xorq    %rcx, %rcx
;;       movq    %rdx, %r8
;;       addq    0x40(%rdi), %r8
;;       movl    $0xffff0000, %r9d
;;       leaq    (%r8, %r9), %rdi
;;       cmpq    %rax, %rdx
;;       cmovaq  %rcx, %rdi
;;       movl    (%rdi), %eax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
