;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -W memory64 -O static-memory-forced -O static-memory-guard-size=4294967295 -O dynamic-memory-guard-size=4294967295"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store offset=0)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load offset=0))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    %rdi, %r8
;;       xorq    %rdi, %rdi
;;       movq    %r8, %r10
;;       movq    %rdx, %rsi
;;       addq    0x38(%r10), %rsi
;;       cmpq    0xd(%rip), %rdx
;;       cmovaq  %rdi, %rsi
;;       movl    %ecx, (%rsi)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   26: addb    %al, (%rax)
;;   28: cld
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    %rdi, %r8
;;       xorq    %rdi, %rdi
;;       movq    %r8, %r10
;;       movq    %rdx, %rsi
;;       addq    0x38(%r10), %rsi
;;       cmpq    0xd(%rip), %rdx
;;       cmovaq  %rdi, %rsi
;;       movl    (%rsi), %eax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   66: addb    %al, (%rax)
;;   68: cld
