;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation=false -W memory64 -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load8_u offset=0))

;; wasm[0]::function[0]:
;;    0: pushq   %rbp
;;    1: movq    %rsp, %rbp
;;    4: movq    0x58(%rdi), %r9
;;    8: cmpq    %r9, %rdx
;;    b: jae     0x1e
;;   11: movq    0x50(%rdi), %r11
;;   15: movb    %cl, (%r11, %rdx)
;;   19: movq    %rbp, %rsp
;;   1c: popq    %rbp
;;   1d: retq
;;   1e: ud2
;;
;; wasm[0]::function[1]:
;;   20: pushq   %rbp
;;   21: movq    %rsp, %rbp
;;   24: movq    0x58(%rdi), %r9
;;   28: cmpq    %r9, %rdx
;;   2b: jae     0x3f
;;   31: movq    0x50(%rdi), %r11
;;   35: movzbq  (%r11, %rdx), %rax
;;   3a: movq    %rbp, %rsp
;;   3d: popq    %rbp
;;   3e: retq
;;   3f: ud2
