;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation=false -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0x1000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load8_u offset=0x1000))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    0x40(%rdi), %rsi
;;       movl    %edx, %r8d
;;       subq    $0x1001, %rsi
;;       cmpq    %rsi, %r8
;;       ja      0x2c
;;   1b: movq    0x38(%rdi), %r9
;;       movb    %cl, 0x1000(%r9, %r8)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   2c: ud2
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    0x40(%rdi), %rsi
;;       movl    %edx, %r8d
;;       subq    $0x1001, %rsi
;;       cmpq    %rsi, %r8
;;       ja      0x6d
;;   5b: movq    0x38(%rdi), %r9
;;       movzbq  0x1000(%r9, %r8), %rax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   6d: ud2
