;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -W memory64 -O static-memory-maximum-size=0 -O static-memory-guard-size=4294967295 -O dynamic-memory-guard-size=4294967295"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store offset=0xffff0000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load offset=0xffff0000))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    0x40(%rdi), %r11
;;       xorq    %r10, %r10
;;       movq    %rdx, %rax
;;       addq    0x38(%rdi), %rax
;;       movl    $0xffff0000, %esi
;;       leaq    (%rax, %rsi), %r9
;;       cmpq    %r11, %rdx
;;       cmovaq  %r10, %r9
;;       movl    %ecx, (%r9)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    0x40(%rdi), %r11
;;       xorq    %r10, %r10
;;       movq    %rdx, %rax
;;       addq    0x38(%rdi), %rax
;;       movl    $0xffff0000, %ecx
;;       leaq    (%rax, %rcx), %r9
;;       cmpq    %r11, %rdx
;;       cmovaq  %r10, %r9
;;       movl    (%r9), %eax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
