;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-maximum-size=0 -O static-memory-guard-size=4294967295 -O dynamic-memory-guard-size=4294967295"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    0x40(%rdi), %rsi
;;       movl    %edx, %edx
;;       xorq    %rax, %rax
;;       movq    %rdx, %r11
;;       addq    0x38(%rdi), %r11
;;       cmpq    %rsi, %rdx
;;       cmovaq  %rax, %r11
;;       movl    %ecx, (%r11)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    0x40(%rdi), %rsi
;;       movl    %edx, %ecx
;;       xorq    %rax, %rax
;;       movq    %rcx, %r11
;;       addq    0x38(%rdi), %r11
;;       cmpq    %rsi, %rcx
;;       cmovaq  %rax, %r11
;;       movl    (%r11), %eax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
