;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-forced -O static-memory-guard-size=4294967295 -O dynamic-memory-guard-size=4294967295"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0xffff0000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0xffff0000))

;; wasm[0]::function[0]:
;;    0: pushq   %rbp
;;    1: movq    %rsp, %rbp
;;    4: movl    %edx, %r9d
;;    7: addq    0x50(%rdi), %r9
;;    b: movl    $0xffff0000, %r10d
;;   11: movl    %ecx, (%r9, %r10)
;;   15: movq    %rbp, %rsp
;;   18: popq    %rbp
;;   19: retq
;;
;; wasm[0]::function[1]:
;;   20: pushq   %rbp
;;   21: movq    %rsp, %rbp
;;   24: movl    %edx, %r9d
;;   27: addq    0x50(%rdi), %r9
;;   2b: movl    $0xffff0000, %r10d
;;   31: movl    (%r9, %r10), %eax
;;   35: movq    %rbp, %rsp
;;   38: popq    %rbp
;;   39: retq
