;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -W memory64 -O static-memory-forced -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0x1000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load8_u offset=0x1000))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       xorq    %r8, %r8
;;       movq    0x38(%rdi), %r9
;;       leaq    0x1000(%r9, %rdx), %rdi
;;       cmpq    0xe(%rip), %rdx
;;       cmovaq  %r8, %rdi
;;       movb    %cl, (%rdi)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   25: addb    %al, (%rax)
;;   27: addb    %bh, %bh
;;   29: outl    %eax, %dx
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       xorq    %r8, %r8
;;       movq    0x38(%rdi), %r9
;;       leaq    0x1000(%r9, %rdx), %rdi
;;       cmpq    0xe(%rip), %rdx
;;       cmovaq  %r8, %rdi
;;       movzbq  (%rdi), %rax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   67: addb    %bh, %bh
;;   69: outl    %eax, %dx
