;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation=false -W memory64 -O static-memory-forced -O static-memory-guard-size=4294967295 -O dynamic-memory-guard-size=4294967295"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store offset=0xffff0000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load offset=0xffff0000))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       cmpq    $0xfffc, %rdx
;;       ja      0x24
;;   11: addq    0x58(%rdi), %rdx
;;       movl    $0xffff0000, %r10d
;;       movl    %ecx, (%rdx, %r10)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   24: ud2
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       cmpq    $0xfffc, %rdx
;;       ja      0x64
;;   51: addq    0x58(%rdi), %rdx
;;       movl    $0xffff0000, %r10d
;;       movl    (%rdx, %r10), %eax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   64: ud2
