;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation=false -W memory64 -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0xffff0000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load8_u offset=0xffff0000))

;; wasm[0]::function[0]:
;;    0: pushq   %rbp
;;    1: movq    %rsp, %rbp
;;    4: movq    %rdx, %r11
;;    7: addq    0x2a(%rip), %r11
;;    e: jb      0x34
;;   14: movq    0x58(%rdi), %rsi
;;   18: cmpq    %rsi, %r11
;;   1b: ja      0x32
;;   21: addq    0x50(%rdi), %rdx
;;   25: movl    $0xffff0000, %eax
;;   2a: movb    %cl, (%rdx, %rax)
;;   2d: movq    %rbp, %rsp
;;   30: popq    %rbp
;;   31: retq
;;   32: ud2
;;   34: ud2
;;   36: addb    %al, (%rax)
;;   38: addl    %eax, (%rax)
;;
;; wasm[0]::function[1]:
;;   40: pushq   %rbp
;;   41: movq    %rsp, %rbp
;;   44: movq    %rdx, %r11
;;   47: addq    0x2a(%rip), %r11
;;   4e: jb      0x76
;;   54: movq    0x58(%rdi), %rsi
;;   58: cmpq    %rsi, %r11
;;   5b: ja      0x74
;;   61: addq    0x50(%rdi), %rdx
;;   65: movl    $0xffff0000, %eax
;;   6a: movzbq  (%rdx, %rax), %rax
;;   6f: movq    %rbp, %rsp
;;   72: popq    %rbp
;;   73: retq
;;   74: ud2
;;   76: ud2
;;   78: addl    %eax, (%rax)
