;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0x1000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0x1000))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    %rdx, %rax
;;       movq    0x40(%rdi), %rdx
;;       movq    0x38(%rdi), %r11
;;       movl    %eax, %eax
;;       leaq    -0x1004(%rdx), %rsi
;;       xorq    %rdx, %rdx
;;       leaq    0x1000(%r11, %rax), %r10
;;       cmpq    %rsi, %rax
;;       cmovaq  %rdx, %r10
;;       movl    %ecx, (%r10)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    0x40(%rdi), %rcx
;;       movq    0x38(%rdi), %r11
;;       movl    %edx, %eax
;;       leaq    -0x1004(%rcx), %rdx
;;       xorq    %rcx, %rcx
;;       leaq    0x1000(%r11, %rax), %r10
;;       cmpq    %rdx, %rax
;;       cmovaq  %rcx, %r10
;;       movl    (%r10), %eax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
