;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-forced -O static-memory-guard-size=4294967295 -O dynamic-memory-guard-size=4294967295"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0x1000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0x1000))

;; wasm[0]::function[0]:
;;    0: pushq   %rbp
;;    1: movq    %rsp, %rbp
;;    4: movq    0x50(%rdi), %r9
;;    8: movl    %edx, %r10d
;;    b: movl    %ecx, 0x1000(%r9, %r10)
;;   13: movq    %rbp, %rsp
;;   16: popq    %rbp
;;   17: retq
;;
;; wasm[0]::function[1]:
;;   20: pushq   %rbp
;;   21: movq    %rsp, %rbp
;;   24: movq    0x50(%rdi), %r9
;;   28: movl    %edx, %r10d
;;   2b: movl    0x1000(%r9, %r10), %eax
;;   33: movq    %rbp, %rsp
;;   36: popq    %rbp
;;   37: retq
