;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation=false -O static-memory-forced -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0xffff0000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0xffff0000))

;; wasm[0]::function[0]:
;;    0: pushq   %rbp
;;    1: movq    %rsp, %rbp
;;    4: movl    %edx, %r9d
;;    7: cmpq    $0xfffc, %r9
;;    e: ja      0x26
;;   14: addq    0x50(%rdi), %r9
;;   18: movl    $0xffff0000, %esi
;;   1d: movl    %ecx, (%r9, %rsi)
;;   21: movq    %rbp, %rsp
;;   24: popq    %rbp
;;   25: retq
;;   26: ud2
;;
;; wasm[0]::function[1]:
;;   30: pushq   %rbp
;;   31: movq    %rsp, %rbp
;;   34: movl    %edx, %r9d
;;   37: cmpq    $0xfffc, %r9
;;   3e: ja      0x56
;;   44: addq    0x50(%rdi), %r9
;;   48: movl    $0xffff0000, %esi
;;   4d: movl    (%r9, %rsi), %eax
;;   51: movq    %rbp, %rsp
;;   54: popq    %rbp
;;   55: retq
;;   56: ud2
