;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -W memory64 -O static-memory-maximum-size=0 -O static-memory-guard-size=4294967295 -O dynamic-memory-guard-size=4294967295"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0xffff0000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load8_u offset=0xffff0000))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    0x40(%rdi), %rax
;;       movq    %rdi, %r9
;;       xorq    %rdi, %rdi
;;       movq    %rdx, %r8
;;       addq    0x38(%r9), %r8
;;       movl    $0xffff0000, %r9d
;;       leaq    (%r8, %r9), %rsi
;;       cmpq    %rax, %rdx
;;       cmovaq  %rdi, %rsi
;;       movb    %cl, (%rsi)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    0x40(%rdi), %rax
;;       movq    %rdi, %r8
;;       xorq    %rdi, %rdi
;;       movq    %rdx, %rcx
;;       addq    0x38(%r8), %rcx
;;       movl    $0xffff0000, %r8d
;;       leaq    (%rcx, %r8), %rsi
;;       cmpq    %rax, %rdx
;;       cmovaq  %rdi, %rsi
;;       movzbq  (%rsi), %rax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
