;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -W memory64 -O static-memory-maximum-size=0 -O static-memory-guard-size=4294967295 -O dynamic-memory-guard-size=4294967295"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0xffff0000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load8_u offset=0xffff0000))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    0x68(%rdi), %rax
;;       xorq    %r8, %r8
;;       movq    %rdx, %r9
;;       addq    0x60(%rdi), %r9
;;       movl    $0xffff0000, %edi
;;       leaq    (%r9, %rdi), %rsi
;;       cmpq    %rax, %rdx
;;       cmovaq  %r8, %rsi
;;       movb    %cl, (%rsi)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    0x68(%rdi), %rax
;;       xorq    %rcx, %rcx
;;       movq    %rdx, %r8
;;       addq    0x60(%rdi), %r8
;;       movl    $0xffff0000, %edi
;;       leaq    (%r8, %rdi), %rsi
;;       cmpq    %rax, %rdx
;;       cmovaq  %rcx, %rsi
;;       movzbq  (%rsi), %rax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
