;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation=false -O static-memory-maximum-size=0 -O static-memory-guard-size=4294967295 -O dynamic-memory-guard-size=4294967295"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0x1000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load8_u offset=0x1000))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movl    %edx, %esi
;;       cmpq    0x40(%rdi), %rsi
;;       ja      0x20
;;   10: movq    0x38(%rdi), %rdi
;;       movb    %cl, 0x1000(%rdi, %rsi)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   20: ud2
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movl    %edx, %esi
;;       cmpq    0x40(%rdi), %rsi
;;       ja      0x62
;;   50: movq    0x38(%rdi), %rdi
;;       movzbq  0x1000(%rdi, %rsi), %rax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   62: ud2
