;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0xffff0000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load8_u offset=0xffff0000))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    %rdi, %rsi
;;       movl    %edx, %edi
;;       movq    %rdi, %rax
;;       addq    0x2d(%rip), %rax
;;       jb      0x3e
;;   19: movq    %rsi, %r8
;;       movq    0x40(%r8), %rsi
;;       xorq    %rdx, %rdx
;;       addq    0x38(%r8), %rdi
;;       movl    $0xffff0000, %r8d
;;       addq    %r8, %rdi
;;       cmpq    %rsi, %rax
;;       cmovaq  %rdx, %rdi
;;       movb    %cl, (%rdi)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   3e: ud2
;;   40: addl    %eax, (%rax)
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    %rdi, %rcx
;;       movl    %edx, %edi
;;       movq    %rdi, %rax
;;       addq    0x35(%rip), %rax
;;       jb      0x9f
;;   79: movq    %rcx, %rsi
;;       movq    0x40(%rsi), %rdx
;;       xorq    %rcx, %rcx
;;       addq    0x38(%rsi), %rdi
;;       movl    $0xffff0000, %esi
;;       addq    %rdi, %rsi
;;       cmpq    %rdx, %rax
;;       cmovaq  %rcx, %rsi
;;       movzbq  (%rsi), %rax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   9f: ud2
;;   a1: addb    %al, (%rax)
;;   a3: addb    %al, (%rax)
;;   a5: addb    %al, (%rax)
;;   a7: addb    %al, (%rcx)
;;   a9: addb    %bh, %bh
;;   ab: incl    (%rax)
;;   ad: addb    %al, (%rax)
