;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-forced -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0x1000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0x1000))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movl    %edx, %r10d
;;       xorq    %r9, %r9
;;       movq    0x38(%rdi), %r11
;;       leaq    0x1000(%r11, %r10), %r8
;;       cmpq    0x13(%rip), %r10
;;       cmovaq  %r9, %r8
;;       movl    %ecx, (%r8)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   29: addb    %al, (%rax)
;;   2b: addb    %al, (%rax)
;;   2d: addb    %al, (%rax)
;;   2f: addb    %bh, %ah
;;   31: outl    %eax, %dx
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movl    %edx, %r10d
;;       xorq    %r9, %r9
;;       movq    0x38(%rdi), %r11
;;       leaq    0x1000(%r11, %r10), %r8
;;       cmpq    0x13(%rip), %r10
;;       cmovaq  %r9, %r8
;;       movl    (%r8), %eax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   69: addb    %al, (%rax)
;;   6b: addb    %al, (%rax)
;;   6d: addb    %al, (%rax)
;;   6f: addb    %bh, %ah
;;   71: outl    %eax, %dx
