;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation=false -O static-memory-maximum-size=0 -O static-memory-guard-size=4294967295 -O dynamic-memory-guard-size=4294967295"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load8_u offset=0))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movl    %edx, %r9d
;;       cmpq    0x68(%rdi), %r9
;;       setae   %r10b
;;       testb   %r10b, %r10b
;;       jne     0x25
;;   18: movq    0x60(%rdi), %rsi
;;       movb    %cl, (%rsi, %r9)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   25: ud2
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movl    %edx, %r9d
;;       cmpq    0x68(%rdi), %r9
;;       setae   %r10b
;;       testb   %r10b, %r10b
;;       jne     0x66
;;   58: movq    0x60(%rdi), %rsi
;;       movzbq  (%rsi, %r9), %rax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   66: ud2
