;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation=false -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    0x40(%rdi), %r8
;;       movl    %edx, %r10d
;;       subq    $4, %r8
;;       cmpq    %r8, %r10
;;       ja      0x25
;;   18: movq    0x38(%rdi), %rsi
;;       movl    %ecx, (%rsi, %r10)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   25: ud2
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    0x40(%rdi), %r8
;;       movl    %edx, %r10d
;;       subq    $4, %r8
;;       cmpq    %r8, %r10
;;       ja      0x65
;;   58: movq    0x38(%rdi), %rsi
;;       movl    (%rsi, %r10), %eax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   65: ud2
