;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    0x40(%rdi), %r8
;;       movl    %edx, %r10d
;;       subq    $4, %r8
;;       xorq    %r11, %r11
;;       movq    %r10, %r9
;;       addq    0x38(%rdi), %r9
;;       cmpq    %r8, %r10
;;       cmovaq  %r11, %r9
;;       movl    %ecx, (%r9)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    0x40(%rdi), %r8
;;       movl    %edx, %r10d
;;       subq    $4, %r8
;;       xorq    %r11, %r11
;;       movq    %r10, %r9
;;       addq    0x38(%rdi), %r9
;;       cmpq    %r8, %r10
;;       cmovaq  %r11, %r9
;;       movl    (%r9), %eax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
