;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0xffff0000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0xffff0000))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movl    %edx, %r10d
;;       movq    %r10, %rdx
;;       addq    0x2f(%rip), %rdx
;;       jb      0x3a
;;   17: movq    0x48(%rdi), %r9
;;       xorq    %r8, %r8
;;       addq    0x40(%rdi), %r10
;;       movl    $0xffff0000, %r11d
;;       addq    %r11, %r10
;;       cmpq    %r9, %rdx
;;       cmovaq  %r8, %r10
;;       movl    %ecx, (%r10)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   3a: ud2
;;   3c: addb    %al, (%rax)
;;   3e: addb    %al, (%rax)
;;   40: addb    $0, %al
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movl    %edx, %r10d
;;       movq    %r10, %rcx
;;       addq    0x2f(%rip), %rcx
;;       jb      0x9a
;;   77: movq    0x48(%rdi), %r8
;;       xorq    %rdx, %rdx
;;       addq    0x40(%rdi), %r10
;;       movl    $0xffff0000, %r9d
;;       addq    %r10, %r9
;;       cmpq    %r8, %rcx
;;       cmovaq  %rdx, %r9
;;       movl    (%r9), %eax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   9a: ud2
;;   9c: addb    %al, (%rax)
;;   9e: addb    %al, (%rax)
;;   a0: addb    $0, %al
