;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-forced -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movl    %edx, %r9d
;;       xorq    %r8, %r8
;;       movq    %r9, %r10
;;       addq    0x38(%rdi), %r10
;;       cmpq    0x10(%rip), %r9
;;       cmovaq  %r8, %r10
;;       movl    %ecx, (%r10)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   24: addb    %al, (%rax)
;;   26: addb    %al, (%rax)
;;   28: cld
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movl    %edx, %r9d
;;       xorq    %r8, %r8
;;       movq    %r9, %r10
;;       addq    0x38(%rdi), %r10
;;       cmpq    0x10(%rip), %r9
;;       cmovaq  %r8, %r10
;;       movl    (%r10), %eax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   64: addb    %al, (%rax)
;;   66: addb    %al, (%rax)
;;   68: cld
