;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation=false -W memory64 -O static-memory-forced -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store offset=0x1000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load offset=0x1000))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       cmpq    0x1d(%rip), %rdx
;;       ja      0x21
;;   11: movq    0x38(%rdi), %rsi
;;       movl    %ecx, 0x1000(%rsi, %rdx)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   21: ud2
;;   23: addb    %al, (%rax)
;;   25: addb    %al, (%rax)
;;   27: addb    %bh, %ah
;;   29: outl    %eax, %dx
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       cmpq    0x1d(%rip), %rdx
;;       ja      0x61
;;   51: movq    0x38(%rdi), %rsi
;;       movl    0x1000(%rsi, %rdx), %eax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   61: ud2
;;   63: addb    %al, (%rax)
;;   65: addb    %al, (%rax)
;;   67: addb    %bh, %ah
;;   69: outl    %eax, %dx
