;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation=false -W memory64 -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store offset=0xffff0000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load offset=0xffff0000))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    %rdx, %r9
;;       addq    0x2a(%rip), %r9
;;       jb      0x2f
;;   14: cmpq    0x40(%rdi), %r9
;;       ja      0x31
;;   1e: addq    0x38(%rdi), %rdx
;;       movl    $0xffff0000, %esi
;;       movl    %ecx, (%rdx, %rsi)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   2f: ud2
;;   31: ud2
;;   33: addb    %al, (%rax)
;;   35: addb    %al, (%rax)
;;   37: addb    %al, (%rax, %rax)
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    %rdx, %r9
;;       addq    0x2a(%rip), %r9
;;       jb      0x6f
;;   54: cmpq    0x40(%rdi), %r9
;;       ja      0x71
;;   5e: addq    0x38(%rdi), %rdx
;;       movl    $0xffff0000, %esi
;;       movl    (%rdx, %rsi), %eax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   6f: ud2
;;   71: ud2
;;   73: addb    %al, (%rax)
;;   75: addb    %al, (%rax)
;;   77: addb    %al, (%rax, %rax)
