;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation=false -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0xffff0000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0xffff0000))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movl    %edx, %esi
;;       movq    %rsi, %r8
;;       addq    0x28(%rip), %r8
;;       jb      0x33
;;   16: cmpq    0x40(%rdi), %r8
;;       ja      0x35
;;   20: addq    0x38(%rdi), %rsi
;;       movl    $0xffff0000, %r10d
;;       movl    %ecx, (%rsi, %r10)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   33: ud2
;;   35: ud2
;;   37: addb    %al, (%rax, %rax)
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movl    %edx, %esi
;;       movq    %rsi, %r8
;;       addq    0x28(%rip), %r8
;;       jb      0x73
;;   56: cmpq    0x40(%rdi), %r8
;;       ja      0x75
;;   60: addq    0x38(%rdi), %rsi
;;       movl    $0xffff0000, %r10d
;;       movl    (%rsi, %r10), %eax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   73: ud2
;;   75: ud2
;;   77: addb    %al, (%rax, %rax)
