;;! target = "x86_64"
;;! test = "compile"
;;! flags = " -C cranelift-enable-heap-access-spectre-mitigation -O static-memory-maximum-size=0 -O static-memory-guard-size=0 -O dynamic-memory-guard-size=0"

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0xffff0000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load8_u offset=0xffff0000))

;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movl    %edx, %r10d
;;       movq    %r10, %rax
;;       addq    0x2f(%rip), %rax
;;       jb      0x3a
;;   17: movq    0x58(%rdi), %r8
;;       xorq    %rdx, %rdx
;;       addq    0x50(%rdi), %r10
;;       movl    $0xffff0000, %r9d
;;       addq    %r10, %r9
;;       cmpq    %r8, %rax
;;       cmovaq  %rdx, %r9
;;       movb    %cl, (%r9)
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   3a: ud2
;;   3c: addb    %al, (%rax)
;;   3e: addb    %al, (%rax)
;;   40: addl    %eax, (%rax)
;;
;; wasm[0]::function[1]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movl    %edx, %r10d
;;       movq    %r10, %rax
;;       addq    0x2f(%rip), %rax
;;       jb      0x9b
;;   77: movq    0x58(%rdi), %rdx
;;       xorq    %rcx, %rcx
;;       addq    0x50(%rdi), %r10
;;       movl    $0xffff0000, %r8d
;;       addq    %r10, %r8
;;       cmpq    %rdx, %rax
;;       cmovaq  %rcx, %r8
;;       movzbq  (%r8), %rax
;;       movq    %rbp, %rsp
;;       popq    %rbp
;;       retq
;;   9b: ud2
;;   9d: addb    %al, (%rax)
;;   9f: addb    %al, (%rcx)
;;   a1: addb    %bh, %bh
;;   a3: incl    (%rax)
;;   a5: addb    %al, (%rax)
