test compile precise-output
target pulley64

function %i8_imm(i8) -> i8 {
block0(v0: i8):
  v3 = iconst.i8 7
  v2 = bxor v0, v3
  return v2
}

; VCode:
; block0:
;   xbxor32_s8 x0, x0, 7
;   ret
;
; Disassembled:
; xbxor32_s8 x0, x0, 7
; ret

function %i8_imm2(i8) -> i8 {
block0(v0: i8):
  v3 = iconst.i8 -7
  v2 = bxor v0, v3
  return v2
}

; VCode:
; block0:
;   xbxor32_s8 x0, x0, -7
;   ret
;
; Disassembled:
; xbxor32_s8 x0, x0, -7
; ret

function %i16_imm(i16) -> i16 {
block0(v0: i16):
  v3 = iconst.i16 7
  v2 = bxor v0, v3
  return v2
}

; VCode:
; block0:
;   xbxor32_s8 x0, x0, 7
;   ret
;
; Disassembled:
; xbxor32_s8 x0, x0, 7
; ret

function %i16_imm2(i16) -> i16 {
block0(v0: i16):
  v3 = iconst.i16 -7
  v2 = bxor v0, v3
  return v2
}

; VCode:
; block0:
;   xbxor32_s8 x0, x0, -7
;   ret
;
; Disassembled:
; xbxor32_s8 x0, x0, -7
; ret

function %i32_imm(i32) -> i32 {
block0(v0: i32):
  v3 = iconst.i32 7
  v2 = bxor v0, v3
  return v2
}

; VCode:
; block0:
;   xbxor32_s8 x0, x0, 7
;   ret
;
; Disassembled:
; xbxor32_s8 x0, x0, 7
; ret

function %i32_imm2(i32) -> i32 {
block0(v0: i32):
  v3 = iconst.i32 -7
  v2 = bxor v0, v3
  return v2
}

; VCode:
; block0:
;   xbxor32_s8 x0, x0, -7
;   ret
;
; Disassembled:
; xbxor32_s8 x0, x0, -7
; ret

function %i32_imm_big(i32) -> i32 {
block0(v0: i32):
  v3 = iconst.i32 77777
  v2 = bxor v0, v3
  return v2
}

; VCode:
; block0:
;   xbxor32_s32 x0, x0, 77777
;   ret
;
; Disassembled:
; xbxor32_s32 x0, x0, 77777
; ret

function %i32_imm_big2(i32) -> i32 {
block0(v0: i32):
  v3 = iconst.i32 -77777
  v2 = bxor v0, v3
  return v2
}

; VCode:
; block0:
;   xbxor32_s32 x0, x0, -77777
;   ret
;
; Disassembled:
; xbxor32_s32 x0, x0, -77777
; ret

function %i64_imm(i64) -> i64 {
block0(v0: i64):
  v3 = iconst.i64 7
  v2 = bxor v0, v3
  return v2
}

; VCode:
; block0:
;   xbxor64_s8 x0, x0, 7
;   ret
;
; Disassembled:
; xbxor64_s8 x0, x0, 7
; ret

function %i64_imm2(i64) -> i64 {
block0(v0: i64):
  v3 = iconst.i64 -7
  v2 = bxor v0, v3
  return v2
}

; VCode:
; block0:
;   xbxor64_s8 x0, x0, -7
;   ret
;
; Disassembled:
; xbxor64_s8 x0, x0, -7
; ret

function %i64_imm_big(i64) -> i64 {
block0(v0: i64):
  v3 = iconst.i64 77777
  v2 = bxor v0, v3
  return v2
}

; VCode:
; block0:
;   xbxor64_s32 x0, x0, 77777
;   ret
;
; Disassembled:
; xbxor64_s32 x0, x0, 77777
; ret

function %i64_imm_big2(i64) -> i64 {
block0(v0: i64):
  v3 = iconst.i64 -77777
  v2 = bxor v0, v3
  return v2
}

; VCode:
; block0:
;   xbxor64_s32 x0, x0, -77777
;   ret
;
; Disassembled:
; xbxor64_s32 x0, x0, -77777
; ret
