test compile precise-output
target pulley64

function %i8() -> i8 {
block0:
    v0 = iconst.i8 0xff
    return v0
}

; VCode:
; block0:
;   x0 = xconst16 255
;   ret
;
; Disassembled:
; xconst16 x0, 255
; ret

function %i16() -> i16 {
block0:
    v0 = iconst.i16 0xffff
    return v0
}

; VCode:
; block0:
;   x0 = xconst32 65535
;   ret
;
; Disassembled:
; xconst32 x0, 65535
; ret

function %i32() -> i32 {
block0:
    v0 = iconst.i32 0xffff_ffff
    return v0
}

; VCode:
; block0:
;   x0 = xconst32 -1
;   ret
;
; Disassembled:
; xconst32 x0, -1
; ret

function %i64() -> i64 {
block0:
    v0 = iconst.i64 0xffff_ffff_ffff_ffff
    return v0
}

; VCode:
; block0:
;   x0 = xconst64 -1
;   ret
;
; Disassembled:
; xconst64 x0, -1
; ret

