test compile precise-output
target pulley64 big_endian

function %load_i32(i64) -> i32 {
block0(v0: i64):
    v1 = load.i32 notrap v0
    return v1
}

; VCode:
; block0:
;   xload32be_o32 x0, x0, 0
;   ret
;
; Disassembled:
; xload32be_o32 x0, x0, 0
; ret

function %load_i64(i64) -> i64 {
block0(v0: i64):
    v1 = load.i64 notrap v0
    return v1
}

; VCode:
; block0:
;   xload64be_o32 x0, x0, 0
;   ret
;
; Disassembled:
; xload64be_o32 x0, x0, 0
; ret

function %load_i32_with_offset(i64) -> i32 {
block0(v0: i64):
    v1 = load.i32 notrap v0+4
    return v1
}

; VCode:
; block0:
;   xload32be_o32 x0, x0, 4
;   ret
;
; Disassembled:
; xload32be_o32 x0, x0, 4
; ret

function %load_i64_with_offset(i64) -> i64 {
block0(v0: i64):
    v1 = load.i64 notrap v0+8
    return v1
}

; VCode:
; block0:
;   xload64be_o32 x0, x0, 8
;   ret
;
; Disassembled:
; xload64be_o32 x0, x0, 8
; ret

