test compile precise-output
set preserve_frame_pointers
target pulley64

function %get_stack_pointer() -> i64 {
block0:
  v0 = get_stack_pointer.i64
  return v0
}

; VCode:
;   push_frame
; block0:
;   xmov x0, x30
;   pop_frame
;   ret
;
; Disassembled:
; push_frame
; xmov x0, sp
; pop_frame
; ret

function %get_frame_pointer() -> i64 {
block0:
  v0 = get_frame_pointer.i64
  return v0
}

; VCode:
;   push_frame
; block0:
;   xmov_fp x0
;   pop_frame
;   ret
;
; Disassembled:
; push_frame
; xmov_fp x0
; pop_frame
; ret

function %get_return_address() -> i64 {
block0:
  v0 = get_return_address.i64
  return v0
}

; VCode:
;   push_frame
; block0:
;   xmov_lr x0
;   pop_frame
;   ret
;
; Disassembled:
; push_frame
; xmov_lr x0
; pop_frame
; ret

