test compile precise-output
target pulley64

function %store_i32(i32, i64) {
block0(v0: i32, v1: i64):
    store v0, v1
    return
}

; VCode:
; block0:
;   xstore32le_z x1, 0, x0
;   ret
;
; Disassembled:
; xstore32le_z x1, 0, x0
; ret

function %store_i64(i64, i64) {
block0(v0: i64, v1: i64):
    store v0, v1
    return
}

; VCode:
; block0:
;   xstore64le_z x1, 0, x0
;   ret
;
; Disassembled:
; xstore64le_z x1, 0, x0
; ret

function %store_i32_with_offset(i32, i64) {
block0(v0: i32, v1: i64):
    store v0, v1+4
    return
}

; VCode:
; block0:
;   xstore32le_z x1, 4, x0
;   ret
;
; Disassembled:
; xstore32le_z x1, 4, x0
; ret

function %store_i64_with_offset(i64, i64) {
block0(v0: i64, v1: i64):
    store v0, v1+8
    return
}

; VCode:
; block0:
;   xstore64le_z x1, 8, x0
;   ret
;
; Disassembled:
; xstore64le_z x1, 8, x0
; ret

