test compile precise-output
target pulley64

function %trap() {
block0:
  trap user1
}

; VCode:
; block0:
;   trap // trap=TrapCode(1)
;
; Disassembled:
; trap

function %trapnz(i64) {
block0(v0: i64):
  v1 = iconst.i64 42
  v2 = icmp eq v0, v1
  trapnz v2, user1
  return
}

; VCode:
; block0:
;   trap_if_xeq64_i32 x0, 42 // code = TrapCode(1)
;   ret
;
; Disassembled:
; br_if_xeq64_i8 x0, 42, 0x8    // target = 0x8
; ret
; trap

function %trapz(i64) {
block0(v0: i64):
  v1 = iconst.i64 42
  v2 = icmp eq v0, v1
  trapz v2, user1
  return
}

; VCode:
; block0:
;   trap_if_xneq64_i32 x0, 42 // code = TrapCode(1)
;   ret
;
; Disassembled:
; br_if_xneq64_i8 x0, 42, 0x8    // target = 0x8
; ret
; trap

function %trapnz_icmp_fold(i64) {
block0(v0: i64):
  v1 = iconst.i64 42
  v2 = icmp eq v0, v1
  trapnz v2, user1
  return
}

; VCode:
; block0:
;   trap_if_xeq64_i32 x0, 42 // code = TrapCode(1)
;   ret
;
; Disassembled:
; br_if_xeq64_i8 x0, 42, 0x8    // target = 0x8
; ret
; trap

function %trapz_icmp_fold(i64) {
block0(v0: i64):
  v1 = iconst.i64 42
  v2 = icmp eq v0, v1
  trapz v2, user1
  return
}

; VCode:
; block0:
;   trap_if_xneq64_i32 x0, 42 // code = TrapCode(1)
;   ret
;
; Disassembled:
; br_if_xneq64_i8 x0, 42, 0x8    // target = 0x8
; ret
; trap

function %trapnz_iconst_fold(i64) {
block0(v0: i64):
  brif v0, block1, block2

block1:
  v1 = iconst.i64 42
  trapnz v1, user1
  return

block2:
  v2 = iconst.i64 0
  trapnz v2, user1
  return
}

; VCode:
; block0:
;   br_if_xneq64_i32 x0, 0, label2; jump label1
; block1:
;   xzero x4
;   trap_if_xneq64_i32 x4, 0 // code = TrapCode(1)
;   ret
; block2:
;   xconst8 x6, 42
;   trap_if_xneq64_i32 x6, 0 // code = TrapCode(1)
;   ret
;
; Disassembled:
; br_if_xneq64_i8 x0, 0, 0x11    // target = 0x11
; xzero x4
; br_if_xneq64_i8 x4, 0, 0x13    // target = 0x1c
; ret
; xconst8 x6, 42
; br_if_xneq64_i8 x6, 0, 0xb    // target = 0x1f
; ret
; trap
; trap

function %trapz_iconst_fold(i64) {
block0(v0: i64):
  brif v0, block1, block2

block1:
  v1 = iconst.i64 42
  trapz v1, user1
  return

block2:
  v2 = iconst.i64 0
  trapz v2, user1
  return
}

; VCode:
; block0:
;   br_if_xneq64_i32 x0, 0, label2; jump label1
; block1:
;   xzero x4
;   trap_if_xeq64_i32 x4, 0 // code = TrapCode(1)
;   ret
; block2:
;   xconst8 x6, 42
;   trap_if_xeq64_i32 x6, 0 // code = TrapCode(1)
;   ret
;
; Disassembled:
; br_if_xneq64_i8 x0, 0, 0x11    // target = 0x11
; xzero x4
; br_if_xeq64_i8 x4, 0, 0x13    // target = 0x1c
; ret
; xconst8 x6, 42
; br_if_xeq64_i8 x6, 0, 0xb    // target = 0x1f
; ret
; trap
; trap

