;;! component_model_async = true
;;! component_model_forward = true

;; Copies which have already made partial progress when `stream.forward` is
;; called keep their remaining buffers on the merged stream.
(component definition $Tester
  (core module $Memory (memory (export "mem") 1))
  (core instance $memory (instantiate $Memory))
  (core module $M
    (import "" "mem" (memory 1))
    (import "" "waitable-set.new" (func $waitable-set.new (result i32)))
    (import "" "waitable-set.poll" (func $waitable-set.poll (param i32 i32) (result i32)))
    (import "" "waitable.join" (func $waitable.join (param i32 i32)))
    (import "" "stream.new" (func $stream.new (result i64)))
    (import "" "stream.read" (func $stream.read (param i32 i32 i32) (result i32)))
    (import "" "stream.write" (func $stream.write (param i32 i32 i32) (result i32)))
    (import "" "stream.forward" (func $stream.forward (param i32 i32)))

    (global $rA (mut i32) (i32.const 0))
    (global $wA (mut i32) (i32.const 0))
    (global $rB (mut i32) (i32.const 0))
    (global $wB (mut i32) (i32.const 0))

    (func $new-ab
      (local $ret64 i64)
      (local.set $ret64 (call $stream.new))
      (global.set $rA (i32.wrap_i64 (local.get $ret64)))
      (global.set $wA (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))
      (local.set $ret64 (call $stream.new))
      (global.set $rB (i32.wrap_i64 (local.get $ret64)))
      (global.set $wB (i32.wrap_i64 (i64.shr_u (local.get $ret64) (i64.const 32))))
    )

    (func $poll (param $waitable i32) (param $code i32) (param $payload i32)
      (local $ws i32)
      (local.set $ws (call $waitable-set.new))
      (call $waitable.join (local.get $waitable) (local.get $ws))
      (if (i32.ne (local.get $code) (call $waitable-set.poll (local.get $ws) (i32.const 32)))
        (then unreachable))
      (if (i32.ne (local.get $waitable) (i32.load (i32.const 32)))
        (then unreachable))
      (if (i32.ne (local.get $payload) (i32.load (i32.const 36)))
        (then unreachable))
      (call $waitable.join (local.get $waitable) (i32.const 0))
    )

    ;; the rest of a partially-consumed write rendezvouses with a read pending
    ;; on the destination during the forward
    (func (export "partial-write-then-forward") (result i32)
      (local $ret i32)
      (call $new-ab)
      (i32.store (i32.const 0) (i32.const 0x04030201))
      (local.set $ret (call $stream.write (global.get $wA) (i32.const 0) (i32.const 4)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (local.set $ret (call $stream.read (global.get $rA) (i32.const 16) (i32.const 2)))
      (if (i32.ne (i32.const 0x20 (; COMPLETED=0 | (2<<4) ;)) (local.get $ret))
        (then unreachable))
      (local.set $ret (call $stream.read (global.get $rB) (i32.const 24) (i32.const 2)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (call $stream.forward (global.get $rA) (global.get $wB))
      (call $poll (global.get $rB) (i32.const 2 (; STREAM_READ ;)) (i32.const 0x20))
      (if (i32.ne (i32.const 0x0403) (i32.load16_u (i32.const 24)))
        (then unreachable))
      (call $poll (global.get $wA) (i32.const 3 (; STREAM_WRITE ;)) (i32.const 0x40))
      (i32.const 42)
    )

    ;; a pending read which is only partially filled by the rendezvous during
    ;; the forward keeps the rest of its buffer
    (func (export "forward-then-partial-read") (result i32)
      (local $ret i32)
      (call $new-ab)
      (local.set $ret (call $stream.read (global.get $rB) (i32.const 8) (i32.const 4)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (i32.store (i32.const 0) (i32.const 0x06050201))
      (local.set $ret (call $stream.write (global.get $wA) (i32.const 0) (i32.const 2)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (call $stream.forward (global.get $rA) (global.get $wB))
      (call $poll (global.get $wA) (i32.const 3 (; STREAM_WRITE ;)) (i32.const 0x20))
      (local.set $ret (call $stream.write (global.get $wA) (i32.const 2) (i32.const 2)))
      (if (i32.ne (i32.const 0x20 (; COMPLETED=0 | (2<<4) ;)) (local.get $ret))
        (then unreachable))
      (call $poll (global.get $rB) (i32.const 2 (; STREAM_READ ;)) (i32.const 0x40))
      (if (i32.ne (i32.const 0x06050201) (i32.load (i32.const 8)))
        (then unreachable))
      (i32.const 42)
    )

    ;; a pending read which was partially filled before the forward keeps the
    ;; rest of its buffer and accumulates further progress
    (func (export "partial-read-then-forward") (result i32)
      (local $ret i32)
      (call $new-ab)
      (local.set $ret (call $stream.read (global.get $rB) (i32.const 8) (i32.const 4)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (i32.store (i32.const 0) (i32.const 0x06050201))
      (local.set $ret (call $stream.write (global.get $wB) (i32.const 0) (i32.const 2)))
      (if (i32.ne (i32.const 0x20 (; COMPLETED=0 | (2<<4) ;)) (local.get $ret))
        (then unreachable))
      (local.set $ret (call $stream.write (global.get $wA) (i32.const 2) (i32.const 2)))
      (if (i32.ne (i32.const -1 (; BLOCKED ;)) (local.get $ret))
        (then unreachable))
      (call $stream.forward (global.get $rA) (global.get $wB))
      (call $poll (global.get $wA) (i32.const 3 (; STREAM_WRITE ;)) (i32.const 0x20))
      (call $poll (global.get $rB) (i32.const 2 (; STREAM_READ ;)) (i32.const 0x40))
      (if (i32.ne (i32.const 0x06050201) (i32.load (i32.const 8)))
        (then unreachable))
      (i32.const 42)
    )
  )
  (type $ST (stream u8))
  (canon waitable-set.new (core func $waitable-set.new))
  (canon waitable-set.poll (memory (core memory $memory "mem")) (core func $waitable-set.poll))
  (canon waitable.join (core func $waitable.join))
  (canon stream.new $ST (core func $stream.new))
  (canon stream.read $ST async (memory (core memory $memory "mem")) (core func $stream.read))
  (canon stream.write $ST async (memory (core memory $memory "mem")) (core func $stream.write))
  (canon stream.forward $ST (core func $stream.forward))
  (core instance $m (instantiate $M (with "" (instance
    (export "mem" (memory $memory "mem"))
    (export "waitable-set.new" (func $waitable-set.new))
    (export "waitable-set.poll" (func $waitable-set.poll))
    (export "waitable.join" (func $waitable.join))
    (export "stream.new" (func $stream.new))
    (export "stream.read" (func $stream.read))
    (export "stream.write" (func $stream.write))
    (export "stream.forward" (func $stream.forward))
  ))))
  (func (export "partial-write-then-forward") (result u32)
    (canon lift (core func $m "partial-write-then-forward")))
  (func (export "forward-then-partial-read") (result u32)
    (canon lift (core func $m "forward-then-partial-read")))
  (func (export "partial-read-then-forward") (result u32)
    (canon lift (core func $m "partial-read-then-forward")))
)

(component instance $i $Tester)
(assert_return (invoke "partial-write-then-forward") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "forward-then-partial-read") (u32.const 42))
(component instance $i $Tester)
(assert_return (invoke "partial-read-then-forward") (u32.const 42))
