;;! target = "x86_64"
(module
  (func (export "large") (param i32) (result i32)
    (block
      (block
        (br_table
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
          (local.get 0)
        )
        (return (i32.const -1))
      )
      (return (i32.const 0))
    )
    (return (i32.const 1))
  )
)
;;      	 55                   	push	rbp
;;      	 4889e5               	mov	rbp, rsp
;;      	 4989fe               	mov	r14, rdi
;;      	 4d8b5e08             	mov	r11, qword ptr [r14 + 8]
;;      	 4d8b1b               	mov	r11, qword ptr [r11]
;;      	 4981c318000000       	add	r11, 0x18
;;      	 4939e3               	cmp	r11, rsp
;;      	 0f87e6800100         	ja	0x18104
;;   1e:	 4883ec18             	sub	rsp, 0x18
;;      	 48897c2410           	mov	qword ptr [rsp + 0x10], rdi
;;      	 4889742408           	mov	qword ptr [rsp + 8], rsi
;;      	 89542404             	mov	dword ptr [rsp + 4], edx
;;      	 8b442404             	mov	eax, dword ptr [rsp + 4]
;;      	 b927600000           	mov	ecx, 0x6027
;;      	 39c1                 	cmp	ecx, eax
;;      	 0f42c1               	cmovb	eax, ecx
;;      	 4c8d1d0a000000       	lea	r11, [rip + 0xa]
;;      	 49630c83             	movsxd	rcx, dword ptr [r11 + rax*4]
;;      	 4901cb               	add	r11, rcx
;;      	 41ffe3               	jmp	r11
;;   4f:	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 a0800100aa800100a0   	
;; 				movabs	al, byte ptr [0xa0000180aa000180]
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 aa                   	stosb	byte ptr [rdi], al
;;      	 800100               	add	byte ptr [rcx], 0
;;      	 b800000000           	mov	eax, 0
;;      	 e905000000           	jmp	0x180fe
;; 180f9:	 b801000000           	mov	eax, 1
;;      	 4883c418             	add	rsp, 0x18
;;      	 5d                   	pop	rbp
;;      	 c3                   	ret	
;; 18104:	 0f0b                 	ud2	
