test compile precise-output
target s390x arch13

function %atomic_rmw_nand_i64(i64, i64, i64) -> i64 {
block0(v0: i64, v1: i64, v2: i64):
  v3 = atomic_rmw.i64 nand v1, v2
  return v3
}

; VCode:
; block0:
;   lg %r0, 0(%r3)
;   0: nngrk %r1, %r0, %r4 ; csg %r0, %r1, 0(%r3) ; jglh 0b ; 1:
;   lgr %r2, %r0
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lg %r0, 0(%r3) ; trap: heap_oob
;   .byte 0xb9, 0x64
;   sth %r1, 0xb01(%r14) ; trap: heap_oob
;   lper %f0, %f0
;   .byte 0x00, 0x30
;   jglh 6
;   lgr %r2, %r0
;   br %r14

function %atomic_rmw_nand_i32(i64, i64, i32) -> i32 {
block0(v0: i64, v1: i64, v2: i32):
  v3 = atomic_rmw.i32 nand v1, v2
  return v3
}

; VCode:
; block0:
;   l %r0, 0(%r3)
;   0: nnrk %r1, %r0, %r4 ; cs %r0, %r1, 0(%r3) ; jglh 0b ; 1:
;   lgr %r2, %r0
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   l %r0, 0(%r3) ; trap: heap_oob
;   .byte 0xb9, 0x74
;   sth %r1, 0xa01(%r11) ; trap: heap_oob
;   lper %f0, %f0
;   jglh 4
;   lgr %r2, %r0
;   br %r14

function %atomic_rmw_nand_i16(i64, i64, i16) -> i16 {
block0(v0: i64, v1: i64, v2: i16):
  v3 = atomic_rmw.i16 nand v1, v2
  return v3
}

; VCode:
; block0:
;   lgr %r2, %r4
;   sllk %r4, %r3, 3
;   nill %r3, 65532
;   l %r0, 0(%r3)
;   0: rll %r1, %r0, 0(%r4) ; rnsbg %r1, %r2, 32, 48, 16 ; xilf %r1, 4294901760 ; rll %r1, %r1, 0(%r4) ; cs %r0, %r1, 0(%r3) ; jglh 0b ; 1:
;   rll %r2, %r0, 16(%r4)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgr %r2, %r4
;   sllk %r4, %r3, 3
;   nill %r3, 0xfffc
;   l %r0, 0(%r3) ; trap: heap_oob
;   rll %r1, %r0, 0(%r4)
;   rnsbg %r1, %r2, 0x20, 0x30, 0x10
;   xilf %r1, 0xffff0000
;   rll %r1, %r1, 0(%r4)
;   cs %r0, %r1, 0(%r3) ; trap: heap_oob
;   jglh 0x12
;   rll %r2, %r0, 0x10(%r4)
;   br %r14

function %atomic_rmw_nand_i8(i64, i64, i8) -> i8 {
block0(v0: i64, v1: i64, v2: i8):
  v3 = atomic_rmw.i8 nand v1, v2
  return v3
}

; VCode:
; block0:
;   lgr %r5, %r4
;   sllk %r4, %r3, 3
;   nill %r3, 65532
;   lcr %r2, %r4
;   l %r0, 0(%r3)
;   0: rll %r1, %r0, 0(%r4) ; rnsbg %r1, %r5, 32, 40, 24 ; xilf %r1, 4278190080 ; rll %r1, %r1, 0(%r2) ; cs %r0, %r1, 0(%r3) ; jglh 0b ; 1:
;   rll %r2, %r0, 8(%r4)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgr %r5, %r4
;   sllk %r4, %r3, 3
;   nill %r3, 0xfffc
;   lcr %r2, %r4
;   l %r0, 0(%r3) ; trap: heap_oob
;   rll %r1, %r0, 0(%r4)
;   rnsbg %r1, %r5, 0x20, 0x28, 0x18
;   xilf %r1, 0xff000000
;   rll %r1, %r1, 0(%r2)
;   cs %r0, %r1, 0(%r3) ; trap: heap_oob
;   jglh 0x14
;   rll %r2, %r0, 8(%r4)
;   br %r14

function %atomic_rmw_nand_i64(i64, i64, i64) -> i64 {
block0(v0: i64, v1: i64, v2: i64):
  v3 = atomic_rmw.i64 little nand v1, v2
  return v3
}

; VCode:
; block0:
;   lrvgr %r4, %r4
;   lg %r0, 0(%r3)
;   0: nngrk %r1, %r0, %r4 ; csg %r0, %r1, 0(%r3) ; jglh 0b ; 1:
;   lrvgr %r2, %r0
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lrvgr %r4, %r4
;   lg %r0, 0(%r3) ; trap: heap_oob
;   .byte 0xb9, 0x64
;   sth %r1, 0xb01(%r14) ; trap: heap_oob
;   lper %f0, %f0
;   .byte 0x00, 0x30
;   jglh 0xa
;   lrvgr %r2, %r0
;   br %r14

function %atomic_rmw_nand_i32(i64, i64, i32) -> i32 {
block0(v0: i64, v1: i64, v2: i32):
  v3 = atomic_rmw.i32 little nand v1, v2
  return v3
}

; VCode:
; block0:
;   lrvr %r4, %r4
;   l %r0, 0(%r3)
;   0: nnrk %r1, %r0, %r4 ; cs %r0, %r1, 0(%r3) ; jglh 0b ; 1:
;   lrvr %r2, %r0
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lrvr %r4, %r4
;   l %r0, 0(%r3) ; trap: heap_oob
;   .byte 0xb9, 0x74
;   sth %r1, 0xa01(%r11) ; trap: heap_oob
;   lper %f0, %f0
;   jglh 8
;   lrvr %r2, %r0
;   br %r14

function %atomic_rmw_nand_i16(i64, i64, i16) -> i16 {
block0(v0: i64, v1: i64, v2: i16):
  v3 = atomic_rmw.i16 little nand v1, v2
  return v3
}

; VCode:
; block0:
;   lgr %r2, %r4
;   sllk %r4, %r3, 3
;   nill %r3, 65532
;   lrvr %r2, %r2
;   l %r0, 0(%r3)
;   0: rll %r1, %r0, 16(%r4) ; rnsbg %r1, %r2, 48, 64, 48 ; xilf %r1, 65535 ; rll %r1, %r1, 16(%r4) ; cs %r0, %r1, 0(%r3) ; jglh 0b ; 1:
;   rll %r2, %r0, 0(%r4)
;   lrvr %r2, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgr %r2, %r4
;   sllk %r4, %r3, 3
;   nill %r3, 0xfffc
;   lrvr %r2, %r2
;   l %r0, 0(%r3) ; trap: heap_oob
;   rll %r1, %r0, 0x10(%r4)
;   rnsbg %r1, %r2, 0x30, 0x40, 0x30
;   xilf %r1, 0xffff
;   rll %r1, %r1, 0x10(%r4)
;   cs %r0, %r1, 0(%r3) ; trap: heap_oob
;   jglh 0x16
;   rll %r2, %r0, 0(%r4)
;   lrvr %r2, %r2
;   br %r14

function %atomic_rmw_nand_i8(i64, i64, i8) -> i8 {
block0(v0: i64, v1: i64, v2: i8):
  v3 = atomic_rmw.i8 little nand v1, v2
  return v3
}

; VCode:
; block0:
;   lgr %r5, %r4
;   sllk %r4, %r3, 3
;   nill %r3, 65532
;   lcr %r2, %r4
;   l %r0, 0(%r3)
;   0: rll %r1, %r0, 0(%r4) ; rnsbg %r1, %r5, 32, 40, 24 ; xilf %r1, 4278190080 ; rll %r1, %r1, 0(%r2) ; cs %r0, %r1, 0(%r3) ; jglh 0b ; 1:
;   rll %r2, %r0, 8(%r4)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgr %r5, %r4
;   sllk %r4, %r3, 3
;   nill %r3, 0xfffc
;   lcr %r2, %r4
;   l %r0, 0(%r3) ; trap: heap_oob
;   rll %r1, %r0, 0(%r4)
;   rnsbg %r1, %r5, 0x20, 0x28, 0x18
;   xilf %r1, 0xff000000
;   rll %r1, %r1, 0(%r2)
;   cs %r0, %r1, 0(%r3) ; trap: heap_oob
;   jglh 0x14
;   rll %r2, %r0, 8(%r4)
;   br %r14

