test compile precise-output
target s390x

function %atomic_store_i64(i64, i64) {
block0(v0: i64, v1: i64):
  atomic_store.i64 little v0, v1
  return
}

; VCode:
; block0:
;   strvg %r2, 0(%r3)
;   bcr 14, 0
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   strvg %r2, 0(%r3) ; trap: heap_oob
;   bnor %r0
;   br %r14

function %atomic_store_i64_sym(i64) {
  gv0 = symbol colocated %sym
block0(v0: i64):
  v1 = symbol_value.i64 gv0
  atomic_store.i64 aligned little v0, v1
  return
}

; VCode:
; block0:
;   larl %r1, %sym + 0 ; strvg %r2, 0(%r1)
;   bcr 14, 0
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   larl %r1, 0 ; reloc_external PCRel32Dbl %sym 2
;   strvg %r2, 0(%r1) ; trap: heap_oob
;   bnor %r0
;   br %r14

function %atomic_store_imm_i64(i64) {
block0(v0: i64):
  v1 = iconst.i64 12345
  atomic_store.i64 little v1, v0
  return
}

; VCode:
; block0:
;   lghi %r4, 12345
;   strvg %r4, 0(%r2)
;   bcr 14, 0
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lghi %r4, 0x3039
;   strvg %r4, 0(%r2) ; trap: heap_oob
;   bnor %r0
;   br %r14

function %atomic_store_i32(i32, i64) {
block0(v0: i32, v1: i64):
  atomic_store.i32 little v0, v1
  return
}

; VCode:
; block0:
;   strv %r2, 0(%r3)
;   bcr 14, 0
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   strv %r2, 0(%r3) ; trap: heap_oob
;   bnor %r0
;   br %r14

function %atomic_store_i32_sym(i32) {
  gv0 = symbol colocated %sym
block0(v0: i32):
  v1 = symbol_value.i64 gv0
  atomic_store.i32 aligned little v0, v1
  return
}

; VCode:
; block0:
;   larl %r1, %sym + 0 ; strv %r2, 0(%r1)
;   bcr 14, 0
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   larl %r1, 0 ; reloc_external PCRel32Dbl %sym 2
;   strv %r2, 0(%r1) ; trap: heap_oob
;   bnor %r0
;   br %r14

function %atomic_store_imm_i32(i64) {
block0(v0: i64):
  v1 = iconst.i32 12345
  atomic_store.i32 little v1, v0
  return
}

; VCode:
; block0:
;   lhi %r4, 12345
;   strv %r4, 0(%r2)
;   bcr 14, 0
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lhi %r4, 0x3039
;   strv %r4, 0(%r2) ; trap: heap_oob
;   bnor %r0
;   br %r14

function %atomic_store_i16(i16, i64) {
block0(v0: i16, v1: i64):
  atomic_store.i16 little v0, v1
  return
}

; VCode:
; block0:
;   strvh %r2, 0(%r3)
;   bcr 14, 0
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   strvh %r2, 0(%r3) ; trap: heap_oob
;   bnor %r0
;   br %r14

function %atomic_store_i16_sym(i16) {
  gv0 = symbol colocated %sym
block0(v0: i16):
  v1 = symbol_value.i64 gv0
  atomic_store.i16 aligned little v0, v1
  return
}

; VCode:
; block0:
;   larl %r1, %sym + 0 ; strvh %r2, 0(%r1)
;   bcr 14, 0
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   larl %r1, 0 ; reloc_external PCRel32Dbl %sym 2
;   strvh %r2, 0(%r1) ; trap: heap_oob
;   bnor %r0
;   br %r14

function %atomic_store_imm_i16(i64) {
block0(v0: i64):
  v1 = iconst.i16 12345
  atomic_store.i16 little v1, v0
  return
}

; VCode:
; block0:
;   mvhhi 0(%r2), 14640
;   bcr 14, 0
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   mvhhi 0(%r2), 0x3930 ; trap: heap_oob
;   bnor %r0
;   br %r14

function %atomic_store_i8(i8, i64) {
block0(v0: i8, v1: i64):
  atomic_store.i8 little v0, v1
  return
}

; VCode:
; block0:
;   stc %r2, 0(%r3)
;   bcr 14, 0
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   stc %r2, 0(%r3) ; trap: heap_oob
;   bnor %r0
;   br %r14

function %atomic_store_imm_i8(i64) {
block0(v0: i64):
  v1 = iconst.i8 123
  atomic_store.i8 little v1, v0
  return
}

; VCode:
; block0:
;   mvi 0(%r2), 123
;   bcr 14, 0
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   mvi 0(%r2), 0x7b ; trap: heap_oob
;   bnor %r0
;   br %r14

