test compile precise-output
target s390x

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; ATOMIC_CAS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

function %atomic_cas_i64(i64, i64, i64) -> i64 {
block0(v0: i64, v1: i64, v2: i64):
  v3 = atomic_cas.i64 v2, v0, v1
  return v3
}

; VCode:
; block0:
;   csg %r2, %r3, 0(%r4)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   csg %r2, %r3, 0(%r4) ; trap: heap_oob
;   br %r14

function %atomic_cas_i32(i32, i32, i64) -> i32 {
block0(v0: i32, v1: i32, v2: i64):
  v3 = atomic_cas.i32 v2, v0, v1
  return v3
}

; VCode:
; block0:
;   cs %r2, %r3, 0(%r4)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   cs %r2, %r3, 0(%r4) ; trap: heap_oob
;   br %r14

function %atomic_cas_i16(i64, i16, i16, i64) -> i16 {
block0(v0: i64, v1: i16, v2: i16, v3: i64):
  v4 = atomic_cas.i16 v3, v1, v2
  return v4
}

; VCode:
; block0:
;   lgr %r2, %r4
;   sllk %r4, %r5, 3
;   nill %r5, 65532
;   l %r0, 0(%r5)
;   0: rll %r1, %r0, 0(%r4) ; rxsbg %r1, %r3, 160, 47, 16 ; jglh 1f ; risbgn %r1, %r2, 32, 47, 16 ; rll %r1, %r1, 0(%r4) ; cs %r0, %r1, 0(%r5) ; jglh 0b ; 1:
;   rll %r2, %r0, 16(%r4)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgr %r2, %r4
;   sllk %r4, %r5, 3
;   nill %r5, 0xfffc
;   l %r0, 0(%r5) ; trap: heap_oob
;   rll %r1, %r0, 0(%r4)
;   rxsbg %r1, %r3, 0xa0, 0x2f, 0x10
;   jglh 0x3a
;   risbgn %r1, %r2, 0x20, 0x2f, 0x10
;   rll %r1, %r1, 0(%r4)
;   cs %r0, %r1, 0(%r5) ; trap: heap_oob
;   jglh 0x12
;   rll %r2, %r0, 0x10(%r4)
;   br %r14

function %atomic_cas_i8(i64, i8, i8, i64) -> i8 {
block0(v0: i64, v1: i8, v2: i8, v3: i64):
  v4 = atomic_cas.i8 v3, v1, v2
  return v4
}

; VCode:
;   stmg %r12, %r15, 96(%r15)
; block0:
;   lgr %r12, %r4
;   sllk %r4, %r5, 3
;   nill %r5, 65532
;   lcr %r2, %r4
;   l %r0, 0(%r5)
;   0: rll %r1, %r0, 0(%r4) ; rxsbg %r1, %r3, 160, 39, 24 ; jglh 1f ; risbgn %r1, %r12, 32, 39, 24 ; rll %r1, %r1, 0(%r2) ; cs %r0, %r1, 0(%r5) ; jglh 0b ; 1:
;   rll %r2, %r0, 8(%r4)
;   lmg %r12, %r15, 96(%r15)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r12, %r15, 0x60(%r15)
; block1: ; offset 0x6
;   lgr %r12, %r4
;   sllk %r4, %r5, 3
;   nill %r5, 0xfffc
;   lcr %r2, %r4
;   l %r0, 0(%r5) ; trap: heap_oob
;   rll %r1, %r0, 0(%r4)
;   rxsbg %r1, %r3, 0xa0, 0x27, 0x18
;   jglh 0x42
;   risbgn %r1, %r12, 0x20, 0x27, 0x18
;   rll %r1, %r1, 0(%r2)
;   cs %r0, %r1, 0(%r5) ; trap: heap_oob
;   jglh 0x1a
;   rll %r2, %r0, 8(%r4)
;   lmg %r12, %r15, 0x60(%r15)
;   br %r14

