test compile precise-output
target s390x

;; Bitcast between integral types is a no-op.

function %bitcast_i8_i8(i8) -> i8 {
block0(v0: i8):
  v1 = bitcast.i8 v0
  return v1
}

; VCode:
; block0:
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   br %r14

function %bitcast_i16_i16(i16) -> i16 {
block0(v0: i16):
  v1 = bitcast.i16 v0
  return v1
}

; VCode:
; block0:
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   br %r14

function %bitcast_i32_i32(i32) -> i32 {
block0(v0: i32):
  v1 = bitcast.i32 v0
  return v1
}

; VCode:
; block0:
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   br %r14

function %bitcast_i64_i64(i64) -> i64 {
block0(v0: i64):
  v1 = bitcast.i64 v0
  return v1
}

; VCode:
; block0:
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   br %r14

function %bitcast_i128_i128(i128) -> i128 {
block0(v0: i128):
  v1 = bitcast.i128 v0
  return v1
}

; VCode:
; block0:
;   vl %v1, 0(%r3)
;   vst %v1, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r3)
;   vst %v1, 0(%r2)
;   br %r14
