test compile precise-output
set enable_multi_ret_implicit_sret
target s390x arch15

function %clz_i128(i128) -> i128 {
block0(v0: i128):
    v1 = clz v0
    return v1
}

; VCode:
; block0:
;   vl %v1, 0(%r3)
;   vclzq %v4, %v1
;   vst %v4, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r3)
;   vclz %v4, %v1, 4
;   vst %v4, 0(%r2)
;   br %r14

function %clz_i64(i64) -> i64 {
block0(v0: i64):
    v1 = clz v0
    return v1
}

; VCode:
; block0:
;   clzg %r2, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0x68
;   .byte 0x00, 0x22
;   br %r14

function %clz_i32(i32) -> i32 {
block0(v0: i32):
    v1 = clz v0
    return v1
}

; VCode:
; block0:
;   llgfr %r2, %r2
;   clzg %r4, %r2
;   ahik %r2, %r4, -32
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llgfr %r2, %r2
;   .byte 0xb9, 0x68
;   .byte 0x00, 0x42
;   ahik %r2, %r4, -0x20
;   br %r14

function %clz_i16(i16) -> i16 {
block0(v0: i16):
    v1 = clz v0
    return v1
}

; VCode:
; block0:
;   llghr %r2, %r2
;   clzg %r4, %r2
;   ahik %r2, %r4, -48
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llghr %r2, %r2
;   .byte 0xb9, 0x68
;   .byte 0x00, 0x42
;   ahik %r2, %r4, -0x30
;   br %r14

function %clz_i8(i8) -> i8 {
block0(v0: i8):
    v1 = clz v0
    return v1
}

; VCode:
; block0:
;   llgcr %r2, %r2
;   clzg %r4, %r2
;   ahik %r2, %r4, -56
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llgcr %r2, %r2
;   .byte 0xb9, 0x68
;   .byte 0x00, 0x42
;   ahik %r2, %r4, -0x38
;   br %r14

function %cls_i128(i128) -> i128 {
block0(v0: i128):
    v1 = cls v0
    return v1
}

; VCode:
; block0:
;   vl %v1, 0(%r3)
;   vrepib %v4, 255
;   vsrab %v6, %v1, %v4
;   vsra %v16, %v6, %v4
;   vx %v16, %v1, %v16
;   vclzq %v16, %v16
;   vaq %v16, %v16, %v4
;   vst %v16, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r3)
;   vrepib %v4, 0xff
;   vsrab %v6, %v1, %v4
;   vsra %v16, %v6, %v4
;   vx %v16, %v1, %v16
;   vclz %v16, %v16, 4
;   vaq %v16, %v16, %v4
;   vst %v16, 0(%r2)
;   br %r14

function %cls_i64(i64) -> i64 {
block0(v0: i64):
    v1 = cls v0
    return v1
}

; VCode:
; block0:
;   srag %r3, %r2, 63
;   xgrk %r4, %r2, %r3
;   clzg %r2, %r4
;   aghi %r2, -1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   srag %r3, %r2, 0x3f
;   xgrk %r4, %r2, %r3
;   .byte 0xb9, 0x68
;   .byte 0x00, 0x24
;   aghi %r2, -1
;   br %r14

function %cls_i32(i32) -> i32 {
block0(v0: i32):
    v1 = cls v0
    return v1
}

; VCode:
; block0:
;   lgfr %r2, %r2
;   srag %r4, %r2, 63
;   xgr %r2, %r4
;   clzg %r2, %r2
;   ahi %r2, -33
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgfr %r2, %r2
;   srag %r4, %r2, 0x3f
;   xgr %r2, %r4
;   .byte 0xb9, 0x68
;   .byte 0x00, 0x22
;   ahi %r2, -0x21
;   br %r14

function %cls_i16(i16) -> i16 {
block0(v0: i16):
    v1 = cls v0
    return v1
}

; VCode:
; block0:
;   lghr %r2, %r2
;   srag %r4, %r2, 63
;   xgr %r2, %r4
;   clzg %r2, %r2
;   ahi %r2, -49
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lghr %r2, %r2
;   srag %r4, %r2, 0x3f
;   xgr %r2, %r4
;   .byte 0xb9, 0x68
;   .byte 0x00, 0x22
;   ahi %r2, -0x31
;   br %r14

function %cls_i8(i8) -> i8 {
block0(v0: i8):
    v1 = cls v0
    return v1
}

; VCode:
; block0:
;   lgbr %r2, %r2
;   srag %r4, %r2, 63
;   xgr %r2, %r4
;   clzg %r2, %r2
;   ahi %r2, -57
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgbr %r2, %r2
;   srag %r4, %r2, 0x3f
;   xgr %r2, %r4
;   .byte 0xb9, 0x68
;   .byte 0x00, 0x22
;   ahi %r2, -0x39
;   br %r14

function %ctz_i128(i128) -> i128 {
block0(v0: i128):
    v1 = ctz v0
    return v1
}

; VCode:
; block0:
;   vl %v1, 0(%r3)
;   vctzq %v4, %v1
;   vst %v4, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r3)
;   vctz %v4, %v1, 4
;   vst %v4, 0(%r2)
;   br %r14

function %ctz_i64(i64) -> i64 {
block0(v0: i64):
    v1 = ctz v0
    return v1
}

; VCode:
; block0:
;   ctzg %r2, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0x69
;   .byte 0x00, 0x22
;   br %r14

function %ctz_i32(i32) -> i32 {
block0(v0: i32):
    v1 = ctz v0
    return v1
}

; VCode:
; block0:
;   oihl %r2, 1
;   ctzg %r2, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   oihl %r2, 1
;   .byte 0xb9, 0x69
;   .byte 0x00, 0x22
;   br %r14

function %ctz_i16(i16) -> i16 {
block0(v0: i16):
    v1 = ctz v0
    return v1
}

; VCode:
; block0:
;   oilh %r2, 1
;   ctzg %r2, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   oilh %r2, 1
;   .byte 0xb9, 0x69
;   .byte 0x00, 0x22
;   br %r14

function %ctz_i8(i8) -> i8 {
block0(v0: i8):
    v1 = ctz v0
    return v1
}

; VCode:
; block0:
;   oill %r2, 256
;   ctzg %r2, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   oill %r2, 0x100
;   .byte 0xb9, 0x69
;   .byte 0x00, 0x22
;   br %r14

