test compile precise-output
target s390x arch13

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; POPCNT
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

function %popcnt_i64(i64) -> i64 {
block0(v0: i64):
    v1 = popcnt v0
    return v1
}

; VCode:
; block0:
;   popcnt %r2, %r2, 8
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0xe1
;   .byte 0x80, 0x22
;   br %r14

function %popcnt_i32(i32) -> i32 {
block0(v0: i32):
    v1 = popcnt v0
    return v1
}

; VCode:
; block0:
;   llgfr %r2, %r2
;   popcnt %r2, %r2, 8
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llgfr %r2, %r2
;   .byte 0xb9, 0xe1
;   .byte 0x80, 0x22
;   br %r14

function %popcnt_i16(i16) -> i16 {
block0(v0: i16):
    v1 = popcnt v0
    return v1
}

; VCode:
; block0:
;   llghr %r2, %r2
;   popcnt %r2, %r2, 8
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llghr %r2, %r2
;   .byte 0xb9, 0xe1
;   .byte 0x80, 0x22
;   br %r14

function %popcnt_i8(i8) -> i8 {
block0(v0: i8):
    v1 = popcnt v0
    return v1
}

; VCode:
; block0:
;   popcnt %r2, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   popcnt %r2, %r2
;   br %r14

