test compile precise-output
set opt_level=speed
target s390x has_mie2

function %band_not_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = band_not.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   ncrk %r2, %r2, %r3
;   br %r14
; 
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0xf5
;   lper %f2, %f2
;   br %r14

function %band_not_i32_reversed(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = bnot v0
  v3 = band v2, v1
  return v3
}

; VCode:
; block0:
;   ncrk %r2, %r3, %r2
;   br %r14
; 
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0xf5
;   lpdr %f2, %f3
;   br %r14

function %bor_not_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = bor_not.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   ocrk %r2, %r2, %r3
;   br %r14
; 
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0x75
;   lper %f2, %f2
;   br %r14

function %bor_not_i32_reversed(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = bnot v0
  v3 = bor v2, v1
  return v3
}

; VCode:
; block0:
;   ocrk %r2, %r3, %r2
;   br %r14
; 
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0x75
;   lpdr %f2, %f3
;   br %r14

function %bxor_not_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = bxor_not.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   nxrk %r2, %r2, %r3
;   br %r14
; 
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0x77
;   lper %f2, %f2
;   br %r14

function %bxor_not_i32_reversed(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = bnot v0
  v3 = bxor v2, v1
  return v3
}

; VCode:
; block0:
;   nxrk %r2, %r3, %r2
;   br %r14
; 
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0x77
;   lpdr %f2, %f3
;   br %r14

function %bnot_of_bxor(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = bxor v0, v1
  v3 = bnot v2
  return v3
}

; VCode:
; block0:
;   nxrk %r2, %r2, %r3
;   br %r14
; 
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0x77
;   lper %f2, %f2
;   br %r14

