
test compile precise-output
target s390x arch13

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; BAND_NOT
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

function %band_not_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
  v2 = band_not.i64 v0, v1
  return v2
}

; VCode:
; block0:
;   ncgrk %r2, %r2, %r3
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0xe5
;   lper %f2, %f2
;   br %r14

function %band_not_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = band_not.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   ncrk %r2, %r2, %r3
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0xf5
;   lper %f2, %f2
;   br %r14

function %band_not_i16(i16, i16) -> i16 {
block0(v0: i16, v1: i16):
  v2 = band_not.i16 v0, v1
  return v2
}

; VCode:
; block0:
;   ncrk %r2, %r2, %r3
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0xf5
;   lper %f2, %f2
;   br %r14

function %band_not_i8(i8, i8) -> i8 {
block0(v0: i8, v1: i8):
  v2 = band_not.i8 v0, v1
  return v2
}

; VCode:
; block0:
;   ncrk %r2, %r2, %r3
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0xf5
;   lper %f2, %f2
;   br %r14

function %bor_not_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
  v2 = bor_not.i64 v0, v1
  return v2
}

; VCode:
; block0:
;   ocgrk %r2, %r2, %r3
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0x65
;   lper %f2, %f2
;   br %r14

function %bor_not_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = bor_not.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   ocrk %r2, %r2, %r3
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0x75
;   lper %f2, %f2
;   br %r14

function %bor_not_i16(i16, i16) -> i16 {
block0(v0: i16, v1: i16):
  v2 = bor_not.i16 v0, v1
  return v2
}

; VCode:
; block0:
;   ocrk %r2, %r2, %r3
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0x75
;   lper %f2, %f2
;   br %r14

function %bor_not_i8(i8, i8) -> i8 {
block0(v0: i8, v1: i8):
  v2 = bor_not.i8 v0, v1
  return v2
}

; VCode:
; block0:
;   ocrk %r2, %r2, %r3
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0x75
;   lper %f2, %f2
;   br %r14

function %bxor_not_i64(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
  v2 = bxor_not.i64 v0, v1
  return v2
}

; VCode:
; block0:
;   nxgrk %r2, %r2, %r3
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0x67
;   lper %f2, %f2
;   br %r14

function %bxor_not_i32(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = bxor_not.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   nxrk %r2, %r2, %r3
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0x77
;   lper %f2, %f2
;   br %r14

function %bxor_not_i16(i16, i16) -> i16 {
block0(v0: i16, v1: i16):
  v2 = bxor_not.i16 v0, v1
  return v2
}

; VCode:
; block0:
;   nxrk %r2, %r2, %r3
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0x77
;   lper %f2, %f2
;   br %r14

function %bxor_not_i8(i8, i8) -> i8 {
block0(v0: i8, v1: i8):
  v2 = bxor_not.i8 v0, v1
  return v2
}

; VCode:
; block0:
;   nxrk %r2, %r2, %r3
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0x77
;   lper %f2, %f2
;   br %r14

function %bnot_i64(i64) -> i64 {
block0(v0: i64):
  v1 = bnot.i64 v0
  return v1
}

; VCode:
; block0:
;   nogrk %r2, %r2, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0x66
;   lpdr %f2, %f2
;   br %r14

function %bnot_i32(i32) -> i32 {
block0(v0: i32):
  v1 = bnot.i32 v0
  return v1
}

; VCode:
; block0:
;   nork %r2, %r2, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0x76
;   lpdr %f2, %f2
;   br %r14

function %bnot_i16(i16) -> i16 {
block0(v0: i16):
  v1 = bnot.i16 v0
  return v1
}

; VCode:
; block0:
;   nork %r2, %r2, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0x76
;   lpdr %f2, %f2
;   br %r14

function %bnot_i8(i8) -> i8 {
block0(v0: i8):
  v1 = bnot.i8 v0
  return v1
}

; VCode:
; block0:
;   nork %r2, %r2, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xb9, 0x76
;   lpdr %f2, %f2
;   br %r14

function %bitselect_i64(i64, i64, i64) -> i64 {
block0(v0: i64, v1: i64, v2: i64):
  v3 = bitselect.i64 v0, v1, v2
  return v3
}

; VCode:
; block0:
;   lgr %r5, %r4
;   ngrk %r4, %r3, %r2
;   lgr %r3, %r5
;   ncgrk %r2, %r3, %r2
;   ogr %r2, %r4
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgr %r5, %r4
;   ngrk %r4, %r3, %r2
;   lgr %r3, %r5
;   .byte 0xb9, 0xe5
;   lpdr %f2, %f3
;   ogr %r2, %r4
;   br %r14

function %bitselect_i32(i32, i32, i32) -> i32 {
block0(v0: i32, v1: i32, v2: i32):
  v3 = bitselect.i32 v0, v1, v2
  return v3
}

; VCode:
; block0:
;   lgr %r5, %r4
;   nrk %r4, %r3, %r2
;   lgr %r3, %r5
;   ncrk %r2, %r3, %r2
;   or %r2, %r4
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgr %r5, %r4
;   nrk %r4, %r3, %r2
;   lgr %r3, %r5
;   .byte 0xb9, 0xf5
;   lpdr %f2, %f3
;   or %r2, %r4
;   br %r14

function %bitselect_i16(i16, i16, i16) -> i16 {
block0(v0: i16, v1: i16, v2: i16):
  v3 = bitselect.i16 v0, v1, v2
  return v3
}

; VCode:
; block0:
;   lgr %r5, %r4
;   nrk %r4, %r3, %r2
;   lgr %r3, %r5
;   ncrk %r2, %r3, %r2
;   or %r2, %r4
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgr %r5, %r4
;   nrk %r4, %r3, %r2
;   lgr %r3, %r5
;   .byte 0xb9, 0xf5
;   lpdr %f2, %f3
;   or %r2, %r4
;   br %r14

function %bitselect_i8(i8, i8, i8) -> i8 {
block0(v0: i8, v1: i8, v2: i8):
  v3 = bitselect.i8 v0, v1, v2
  return v3
}

; VCode:
; block0:
;   lgr %r5, %r4
;   nrk %r4, %r3, %r2
;   lgr %r3, %r5
;   ncrk %r2, %r3, %r2
;   or %r2, %r4
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgr %r5, %r4
;   nrk %r4, %r3, %r2
;   lgr %r3, %r5
;   .byte 0xb9, 0xf5
;   lpdr %f2, %f3
;   or %r2, %r4
;   br %r14

