test compile precise-output
set enable_multi_ret_implicit_sret
target s390x

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; CALL
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

function %call(i64) -> i64 {
    fn0 = %g(i64) -> i64

block0(v0: i64):
    v1 = call fn0(v0)
    return v1
}

; VCode:
;   stmg %r14, %r15, 112(%r15)
;   aghi %r15, -160
; block0:
;   bras %r1, 12 ; data %g + 0 ; lg %r3, 0(%r1)
;   basr %r14, %r3
;   lmg %r14, %r15, 272(%r15)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r14, %r15, 0x70(%r15)
;   aghi %r15, -0xa0
; block1: ; offset 0xa
;   bras %r1, 0x16
;   .byte 0x00, 0x00 ; reloc_external Abs8 %g 0
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   lg %r3, 0(%r1)
;   basr %r14, %r3
;   lmg %r14, %r15, 0x110(%r15)
;   br %r14

function %call_uext(i32) -> i64 {
    fn0 = %g(i32 uext) -> i64

block0(v0: i32):
    v1 = call fn0(v0)
    return v1
}

; VCode:
;   stmg %r14, %r15, 112(%r15)
;   aghi %r15, -160
; block0:
;   llgfr %r2, %r2
;   bras %r1, 12 ; data %g + 0 ; lg %r5, 0(%r1)
;   basr %r14, %r5
;   lmg %r14, %r15, 272(%r15)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r14, %r15, 0x70(%r15)
;   aghi %r15, -0xa0
; block1: ; offset 0xa
;   llgfr %r2, %r2
;   bras %r1, 0x1a
;   .byte 0x00, 0x00 ; reloc_external Abs8 %g 0
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   lg %r5, 0(%r1)
;   basr %r14, %r5
;   lmg %r14, %r15, 0x110(%r15)
;   br %r14

function %ret_uext(i32) -> i32 uext {
block0(v0: i32):
    return v0
}

; VCode:
; block0:
;   llgfr %r2, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llgfr %r2, %r2
;   br %r14

function %call_uext(i32) -> i64 {
    fn0 = %g(i32 sext) -> i64

block0(v0: i32):
    v1 = call fn0(v0)
    return v1
}

; VCode:
;   stmg %r14, %r15, 112(%r15)
;   aghi %r15, -160
; block0:
;   lgfr %r2, %r2
;   bras %r1, 12 ; data %g + 0 ; lg %r5, 0(%r1)
;   basr %r14, %r5
;   lmg %r14, %r15, 272(%r15)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r14, %r15, 0x70(%r15)
;   aghi %r15, -0xa0
; block1: ; offset 0xa
;   lgfr %r2, %r2
;   bras %r1, 0x1a
;   .byte 0x00, 0x00 ; reloc_external Abs8 %g 0
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   lg %r5, 0(%r1)
;   basr %r14, %r5
;   lmg %r14, %r15, 0x110(%r15)
;   br %r14

function %ret_uext(i32) -> i32 sext {
block0(v0: i32):
    return v0
}

; VCode:
; block0:
;   lgfr %r2, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgfr %r2, %r2
;   br %r14

function %call_colocated(i64) -> i64 {
    fn0 = colocated %g(i64) -> i64

block0(v0: i64):
    v1 = call fn0(v0)
    return v1
}

; VCode:
;   stmg %r14, %r15, 112(%r15)
;   aghi %r15, -160
; block0:
;   brasl %r14, %g
;   lmg %r14, %r15, 272(%r15)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r14, %r15, 0x70(%r15)
;   aghi %r15, -0xa0
; block1: ; offset 0xa
;   brasl %r14, 0xa ; reloc_external PLTRel32Dbl %g 2
;   lmg %r14, %r15, 0x110(%r15)
;   br %r14

function %f2(i32) -> i64 {
    fn0 = %g(i32 uext) -> i64

block0(v0: i32):
    v1 = call fn0(v0)
    return v1
}

; VCode:
;   stmg %r14, %r15, 112(%r15)
;   aghi %r15, -160
; block0:
;   llgfr %r2, %r2
;   bras %r1, 12 ; data %g + 0 ; lg %r5, 0(%r1)
;   basr %r14, %r5
;   lmg %r14, %r15, 272(%r15)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r14, %r15, 0x70(%r15)
;   aghi %r15, -0xa0
; block1: ; offset 0xa
;   llgfr %r2, %r2
;   bras %r1, 0x1a
;   .byte 0x00, 0x00 ; reloc_external Abs8 %g 0
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   lg %r5, 0(%r1)
;   basr %r14, %r5
;   lmg %r14, %r15, 0x110(%r15)
;   br %r14

function %call_indirect(i64, i64) -> i64 {
    sig0 = (i64) -> i64
block0(v0: i64, v1: i64):
    v2 = call_indirect.i64 sig0, v1(v0)
    return v2
}

; VCode:
;   stmg %r14, %r15, 112(%r15)
;   aghi %r15, -160
; block0:
;   basr %r14, %r3
;   lmg %r14, %r15, 272(%r15)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r14, %r15, 0x70(%r15)
;   aghi %r15, -0xa0
; block1: ; offset 0xa
;   basr %r14, %r3
;   lmg %r14, %r15, 0x110(%r15)
;   br %r14

function %incoming_args(i64, i32, i32 uext, i32 sext, i16, i16 uext, i16 sext, i8, i8 uext, i8 sext) -> i64 {
block0(v0: i64, v1: i32, v2: i32, v3: i32, v4: i16, v5: i16, v6: i16, v7: i8, v8: i8, v9: i8):
    v10 = uextend.i64 v1
    v11 = uextend.i64 v2
    v12 = uextend.i64 v3
    v13 = uextend.i64 v4
    v14 = uextend.i64 v5
    v15 = uextend.i64 v6
    v16 = uextend.i64 v7
    v17 = uextend.i64 v8
    v18 = uextend.i64 v9
    v19 = iadd v0, v10
    v20 = iadd v11, v12
    v21 = iadd v13, v14
    v22 = iadd v15, v16
    v23 = iadd v17, v18
    v24 = iadd v19, v20
    v25 = iadd v21, v22
    v26 = iadd v23, v24
    v27 = iadd v25, v26
    return v27
}

; VCode:
;   stmg %r6, %r15, 48(%r15)
; block0:
;   lgr %r9, %r6
;   lg %r6, 160(%r15)
;   lg %r8, 168(%r15)
;   llgc %r10, 183(%r15)
;   lg %r12, 184(%r15)
;   lg %r14, 192(%r15)
;   llgfr %r3, %r3
;   llgfr %r4, %r4
;   llgfr %r7, %r5
;   lgr %r5, %r9
;   llghr %r9, %r5
;   llghr %r5, %r6
;   llghr %r6, %r8
;   llgcr %r8, %r10
;   llgcr %r10, %r12
;   llgcr %r11, %r14
;   agr %r2, %r3
;   agrk %r3, %r4, %r7
;   agrk %r4, %r9, %r5
;   agrk %r5, %r6, %r8
;   agrk %r6, %r10, %r11
;   agr %r2, %r3
;   agrk %r3, %r4, %r5
;   agrk %r2, %r6, %r2
;   agrk %r2, %r3, %r2
;   lmg %r6, %r15, 48(%r15)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r6, %r15, 0x30(%r15)
; block1: ; offset 0x6
;   lgr %r9, %r6
;   lg %r6, 0xa0(%r15)
;   lg %r8, 0xa8(%r15)
;   llgc %r10, 0xb7(%r15)
;   lg %r12, 0xb8(%r15)
;   lg %r14, 0xc0(%r15)
;   llgfr %r3, %r3
;   llgfr %r4, %r4
;   llgfr %r7, %r5
;   lgr %r5, %r9
;   llghr %r9, %r5
;   llghr %r5, %r6
;   llghr %r6, %r8
;   llgcr %r8, %r10
;   llgcr %r10, %r12
;   llgcr %r11, %r14
;   agr %r2, %r3
;   agrk %r3, %r4, %r7
;   agrk %r4, %r9, %r5
;   agrk %r5, %r6, %r8
;   agrk %r6, %r10, %r11
;   agr %r2, %r3
;   agrk %r3, %r4, %r5
;   agrk %r2, %r6, %r2
;   agrk %r2, %r3, %r2
;   lmg %r6, %r15, 0x30(%r15)
;   br %r14

function %incoming_args_i128(i128, i128, i128, i128, i128, i128, i128, i128) -> i128 {
block0(v0: i128, v1: i128, v2: i128, v3: i128, v4: i128, v5: i128, v6: i128, v7: i128):
    v8 = iadd v0, v1
    v9 = iadd v2, v3
    v10 = iadd v4, v5
    v11 = iadd v6, v7
    v12 = iadd v8, v9
    v13 = iadd v10, v11
    v14 = iadd v12, v13
    return v14
}

; VCode:
;   stmg %r6, %r15, 48(%r15)
; block0:
;   vl %v1, 0(%r3)
;   vl %v3, 0(%r4)
;   vl %v5, 0(%r5)
;   vl %v7, 0(%r6)
;   lg %r3, 160(%r15)
;   vl %v16, 0(%r3)
;   lg %r3, 168(%r15)
;   vl %v17, 0(%r3)
;   lg %r3, 176(%r15)
;   vl %v18, 0(%r3)
;   lg %r3, 184(%r15)
;   vl %v19, 0(%r3)
;   vaq %v28, %v1, %v3
;   vaq %v29, %v5, %v7
;   vaq %v30, %v16, %v17
;   vaq %v31, %v18, %v19
;   vaq %v28, %v28, %v29
;   vaq %v29, %v30, %v31
;   vaq %v28, %v28, %v29
;   vst %v28, 0(%r2)
;   lmg %r6, %r15, 48(%r15)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r6, %r15, 0x30(%r15)
; block1: ; offset 0x6
;   vl %v1, 0(%r3)
;   vl %v3, 0(%r4)
;   vl %v5, 0(%r5)
;   vl %v7, 0(%r6)
;   lg %r3, 0xa0(%r15)
;   vl %v16, 0(%r3)
;   lg %r3, 0xa8(%r15)
;   vl %v17, 0(%r3)
;   lg %r3, 0xb0(%r15)
;   vl %v18, 0(%r3)
;   lg %r3, 0xb8(%r15)
;   vl %v19, 0(%r3)
;   vaq %v28, %v1, %v3
;   vaq %v29, %v5, %v7
;   vaq %v30, %v16, %v17
;   vaq %v31, %v18, %v19
;   vaq %v28, %v28, %v29
;   vaq %v29, %v30, %v31
;   vaq %v28, %v28, %v29
;   vst %v28, 0(%r2)
;   lmg %r6, %r15, 0x30(%r15)
;   br %r14

function %call_sret() -> i64 {
    fn0 = colocated %g(i64 sret)

block0:
    v1 = iconst.i64 0
    call fn0(v1)
    trap user1
}

; VCode:
;   stmg %r14, %r15, 112(%r15)
;   aghi %r15, -160
; block0:
;   lghi %r2, 0
;   brasl %r14, %g
;   .word 0x0000 # trap=user1
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r14, %r15, 0x70(%r15)
;   aghi %r15, -0xa0
; block1: ; offset 0xa
;   lghi %r2, 0
;   brasl %r14, 0xe ; reloc_external PLTRel32Dbl %g 2
;   .byte 0x00, 0x00 ; trap: user1

function %second_f16(f16, f16) -> f16 {
block0(v0: f16, v1: f16):
    return v1
}

; VCode:
; block0:
;   vlr %v0, %v2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vlr %v0, %v2
;   br %r14

function %second_f128(f128, f128) -> f128 {
block0(v0: f128, v1: f128):
    return v1
}

; VCode:
; block0:
;   vl %v1, 0(%r4)
;   vst %v1, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r4)
;   vst %v1, 0(%r2)
;   br %r14

function %call_f128(f128) -> f128 {
    fn0 = %g(f128) -> f128

block0(v0: f128):
    v1 = call fn0(v0)
    return v1
}

; VCode:
;   stmg %r8, %r15, 64(%r15)
;   aghi %r15, -208
; block0:
;   lgr %r8, %r2
;   vl %v1, 0(%r3)
;   la %r3, 160(%r15)
;   vst %v1, 0(%r3)
;   la %r2, 176(%r15)
;   bras %r1, 12 ; data %g + 0 ; lg %r4, 0(%r1)
;   basr %r14, %r4 ; vl %v1, 176(%r15) ; vst %v1, 192(%r15)
;   lgr %r2, %r8
;   vl %v16, 192(%r15)
;   vst %v16, 0(%r2)
;   lmg %r8, %r15, 272(%r15)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r8, %r15, 0x40(%r15)
;   aghi %r15, -0xd0
; block1: ; offset 0xa
;   lgr %r8, %r2
;   vl %v1, 0(%r3)
;   la %r3, 0xa0(%r15)
;   vst %v1, 0(%r3)
;   la %r2, 0xb0(%r15)
;   bras %r1, 0x2e
;   .byte 0x00, 0x00 ; reloc_external Abs8 %g 0
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   lg %r4, 0(%r1)
;   basr %r14, %r4
;   vl %v1, 0xb0(%r15)
;   vst %v1, 0xc0(%r15)
;   lgr %r2, %r8
;   vl %v16, 0xc0(%r15)
;   vst %v16, 0(%r2)
;   lmg %r8, %r15, 0x110(%r15)
;   br %r14

