test compile precise-output
set enable_multi_ret_implicit_sret
target s390x

function %iconcat_i64(i64, i64) -> i128 {
block0(v0: i64, v1: i64):
  v2 = iconcat.i64 v0, v1
  return v2
}

; VCode:
; block0:
;   vlvgp %v4, %r4, %r3
;   vst %v4, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vlvgp %v4, %r4, %r3
;   vst %v4, 0(%r2)
;   br %r14

function %isplit_i128(i128) -> i64, i64 {
block0(v0: i128):
  v1, v2 = isplit.i128 v0
  return v1, v2
}

; VCode:
; block0:
;   vl %v1, 0(%r2)
;   lgdr %r3, %f1
;   vlgvg %r2, %v1, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r2)
;   lgdr %r3, %f1
;   vlgvg %r2, %v1, 1
;   br %r14

