test compile precise-output
target s390x

function %load_f64(i64) -> f64 {
block0(v0: i64):
  v1 = load.f64 v0
  return v1
}

; VCode:
; block0:
;   ld %f0, 0(%r2)
;   br %r14
; 
; Disassembled:
; block0: ; offset 0x0
;   ld %f0, 0(%r2)
;   br %r14

function %load_f32(i64) -> f32 {
block0(v0: i64):
  v1 = load.f32 v0
  return v1
}

; VCode:
; block0:
;   le %f0, 0(%r2)
;   br %r14
; 
; Disassembled:
; block0: ; offset 0x0
;   le %f0, 0(%r2)
;   br %r14

function %load_f64_little(i64) -> f64 {
block0(v0: i64):
  v1 = load.f64 little v0
  return v1
}

; VCode:
; block0:
;   lrvg %r4, 0(%r2)
;   ldgr %f0, %r4
;   br %r14
; 
; Disassembled:
; block0: ; offset 0x0
;   lrvg %r4, 0(%r2)
;   ldgr %f0, %r4
;   br %r14

function %load_f32_little(i64) -> f32 {
block0(v0: i64):
  v1 = load.f32 little v0
  return v1
}

; VCode:
; block0:
;   lrv %r4, 0(%r2)
;   vlvgf %v0, %r4, 0
;   br %r14
; 
; Disassembled:
; block0: ; offset 0x0
;   lrv %r4, 0(%r2)
;   vlvgf %v0, %r4, 0
;   br %r14

function %store_f64(f64, i64) {
block0(v0: f64, v1: i64):
  store.f64 v0, v1
  return
}

; VCode:
; block0:
;   std %f0, 0(%r2)
;   br %r14
; 
; Disassembled:
; block0: ; offset 0x0
;   std %f0, 0(%r2)
;   br %r14

function %store_f32(f32, i64) {
block0(v0: f32, v1: i64):
  store.f32 v0, v1
  return
}

; VCode:
; block0:
;   ste %f0, 0(%r2)
;   br %r14
; 
; Disassembled:
; block0: ; offset 0x0
;   ste %f0, 0(%r2)
;   br %r14

function %store_f64_little(f64, i64) {
block0(v0: f64, v1: i64):
  store.f64 little v0, v1
  return
}

; VCode:
; block0:
;   lgdr %r5, %f0
;   strvg %r5, 0(%r2)
;   br %r14
; 
; Disassembled:
; block0: ; offset 0x0
;   lgdr %r5, %f0
;   strvg %r5, 0(%r2)
;   br %r14

function %store_f32_little(f32, i64) {
block0(v0: f32, v1: i64):
  store.f32 little v0, v1
  return
}

; VCode:
; block0:
;   vlgvf %r5, %v0, 0
;   strv %r5, 0(%r2)
;   br %r14
; 
; Disassembled:
; block0: ; offset 0x0
;   vlgvf %r5, %v0, 0
;   strv %r5, 0(%r2)
;   br %r14

