test compile precise-output
target s390x

function %dynamic_heap_check(i64 vmctx, i32) -> i64 {
    gv0 = vmctx
    gv1 = load.i64 notrap aligned gv0
    heap0 = dynamic gv0, bound gv1, offset_guard 0x1000, index_type i32

block0(v0: i64, v1: i32):
    v2 = heap_addr.i64 heap0, v1, 0
    return v2
}

; block0:
;   llgfr %r5, %r3
;   lgr %r4, %r2
;   lg %r2, 0(%r4)
;   aghik %r3, %r2, 0
;   clgr %r5, %r3
;   jgnh label1 ; jg label2
; block1:
;   agrk %r2, %r4, %r5
;   lghi %r4, 0
;   clgr %r5, %r3
;   locgrh %r2, %r4
;   br %r14
; block2:
;   trap

function %static_heap_check(i64 vmctx, i32) -> i64 {
    gv0 = vmctx
    heap0 = static gv0, bound 0x1_0000, offset_guard 0x1000, index_type i32

block0(v0: i64, v1: i32):
    v2 = heap_addr.i64 heap0, v1, 0
    return v2
}

; block0:
;   llgfr %r4, %r3
;   clgfi %r4, 65536
;   jgnh label1 ; jg label2
; block1:
;   agr %r2, %r4
;   lghi %r5, 0
;   clgfi %r4, 65536
;   locgrh %r2, %r5
;   br %r14
; block2:
;   trap

