test compile precise-output
target s390x arch15

function %icmp_eq_i128(i128, i128) -> i8 {
block0(v0: i128, v1: i128):
  v2 = icmp.i128 eq v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r2)
;   vl %v3, 0(%r3)
;   veclq %v1, %v3
;   lhi %r2, 0
;   lochie %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r2)
;   vl %v3, 0(%r3)
;   vecl %v1, %v3, 4
;   lhi %r2, 0
;   lochie %r2, 1
;   br %r14

function %icmp_ne_i128(i128, i128) -> i8 {
block0(v0: i128, v1: i128):
  v2 = icmp.i128 ne v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r2)
;   vl %v3, 0(%r3)
;   veclq %v1, %v3
;   lhi %r2, 0
;   lochilh %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r2)
;   vl %v3, 0(%r3)
;   vecl %v1, %v3, 4
;   lhi %r2, 0
;   lochilh %r2, 1
;   br %r14

function %icmp_slt_i128(i128, i128) -> i8 {
block0(v0: i128, v1: i128):
  v2 = icmp.i128 slt v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r2)
;   vl %v3, 0(%r3)
;   vecq %v1, %v3
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r2)
;   vl %v3, 0(%r3)
;   vec %v1, %v3, 4
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_sgt_i128(i128, i128) -> i8 {
block0(v0: i128, v1: i128):
  v2 = icmp.i128 sgt v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r2)
;   vl %v3, 0(%r3)
;   vecq %v1, %v3
;   lhi %r2, 0
;   lochih %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r2)
;   vl %v3, 0(%r3)
;   vec %v1, %v3, 4
;   lhi %r2, 0
;   lochih %r2, 1
;   br %r14

function %icmp_sle_i128(i128, i128) -> i8 {
block0(v0: i128, v1: i128):
  v2 = icmp.i128 sle v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r2)
;   vl %v3, 0(%r3)
;   vecq %v1, %v3
;   lhi %r2, 0
;   lochile %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r2)
;   vl %v3, 0(%r3)
;   vec %v1, %v3, 4
;   lhi %r2, 0
;   lochile %r2, 1
;   br %r14

function %icmp_sge_i128(i128, i128) -> i8 {
block0(v0: i128, v1: i128):
  v2 = icmp.i128 sge v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r2)
;   vl %v3, 0(%r3)
;   vecq %v1, %v3
;   lhi %r2, 0
;   lochihe %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r2)
;   vl %v3, 0(%r3)
;   vec %v1, %v3, 4
;   lhi %r2, 0
;   lochihe %r2, 1
;   br %r14

function %icmp_ult_i128(i128, i128) -> i8 {
block0(v0: i128, v1: i128):
  v2 = icmp.i128 ult v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r2)
;   vl %v3, 0(%r3)
;   veclq %v1, %v3
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r2)
;   vl %v3, 0(%r3)
;   vecl %v1, %v3, 4
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ugt_i128(i128, i128) -> i8 {
block0(v0: i128, v1: i128):
  v2 = icmp.i128 ugt v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r2)
;   vl %v3, 0(%r3)
;   veclq %v1, %v3
;   lhi %r2, 0
;   lochih %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r2)
;   vl %v3, 0(%r3)
;   vecl %v1, %v3, 4
;   lhi %r2, 0
;   lochih %r2, 1
;   br %r14

function %icmp_ule_i128(i128, i128) -> i8 {
block0(v0: i128, v1: i128):
  v2 = icmp.i128 ule v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r2)
;   vl %v3, 0(%r3)
;   veclq %v1, %v3
;   lhi %r2, 0
;   lochile %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r2)
;   vl %v3, 0(%r3)
;   vecl %v1, %v3, 4
;   lhi %r2, 0
;   lochile %r2, 1
;   br %r14

function %icmp_uge_i128(i128, i128) -> i8 {
block0(v0: i128, v1: i128):
  v2 = icmp.i128 uge v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r2)
;   vl %v3, 0(%r3)
;   veclq %v1, %v3
;   lhi %r2, 0
;   lochihe %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r2)
;   vl %v3, 0(%r3)
;   vecl %v1, %v3, 4
;   lhi %r2, 0
;   lochihe %r2, 1
;   br %r14

function %f4(i8x16, i8x16, i8x16) -> i8x16 {
block0(v0: i8x16, v1: i8x16, v2: i8x16):
   v3 = x86_blendv v0, v1, v2
   return v3
}

; VCode:
; block0:
;   vblend %v24, %v24, %v25, %v26
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0xe7, 0x88
;   stm %r0, %r0, 0xf89(%r10)
;   br %r14

