test compile precise-output
target s390x

function %icmp_slt_i64(i64, i64) -> i8 {
block0(v0: i64, v1: i64):
  v2 = icmp.i64 slt v0, v1
  return v2
}

; VCode:
; block0:
;   cgr %r2, %r3
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   cgr %r2, %r3
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i64_ext32(i64, i32) -> i8 {
block0(v0: i64, v1: i32):
  v2 = sextend.i64 v1
  v3 = icmp.i64 slt v0, v2
  return v3
}

; VCode:
; block0:
;   cgfr %r2, %r3
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   cgfr %r2, %r3
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i64_imm16(i64) -> i8 {
block0(v0: i64):
  v1 = iconst.i64 1
  v2 = icmp.i64 slt v0, v1
  return v2
}

; VCode:
; block0:
;   cghi %r2, 1
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   cghi %r2, 1
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i64_imm32(i64) -> i8 {
block0(v0: i64):
  v1 = iconst.i64 32768
  v2 = icmp.i64 slt v0, v1
  return v2
}

; VCode:
; block0:
;   cgfi %r2, 32768
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   cgfi %r2, 0x8000
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i64_mem(i64, i64) -> i8 {
block0(v0: i64, v1: i64):
  v2 = load.i64 v1
  v3 = icmp.i64 slt v0, v2
  return v3
}

; VCode:
; block0:
;   cg %r2, 0(%r3)
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   cg %r2, 0(%r3) ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i64_sym(i64) -> i8 {
  gv0 = symbol colocated %sym
block0(v0: i64):
  v1 = symbol_value.i64 gv0
  v2 = load.i64 aligned v1
  v3 = icmp.i64 slt v0, v2
  return v3
}

; VCode:
; block0:
;   cgrl %r2, %sym + 0
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   cgrl %r2, 0 ; reloc_external PCRel32Dbl %sym 2 ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i64_mem_ext16(i64, i64) -> i8 {
block0(v0: i64, v1: i64):
  v2 = sload16.i64 v1
  v3 = icmp.i64 slt v0, v2
  return v3
}

; VCode:
; block0:
;   cgh %r2, 0(%r3)
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   cgh %r2, 0(%r3) ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i64_sym_ext16(i64) -> i8 {
  gv0 = symbol colocated %sym
block0(v0: i64):
  v1 = symbol_value.i64 gv0
  v2 = sload16.i64 aligned v1
  v3 = icmp.i64 slt v0, v2
  return v3
}

; VCode:
; block0:
;   cghrl %r2, %sym + 0
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   cghrl %r2, 0 ; reloc_external PCRel32Dbl %sym 2 ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i64_mem_ext32(i64, i64) -> i8 {
block0(v0: i64, v1: i64):
  v2 = sload32.i64 v1
  v3 = icmp.i64 slt v0, v2
  return v3
}

; VCode:
; block0:
;   cgf %r2, 0(%r3)
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   cgf %r2, 0(%r3) ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i64_sym_ext32(i64) -> i8 {
  gv0 = symbol colocated %sym
block0(v0: i64):
  v1 = symbol_value.i64 gv0
  v2 = sload32.i64 aligned v1
  v3 = icmp.i64 slt v0, v2
  return v3
}

; VCode:
; block0:
;   cgfrl %r2, %sym + 0
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   cgfrl %r2, 0 ; reloc_external PCRel32Dbl %sym 2 ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i32(i32, i32) -> i8 {
block0(v0: i32, v1: i32):
  v2 = icmp.i32 slt v0, v1
  return v2
}

; VCode:
; block0:
;   cr %r2, %r3
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   cr %r2, %r3
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i32_imm16(i32) -> i8 {
block0(v0: i32):
  v1 = iconst.i32 1
  v2 = icmp.i32 slt v0, v1
  return v2
}

; VCode:
; block0:
;   chi %r2, 1
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   chi %r2, 1
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i32_imm(i32) -> i8 {
block0(v0: i32):
  v1 = iconst.i32 32768
  v2 = icmp.i32 slt v0, v1
  return v2
}

; VCode:
; block0:
;   cfi %r2, 32768
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   cfi %r2, 0x8000
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i32_mem(i32, i64) -> i8 {
block0(v0: i32, v1: i64):
  v2 = load.i32 v1
  v3 = icmp.i32 slt v0, v2
  return v3
}

; VCode:
; block0:
;   c %r2, 0(%r3)
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   c %r2, 0(%r3) ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i32_memoff(i32, i64) -> i8 {
block0(v0: i32, v1: i64):
  v2 = load.i32 v1+4096
  v3 = icmp.i32 slt v0, v2
  return v3
}

; VCode:
; block0:
;   cy %r2, 4096(%r3)
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   cy %r2, 0x1000(%r3) ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i32_sym(i32) -> i8 {
  gv0 = symbol colocated %sym
block0(v0: i32):
  v1 = symbol_value.i64 gv0
  v2 = load.i32 aligned v1
  v3 = icmp.i32 slt v0, v2
  return v3
}

; VCode:
; block0:
;   crl %r2, %sym + 0
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   crl %r2, 0 ; reloc_external PCRel32Dbl %sym 2 ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i32_mem_ext16(i32, i64) -> i8 {
block0(v0: i32, v1: i64):
  v2 = sload16.i32 v1
  v3 = icmp.i32 slt v0, v2
  return v3
}

; VCode:
; block0:
;   ch %r2, 0(%r3)
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   ch %r2, 0(%r3) ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i32_memoff_ext16(i32, i64) -> i8 {
block0(v0: i32, v1: i64):
  v2 = sload16.i32 v1+4096
  v3 = icmp.i32 slt v0, v2
  return v3
}

; VCode:
; block0:
;   chy %r2, 4096(%r3)
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   chy %r2, 0x1000(%r3) ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i32_sym_ext16(i32) -> i8 {
  gv0 = symbol colocated %sym
block0(v0: i32):
  v1 = symbol_value.i64 gv0
  v2 = sload16.i32 aligned v1
  v3 = icmp.i32 slt v0, v2
  return v3
}

; VCode:
; block0:
;   chrl %r2, %sym + 0
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   chrl %r2, 0 ; reloc_external PCRel32Dbl %sym 2 ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i16(i16, i16) -> i8 {
block0(v0: i16, v1: i16):
  v2 = icmp.i16 slt v0, v1
  return v2
}

; VCode:
; block0:
;   lgr %r4, %r3
;   lhr %r3, %r2
;   lgr %r2, %r4
;   lhr %r5, %r2
;   cr %r3, %r5
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgr %r4, %r3
;   lhr %r3, %r2
;   lgr %r2, %r4
;   lhr %r5, %r2
;   cr %r3, %r5
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i16_imm(i16) -> i8 {
block0(v0: i16):
  v1 = iconst.i16 1
  v2 = icmp.i16 slt v0, v1
  return v2
}

; VCode:
; block0:
;   lhr %r2, %r2
;   chi %r2, 1
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lhr %r2, %r2
;   chi %r2, 1
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i16_mem(i16, i64) -> i8 {
block0(v0: i16, v1: i64):
  v2 = load.i16 v1
  v3 = icmp.i16 slt v0, v2
  return v3
}

; VCode:
; block0:
;   lhr %r4, %r2
;   ch %r4, 0(%r3)
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lhr %r4, %r2
;   ch %r4, 0(%r3) ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i16_sym(i16) -> i8 {
  gv0 = symbol colocated %sym
block0(v0: i16):
  v1 = symbol_value.i64 gv0
  v2 = load.i16 aligned v1
  v3 = icmp.i16 slt v0, v2
  return v3
}

; VCode:
; block0:
;   lhr %r2, %r2
;   chrl %r2, %sym + 0
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lhr %r2, %r2
;   chrl %r2, 4 ; reloc_external PCRel32Dbl %sym 2 ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i8(i8, i8) -> i8 {
block0(v0: i8, v1: i8):
  v2 = icmp.i8 slt v0, v1
  return v2
}

; VCode:
; block0:
;   lgr %r4, %r3
;   lbr %r3, %r2
;   lgr %r2, %r4
;   lbr %r5, %r2
;   cr %r3, %r5
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgr %r4, %r3
;   lbr %r3, %r2
;   lgr %r2, %r4
;   lbr %r5, %r2
;   cr %r3, %r5
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i8_imm(i8) -> i8 {
block0(v0: i8):
  v1 = iconst.i8 1
  v2 = icmp.i8 slt v0, v1
  return v2
}

; VCode:
; block0:
;   lbr %r2, %r2
;   chi %r2, 1
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lbr %r2, %r2
;   chi %r2, 1
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_slt_i8_mem(i8, i64) -> i8 {
block0(v0: i8, v1: i64):
  v2 = load.i8 v1
  v3 = icmp.i8 slt v0, v2
  return v3
}

; VCode:
; block0:
;   lgr %r4, %r3
;   lbr %r3, %r2
;   lgr %r2, %r4
;   lb %r5, 0(%r2)
;   cr %r3, %r5
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgr %r4, %r3
;   lbr %r3, %r2
;   lgr %r2, %r4
;   lb %r5, 0(%r2) ; trap: heap_oob
;   cr %r3, %r5
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i64(i64, i64) -> i8 {
block0(v0: i64, v1: i64):
  v2 = icmp.i64 ult v0, v1
  return v2
}

; VCode:
; block0:
;   clgr %r2, %r3
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   clgr %r2, %r3
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i64_ext32(i64, i32) -> i8 {
block0(v0: i64, v1: i32):
  v2 = uextend.i64 v1
  v3 = icmp.i64 ult v0, v2
  return v3
}

; VCode:
; block0:
;   clgfr %r2, %r3
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   clgfr %r2, %r3
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i64_imm(i64) -> i8 {
block0(v0: i64):
  v1 = iconst.i64 1
  v2 = icmp.i64 ult v0, v1
  return v2
}

; VCode:
; block0:
;   clgfi %r2, 1
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   clgfi %r2, 1
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i64_mem(i64, i64) -> i8 {
block0(v0: i64, v1: i64):
  v2 = load.i64 v1
  v3 = icmp.i64 ult v0, v2
  return v3
}

; VCode:
; block0:
;   clg %r2, 0(%r3)
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   clg %r2, 0(%r3) ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i64_sym(i64) -> i8 {
  gv0 = symbol colocated %sym
block0(v0: i64):
  v1 = symbol_value.i64 gv0
  v2 = load.i64 aligned v1
  v3 = icmp.i64 ult v0, v2
  return v3
}

; VCode:
; block0:
;   clgrl %r2, %sym + 0
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   clgrl %r2, 0 ; reloc_external PCRel32Dbl %sym 2 ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i64_mem_ext32(i64, i64) -> i8 {
block0(v0: i64, v1: i64):
  v2 = uload32.i64 v1
  v3 = icmp.i64 ult v0, v2
  return v3
}

; VCode:
; block0:
;   clgf %r2, 0(%r3)
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   clgf %r2, 0(%r3) ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i64_sym_ext32(i64) -> i8 {
  gv0 = symbol colocated %sym
block0(v0: i64):
  v1 = symbol_value.i64 gv0
  v2 = uload32.i64 aligned v1
  v3 = icmp.i64 ult v0, v2
  return v3
}

; VCode:
; block0:
;   clgfrl %r2, %sym + 0
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   clgfrl %r2, 0 ; reloc_external PCRel32Dbl %sym 2 ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i64_mem_ext16(i64, i64) -> i8 {
block0(v0: i64, v1: i64):
  v2 = uload16.i64 v1
  v3 = icmp.i64 ult v0, v2
  return v3
}

; VCode:
; block0:
;   llgh %r5, 0(%r3)
;   clgr %r2, %r5
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llgh %r5, 0(%r3) ; trap: heap_oob
;   clgr %r2, %r5
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i64_sym_ext16(i64) -> i8 {
  gv0 = symbol colocated %sym
block0(v0: i64):
  v1 = symbol_value.i64 gv0
  v2 = uload16.i64 aligned v1
  v3 = icmp.i64 ult v0, v2
  return v3
}

; VCode:
; block0:
;   clghrl %r2, %sym + 0
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   clghrl %r2, 0 ; reloc_external PCRel32Dbl %sym 2 ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i32(i32, i32) -> i8 {
block0(v0: i32, v1: i32):
  v2 = icmp.i32 ult v0, v1
  return v2
}

; VCode:
; block0:
;   clr %r2, %r3
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   clr %r2, %r3
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i32_imm(i32) -> i8 {
block0(v0: i32):
  v1 = iconst.i32 1
  v2 = icmp.i32 ult v0, v1
  return v2
}

; VCode:
; block0:
;   clfi %r2, 1
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   clfi %r2, 1
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i32_mem(i32, i64) -> i8 {
block0(v0: i32, v1: i64):
  v2 = load.i32 v1
  v3 = icmp.i32 ult v0, v2
  return v3
}

; VCode:
; block0:
;   cl %r2, 0(%r3)
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   cl %r2, 0(%r3) ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i32_memoff(i32, i64) -> i8 {
block0(v0: i32, v1: i64):
  v2 = load.i32 v1+4096
  v3 = icmp.i32 ult v0, v2
  return v3
}

; VCode:
; block0:
;   cly %r2, 4096(%r3)
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   cly %r2, 0x1000(%r3) ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i32_sym(i32) -> i8 {
  gv0 = symbol colocated %sym
block0(v0: i32):
  v1 = symbol_value.i64 gv0
  v2 = load.i32 aligned v1
  v3 = icmp.i32 ult v0, v2
  return v3
}

; VCode:
; block0:
;   clrl %r2, %sym + 0
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   clrl %r2, 0 ; reloc_external PCRel32Dbl %sym 2 ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i32_mem_ext16(i32, i64) -> i8 {
block0(v0: i32, v1: i64):
  v2 = uload16.i32 v1
  v3 = icmp.i32 ult v0, v2
  return v3
}

; VCode:
; block0:
;   llh %r5, 0(%r3)
;   clr %r2, %r5
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llh %r5, 0(%r3) ; trap: heap_oob
;   clr %r2, %r5
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i32_sym_ext16(i32) -> i8 {
  gv0 = symbol colocated %sym
block0(v0: i32):
  v1 = symbol_value.i64 gv0
  v2 = uload16.i32 aligned v1
  v3 = icmp.i32 ult v0, v2
  return v3
}

; VCode:
; block0:
;   clhrl %r2, %sym + 0
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   clhrl %r2, 0 ; reloc_external PCRel32Dbl %sym 2 ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i16(i16, i16) -> i8 {
block0(v0: i16, v1: i16):
  v2 = icmp.i16 ult v0, v1
  return v2
}

; VCode:
; block0:
;   lgr %r4, %r3
;   llhr %r3, %r2
;   lgr %r2, %r4
;   llhr %r5, %r2
;   clr %r3, %r5
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgr %r4, %r3
;   llhr %r3, %r2
;   lgr %r2, %r4
;   llhr %r5, %r2
;   clr %r3, %r5
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i16_imm(i16) -> i8 {
block0(v0: i16):
  v1 = iconst.i16 1
  v2 = icmp.i16 ult v0, v1
  return v2
}

; VCode:
; block0:
;   llhr %r2, %r2
;   clfi %r2, 1
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llhr %r2, %r2
;   clfi %r2, 1
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i16_mem(i16, i64) -> i8 {
block0(v0: i16, v1: i64):
  v2 = load.i16 v1
  v3 = icmp.i16 ult v0, v2
  return v3
}

; VCode:
; block0:
;   lgr %r4, %r3
;   llhr %r3, %r2
;   lgr %r2, %r4
;   llh %r5, 0(%r2)
;   clr %r3, %r5
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgr %r4, %r3
;   llhr %r3, %r2
;   lgr %r2, %r4
;   llh %r5, 0(%r2) ; trap: heap_oob
;   clr %r3, %r5
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i16_mem(i16) -> i8 {
  gv0 = symbol colocated %sym
block0(v0: i16):
  v1 = symbol_value.i64 gv0
  v2 = load.i16 aligned v1
  v3 = icmp.i16 ult v0, v2
  return v3
}

; VCode:
; block0:
;   llhr %r2, %r2
;   clhrl %r2, %sym + 0
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llhr %r2, %r2
;   clhrl %r2, 4 ; reloc_external PCRel32Dbl %sym 2 ; trap: heap_oob
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i8(i8, i8) -> i8 {
block0(v0: i8, v1: i8):
  v2 = icmp.i8 ult v0, v1
  return v2
}

; VCode:
; block0:
;   lgr %r4, %r3
;   llcr %r3, %r2
;   lgr %r2, %r4
;   llcr %r5, %r2
;   clr %r3, %r5
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgr %r4, %r3
;   llcr %r3, %r2
;   lgr %r2, %r4
;   llcr %r5, %r2
;   clr %r3, %r5
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i8_imm(i8) -> i8 {
block0(v0: i8):
  v1 = iconst.i8 1
  v2 = icmp.i8 ult v0, v1
  return v2
}

; VCode:
; block0:
;   llcr %r2, %r2
;   clfi %r2, 1
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llcr %r2, %r2
;   clfi %r2, 1
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

function %icmp_ult_i8_mem(i8, i64) -> i8 {
block0(v0: i8, v1: i64):
  v2 = load.i8 v1
  v3 = icmp.i8 ult v0, v2
  return v3
}

; VCode:
; block0:
;   lgr %r4, %r3
;   llcr %r3, %r2
;   lgr %r2, %r4
;   llc %r5, 0(%r2)
;   clr %r3, %r5
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgr %r4, %r3
;   llcr %r3, %r2
;   lgr %r2, %r4
;   llc %r5, 0(%r2) ; trap: heap_oob
;   clr %r3, %r5
;   lhi %r2, 0
;   lochil %r2, 1
;   br %r14

