test compile precise-output
target s390x

function %f(i32) -> i32 {
block0(v0: i32):
  br_table v0, block4, [block1, block2, block3]

block1:
  v1 = iconst.i32 1
  jump block5(v1)

block2:
  v2 = iconst.i32 2
  jump block5(v2)

block3:
  v3 = iconst.i32 3
  jump block5(v3)

block4:
  v4 = iconst.i32 4
  jump block5(v4)

block5(v5: i32):
  v6 = iadd.i32 v0, v5
  return v6
}

; VCode:
; block0:
;   llgfr %r4, %r2
;   sllg %r3, %r4, 2
;   clgfi %r4, 3
;   jghe label4 ; larl %r1, 14 ; agf %r1, 0(%r1, %r3) ; br %r1 ; jt_entries label3 label2 label1
; block1:
;   lhi %r3, 3
;   jg label5
; block2:
;   lhi %r3, 2
;   jg label5
; block3:
;   lhi %r3, 1
;   jg label5
; block4:
;   lhi %r3, 4
;   jg label5
; block5:
;   ar %r2, %r3
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llgfr %r4, %r2
;   sllg %r3, %r4, 2
;   clgfi %r4, 3
;   jghe 0x4e
;   larl %r1, 0x24
;   agf %r1, 0(%r3, %r1)
;   br %r1
;   .byte 0x00, 0x00
;   .byte 0x00, 0x20
;   .byte 0x00, 0x00
;   .byte 0x00, 0x16
;   .byte 0x00, 0x00
;   .byte 0x00, 0x0c
; block1: ; offset 0x30
;   lhi %r3, 3
;   jg 0x52
; block2: ; offset 0x3a
;   lhi %r3, 2
;   jg 0x52
; block3: ; offset 0x44
;   lhi %r3, 1
;   jg 0x52
; block4: ; offset 0x4e
;   lhi %r3, 4
; block5: ; offset 0x52
;   ar %r2, %r3
;   br %r14

