test compile precise-output
target s390x

function %f0(r64, r64) -> r64 {
block0(v0: r64, v1: r64):
  return v1
}

; VCode:
; block0:
;   lgr %r2, %r3
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgr %r2, %r3
;   br %r14

function %f1(r64) -> i8 {
block0(v0: r64):
  v1 = is_null v0
  return v1
}

; VCode:
; block0:
;   cghi %r2, 0
;   lhi %r2, 0
;   lochie %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   cghi %r2, 0
;   lhi %r2, 0
;   lochie %r2, 1
;   br %r14

function %f2(r64) -> i8 {
block0(v0: r64):
  v1 = is_invalid v0
  return v1
}

; VCode:
; block0:
;   cghi %r2, -1
;   lhi %r2, 0
;   lochie %r2, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   cghi %r2, -1
;   lhi %r2, 0
;   lochie %r2, 1
;   br %r14

function %f3() -> r64 {
block0:
  v0 = null.r64
  return v0
}

; VCode:
; block0:
;   lghi %r2, 0
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lghi %r2, 0
;   br %r14

function %f4(r64, r64) -> r64, r64, r64 {
    fn0 = %f(r64) -> i8
    ss0 = explicit_slot 8

block0(v0: r64, v1: r64):
    v2 = call fn0(v0)
    stack_store.r64 v0, ss0
    brif v2, block2(v0, v1), block1(v1, v0)

block1(v3: r64, v4: r64):
    jump block3(v3, v4)

block2(v5: r64, v6: r64):
    jump block3(v5, v6)

block3(v7: r64, v8: r64):
    v9 = stack_load.r64 ss0
    return v7, v8, v9
}

; VCode:
;   stmg %r11, %r15, 88(%r15)
;   aghi %r15, -184
; block0:
;   stg %r3, 176(%r15)
;   lgr %r3, %r2
;   lgr %r2, %r3
;   lgr %r11, %r3
;   bras %r1, 12 ; data %f + 0 ; lg %r3, 0(%r1)
;   stg %r11, 168(%r15)
;   basr %r14, %r3
;   la %r5, 160(%r15)
;   lgr %r3, %r11
;   stg %r3, 0(%r5)
;   lbr %r2, %r2
;   chi %r2, 0
;   jglh label2 ; jg label1
; block1:
;   lg %r2, 176(%r15)
;   lgr %r3, %r11
;   jg label3
; block2:
;   lgr %r2, %r11
;   lg %r3, 176(%r15)
;   jg label3
; block3:
;   la %r4, 160(%r15)
;   lg %r4, 0(%r4)
;   lmg %r11, %r15, 272(%r15)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r11, %r15, 0x58(%r15)
;   aghi %r15, -0xb8
; block1: ; offset 0xa
;   stg %r3, 0xb0(%r15)
;   lgr %r3, %r2
;   lgr %r2, %r3
;   lgr %r11, %r3
;   bras %r1, 0x28
;   .byte 0x00, 0x00 ; reloc_external Abs8 %f 0
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   lg %r3, 0(%r1)
;   stg %r11, 0xa8(%r15)
;   basr %r14, %r3
;   la %r5, 0xa0(%r15)
;   lgr %r3, %r11
;   stg %r3, 0(%r5)
;   lbr %r2, %r2
;   chi %r2, 0
;   jglh 0x62
; block2: ; offset 0x52
;   lg %r2, 0xb0(%r15)
;   lgr %r3, %r11
;   jg 0x6c
; block3: ; offset 0x62
;   lgr %r2, %r11
;   lg %r3, 0xb0(%r15)
; block4: ; offset 0x6c
;   la %r4, 0xa0(%r15)
;   lg %r4, 0(%r4)
;   lmg %r11, %r15, 0x110(%r15)
;   br %r14

