test compile precise-output
set enable_multi_ret_implicit_sret
set preserve_frame_pointers=true
target s390x

;;;; Test passing `i64`s ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

function %callee_i64(i64) -> i64 tail {
block0(v0: i64):
    v1 = iadd_imm.i64 v0, 10
    return v1
}

; VCode:
;   stmg %r14, %r15, 112(%r15)
;   lgr %r1, %r15
;   aghi %r15, -160
;   stg %r1, 0(%r15)
; block0:
;   aghi %r2, 10
;   lmg %r14, %r15, 272(%r15)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r14, %r15, 0x70(%r15)
;   lgr %r1, %r15
;   aghi %r15, -0xa0
;   stg %r1, 0(%r15)
; block1: ; offset 0x14
;   aghi %r2, 0xa
;   lmg %r14, %r15, 0x110(%r15)
;   br %r14

function %call_i64(i64) -> i64 tail {
    fn0 = %callee_i64(i64) -> i64 tail

block0(v0: i64):
    return_call fn0(v0)
}

; VCode:
;   stmg %r14, %r15, 112(%r15)
;   lgr %r1, %r15
;   aghi %r15, -160
;   stg %r1, 0(%r15)
; block0:
;   bras %r1, 12 ; data %callee_i64 + 0 ; lg %r4, 0(%r1)
;   lmg %r14, %r15, 272(%r15) ; br %r4
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r14, %r15, 0x70(%r15)
;   lgr %r1, %r15
;   aghi %r15, -0xa0
;   stg %r1, 0(%r15)
; block1: ; offset 0x14
;   bras %r1, 0x20
;   .byte 0x00, 0x00 ; reloc_external Abs8 %callee_i64 0
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   lg %r4, 0(%r1)
;   lmg %r14, %r15, 0x110(%r15)
;   br %r4

function %call_i64_multiret(i64) -> i64, i64, i64, i64, i64, i64, i64, i64 tail {
    fn0 = %callee_i64_multiret(i64) -> i64, i64, i64, i64, i64, i64, i64, i64 tail

block0(v0: i64):
    return_call fn0(v0)
}

; VCode:
;   stmg %r14, %r15, 112(%r15)
;   lgr %r1, %r15
;   aghi %r15, -160
;   stg %r1, 0(%r15)
; block0:
;   bras %r1, 12 ; data %callee_i64_multiret + 0 ; lg %r5, 0(%r1)
;   lmg %r14, %r15, 272(%r15) ; br %r5
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r14, %r15, 0x70(%r15)
;   lgr %r1, %r15
;   aghi %r15, -0xa0
;   stg %r1, 0(%r15)
; block1: ; offset 0x14
;   bras %r1, 0x20
;   .byte 0x00, 0x00 ; reloc_external Abs8 %callee_i64_multiret 0
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   lg %r5, 0(%r1)
;   lmg %r14, %r15, 0x110(%r15)
;   br %r5

function %call_i64_multiret_clobber(i64) -> i64, i64, i64, i64, i64, i64, i64, i64 tail {
    fn0 = %callee_i64_multiret(i64) -> i64, i64, i64, i64, i64, i64, i64, i64 tail
    fn1 = %callee_i64(i64) -> i64 tail

block0(v0: i64):
    v1 = call fn1(v0)
    return_call fn0(v1)
}

; VCode:
;   stmg %r9, %r15, 72(%r15)
;   lgr %r1, %r15
;   aghi %r15, -160
;   stg %r1, 0(%r15)
; block0:
;   lgr %r9, %r2
;   bras %r1, 12 ; data %callee_i64 + 0 ; lg %r7, 0(%r1)
;   lgr %r2, %r3
;   basr %r14, %r7
;   bras %r1, 12 ; data %callee_i64_multiret + 0 ; lg %r7, 0(%r1)
;   lgr %r3, %r2
;   lgr %r2, %r9
;   lmg %r9, %r15, 232(%r15) ; br %r7
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r9, %r15, 0x48(%r15)
;   lgr %r1, %r15
;   aghi %r15, -0xa0
;   stg %r1, 0(%r15)
; block1: ; offset 0x14
;   lgr %r9, %r2
;   bras %r1, 0x24
;   .byte 0x00, 0x00 ; reloc_external Abs8 %callee_i64 0
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   lg %r7, 0(%r1)
;   lgr %r2, %r3
;   basr %r14, %r7
;   bras %r1, 0x3c
;   .byte 0x00, 0x00 ; reloc_external Abs8 %callee_i64_multiret 0
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   lg %r7, 0(%r1)
;   lgr %r3, %r2
;   lgr %r2, %r9
;   lmg %r9, %r15, 0xe8(%r15)
;   br %r7

;;;; Test colocated tail calls ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

function %colocated_i64(i64) -> i64 tail {
    fn0 = colocated %callee_i64(i64) -> i64 tail

block0(v0: i64):
    return_call fn0(v0)
}

; VCode:
;   stmg %r14, %r15, 112(%r15)
;   lgr %r1, %r15
;   aghi %r15, -160
;   stg %r1, 0(%r15)
; block0:
;   lmg %r14, %r15, 272(%r15) ; jg %callee_i64
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r14, %r15, 0x70(%r15)
;   lgr %r1, %r15
;   aghi %r15, -0xa0
;   stg %r1, 0(%r15)
; block1: ; offset 0x14
;   lmg %r14, %r15, 0x110(%r15)
;   jg 0x1a ; reloc_external PLTRel32Dbl %callee_i64 2

;;;; Test passing `f64`s ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

function %callee_f64(f64) -> f64 tail {
block0(v0: f64):
    v1 = f64const 0x10.0
    v2 = fadd.f64 v0, v1
    return v2
}

; VCode:
;   stmg %r14, %r15, 112(%r15)
;   lgr %r1, %r15
;   aghi %r15, -160
;   stg %r1, 0(%r15)
; block0:
;   larl %r1, [const(0)] ; ld %f3, 0(%r1)
;   adbr %f0, %f3
;   lmg %r14, %r15, 272(%r15)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r14, %r15, 0x70(%r15)
;   lgr %r1, %r15
;   aghi %r15, -0xa0
;   stg %r1, 0(%r15)
; block1: ; offset 0x14
;   larl %r1, 0x30
;   ld %f3, 0(%r1)
;   adbr %f0, %f3
;   lmg %r14, %r15, 0x110(%r15)
;   br %r14
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   sth %r3, 0
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00

function %call_f64(f64) -> f64 tail {
    fn0 = %callee_f64(f64) -> f64 tail

block0(v0: f64):
    return_call fn0(v0)
}

; VCode:
;   stmg %r14, %r15, 112(%r15)
;   lgr %r1, %r15
;   aghi %r15, -160
;   stg %r1, 0(%r15)
; block0:
;   bras %r1, 12 ; data %callee_f64 + 0 ; lg %r4, 0(%r1)
;   lmg %r14, %r15, 272(%r15) ; br %r4
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r14, %r15, 0x70(%r15)
;   lgr %r1, %r15
;   aghi %r15, -0xa0
;   stg %r1, 0(%r15)
; block1: ; offset 0x14
;   bras %r1, 0x20
;   .byte 0x00, 0x00 ; reloc_external Abs8 %callee_f64 0
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   lg %r4, 0(%r1)
;   lmg %r14, %r15, 0x110(%r15)
;   br %r4

;;;; Test passing `i8`s ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

function %callee_i8(i8) -> i8 tail {
block0(v0: i8):
    v1 = iconst.i8 0
    v2 = icmp eq v0, v1
    return v2
}

; VCode:
;   stmg %r14, %r15, 112(%r15)
;   lgr %r1, %r15
;   aghi %r15, -160
;   stg %r1, 0(%r15)
; block0:
;   llcr %r4, %r2
;   clfi %r4, 0
;   lhi %r2, 0
;   lochie %r2, 1
;   lmg %r14, %r15, 272(%r15)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r14, %r15, 0x70(%r15)
;   lgr %r1, %r15
;   aghi %r15, -0xa0
;   stg %r1, 0(%r15)
; block1: ; offset 0x14
;   llcr %r4, %r2
;   clfi %r4, 0
;   lhi %r2, 0
;   lochie %r2, 1
;   lmg %r14, %r15, 0x110(%r15)
;   br %r14

function %call_i8(i8) -> i8 tail {
    fn0 = %callee_i8(i8) -> i8 tail

block0(v0: i8):
    return_call fn0(v0)
}

; VCode:
;   stmg %r14, %r15, 112(%r15)
;   lgr %r1, %r15
;   aghi %r15, -160
;   stg %r1, 0(%r15)
; block0:
;   bras %r1, 12 ; data %callee_i8 + 0 ; lg %r4, 0(%r1)
;   lmg %r14, %r15, 272(%r15) ; br %r4
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r14, %r15, 0x70(%r15)
;   lgr %r1, %r15
;   aghi %r15, -0xa0
;   stg %r1, 0(%r15)
; block1: ; offset 0x14
;   bras %r1, 0x20
;   .byte 0x00, 0x00 ; reloc_external Abs8 %callee_i8 0
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   lg %r4, 0(%r1)
;   lmg %r14, %r15, 0x110(%r15)
;   br %r4

;;;; Test passing fewer arguments on the stack ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

function %one_stack_arg(i32, i32, i32, i32, i32, i32, i32) tail {
block0(v0: i32, v1: i32, v2: i32, v3: i32, v4: i32, v5: i32, v6: i32):
    return
}

; VCode:
;   stmg %r14, %r15, 280(%r15)
;   la %r1, 168(%r15)
;   aghi %r15, -160
;   stg %r1, 0(%r15)
; block0:
;   aghi %r15, 328
;   lmg %r14, %r14, 112(%r15)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r14, %r15, 0x118(%r15)
;   la %r1, 0xa8(%r15)
;   aghi %r15, -0xa0
;   stg %r1, 0(%r15)
; block1: ; offset 0x14
;   aghi %r15, 0x148
;   lmg %r14, %r14, 0x70(%r15)
;   br %r14

function %call_one_stack_arg(i32, i32, i32, i32, i32, i32, i32, i32, i32) tail {
    fn0 = colocated %one_stack_arg(i32, i32, i32, i32, i32, i32, i32) tail

block0(v0: i32, v1: i32, v2: i32, v3: i32, v4: i32, v5: i32, v6: i32, v7: i32, v8: i32):
    return_call fn0(v2, v3, v4, v5, v6, v7, v8)
}

; VCode:
;   stmg %r9, %r15, 256(%r15)
;   la %r1, 184(%r15)
;   aghi %r15, -160
;   stg %r1, 0(%r15)
; block0:
;   lgr %r9, %r7
;   lgr %r14, %r6
;   llgf %r6, 324(%r15)
;   llgf %r7, 332(%r15)
;   llgf %r2, 340(%r15)
;   lg %r3, 344(%r15)
;   stg %r3, 176(%r15)
;   st %r2, 340(%r15)
;   lgr %r3, %r5
;   lgr %r5, %r9
;   lgr %r2, %r4
;   lgr %r4, %r14
;   aghi %r15, 176 ; lmg %r9, %r14, 240(%r15) ; jg %one_stack_arg ; callee_pop_size 168
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r9, %r15, 0x100(%r15)
;   la %r1, 0xb8(%r15)
;   aghi %r15, -0xa0
;   stg %r1, 0(%r15)
; block1: ; offset 0x14
;   lgr %r9, %r7
;   lgr %r14, %r6
;   llgf %r6, 0x144(%r15)
;   llgf %r7, 0x14c(%r15)
;   llgf %r2, 0x154(%r15)
;   lg %r3, 0x158(%r15)
;   stg %r3, 0xb0(%r15)
;   st %r2, 0x154(%r15)
;   lgr %r3, %r5
;   lgr %r5, %r9
;   lgr %r2, %r4
;   lgr %r4, %r14
;   aghi %r15, 0xb0
;   lmg %r9, %r14, 0xf0(%r15)
;   jg 0x58 ; reloc_external PLTRel32Dbl %one_stack_arg 2

function %call_zero_stack_args(i32, i32, i32, i32, i32, i32, i32, i32, i8) -> i8 tail {
    fn0 = colocated %callee_i8(i8) -> i8 tail

block0(v0: i32, v1: i32, v2: i32, v3: i32, v4: i32, v5: i32, v6: i32, v7: i32, v8: i8):
    return_call fn0(v8)
}

; VCode:
;   stmg %r14, %r15, 296(%r15)
;   la %r1, 184(%r15)
;   aghi %r15, -160
;   stg %r1, 0(%r15)
; block0:
;   llgc %r2, 343(%r15)
;   aghi %r15, 344 ; lmg %r14, %r14, 112(%r15) ; jg %callee_i8
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r14, %r15, 0x128(%r15)
;   la %r1, 0xb8(%r15)
;   aghi %r15, -0xa0
;   stg %r1, 0(%r15)
; block1: ; offset 0x14
;   llgc %r2, 0x157(%r15)
;   aghi %r15, 0x158
;   lmg %r14, %r14, 0x70(%r15)
;   jg 0x24 ; reloc_external PLTRel32Dbl %callee_i8 2

;;;; Test growing the argument area when it's non-empty ;;;;;;;;;;;;;;;;;;;;;;;;

function %call_from_one_stack_arg(i32, i32, i32, i32, i32, i32, i32) tail {
    fn0 = colocated %call_one_stack_arg(i32, i32, i32, i32, i32, i32, i32, i32, i32) tail

block0(v0: i32, v1: i32, v2: i32, v3: i32, v4: i32, v5: i32, v6: i32):
    return_call fn0(v1, v2, v3, v4, v5, v6, v0, v0, v1)
}

; VCode:
;   stmg %r8, %r15, 232(%r15)
;   la %r1, 168(%r15)
;   aghi %r15, -176
;   stg %r1, 0(%r15)
; block0:
;   lgr %r8, %r7
;   llgf %r7, 340(%r15)
;   lg %r10, 344(%r15)
;   stg %r10, 160(%r15)
;   st %r2, 324(%r15)
;   st %r2, 332(%r15)
;   st %r3, 340(%r15)
;   lgr %r2, %r3
;   lgr %r3, %r4
;   lgr %r4, %r5
;   lgr %r5, %r6
;   lgr %r6, %r8
;   aghi %r15, 160 ; lmg %r8, %r14, 248(%r15) ; jg %call_one_stack_arg ; callee_pop_size 184
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r8, %r15, 0xe8(%r15)
;   la %r1, 0xa8(%r15)
;   aghi %r15, -0xb0
;   stg %r1, 0(%r15)
; block1: ; offset 0x14
;   lgr %r8, %r7
;   llgf %r7, 0x154(%r15)
;   lg %r10, 0x158(%r15)
;   stg %r10, 0xa0(%r15)
;   st %r2, 0x144(%r15)
;   st %r2, 0x14c(%r15)
;   st %r3, 0x154(%r15)
;   lgr %r2, %r3
;   lgr %r3, %r4
;   lgr %r4, %r5
;   lgr %r5, %r6
;   lgr %r6, %r8
;   aghi %r15, 0xa0
;   lmg %r8, %r14, 0xf8(%r15)
;   jg 0x54 ; reloc_external PLTRel32Dbl %call_one_stack_arg 2

;;;; Test passing many arguments on stack ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

function %tail_callee_stack_args(i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64) -> i64 tail {
block0(v0: i64, v1: i64, v2: i64, v3: i64, v4: i64, v5: i64, v6: i64, v7: i64, v8: i64, v9: i64, v10: i64, v11: i64, v12: i64, v13: i64, v14: i64, v15: i64, v16: i64, v17: i64, v18: i64, v19: i64, v20: i64, v21: i64, v22: i64, v23: i64, v24: i64, v25: i64):
    return v25
}

; VCode:
;   stmg %r14, %r15, 432(%r15)
;   la %r1, 320(%r15)
;   aghi %r15, -160
;   stg %r1, 0(%r15)
; block0:
;   lg %r2, 472(%r15)
;   aghi %r15, 480
;   lmg %r14, %r14, 112(%r15)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r14, %r15, 0x1b0(%r15)
;   la %r1, 0x140(%r15)
;   aghi %r15, -0xa0
;   stg %r1, 0(%r15)
; block1: ; offset 0x14
;   lg %r2, 0x1d8(%r15)
;   aghi %r15, 0x1e0
;   lmg %r14, %r14, 0x70(%r15)
;   br %r14

function %tail_caller_stack_args() -> i64 tail {
    fn0 = %tail_callee_stack_args(i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64) -> i64 tail

block0:
    v0 = iconst.i64 10
    v1 = iconst.i64 15
    v2 = iconst.i64 20
    v3 = iconst.i64 25
    v4 = iconst.i64 30
    v5 = iconst.i64 35
    v6 = iconst.i64 40
    v7 = iconst.i64 45
    v8 = iconst.i64 50
    v9 = iconst.i64 55
    v10 = iconst.i64 60
    v11 = iconst.i64 65
    v12 = iconst.i64 70
    v13 = iconst.i64 75
    v14 = iconst.i64 80
    v15 = iconst.i64 85
    v16 = iconst.i64 90
    v17 = iconst.i64 95
    v18 = iconst.i64 100
    v19 = iconst.i64 105
    v20 = iconst.i64 110
    v21 = iconst.i64 115
    v22 = iconst.i64 120
    v23 = iconst.i64 125
    v24 = iconst.i64 130
    v25 = iconst.i64 135
    return_call fn0(v0, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, v22, v23, v24, v25)
}

; VCode:
;   stmg %r8, %r15, 64(%r15)
;   lgr %r1, %r15
;   aghi %r15, -592
;   stg %r1, 0(%r15)
; block0:
;   lghi %r3, 10
;   stg %r3, 264(%r15)
;   lghi %r4, 15
;   stg %r4, 256(%r15)
;   lghi %r5, 20
;   stg %r5, 248(%r15)
;   lghi %r6, 25
;   stg %r6, 240(%r15)
;   lghi %r7, 30
;   stg %r7, 232(%r15)
;   lghi %r7, 35
;   stg %r7, 224(%r15)
;   lghi %r14, 40
;   lghi %r8, 45
;   lghi %r9, 50
;   lghi %r10, 55
;   lghi %r11, 60
;   lghi %r12, 65
;   lghi %r13, 70
;   lghi %r2, 75
;   lghi %r3, 80
;   lghi %r4, 85
;   lghi %r6, 90
;   stg %r6, 216(%r15)
;   lghi %r6, 95
;   lghi %r7, 100
;   lghi %r5, 105
;   stg %r5, 208(%r15)
;   lghi %r5, 110
;   stg %r5, 200(%r15)
;   lghi %r5, 115
;   stg %r5, 192(%r15)
;   lghi %r5, 120
;   stg %r5, 184(%r15)
;   lghi %r5, 125
;   stg %r5, 176(%r15)
;   lghi %r5, 130
;   stg %r5, 168(%r15)
;   lghi %r5, 135
;   stg %r5, 160(%r15)
;   lg %r5, 592(%r15)
;   stg %r5, 272(%r15)
;   stg %r14, 432(%r15)
;   stg %r8, 440(%r15)
;   stg %r9, 448(%r15)
;   stg %r10, 456(%r15)
;   stg %r11, 464(%r15)
;   stg %r12, 472(%r15)
;   stg %r13, 480(%r15)
;   stg %r2, 488(%r15)
;   stg %r3, 496(%r15)
;   stg %r4, 504(%r15)
;   lg %r4, 216(%r15)
;   stg %r4, 512(%r15)
;   stg %r6, 520(%r15)
;   stg %r7, 528(%r15)
;   lg %r5, 208(%r15)
;   stg %r5, 536(%r15)
;   lg %r5, 200(%r15)
;   stg %r5, 544(%r15)
;   lg %r5, 192(%r15)
;   stg %r5, 552(%r15)
;   lg %r5, 184(%r15)
;   stg %r5, 560(%r15)
;   lg %r5, 176(%r15)
;   stg %r5, 568(%r15)
;   lg %r5, 168(%r15)
;   stg %r5, 576(%r15)
;   lg %r5, 160(%r15)
;   stg %r5, 584(%r15)
;   bras %r1, 12 ; data %tail_callee_stack_args + 0 ; lg %r8, 0(%r1)
;   lg %r2, 264(%r15)
;   lg %r3, 256(%r15)
;   lg %r4, 248(%r15)
;   lg %r5, 240(%r15)
;   lg %r6, 232(%r15)
;   lg %r7, 224(%r15)
;   lgr %r1, %r8 ; aghi %r15, 272 ; lmg %r8, %r14, 384(%r15) ; br %r1 ; callee_pop_size 320
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r8, %r15, 0x40(%r15)
;   lgr %r1, %r15
;   aghi %r15, -0x250
;   stg %r1, 0(%r15)
; block1: ; offset 0x14
;   lghi %r3, 0xa
;   stg %r3, 0x108(%r15)
;   lghi %r4, 0xf
;   stg %r4, 0x100(%r15)
;   lghi %r5, 0x14
;   stg %r5, 0xf8(%r15)
;   lghi %r6, 0x19
;   stg %r6, 0xf0(%r15)
;   lghi %r7, 0x1e
;   stg %r7, 0xe8(%r15)
;   lghi %r7, 0x23
;   stg %r7, 0xe0(%r15)
;   lghi %r14, 0x28
;   lghi %r8, 0x2d
;   lghi %r9, 0x32
;   lghi %r10, 0x37
;   lghi %r11, 0x3c
;   lghi %r12, 0x41
;   lghi %r13, 0x46
;   lghi %r2, 0x4b
;   lghi %r3, 0x50
;   lghi %r4, 0x55
;   lghi %r6, 0x5a
;   stg %r6, 0xd8(%r15)
;   lghi %r6, 0x5f
;   lghi %r7, 0x64
;   lghi %r5, 0x69
;   stg %r5, 0xd0(%r15)
;   lghi %r5, 0x6e
;   stg %r5, 0xc8(%r15)
;   lghi %r5, 0x73
;   stg %r5, 0xc0(%r15)
;   lghi %r5, 0x78
;   stg %r5, 0xb8(%r15)
;   lghi %r5, 0x7d
;   stg %r5, 0xb0(%r15)
;   lghi %r5, 0x82
;   stg %r5, 0xa8(%r15)
;   lghi %r5, 0x87
;   stg %r5, 0xa0(%r15)
;   lg %r5, 0x250(%r15)
;   stg %r5, 0x110(%r15)
;   stg %r14, 0x1b0(%r15)
;   stg %r8, 0x1b8(%r15)
;   stg %r9, 0x1c0(%r15)
;   stg %r10, 0x1c8(%r15)
;   stg %r11, 0x1d0(%r15)
;   stg %r12, 0x1d8(%r15)
;   stg %r13, 0x1e0(%r15)
;   stg %r2, 0x1e8(%r15)
;   stg %r3, 0x1f0(%r15)
;   stg %r4, 0x1f8(%r15)
;   lg %r4, 0xd8(%r15)
;   stg %r4, 0x200(%r15)
;   stg %r6, 0x208(%r15)
;   stg %r7, 0x210(%r15)
;   lg %r5, 0xd0(%r15)
;   stg %r5, 0x218(%r15)
;   lg %r5, 0xc8(%r15)
;   stg %r5, 0x220(%r15)
;   lg %r5, 0xc0(%r15)
;   stg %r5, 0x228(%r15)
;   lg %r5, 0xb8(%r15)
;   stg %r5, 0x230(%r15)
;   lg %r5, 0xb0(%r15)
;   stg %r5, 0x238(%r15)
;   lg %r5, 0xa8(%r15)
;   stg %r5, 0x240(%r15)
;   lg %r5, 0xa0(%r15)
;   stg %r5, 0x248(%r15)
;   bras %r1, 0x190
;   .byte 0x00, 0x00 ; reloc_external Abs8 %tail_callee_stack_args 0
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   lg %r8, 0(%r1)
;   lg %r2, 0x108(%r15)
;   lg %r3, 0x100(%r15)
;   lg %r4, 0xf8(%r15)
;   lg %r5, 0xf0(%r15)
;   lg %r6, 0xe8(%r15)
;   lg %r7, 0xe0(%r15)
;   lgr %r1, %r8
;   aghi %r15, 0x110
;   lmg %r8, %r14, 0x180(%r15)
;   br %r1

