test compile precise-output
set enable_multi_ret_implicit_sret
target s390x

function %rotr_i128_vr(i128, i128) -> i128 {
block0(v0: i128, v1: i128):
  v2 = rotr.i128 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r3)
;   vl %v3, 0(%r4)
;   vrepb %v6, %v3, 15
;   vlcb %v16, %v6
;   vslb %v17, %v1, %v16
;   vsl %v16, %v17, %v16
;   vsrlb %v17, %v1, %v6
;   vsrl %v17, %v17, %v6
;   vo %v18, %v16, %v17
;   vst %v18, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r3)
;   vl %v3, 0(%r4)
;   vrepb %v6, %v3, 0xf
;   vlcb %v16, %v6
;   vslb %v17, %v1, %v16
;   vsl %v16, %v17, %v16
;   vsrlb %v17, %v1, %v6
;   vsrl %v17, %v17, %v6
;   vo %v18, %v16, %v17
;   vst %v18, 0(%r2)
;   br %r14

function %rotr_i128_reg(i128, i64) -> i128 {
block0(v0: i128, v1: i64):
  v2 = rotr.i128 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r3)
;   vlvgb %v5, %r4, 0
;   vrepb %v7, %v5, 0
;   vlcb %v16, %v7
;   vslb %v17, %v1, %v16
;   vsl %v16, %v17, %v16
;   vsrlb %v17, %v1, %v7
;   vsrl %v17, %v17, %v7
;   vo %v19, %v16, %v17
;   vst %v19, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r3)
;   vlvgb %v5, %r4, 0
;   vrepb %v7, %v5, 0
;   vlcb %v16, %v7
;   vslb %v17, %v1, %v16
;   vsl %v16, %v17, %v16
;   vsrlb %v17, %v1, %v7
;   vsrl %v17, %v17, %v7
;   vo %v19, %v16, %v17
;   vst %v19, 0(%r2)
;   br %r14

function %rotr_i128_imm(i128) -> i128 {
block0(v0: i128):
  v1 = iconst.i32 17
  v2 = rotr.i128 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r3)
;   vrepib %v4, 17
;   vlcb %v6, %v4
;   vslb %v16, %v1, %v6
;   vsl %v16, %v16, %v6
;   vsrlb %v17, %v1, %v4
;   vsrl %v17, %v17, %v4
;   vo %v16, %v16, %v17
;   vst %v16, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r3)
;   vrepib %v4, 0x11
;   vlcb %v6, %v4
;   vslb %v16, %v1, %v6
;   vsl %v16, %v16, %v6
;   vsrlb %v17, %v1, %v4
;   vsrl %v17, %v17, %v4
;   vo %v16, %v16, %v17
;   vst %v16, 0(%r2)
;   br %r14

function %rotr_i64_vr(i64, i128) -> i64 {
block0(v0: i64, v1: i128):
  v2 = rotr.i64 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v2, 0(%r3)
;   vlgvg %r4, %v2, 1
;   lcr %r3, %r4
;   rllg %r2, %r2, 0(%r3)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v2, 0(%r3)
;   vlgvg %r4, %v2, 1
;   lcr %r3, %r4
;   rllg %r2, %r2, 0(%r3)
;   br %r14

function %rotr_i64_reg(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
  v2 = rotr.i64 v0, v1
  return v2
}

; VCode:
; block0:
;   lcr %r3, %r3
;   rllg %r2, %r2, 0(%r3)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lcr %r3, %r3
;   rllg %r2, %r2, 0(%r3)
;   br %r14

function %rotr_i64_imm(i64) -> i64 {
block0(v0: i64):
  v1 = iconst.i32 17
  v2 = rotr.i64 v0, v1
  return v2
}

; VCode:
; block0:
;   rllg %r2, %r2, 47
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   rllg %r2, %r2, 0x2f
;   br %r14

function %rotr_i32_vr(i32, i128) -> i32 {
block0(v0: i32, v1: i128):
  v2 = rotr.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v2, 0(%r3)
;   vlgvg %r4, %v2, 1
;   lcr %r3, %r4
;   rll %r2, %r2, 0(%r3)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v2, 0(%r3)
;   vlgvg %r4, %v2, 1
;   lcr %r3, %r4
;   rll %r2, %r2, 0(%r3)
;   br %r14

function %rotr_i32_reg(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = rotr.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   lcr %r3, %r3
;   rll %r2, %r2, 0(%r3)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lcr %r3, %r3
;   rll %r2, %r2, 0(%r3)
;   br %r14

function %rotr_i32_imm(i32) -> i32 {
block0(v0: i32):
  v1 = iconst.i32 17
  v2 = rotr.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   rll %r2, %r2, 15
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   rll %r2, %r2, 0xf
;   br %r14

function %rotr_i16_vr(i16, i128) -> i16 {
block0(v0: i16, v1: i128):
  v2 = rotr.i16 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v2, 0(%r3)
;   llhr %r4, %r2
;   vlgvg %r2, %v2, 1
;   lcr %r3, %r2
;   nill %r2, 15
;   nill %r3, 15
;   sllk %r3, %r4, 0(%r3)
;   srlk %r2, %r4, 0(%r2)
;   ork %r2, %r3, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v2, 0(%r3)
;   llhr %r4, %r2
;   vlgvg %r2, %v2, 1
;   lcr %r3, %r2
;   nill %r2, 0xf
;   nill %r3, 0xf
;   sllk %r3, %r4, 0(%r3)
;   srlk %r2, %r4, 0(%r2)
;   ork %r2, %r3, %r2
;   br %r14

function %rotr_i16_reg(i16, i16) -> i16 {
block0(v0: i16, v1: i16):
  v2 = rotr.i16 v0, v1
  return v2
}

; VCode:
; block0:
;   llhr %r4, %r2
;   lcr %r2, %r3
;   nill %r3, 15
;   nill %r2, 15
;   sllk %r2, %r4, 0(%r2)
;   srlk %r3, %r4, 0(%r3)
;   or %r2, %r3
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llhr %r4, %r2
;   lcr %r2, %r3
;   nill %r3, 0xf
;   nill %r2, 0xf
;   sllk %r2, %r4, 0(%r2)
;   srlk %r3, %r4, 0(%r3)
;   or %r2, %r3
;   br %r14

function %rotr_i16_imm(i16) -> i16 {
block0(v0: i16):
  v1 = iconst.i32 10
  v2 = rotr.i16 v0, v1
  return v2
}

; VCode:
; block0:
;   llhr %r2, %r2
;   sllk %r4, %r2, 6
;   srlk %r2, %r2, 10
;   ork %r2, %r4, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llhr %r2, %r2
;   sllk %r4, %r2, 6
;   srlk %r2, %r2, 0xa
;   ork %r2, %r4, %r2
;   br %r14

function %rotr_i8_vr(i8, i128) -> i8 {
block0(v0: i8, v1: i128):
  v2 = rotr.i8 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v2, 0(%r3)
;   llcr %r4, %r2
;   vlgvg %r2, %v2, 1
;   lcr %r3, %r2
;   nill %r2, 7
;   nill %r3, 7
;   sllk %r3, %r4, 0(%r3)
;   srlk %r2, %r4, 0(%r2)
;   ork %r2, %r3, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v2, 0(%r3)
;   llcr %r4, %r2
;   vlgvg %r2, %v2, 1
;   lcr %r3, %r2
;   nill %r2, 7
;   nill %r3, 7
;   sllk %r3, %r4, 0(%r3)
;   srlk %r2, %r4, 0(%r2)
;   ork %r2, %r3, %r2
;   br %r14

function %rotr_i8_reg(i8, i8) -> i8 {
block0(v0: i8, v1: i8):
  v2 = rotr.i8 v0, v1
  return v2
}

; VCode:
; block0:
;   llcr %r4, %r2
;   lcr %r2, %r3
;   nill %r3, 7
;   nill %r2, 7
;   sllk %r2, %r4, 0(%r2)
;   srlk %r3, %r4, 0(%r3)
;   or %r2, %r3
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llcr %r4, %r2
;   lcr %r2, %r3
;   nill %r3, 7
;   nill %r2, 7
;   sllk %r2, %r4, 0(%r2)
;   srlk %r3, %r4, 0(%r3)
;   or %r2, %r3
;   br %r14

function %rotr_i8_imm(i8) -> i8 {
block0(v0: i8):
  v1 = iconst.i32 3
  v2 = rotr.i8 v0, v1
  return v2
}

; VCode:
; block0:
;   llcr %r2, %r2
;   sllk %r4, %r2, 5
;   srlk %r2, %r2, 3
;   ork %r2, %r4, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llcr %r2, %r2
;   sllk %r4, %r2, 5
;   srlk %r2, %r2, 3
;   ork %r2, %r4, %r2
;   br %r14

function %rotl_i128_vr(i128, i128) -> i128 {
block0(v0: i128, v1: i128):
  v2 = rotl.i128 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r3)
;   vl %v3, 0(%r4)
;   vrepb %v6, %v3, 15
;   vlcb %v16, %v6
;   vslb %v17, %v1, %v6
;   vsl %v17, %v17, %v6
;   vsrlb %v18, %v1, %v16
;   vsrl %v16, %v18, %v16
;   vo %v18, %v17, %v16
;   vst %v18, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r3)
;   vl %v3, 0(%r4)
;   vrepb %v6, %v3, 0xf
;   vlcb %v16, %v6
;   vslb %v17, %v1, %v6
;   vsl %v17, %v17, %v6
;   vsrlb %v18, %v1, %v16
;   vsrl %v16, %v18, %v16
;   vo %v18, %v17, %v16
;   vst %v18, 0(%r2)
;   br %r14

function %rotl_i128_reg(i128, i64) -> i128 {
block0(v0: i128, v1: i64):
  v2 = rotl.i128 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r3)
;   vlvgb %v5, %r4, 0
;   vrepb %v7, %v5, 0
;   vlcb %v16, %v7
;   vslb %v17, %v1, %v7
;   vsl %v17, %v17, %v7
;   vsrlb %v18, %v1, %v16
;   vsrl %v18, %v18, %v16
;   vo %v19, %v17, %v18
;   vst %v19, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r3)
;   vlvgb %v5, %r4, 0
;   vrepb %v7, %v5, 0
;   vlcb %v16, %v7
;   vslb %v17, %v1, %v7
;   vsl %v17, %v17, %v7
;   vsrlb %v18, %v1, %v16
;   vsrl %v18, %v18, %v16
;   vo %v19, %v17, %v18
;   vst %v19, 0(%r2)
;   br %r14

function %rotl_i128_imm(i128) -> i128 {
block0(v0: i128):
  v1 = iconst.i32 17
  v2 = rotl.i128 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r3)
;   vrepib %v4, 17
;   vlcb %v6, %v4
;   vslb %v16, %v1, %v4
;   vsl %v16, %v16, %v4
;   vsrlb %v17, %v1, %v6
;   vsrl %v17, %v17, %v6
;   vo %v16, %v16, %v17
;   vst %v16, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r3)
;   vrepib %v4, 0x11
;   vlcb %v6, %v4
;   vslb %v16, %v1, %v4
;   vsl %v16, %v16, %v4
;   vsrlb %v17, %v1, %v6
;   vsrl %v17, %v17, %v6
;   vo %v16, %v16, %v17
;   vst %v16, 0(%r2)
;   br %r14

function %rotl_i64_vr(i64, i128) -> i64 {
block0(v0: i64, v1: i128):
  v2 = rotl.i64 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v2, 0(%r3)
;   vlgvg %r4, %v2, 1
;   rllg %r2, %r2, 0(%r4)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v2, 0(%r3)
;   vlgvg %r4, %v2, 1
;   rllg %r2, %r2, 0(%r4)
;   br %r14

function %rotl_i64_reg(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
  v2 = rotl.i64 v0, v1
  return v2
}

; VCode:
; block0:
;   rllg %r2, %r2, 0(%r3)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   rllg %r2, %r2, 0(%r3)
;   br %r14

function %rotl_i64_imm(i64) -> i64 {
block0(v0: i64):
  v1 = iconst.i32 17
  v2 = rotl.i64 v0, v1
  return v2
}

; VCode:
; block0:
;   rllg %r2, %r2, 17
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   rllg %r2, %r2, 0x11
;   br %r14

function %rotl_i32_vr(i32, i128) -> i32 {
block0(v0: i32, v1: i128):
  v2 = rotl.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v2, 0(%r3)
;   vlgvg %r4, %v2, 1
;   rll %r2, %r2, 0(%r4)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v2, 0(%r3)
;   vlgvg %r4, %v2, 1
;   rll %r2, %r2, 0(%r4)
;   br %r14

function %rotl_i32_reg(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = rotl.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   rll %r2, %r2, 0(%r3)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   rll %r2, %r2, 0(%r3)
;   br %r14

function %rotl_i32_imm(i32) -> i32 {
block0(v0: i32):
  v1 = iconst.i32 17
  v2 = rotl.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   rll %r2, %r2, 17
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   rll %r2, %r2, 0x11
;   br %r14

function %rotl_i16_vr(i16, i128) -> i16 {
block0(v0: i16, v1: i128):
  v2 = rotl.i16 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v2, 0(%r3)
;   llhr %r4, %r2
;   vlgvg %r3, %v2, 1
;   lcr %r2, %r3
;   nill %r3, 15
;   nill %r2, 15
;   sllk %r3, %r4, 0(%r3)
;   srlk %r2, %r4, 0(%r2)
;   ork %r2, %r3, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v2, 0(%r3)
;   llhr %r4, %r2
;   vlgvg %r3, %v2, 1
;   lcr %r2, %r3
;   nill %r3, 0xf
;   nill %r2, 0xf
;   sllk %r3, %r4, 0(%r3)
;   srlk %r2, %r4, 0(%r2)
;   ork %r2, %r3, %r2
;   br %r14

function %rotl_i16_reg(i16, i16) -> i16 {
block0(v0: i16, v1: i16):
  v2 = rotl.i16 v0, v1
  return v2
}

; VCode:
; block0:
;   llhr %r4, %r2
;   lcr %r2, %r3
;   nill %r3, 15
;   nill %r2, 15
;   sllk %r3, %r4, 0(%r3)
;   srlk %r2, %r4, 0(%r2)
;   ork %r2, %r3, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llhr %r4, %r2
;   lcr %r2, %r3
;   nill %r3, 0xf
;   nill %r2, 0xf
;   sllk %r3, %r4, 0(%r3)
;   srlk %r2, %r4, 0(%r2)
;   ork %r2, %r3, %r2
;   br %r14

function %rotl_i16_imm(i16) -> i16 {
block0(v0: i16):
  v1 = iconst.i32 10
  v2 = rotl.i16 v0, v1
  return v2
}

; VCode:
; block0:
;   llhr %r2, %r2
;   sllk %r4, %r2, 10
;   srlk %r2, %r2, 6
;   ork %r2, %r4, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llhr %r2, %r2
;   sllk %r4, %r2, 0xa
;   srlk %r2, %r2, 6
;   ork %r2, %r4, %r2
;   br %r14

function %rotl_i8_vr(i8, i128) -> i8 {
block0(v0: i8, v1: i128):
  v2 = rotl.i8 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v2, 0(%r3)
;   llcr %r4, %r2
;   vlgvg %r3, %v2, 1
;   lcr %r2, %r3
;   nill %r3, 7
;   nill %r2, 7
;   sllk %r3, %r4, 0(%r3)
;   srlk %r2, %r4, 0(%r2)
;   ork %r2, %r3, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v2, 0(%r3)
;   llcr %r4, %r2
;   vlgvg %r3, %v2, 1
;   lcr %r2, %r3
;   nill %r3, 7
;   nill %r2, 7
;   sllk %r3, %r4, 0(%r3)
;   srlk %r2, %r4, 0(%r2)
;   ork %r2, %r3, %r2
;   br %r14

function %rotl_i8_reg(i8, i8) -> i8 {
block0(v0: i8, v1: i8):
  v2 = rotl.i8 v0, v1
  return v2
}

; VCode:
; block0:
;   llcr %r4, %r2
;   lcr %r2, %r3
;   nill %r3, 7
;   nill %r2, 7
;   sllk %r3, %r4, 0(%r3)
;   srlk %r2, %r4, 0(%r2)
;   ork %r2, %r3, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llcr %r4, %r2
;   lcr %r2, %r3
;   nill %r3, 7
;   nill %r2, 7
;   sllk %r3, %r4, 0(%r3)
;   srlk %r2, %r4, 0(%r2)
;   ork %r2, %r3, %r2
;   br %r14

function %rotr_i8_imm(i8) -> i8 {
block0(v0: i8):
  v1 = iconst.i32 3
  v2 = rotl.i8 v0, v1
  return v2
}

; VCode:
; block0:
;   llcr %r2, %r2
;   sllk %r4, %r2, 3
;   srlk %r2, %r2, 5
;   ork %r2, %r4, %r2
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llcr %r2, %r2
;   sllk %r4, %r2, 3
;   srlk %r2, %r2, 5
;   ork %r2, %r4, %r2
;   br %r14

function %ushr_i128_vr(i128, i128) -> i128 {
block0(v0: i128, v1: i128):
  v2 = ushr.i128 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r3)
;   vl %v3, 0(%r4)
;   vrepb %v6, %v3, 15
;   vsrlb %v16, %v1, %v6
;   vsrl %v16, %v16, %v6
;   vst %v16, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r3)
;   vl %v3, 0(%r4)
;   vrepb %v6, %v3, 0xf
;   vsrlb %v16, %v1, %v6
;   vsrl %v16, %v16, %v6
;   vst %v16, 0(%r2)
;   br %r14

function %ushr_i128_reg(i128, i64) -> i128 {
block0(v0: i128, v1: i64):
  v2 = ushr.i128 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r3)
;   vlvgb %v5, %r4, 0
;   vrepb %v7, %v5, 0
;   vsrlb %v16, %v1, %v7
;   vsrl %v16, %v16, %v7
;   vst %v16, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r3)
;   vlvgb %v5, %r4, 0
;   vrepb %v7, %v5, 0
;   vsrlb %v16, %v1, %v7
;   vsrl %v16, %v16, %v7
;   vst %v16, 0(%r2)
;   br %r14

function %ushr_i128_imm(i128) -> i128 {
block0(v0: i128):
  v1 = iconst.i32 17
  v2 = ushr.i128 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r3)
;   vrepib %v4, 17
;   vsrlb %v6, %v1, %v4
;   vsrl %v16, %v6, %v4
;   vst %v16, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r3)
;   vrepib %v4, 0x11
;   vsrlb %v6, %v1, %v4
;   vsrl %v16, %v6, %v4
;   vst %v16, 0(%r2)
;   br %r14

function %ushr_i64_vr(i64, i128) -> i64 {
block0(v0: i64, v1: i128):
  v2 = ushr.i64 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v2, 0(%r3)
;   vlgvg %r4, %v2, 1
;   srlg %r2, %r2, 0(%r4)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v2, 0(%r3)
;   vlgvg %r4, %v2, 1
;   srlg %r2, %r2, 0(%r4)
;   br %r14

function %ushr_i64_reg(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
  v2 = ushr.i64 v0, v1
  return v2
}

; VCode:
; block0:
;   srlg %r2, %r2, 0(%r3)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   srlg %r2, %r2, 0(%r3)
;   br %r14

function %ushr_i64_imm(i64) -> i64 {
block0(v0: i64):
  v1 = iconst.i32 17
  v2 = ushr.i64 v0, v1
  return v2
}

; VCode:
; block0:
;   srlg %r2, %r2, 17
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   srlg %r2, %r2, 0x11
;   br %r14

function %ushr_i32_vr(i32, i128) -> i32 {
block0(v0: i32, v1: i128):
  v2 = ushr.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v2, 0(%r3)
;   vlgvg %r5, %v2, 1
;   nill %r5, 31
;   srlk %r2, %r2, 0(%r5)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v2, 0(%r3)
;   vlgvg %r5, %v2, 1
;   nill %r5, 0x1f
;   srlk %r2, %r2, 0(%r5)
;   br %r14

function %ushr_i32_reg(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = ushr.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   nill %r3, 31
;   srlk %r2, %r2, 0(%r3)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   nill %r3, 0x1f
;   srlk %r2, %r2, 0(%r3)
;   br %r14

function %ushr_i32_imm(i32) -> i32 {
block0(v0: i32):
  v1 = iconst.i32 17
  v2 = ushr.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   srlk %r2, %r2, 17
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   srlk %r2, %r2, 0x11
;   br %r14

function %ushr_i16_vr(i16, i128) -> i16 {
block0(v0: i16, v1: i128):
  v2 = ushr.i16 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v2, 0(%r3)
;   llhr %r4, %r2
;   vlgvg %r2, %v2, 1
;   nill %r2, 15
;   srlk %r2, %r4, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v2, 0(%r3)
;   llhr %r4, %r2
;   vlgvg %r2, %v2, 1
;   nill %r2, 0xf
;   srlk %r2, %r4, 0(%r2)
;   br %r14

function %ushr_i16_reg(i16, i16) -> i16 {
block0(v0: i16, v1: i16):
  v2 = ushr.i16 v0, v1
  return v2
}

; VCode:
; block0:
;   llhr %r4, %r2
;   nill %r3, 15
;   srlk %r2, %r4, 0(%r3)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llhr %r4, %r2
;   nill %r3, 0xf
;   srlk %r2, %r4, 0(%r3)
;   br %r14

function %ushr_i16_imm(i16) -> i16 {
block0(v0: i16):
  v1 = iconst.i32 10
  v2 = ushr.i16 v0, v1
  return v2
}

; VCode:
; block0:
;   llhr %r2, %r2
;   srlk %r2, %r2, 10
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llhr %r2, %r2
;   srlk %r2, %r2, 0xa
;   br %r14

function %ushr_i8_vr(i8, i128) -> i8 {
block0(v0: i8, v1: i128):
  v2 = ushr.i8 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v2, 0(%r3)
;   llcr %r4, %r2
;   vlgvg %r2, %v2, 1
;   nill %r2, 7
;   srlk %r2, %r4, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v2, 0(%r3)
;   llcr %r4, %r2
;   vlgvg %r2, %v2, 1
;   nill %r2, 7
;   srlk %r2, %r4, 0(%r2)
;   br %r14

function %ushr_i8_reg(i8, i8) -> i8 {
block0(v0: i8, v1: i8):
  v2 = ushr.i8 v0, v1
  return v2
}

; VCode:
; block0:
;   llcr %r4, %r2
;   nill %r3, 7
;   srlk %r2, %r4, 0(%r3)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llcr %r4, %r2
;   nill %r3, 7
;   srlk %r2, %r4, 0(%r3)
;   br %r14

function %ushr_i8_imm(i8) -> i8 {
block0(v0: i8):
  v1 = iconst.i32 3
  v2 = ushr.i8 v0, v1
  return v2
}

; VCode:
; block0:
;   llcr %r2, %r2
;   srlk %r2, %r2, 3
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llcr %r2, %r2
;   srlk %r2, %r2, 3
;   br %r14

function %ishl_i128_vr(i128, i128) -> i128 {
block0(v0: i128, v1: i128):
  v2 = ishl.i128 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r3)
;   vl %v3, 0(%r4)
;   vrepb %v6, %v3, 15
;   vslb %v16, %v1, %v6
;   vsl %v16, %v16, %v6
;   vst %v16, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r3)
;   vl %v3, 0(%r4)
;   vrepb %v6, %v3, 0xf
;   vslb %v16, %v1, %v6
;   vsl %v16, %v16, %v6
;   vst %v16, 0(%r2)
;   br %r14

function %ishl_i128_reg(i128, i64) -> i128 {
block0(v0: i128, v1: i64):
  v2 = ishl.i128 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r3)
;   vlvgb %v5, %r4, 0
;   vrepb %v7, %v5, 0
;   vslb %v16, %v1, %v7
;   vsl %v16, %v16, %v7
;   vst %v16, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r3)
;   vlvgb %v5, %r4, 0
;   vrepb %v7, %v5, 0
;   vslb %v16, %v1, %v7
;   vsl %v16, %v16, %v7
;   vst %v16, 0(%r2)
;   br %r14

function %ishl_i128_imm(i128) -> i128 {
block0(v0: i128):
  v1 = iconst.i32 17
  v2 = ishl.i128 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r3)
;   vrepib %v4, 17
;   vslb %v6, %v1, %v4
;   vsl %v16, %v6, %v4
;   vst %v16, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r3)
;   vrepib %v4, 0x11
;   vslb %v6, %v1, %v4
;   vsl %v16, %v6, %v4
;   vst %v16, 0(%r2)
;   br %r14

function %ishl_i64_vr(i64, i128) -> i64 {
block0(v0: i64, v1: i128):
  v2 = ishl.i64 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v2, 0(%r3)
;   vlgvg %r4, %v2, 1
;   sllg %r2, %r2, 0(%r4)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v2, 0(%r3)
;   vlgvg %r4, %v2, 1
;   sllg %r2, %r2, 0(%r4)
;   br %r14

function %ishl_i64_reg(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
  v2 = ishl.i64 v0, v1
  return v2
}

; VCode:
; block0:
;   sllg %r2, %r2, 0(%r3)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   sllg %r2, %r2, 0(%r3)
;   br %r14

function %ishl_i64_imm(i64) -> i64 {
block0(v0: i64):
  v1 = iconst.i32 17
  v2 = ishl.i64 v0, v1
  return v2
}

; VCode:
; block0:
;   sllg %r2, %r2, 17
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   sllg %r2, %r2, 0x11
;   br %r14

function %ishl_i32_vr(i32, i128) -> i32 {
block0(v0: i32, v1: i128):
  v2 = ishl.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v2, 0(%r3)
;   vlgvg %r5, %v2, 1
;   nill %r5, 31
;   sllk %r2, %r2, 0(%r5)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v2, 0(%r3)
;   vlgvg %r5, %v2, 1
;   nill %r5, 0x1f
;   sllk %r2, %r2, 0(%r5)
;   br %r14

function %ishl_i32_reg(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = ishl.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   nill %r3, 31
;   sllk %r2, %r2, 0(%r3)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   nill %r3, 0x1f
;   sllk %r2, %r2, 0(%r3)
;   br %r14

function %ishl_i32_imm(i32) -> i32 {
block0(v0: i32):
  v1 = iconst.i32 17
  v2 = ishl.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   sllk %r2, %r2, 17
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   sllk %r2, %r2, 0x11
;   br %r14

function %ishl_i16_vr(i16, i128) -> i16 {
block0(v0: i16, v1: i128):
  v2 = ishl.i16 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v2, 0(%r3)
;   vlgvg %r5, %v2, 1
;   nill %r5, 15
;   sllk %r2, %r2, 0(%r5)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v2, 0(%r3)
;   vlgvg %r5, %v2, 1
;   nill %r5, 0xf
;   sllk %r2, %r2, 0(%r5)
;   br %r14

function %ishl_i16_reg(i16, i16) -> i16 {
block0(v0: i16, v1: i16):
  v2 = ishl.i16 v0, v1
  return v2
}

; VCode:
; block0:
;   nill %r3, 15
;   sllk %r2, %r2, 0(%r3)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   nill %r3, 0xf
;   sllk %r2, %r2, 0(%r3)
;   br %r14

function %ishl_i16_imm(i16) -> i16 {
block0(v0: i16):
  v1 = iconst.i32 10
  v2 = ishl.i16 v0, v1
  return v2
}

; VCode:
; block0:
;   sllk %r2, %r2, 10
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   sllk %r2, %r2, 0xa
;   br %r14

function %ishl_i8_vr(i8, i128) -> i8 {
block0(v0: i8, v1: i128):
  v2 = ishl.i8 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v2, 0(%r3)
;   vlgvg %r5, %v2, 1
;   nill %r5, 7
;   sllk %r2, %r2, 0(%r5)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v2, 0(%r3)
;   vlgvg %r5, %v2, 1
;   nill %r5, 7
;   sllk %r2, %r2, 0(%r5)
;   br %r14

function %ishl_i8_reg(i8, i8) -> i8 {
block0(v0: i8, v1: i8):
  v2 = ishl.i8 v0, v1
  return v2
}

; VCode:
; block0:
;   nill %r3, 7
;   sllk %r2, %r2, 0(%r3)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   nill %r3, 7
;   sllk %r2, %r2, 0(%r3)
;   br %r14

function %ishl_i8_imm(i8) -> i8 {
block0(v0: i8):
  v1 = iconst.i32 3
  v2 = ishl.i8 v0, v1
  return v2
}

; VCode:
; block0:
;   sllk %r2, %r2, 3
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   sllk %r2, %r2, 3
;   br %r14

function %sshr_i128_vr(i128, i128) -> i128 {
block0(v0: i128, v1: i128):
  v2 = sshr.i128 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r3)
;   vl %v3, 0(%r4)
;   vrepb %v6, %v3, 15
;   vsrab %v16, %v1, %v6
;   vsra %v16, %v16, %v6
;   vst %v16, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r3)
;   vl %v3, 0(%r4)
;   vrepb %v6, %v3, 0xf
;   vsrab %v16, %v1, %v6
;   vsra %v16, %v16, %v6
;   vst %v16, 0(%r2)
;   br %r14

function %sshr_i128_reg(i128, i64) -> i128 {
block0(v0: i128, v1: i64):
  v2 = sshr.i128 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r3)
;   vlvgb %v5, %r4, 0
;   vrepb %v7, %v5, 0
;   vsrab %v16, %v1, %v7
;   vsra %v16, %v16, %v7
;   vst %v16, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r3)
;   vlvgb %v5, %r4, 0
;   vrepb %v7, %v5, 0
;   vsrab %v16, %v1, %v7
;   vsra %v16, %v16, %v7
;   vst %v16, 0(%r2)
;   br %r14

function %sshr_i128_imm(i128) -> i128 {
block0(v0: i128):
  v1 = iconst.i32 17
  v2 = sshr.i128 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v1, 0(%r3)
;   vrepib %v4, 17
;   vsrab %v6, %v1, %v4
;   vsra %v16, %v6, %v4
;   vst %v16, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v1, 0(%r3)
;   vrepib %v4, 0x11
;   vsrab %v6, %v1, %v4
;   vsra %v16, %v6, %v4
;   vst %v16, 0(%r2)
;   br %r14

function %sshr_i64_vr(i64, i128) -> i64 {
block0(v0: i64, v1: i128):
  v2 = sshr.i64 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v2, 0(%r3)
;   vlgvg %r4, %v2, 1
;   srag %r2, %r2, 0(%r4)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v2, 0(%r3)
;   vlgvg %r4, %v2, 1
;   srag %r2, %r2, 0(%r4)
;   br %r14

function %sshr_i64_reg(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
  v2 = sshr.i64 v0, v1
  return v2
}

; VCode:
; block0:
;   srag %r2, %r2, 0(%r3)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   srag %r2, %r2, 0(%r3)
;   br %r14

function %sshr_i64_imm(i64) -> i64 {
block0(v0: i64):
  v1 = iconst.i32 17
  v2 = sshr.i64 v0, v1
  return v2
}

; VCode:
; block0:
;   srag %r2, %r2, 17
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   srag %r2, %r2, 0x11
;   br %r14

function %sshr_i32_vr(i32, i128) -> i32 {
block0(v0: i32, v1: i128):
  v2 = sshr.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v2, 0(%r3)
;   vlgvg %r5, %v2, 1
;   nill %r5, 31
;   srak %r2, %r2, 0(%r5)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v2, 0(%r3)
;   vlgvg %r5, %v2, 1
;   nill %r5, 0x1f
;   srak %r2, %r2, 0(%r5)
;   br %r14

function %sshr_i32_reg(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
  v2 = sshr.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   nill %r3, 31
;   srak %r2, %r2, 0(%r3)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   nill %r3, 0x1f
;   srak %r2, %r2, 0(%r3)
;   br %r14

function %sshr_i32_imm(i32) -> i32 {
block0(v0: i32):
  v1 = iconst.i32 17
  v2 = sshr.i32 v0, v1
  return v2
}

; VCode:
; block0:
;   srak %r2, %r2, 17
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   srak %r2, %r2, 0x11
;   br %r14

function %sshr_i16_vr(i16, i128) -> i16 {
block0(v0: i16, v1: i128):
  v2 = sshr.i16 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v2, 0(%r3)
;   lhr %r4, %r2
;   vlgvg %r2, %v2, 1
;   nill %r2, 15
;   srak %r2, %r4, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v2, 0(%r3)
;   lhr %r4, %r2
;   vlgvg %r2, %v2, 1
;   nill %r2, 0xf
;   srak %r2, %r4, 0(%r2)
;   br %r14

function %sshr_i16_reg(i16, i16) -> i16 {
block0(v0: i16, v1: i16):
  v2 = sshr.i16 v0, v1
  return v2
}

; VCode:
; block0:
;   lhr %r4, %r2
;   nill %r3, 15
;   srak %r2, %r4, 0(%r3)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lhr %r4, %r2
;   nill %r3, 0xf
;   srak %r2, %r4, 0(%r3)
;   br %r14

function %sshr_i16_imm(i16) -> i16 {
block0(v0: i16):
  v1 = iconst.i32 10
  v2 = sshr.i16 v0, v1
  return v2
}

; VCode:
; block0:
;   lhr %r2, %r2
;   srak %r2, %r2, 10
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lhr %r2, %r2
;   srak %r2, %r2, 0xa
;   br %r14

function %sshr_i8_vr(i8, i128) -> i8 {
block0(v0: i8, v1: i128):
  v2 = sshr.i8 v0, v1
  return v2
}

; VCode:
; block0:
;   vl %v2, 0(%r3)
;   lbr %r4, %r2
;   vlgvg %r2, %v2, 1
;   nill %r2, 7
;   srak %r2, %r4, 0(%r2)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vl %v2, 0(%r3)
;   lbr %r4, %r2
;   vlgvg %r2, %v2, 1
;   nill %r2, 7
;   srak %r2, %r4, 0(%r2)
;   br %r14

function %sshr_i8_reg(i8, i8) -> i8 {
block0(v0: i8, v1: i8):
  v2 = sshr.i8 v0, v1
  return v2
}

; VCode:
; block0:
;   lbr %r4, %r2
;   nill %r3, 7
;   srak %r2, %r4, 0(%r3)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lbr %r4, %r2
;   nill %r3, 7
;   srak %r2, %r4, 0(%r3)
;   br %r14

function %sshr_i8_imm(i8) -> i8 {
block0(v0: i8):
  v1 = iconst.i32 3
  v2 = sshr.i8 v0, v1
  return v2
}

; VCode:
; block0:
;   lbr %r2, %r2
;   srak %r2, %r2, 3
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lbr %r2, %r2
;   srak %r2, %r2, 3
;   br %r14

