test compile precise-output
target s390x

function %f2(i8, i8) -> i8, i8 {
block0(v0: i8, v1: i8):
    v2, v3 = smul_overflow v0, v1
    return v2, v3
}

; VCode:
; block0:
;   lbr %r3, %r3
;   sllk %r5, %r2, 24
;   msrkc %r2, %r5, %r3
;   lhi %r3, 0
;   lochio %r3, 1
;   srlk %r2, %r2, 24
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lbr %r3, %r3
;   sllk %r5, %r2, 0x18
;   msrkc %r2, %r5, %r3
;   lhi %r3, 0
;   lochio %r3, 1
;   srlk %r2, %r2, 0x18
;   br %r14

function %f2(i16, i16) -> i16, i8 {
block0(v0: i16, v1: i16):
    v2, v3 = smul_overflow v0, v1
    return v2, v3
}

; VCode:
; block0:
;   lhr %r3, %r3
;   sllk %r5, %r2, 16
;   msrkc %r2, %r5, %r3
;   lhi %r3, 0
;   lochio %r3, 1
;   srlk %r2, %r2, 16
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lhr %r3, %r3
;   sllk %r5, %r2, 0x10
;   msrkc %r2, %r5, %r3
;   lhi %r3, 0
;   lochio %r3, 1
;   srlk %r2, %r2, 0x10
;   br %r14

function %f2(i32, i32) -> i32, i8 {
block0(v0: i32, v1: i32):
    v2, v3 = smul_overflow v0, v1
    return v2, v3
}

; VCode:
; block0:
;   msrkc %r2, %r2, %r3
;   lhi %r3, 0
;   lochio %r3, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   msrkc %r2, %r2, %r3
;   lhi %r3, 0
;   lochio %r3, 1
;   br %r14

function %f4(i64, i64) -> i64, i8 {
block0(v0: i64, v1: i64):
    v2, v3 = smul_overflow v0, v1
    return v2, v3
}

; VCode:
; block0:
;   msgrkc %r2, %r2, %r3
;   lhi %r3, 0
;   lochio %r3, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   msgrkc %r2, %r2, %r3
;   lhi %r3, 0
;   lochio %r3, 1
;   br %r14

