test compile precise-output
target s390x

; FIXME: Should allocate register save area.

function %stack_addr_small() -> i64 {
ss0 = explicit_slot 8

block0:
  v0 = stack_addr.i64 ss0
  return v0
}

; VCode:
;   aghi %r15, -8
; block0:
;   la %r2, 0(%r15)
;   aghi %r15, 8
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   aghi %r15, -8
; block1: ; offset 0x4
;   la %r2, 0(%r15)
;   aghi %r15, 8
;   br %r14

function %stack_addr_big() -> i64 {
ss0 = explicit_slot 100000
ss1 = explicit_slot 8

block0:
  v0 = stack_addr.i64 ss0
  return v0
}

; VCode:
;   agfi %r15, -100008
; block0:
;   la %r2, 0(%r15)
;   agfi %r15, 100008
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   agfi %r15, -0x186a8
; block1: ; offset 0x6
;   la %r2, 0(%r15)
;   agfi %r15, 0x186a8
;   br %r14

function %stack_load_small() -> i64 {
ss0 = explicit_slot 8

block0:
  v0 = stack_load.i64 ss0
  return v0
}

; VCode:
;   aghi %r15, -8
; block0:
;   la %r3, 0(%r15)
;   lg %r2, 0(%r3)
;   aghi %r15, 8
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   aghi %r15, -8
; block1: ; offset 0x4
;   la %r3, 0(%r15)
;   lg %r2, 0(%r3)
;   aghi %r15, 8
;   br %r14

function %stack_load_big() -> i64 {
ss0 = explicit_slot 100000
ss1 = explicit_slot 8

block0:
  v0 = stack_load.i64 ss0
  return v0
}

; VCode:
;   agfi %r15, -100008
; block0:
;   la %r3, 0(%r15)
;   lg %r2, 0(%r3)
;   agfi %r15, 100008
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   agfi %r15, -0x186a8
; block1: ; offset 0x6
;   la %r3, 0(%r15)
;   lg %r2, 0(%r3)
;   agfi %r15, 0x186a8
;   br %r14

function %stack_store_small(i64) {
ss0 = explicit_slot 8

block0(v0: i64):
  stack_store.i64 v0, ss0
  return
}

; VCode:
;   aghi %r15, -8
; block0:
;   la %r4, 0(%r15)
;   stg %r2, 0(%r4)
;   aghi %r15, 8
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   aghi %r15, -8
; block1: ; offset 0x4
;   la %r4, 0(%r15)
;   stg %r2, 0(%r4)
;   aghi %r15, 8
;   br %r14

function %stack_store_big(i64) {
ss0 = explicit_slot 100000
ss1 = explicit_slot 8

block0(v0: i64):
  stack_store.i64 v0, ss0
  return
}

; VCode:
;   agfi %r15, -100008
; block0:
;   la %r4, 0(%r15)
;   stg %r2, 0(%r4)
;   agfi %r15, 100008
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   agfi %r15, -0x186a8
; block1: ; offset 0x6
;   la %r4, 0(%r15)
;   stg %r2, 0(%r4)
;   agfi %r15, 0x186a8
;   br %r14

