test compile precise-output
set tls_model=elf_gd
target s390x

function u0:0(i32) -> i64 {
gv0 = symbol colocated tls u1:0

block0(v0: i32):
    v1 = tls_value.i64 gv0
    return v1
}

; VCode:
;   stmg %r12, %r15, 96(%r15)
;   aghi %r15, -160
; block0:
;   larl %r12, %ElfGlobalOffsetTable + 0
;   bras %r1, 12 ; data userextname0@tlsgd ; lg %r2, 0(%r1)
;   brasl %r14, tls_gdcall:userextname0
;   ear %r3, %a0
;   sllg %r3, %r3, 32
;   ear %r3, %a1
;   agr %r2, %r3
;   lmg %r12, %r15, 256(%r15)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r12, %r15, 0x60(%r15)
;   aghi %r15, -0xa0
; block1: ; offset 0xa
;   larl %r12, 0xa ; reloc_external PCRel32Dbl %ElfGlobalOffsetTable 2
;   bras %r1, 0x1c
;   .byte 0x00, 0x00 ; reloc_external TlsGd64 u1:0 0
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   .byte 0x00, 0x00
;   lg %r2, 0(%r1)
;   brasl %r14, 0x22 ; reloc_external PLTRel32Dbl %ElfTlsGetOffset 2 ; reloc_external TlsGdCall u1:0 0
;   ear %r3, %a0
;   sllg %r3, %r3, 0x20
;   ear %r3, %a1
;   agr %r2, %r3
;   lmg %r12, %r15, 0x100(%r15)
;   br %r14

