test compile precise-output
target s390x

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; TRAP
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

function %trap() {
block0:
  trap user0
}

; VCode:
; block0:
;   .word 0x0000 # trap=user0
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x00, 0x00 ; trap: user0

function %trapz(i64) {
block0(v0: i64):
  v1 = iconst.i64 42
  v2 = icmp eq v0, v1
  trapz v2, user0
  return
}

; VCode:
; block0:
;   clgfi %r2, 42
;   jge label2 ; jg label1
; block2:
;   br %r14
; block1:
;   .word 0x0000 # trap=user0
;
; Disassembled:
; block0: ; offset 0x0
;   clgfi %r2, 0x2a
;   jgne 0xe
; block1: ; offset 0xc
;   br %r14
; block2: ; offset 0xe
;   .byte 0x00, 0x00 ; trap: user0

function %trapnz(i64) {
block0(v0: i64):
  v1 = iconst.i64 42
  v2 = icmp eq v0, v1
  trapnz v2, user0
  return
}

; VCode:
; block0:
;   clgfi %r2, 42
;   jge label2 ; jg label1
; block1:
;   br %r14
; block2:
;   .word 0x0000 # trap=user0
;
; Disassembled:
; block0: ; offset 0x0
;   clgfi %r2, 0x2a
;   jge 0xe
; block1: ; offset 0xc
;   br %r14
; block2: ; offset 0xe
;   .byte 0x00, 0x00 ; trap: user0

function %h() {
block0:
  debugtrap
  return
}

; VCode:
; block0:
;   .word 0x0001 # debugtrap
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   .byte 0x00, 0x01
;   br %r14
