test compile precise-output
target s390x

function %f0(i32) -> i32 {
block0(v0: i32):
    v1 = iconst.i32 127
    v2 = uadd_overflow_trap v0, v1, user0
    return v2
}

; block0:
;   alfi %r2, 127
;   jle 6 ; trap
;   br %r14

function %f1(i32) -> i32 {
block0(v0: i32):
    v1 = iconst.i32 127
    v2 = uadd_overflow_trap v1, v0, user0
    return v2
}

; block0:
;   alfi %r2, 127
;   jle 6 ; trap
;   br %r14

function %f2(i32, i32) -> i32 {
block0(v0: i32, v1: i32):
    v2 = uadd_overflow_trap v0, v1, user0
    return v2
}

; block0:
;   alr %r2, %r3
;   jle 6 ; trap
;   br %r14

function %f3(i64) -> i64 {
block0(v0: i64):
    v1 = iconst.i64 127
    v2 = uadd_overflow_trap v0, v1, user0
    return v2
}

; block0:
;   algfi %r2, 127
;   jle 6 ; trap
;   br %r14

function %f3(i64) -> i64 {
block0(v0: i64):
    v1 = iconst.i64 127
    v2 = uadd_overflow_trap v1, v0, user0
    return v2
}

; block0:
;   algfi %r2, 127
;   jle 6 ; trap
;   br %r14

function %f4(i64, i64) -> i64 {
block0(v0: i64, v1: i64):
    v2 = uadd_overflow_trap v0, v1, user0
    return v2
}

; block0:
;   algr %r2, %r3
;   jle 6 ; trap
;   br %r14

function %f5(i64, i32) -> i64 {
block0(v0: i64, v1: i32):
    v2 = uextend.i64 v1
    v3 = uadd_overflow_trap v0, v2, user0
    return v3
}

; block0:
;   algfr %r2, %r3
;   jle 6 ; trap
;   br %r14
