test compile precise-output
target s390x

function %f2(i8, i8) -> i8, i8 {
block0(v0: i8, v1: i8):
    v2, v3 = umul_overflow v0, v1
    return v2, v3
}

; VCode:
; block0:
;   llgcr %r3, %r3
;   llgcr %r5, %r2
;   msgrkc %r2, %r3, %r5
;   srlg %r3, %r2, 8
;   chi %r3, 0
;   lhi %r3, 0
;   lochine %r3, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llgcr %r3, %r3
;   llgcr %r5, %r2
;   msgrkc %r2, %r3, %r5
;   srlg %r3, %r2, 8
;   chi %r3, 0
;   lhi %r3, 0
;   lochine %r3, 1
;   br %r14

function %f2(i16, i16) -> i16, i8 {
block0(v0: i16, v1: i16):
    v2, v3 = umul_overflow v0, v1
    return v2, v3
}

; VCode:
; block0:
;   llghr %r3, %r3
;   llghr %r5, %r2
;   msgrkc %r2, %r3, %r5
;   srlg %r3, %r2, 16
;   chi %r3, 0
;   lhi %r3, 0
;   lochine %r3, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llghr %r3, %r3
;   llghr %r5, %r2
;   msgrkc %r2, %r3, %r5
;   srlg %r3, %r2, 0x10
;   chi %r3, 0
;   lhi %r3, 0
;   lochine %r3, 1
;   br %r14

function %f2(i32, i32) -> i32, i8 {
block0(v0: i32, v1: i32):
    v2, v3 = umul_overflow v0, v1
    return v2, v3
}

; VCode:
; block0:
;   llgfr %r3, %r3
;   llgfr %r5, %r2
;   msgrkc %r2, %r3, %r5
;   srlg %r3, %r2, 32
;   chi %r3, 0
;   lhi %r3, 0
;   lochine %r3, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   llgfr %r3, %r3
;   llgfr %r5, %r2
;   msgrkc %r2, %r3, %r5
;   srlg %r3, %r2, 0x20
;   chi %r3, 0
;   lhi %r3, 0
;   lochine %r3, 1
;   br %r14

function %f4(i64, i64) -> i64, i8 {
block0(v0: i64, v1: i64):
    v2, v3 = umul_overflow v0, v1
    return v2, v3
}

; VCode:
; block0:
;   mlgr %r2, %r2
;   lgr %r4, %r3
;   cghi %r2, 0
;   lhi %r3, 0
;   lochine %r3, 1
;   lgr %r2, %r4
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   mlgr %r2, %r2
;   lgr %r4, %r3
;   cghi %r2, 0
;   lhi %r3, 0
;   lochine %r3, 1
;   lgr %r2, %r4
;   br %r14

