test compile precise-output
set unwind_info=false
set enable_probestack=false
target s390x

function %foo() system_v {
    ss0 = explicit_slot 12, align = 4
    sig0 = (i32) system_v
    fn0 = colocated u0:0 sig0

block0:
    v0 = iconst.i32 0
    v1 = iconst.i32 1
    v2 = iconst.i32 2
    v3 = iconst.i32 3

    stack_store v0, ss0
    stack_store v1, ss0+4
    stack_store v2, ss0+8
    call fn0(v0), stack_map=[i32 @ ss0+0, i32 @ ss0+4, i32 @ ss0+8]

    stack_store v1, ss0
    stack_store v2, ss0+4
    call fn0(v0), stack_map=[i32 @ ss0+0, i32 @ ss0+4]

    stack_store v2, ss0
    call fn0(v1), stack_map=[i32 @ ss0+0]

    call fn0(v2)

    return
}

; VCode:
;   stmg %r6, %r15, 48(%r15)
;   aghi %r15, -176
; block0:
;   lhi %r8, 0
;   lhi %r6, 1
;   lhi %r7, 2
;   la %r2, 160(%r15)
;   mvhi 0(%r2), 0
;   la %r3, 164(%r15)
;   mvhi 0(%r3), 1
;   la %r4, 168(%r15)
;   mvhi 0(%r4), 2
;   lgr %r2, %r8
;   brasl %r14, userextname0
;   ; UserStackMap { by_type: [(types::I32, CompoundBitSet {0, 4, 8})], sp_to_sized_stack_slots: None }
;   la %r2, 160(%r15)
;   mvhi 0(%r2), 1
;   la %r3, 164(%r15)
;   mvhi 0(%r3), 2
;   lgr %r2, %r8
;   brasl %r14, userextname0
;   ; UserStackMap { by_type: [(types::I32, CompoundBitSet {0, 4})], sp_to_sized_stack_slots: None }
;   la %r5, 160(%r15)
;   mvhi 0(%r5), 2
;   lgr %r2, %r6
;   brasl %r14, userextname0
;   ; UserStackMap { by_type: [(types::I32, CompoundBitSet {0})], sp_to_sized_stack_slots: None }
;   lgr %r2, %r7
;   brasl %r14, userextname0
;   lmg %r6, %r15, 224(%r15)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r6, %r15, 0x30(%r15)
;   aghi %r15, -0xb0
; block1: ; offset 0xa
;   lhi %r8, 0
;   lhi %r6, 1
;   lhi %r7, 2
;   la %r2, 0xa0(%r15)
;   mvhi 0(%r2), 0
;   la %r3, 0xa4(%r15)
;   mvhi 0(%r3), 1
;   la %r4, 0xa8(%r15)
;   mvhi 0(%r4), 2
;   lgr %r2, %r8
;   brasl %r14, 0x38 ; reloc_external PLTRel32Dbl u0:0 2
;   la %r2, 0xa0(%r15)
;   mvhi 0(%r2), 1
;   la %r3, 0xa4(%r15)
;   mvhi 0(%r3), 2
;   lgr %r2, %r8
;   brasl %r14, 0x56 ; reloc_external PLTRel32Dbl u0:0 2
;   la %r5, 0xa0(%r15)
;   mvhi 0(%r5), 2
;   lgr %r2, %r6
;   brasl %r14, 0x6a ; reloc_external PLTRel32Dbl u0:0 2
;   lgr %r2, %r7
;   brasl %r14, 0x74 ; reloc_external PLTRel32Dbl u0:0 2
;   lmg %r6, %r15, 0xe0(%r15)
;   br %r14

function %different_types(i8, i16, i32, i64, f32, f64) -> i8, i16, i32, i64, f32, f64 fast {
    ss0 = explicit_slot 1
    ss1 = explicit_slot 2, align = 2
    ss2 = explicit_slot 8, align = 4
    ss3 = explicit_slot 16, align = 8
    ss4 = explicit_slot 48, align = 16
    sig0 = () system_v
    fn0 = colocated u0:0 sig0

block0(v0: i8, v1: i16, v2: i32, v3: i64, v4: f32, v5: f64):
    stack_store v0, ss0
    stack_store v1, ss1
    stack_store v2, ss2
    stack_store v4, ss2+4
    stack_store v3, ss3
    stack_store v5, ss3+8
    call fn0(), stack_map=[i8 @ ss0+0, i16 @ ss1+0, i32 @ ss2+0, f32 @ ss2+4, i64 @ ss3+0, f64 @ ss3+8]
    return v0, v1, v2, v3, v4, v5
}

; VCode:
;   stmg %r6, %r15, 48(%r15)
;   aghi %r15, -352
;   std %f8, 288(%r15)
;   std %f9, 296(%r15)
;   std %f10, 304(%r15)
;   std %f11, 312(%r15)
;   std %f12, 320(%r15)
;   std %f13, 328(%r15)
;   std %f14, 336(%r15)
;   std %f15, 344(%r15)
; block0:
;   la %r9, 160(%r15)
;   stc %r2, 0(%r9)
;   lgr %r9, %r2
;   la %r2, 168(%r15)
;   sth %r3, 0(%r2)
;   lgr %r6, %r3
;   la %r2, 176(%r15)
;   st %r4, 0(%r2)
;   lgr %r11, %r4
;   la %r2, 180(%r15)
;   ste %f0, 0(%r2)
;   vst %v0, 256(%r15)
;   la %r2, 184(%r15)
;   stg %r5, 0(%r2)
;   lgr %r8, %r5
;   la %r3, 192(%r15)
;   std %f2, 0(%r3)
;   vst %v2, 272(%r15)
;   brasl %r14, userextname0
;   ; UserStackMap { by_type: [(types::I8, CompoundBitSet {0}), (types::I16, CompoundBitSet {8}), (types::I32, CompoundBitSet {16}), (types::F32, CompoundBitSet {20}), (types::I64, CompoundBitSet {24}), (types::F64, CompoundBitSet {32})], sp_to_sized_stack_slots: None }
;   lgr %r2, %r9
;   lgr %r3, %r6
;   lgr %r4, %r11
;   lgr %r5, %r8
;   vl %v0, 256(%r15)
;   vl %v2, 272(%r15)
;   ld %f8, 288(%r15)
;   ld %f9, 296(%r15)
;   ld %f10, 304(%r15)
;   ld %f11, 312(%r15)
;   ld %f12, 320(%r15)
;   ld %f13, 328(%r15)
;   ld %f14, 336(%r15)
;   ld %f15, 344(%r15)
;   lmg %r6, %r15, 400(%r15)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   stmg %r6, %r15, 0x30(%r15)
;   aghi %r15, -0x160
;   std %f8, 0x120(%r15)
;   std %f9, 0x128(%r15)
;   std %f10, 0x130(%r15)
;   std %f11, 0x138(%r15)
;   std %f12, 0x140(%r15)
;   std %f13, 0x148(%r15)
;   std %f14, 0x150(%r15)
;   std %f15, 0x158(%r15)
; block1: ; offset 0x2a
;   la %r9, 0xa0(%r15)
;   stc %r2, 0(%r9)
;   lgr %r9, %r2
;   la %r2, 0xa8(%r15)
;   sth %r3, 0(%r2)
;   lgr %r6, %r3
;   la %r2, 0xb0(%r15)
;   st %r4, 0(%r2)
;   lgr %r11, %r4
;   la %r2, 0xb4(%r15)
;   ste %f0, 0(%r2)
;   vst %v0, 0x100(%r15)
;   la %r2, 0xb8(%r15)
;   stg %r5, 0(%r2)
;   lgr %r8, %r5
;   la %r3, 0xc0(%r15)
;   std %f2, 0(%r3)
;   vst %v2, 0x110(%r15)
;   brasl %r14, 0x78 ; reloc_external PLTRel32Dbl u0:0 2
;   lgr %r2, %r9
;   lgr %r3, %r6
;   lgr %r4, %r11
;   lgr %r5, %r8
;   vl %v0, 0x100(%r15)
;   vl %v2, 0x110(%r15)
;   ld %f8, 0x120(%r15)
;   ld %f9, 0x128(%r15)
;   ld %f10, 0x130(%r15)
;   ld %f11, 0x138(%r15)
;   ld %f12, 0x140(%r15)
;   ld %f13, 0x148(%r15)
;   ld %f14, 0x150(%r15)
;   ld %f15, 0x158(%r15)
;   lmg %r6, %r15, 0x190(%r15)
;   br %r14

