test compile precise-output
set enable_multi_ret_implicit_sret
target s390x

function %f2(i8, i8) -> i8, i8 {
block0(v0: i8, v1: i8):
    v2, v3 = usub_overflow v0, v1
    return v2, v3
}

; VCode:
; block0:
;   lgr %r4, %r3
;   sllk %r3, %r2, 24
;   lgr %r2, %r4
;   sllk %r5, %r2, 24
;   slrk %r2, %r3, %r5
;   lhi %r3, 0
;   lochile %r3, 1
;   srlk %r2, %r2, 24
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgr %r4, %r3
;   sllk %r3, %r2, 0x18
;   lgr %r2, %r4
;   sllk %r5, %r2, 0x18
;   slrk %r2, %r3, %r5
;   lhi %r3, 0
;   lochile %r3, 1
;   srlk %r2, %r2, 0x18
;   br %r14

function %f2(i16, i16) -> i16, i8 {
block0(v0: i16, v1: i16):
    v2, v3 = usub_overflow v0, v1
    return v2, v3
}

; VCode:
; block0:
;   lgr %r4, %r3
;   sllk %r3, %r2, 16
;   lgr %r2, %r4
;   sllk %r5, %r2, 16
;   slrk %r2, %r3, %r5
;   lhi %r3, 0
;   lochile %r3, 1
;   srlk %r2, %r2, 16
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgr %r4, %r3
;   sllk %r3, %r2, 0x10
;   lgr %r2, %r4
;   sllk %r5, %r2, 0x10
;   slrk %r2, %r3, %r5
;   lhi %r3, 0
;   lochile %r3, 1
;   srlk %r2, %r2, 0x10
;   br %r14

function %f2(i32, i32) -> i32, i8 {
block0(v0: i32, v1: i32):
    v2, v3 = usub_overflow v0, v1
    return v2, v3
}

; VCode:
; block0:
;   slr %r2, %r3
;   lhi %r3, 0
;   lochile %r3, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   slr %r2, %r3
;   lhi %r3, 0
;   lochile %r3, 1
;   br %r14

function %f4(i64, i64) -> i64, i8 {
block0(v0: i64, v1: i64):
    v2, v3 = usub_overflow v0, v1
    return v2, v3
}

; VCode:
; block0:
;   slgr %r2, %r3
;   lhi %r3, 0
;   lochile %r3, 1
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   slgr %r2, %r3
;   lhi %r3, 0
;   lochile %r3, 1
;   br %r14

function %f5(i128, i128) -> i128, i8 {
block0(v0: i128, v1: i128):
    v2, v3 = usub_overflow v0, v1
    return v2, v3
}

; VCode:
; block0:
;   lgr %r5, %r2
;   vl %v1, 0(%r3)
;   vl %v3, 0(%r4)
;   vsq %v6, %v1, %v3
;   vscbiq %v16, %v1, %v3
;   vlgvg %r2, %v16, 1
;   xilf %r2, 1
;   lgr %r3, %r5
;   vst %v6, 0(%r3)
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   lgr %r5, %r2
;   vl %v1, 0(%r3)
;   vl %v3, 0(%r4)
;   vsq %v6, %v1, %v3
;   vscbiq %v16, %v1, %v3
;   vlgvg %r2, %v16, 1
;   xilf %r2, 1
;   lgr %r3, %r5
;   vst %v6, 0(%r3)
;   br %r14

