test compile precise-output
target s390x arch15

function %imul_i64x2(i64x2, i64x2) -> i64x2 {
block0(v0: i64x2, v1: i64x2):
  v2 = imul.i64x2 v0, v1
  return v2
}

; VCode:
; block0:
;   vmlg %v24, %v24, %v25
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vml %v24, %v24, %v25, 3
;   br %r14

function %umulhi_i64x2(i64x2, i64x2) -> i64x2 {
block0(v0: i64x2, v1: i64x2):
  v2 = umulhi.i64x2 v0, v1
  return v2
}

; VCode:
; block0:
;   vmlhg %v24, %v24, %v25
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vmlh %v24, %v24, %v25, 3
;   br %r14

function %smulhi_i64x2(i64x2, i64x2) -> i64x2 {
block0(v0: i64x2, v1: i64x2):
  v2 = smulhi.i64x2 v0, v1
  return v2
}

; VCode:
; block0:
;   vmhg %v24, %v24, %v25
;   br %r14
;
; Disassembled:
; block0: ; offset 0x0
;   vmh %v24, %v24, %v25, 3
;   br %r14

