test optimize precise-output
target x86_64

function u0:0(i32, i32, i32) -> i32 {
block0(v0: i32, v1: i32, v2: i32):
    brif v0, block1(v1), block1(v2)

block1(v3: i32):
    brif v0, block3(v3), block2(v3)

block2(v4: i32):
    jump block3(v4)

block3(v5: i32):
    return v5
}

; function u0:0(i32, i32, i32) -> i32 fast {
; block0(v0: i32, v1: i32, v2: i32):
;     brif v0, block1(v1), block1(v2)
;
; block1(v3: i32):
;     v4 -> v3
;     v5 -> v3
;     brif.i32 v0, block3, block2
;
; block2:
;     jump block3
;
; block3:
;     return v5
; }

