;;! target = "x86_64"
;;! test = "winch"

(module
    (func (result i32)
        (local i64)

        (local.get 0)
        (i32.wrap_i64)
    )
)
;; wasm[0]::function[0]:
;;       pushq   %rbp
;;       movq    %rsp, %rbp
;;       movq    8(%rdi), %r11
;;       movq    0x18(%r11), %r11
;;       addq    $0x20, %r11
;;       cmpq    %rsp, %r11
;;       ja      0x49
;;   1c: movq    %rdi, %r14
;;       subq    $0x20, %rsp
;;       movq    %rdi, 0x18(%rsp)
;;       movq    %rsi, 0x10(%rsp)
;;       movq    $0, 8(%rsp)
;;       movq    8(%rsp), %rax
;;       movl    %eax, %eax
;;       addq    $0x20, %rsp
;;       popq    %rbp
;;       retq
;;   49: ud2
