;;! target = "riscv64"
;;!
;;! settings = ['enable_heap_access_spectre_mitigation=true']
;;!
;;! compile = true
;;!
;;! [globals.vmctx]
;;! type = "i64"
;;! vmctx = true
;;!
;;! [globals.heap_base]
;;! type = "i64"
;;! load = { base = "vmctx", offset = 0, readonly = true }
;;!
;;! [globals.heap_bound]
;;! type = "i64"
;;! load = { base = "vmctx", offset = 8, readonly = true }
;;!
;;! [[heaps]]
;;! base = "heap_base"
;;! min_size = 0x10000
;;! offset_guard_size = 0xffffffff
;;! index_type = "i32"
;;! style = { kind = "dynamic", bound = "heap_bound" }

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0x1000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load8_u offset=0x1000))

;; function u0:0:
;; block0:
;;   slli a3,a0,32
;;   srli a5,a3,32
;;   ld a3,8(a2)
;;   ugt a4,a5,a3##ty=i64
;;   ld a3,0(a2)
;;   add a3,a3,a5
;;   lui a5,1
;;   add a3,a3,a5
;;   li a5,0
;;   andi t0,a4,255
;;   sltu t2,zero,t0
;;   sub a2,zero,t2
;;   and a4,a5,a2
;;   not a5,a2
;;   and a7,a3,a5
;;   or t4,a4,a7
;;   sb a1,0(t4)
;;   j label1
;; block1:
;;   ret
;;
;; function u0:1:
;; block0:
;;   slli a2,a0,32
;;   srli a5,a2,32
;;   ld a3,8(a1)
;;   ugt a4,a5,a3##ty=i64
;;   ld a3,0(a1)
;;   add a3,a3,a5
;;   lui a5,1
;;   add a3,a3,a5
;;   li a5,0
;;   andi t0,a4,255
;;   sltu t2,zero,t0
;;   sub a1,zero,t2
;;   and a4,a5,a1
;;   not a5,a1
;;   and a7,a3,a5
;;   or t4,a4,a7
;;   lbu a0,0(t4)
;;   j label1
;; block1:
;;   ret
