;;! target = "riscv64"
;;!
;;! settings = ['enable_heap_access_spectre_mitigation=true']
;;!
;;! compile = true
;;!
;;! [globals.vmctx]
;;! type = "i64"
;;! vmctx = true
;;!
;;! [globals.heap_base]
;;! type = "i64"
;;! load = { base = "vmctx", offset = 0, readonly = true }
;;!
;;! [globals.heap_bound]
;;! type = "i64"
;;! load = { base = "vmctx", offset = 8, readonly = true }
;;!
;;! [[heaps]]
;;! base = "heap_base"
;;! min_size = 0x10000
;;! offset_guard_size = 0
;;! index_type = "i32"
;;! style = { kind = "dynamic", bound = "heap_bound" }

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0x1000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0x1000))

;; function u0:0:
;; block0:
;;   slli a4,a0,32
;;   srli a0,a4,32
;;   ld a5,8(a2)
;;   lui a4,1
;;   addi a3,a4,4
;;   sub a5,a5,a3
;;   sltu a5,a5,a0
;;   ld a2,0(a2)
;;   add a0,a2,a0
;;   lui a2,1
;;   add a0,a0,a2
;;   sub a3,zero,a5
;;   not a5,a3
;;   and a2,a0,a5
;;   sw a1,0(a2)
;;   j label1
;; block1:
;;   ret
;;
;; function u0:1:
;; block0:
;;   slli a4,a0,32
;;   srli a0,a4,32
;;   ld a5,8(a1)
;;   lui a4,1
;;   addi a2,a4,4
;;   sub a5,a5,a2
;;   sltu a5,a5,a0
;;   ld a1,0(a1)
;;   add a0,a1,a0
;;   lui a1,1
;;   add a0,a0,a1
;;   sub a3,zero,a5
;;   not a5,a3
;;   and a1,a0,a5
;;   lw a0,0(a1)
;;   j label1
;; block1:
;;   ret
