;;! target = "riscv64"
;;!
;;! settings = ['enable_heap_access_spectre_mitigation=true']
;;!
;;! compile = true
;;!
;;! [globals.vmctx]
;;! type = "i64"
;;! vmctx = true
;;!
;;! [globals.heap_base]
;;! type = "i64"
;;! load = { base = "vmctx", offset = 0, readonly = true }
;;!
;;! [globals.heap_bound]
;;! type = "i64"
;;! load = { base = "vmctx", offset = 8, readonly = true }
;;!
;;! [[heaps]]
;;! base = "heap_base"
;;! min_size = 0x10000
;;! offset_guard_size = 0xffffffff
;;! index_type = "i64"
;;! style = { kind = "dynamic", bound = "heap_bound" }

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store offset=0xffff0000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load offset=0xffff0000))

;; function u0:0:
;; block0:
;;   ld a3,8(a2)
;;   ugt a3,a0,a3##ty=i64
;;   ld a2,0(a2)
;;   add a2,a2,a0
;;   lui a4,16
;;   addi a0,a4,-1
;;   slli a4,a0,16
;;   add a2,a2,a4
;;   li a0,0
;;   sltu a3,zero,a3
;;   sub a3,zero,a3
;;   and a5,a0,a3
;;   not a3,a3
;;   and a3,a2,a3
;;   or a5,a5,a3
;;   sw a1,0(a5)
;;   j label1
;; block1:
;;   ret
;;
;; function u0:1:
;; block0:
;;   ld a2,8(a1)
;;   ugt a2,a0,a2##ty=i64
;;   ld a1,0(a1)
;;   add a1,a1,a0
;;   lui a4,16
;;   addi a0,a4,-1
;;   slli a3,a0,16
;;   add a1,a1,a3
;;   li a0,0
;;   sltu a2,zero,a2
;;   sub a3,zero,a2
;;   and a5,a0,a3
;;   not a2,a3
;;   and a3,a1,a2
;;   or a5,a5,a3
;;   lw a0,0(a5)
;;   j label1
;; block1:
;;   ret
