;;! target = "riscv64"
;;!
;;! settings = ['enable_heap_access_spectre_mitigation=true']
;;!
;;! compile = true
;;!
;;! [globals.vmctx]
;;! type = "i64"
;;! vmctx = true
;;!
;;! [globals.heap_base]
;;! type = "i64"
;;! load = { base = "vmctx", offset = 0, readonly = true }
;;!
;;! [globals.heap_bound]
;;! type = "i64"
;;! load = { base = "vmctx", offset = 8, readonly = true }
;;!
;;! [[heaps]]
;;! base = "heap_base"
;;! min_size = 0x10000
;;! offset_guard_size = 0
;;! index_type = "i64"
;;! style = { kind = "dynamic", bound = "heap_bound" }

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0xffff0000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load8_u offset=0xffff0000))

;; function u0:0:
;; block0:
;;   ld a3,[const(1)]
;;   add a3,a0,a3
;;   trap_if heap_oob##(a3 ult a0)
;;   ld a4,8(a2)
;;   ugt a4,a3,a4##ty=i64
;;   ld a2,0(a2)
;;   add a2,a2,a0
;;   ld a3,[const(0)]
;;   add a3,a2,a3
;;   li a2,0
;;   sltu a4,zero,a4
;;   sub a4,zero,a4
;;   and a0,a2,a4
;;   not a2,a4
;;   and a4,a3,a2
;;   or a0,a0,a4
;;   sb a1,0(a0)
;;   j label1
;; block1:
;;   ret
;;
;; function u0:1:
;; block0:
;;   ld a2,[const(1)]
;;   add a2,a0,a2
;;   trap_if heap_oob##(a2 ult a0)
;;   ld a3,8(a1)
;;   ugt a3,a2,a3##ty=i64
;;   ld a1,0(a1)
;;   add a1,a1,a0
;;   ld a2,[const(0)]
;;   add a2,a1,a2
;;   li a1,0
;;   sltu a3,zero,a3
;;   sub a4,zero,a3
;;   and a0,a1,a4
;;   not a3,a4
;;   and a4,a2,a3
;;   or a0,a0,a4
;;   lbu a0,0(a0)
;;   j label1
;; block1:
;;   ret
