;;! target = "riscv64"
;;!
;;! settings = ['enable_heap_access_spectre_mitigation=false']
;;!
;;! compile = true
;;!
;;! [globals.vmctx]
;;! type = "i64"
;;! vmctx = true
;;!
;;! [globals.heap_base]
;;! type = "i64"
;;! load = { base = "vmctx", offset = 0, readonly = true }
;;!
;;! [globals.heap_bound]
;;! type = "i64"
;;! load = { base = "vmctx", offset = 8, readonly = true }
;;!
;;! [[heaps]]
;;! base = "heap_base"
;;! min_size = 0x10000
;;! offset_guard_size = 0xffffffff
;;! index_type = "i32"
;;! style = { kind = "dynamic", bound = "heap_bound" }

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0xffff0000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0xffff0000))

;; function u0:0:
;; block0:
;;   uext.w t0,a0
;;   auipc t3,0; ld t3,12(t3); j 12; .8byte 0xffff0004
;;   add t1,t0,t3
;;   ult t2,t1,t0##ty=i64
;;   trap_if t2,heap_oob
;;   ld t2,8(a2)
;;   ule t1,t1,t2##ty=i64
;;   bne t1,zero,taken(label1),not_taken(label3)
;; block1:
;;   ld t2,0(a2)
;;   add t2,t2,t0
;;   auipc t1,0; ld t1,12(t1); j 12; .8byte 0xffff0000
;;   add a0,t2,t1
;;   sw a1,0(a0)
;;   j label2
;; block2:
;;   ret
;; block3:
;;   udf##trap_code=heap_oob
;;
;; function u0:1:
;; block0:
;;   uext.w t0,a0
;;   auipc t3,0; ld t3,12(t3); j 12; .8byte 0xffff0004
;;   add t1,t0,t3
;;   ult t2,t1,t0##ty=i64
;;   trap_if t2,heap_oob
;;   ld t2,8(a1)
;;   ule t1,t1,t2##ty=i64
;;   bne t1,zero,taken(label1),not_taken(label3)
;; block1:
;;   ld t2,0(a1)
;;   add t2,t2,t0
;;   auipc t1,0; ld t1,12(t1); j 12; .8byte 0xffff0000
;;   add a0,t2,t1
;;   lw a0,0(a0)
;;   j label2
;; block2:
;;   ret
;; block3:
;;   udf##trap_code=heap_oob