;;! target = "riscv64"
;;!
;;! settings = ['enable_heap_access_spectre_mitigation=true']
;;!
;;! compile = true
;;!
;;! [globals.vmctx]
;;! type = "i64"
;;! vmctx = true
;;!
;;! [globals.heap_base]
;;! type = "i64"
;;! load = { base = "vmctx", offset = 0, readonly = true }
;;!
;;! # (no heap_bound global for static heaps)
;;!
;;! [[heaps]]
;;! base = "heap_base"
;;! min_size = 0x10000
;;! offset_guard_size = 0xffffffff
;;! index_type = "i64"
;;! style = { kind = "static", bound = 0x10000000 }

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store offset=0)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load offset=0))

;; function u0:0:
;; block0:
;;   lui t2,65536
;;   addi t2,t2,4093
;;   sltu a3,a0,t2
;;   xori a4,a3,1
;;   ld a2,0(a2)
;;   add a2,a2,a0
;;   li a3,0
;;   andi t3,a4,255
;;   snez t0,t3
;;   sub t2,zero,t0
;;   and a3,a3,t2
;;   not a4,t2
;;   and a5,a2,a4
;;   or a7,a3,a5
;;   sw a1,0(a7)
;;   j label1
;; block1:
;;   ret
;;
;; function u0:1:
;; block0:
;;   lui t2,65536
;;   addi t2,t2,4093
;;   sltu a2,a0,t2
;;   xori a4,a2,1
;;   ld a1,0(a1)
;;   add a1,a1,a0
;;   li a2,0
;;   andi t3,a4,255
;;   snez t0,t3
;;   sub t2,zero,t0
;;   and a2,a2,t2
;;   not a3,t2
;;   and a5,a1,a3
;;   or a7,a2,a5
;;   lw a0,0(a7)
;;   j label1
;; block1:
;;   ret
