;;! target = "riscv64"
;;!
;;! settings = ['enable_heap_access_spectre_mitigation=true']
;;!
;;! compile = true
;;!
;;! [globals.vmctx]
;;! type = "i64"
;;! vmctx = true
;;!
;;! [globals.heap_base]
;;! type = "i64"
;;! load = { base = "vmctx", offset = 0, readonly = true }
;;!
;;! [globals.heap_bound]
;;! type = "i64"
;;! load = { base = "vmctx", offset = 8, readonly = true }
;;!
;;! [[heaps]]
;;! base = "heap_base"
;;! min_size = 0x10000
;;! offset_guard_size = 0
;;! index_type = "i64"
;;! style = { kind = "dynamic", bound = "heap_bound" }

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store offset=0xffff0000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load offset=0xffff0000))

;; function u0:0:
;; block0:
;;   lui a3,262140
;;   addi a3,a3,1
;;   slli a4,a3,2
;;   add a3,a0,a4
;;   trap_if heap_oob##(a3 ult a0)
;;   ld a4,8(a2)
;;   ugt a3,a3,a4##ty=i64
;;   ld a4,0(a2)
;;   add a4,a4,a0
;;   lui a2,65535
;;   slli a5,a2,4
;;   add a4,a4,a5
;;   li a5,0
;;   sub a0,zero,a3
;;   and a2,a5,a0
;;   not a3,a0
;;   and a5,a4,a3
;;   or a2,a2,a5
;;   sw a1,0(a2)
;;   j label1
;; block1:
;;   ret
;;
;; function u0:1:
;; block0:
;;   lui a2,262140
;;   addi a2,a2,1
;;   slli a4,a2,2
;;   add a2,a0,a4
;;   trap_if heap_oob##(a2 ult a0)
;;   ld a3,8(a1)
;;   ugt a3,a2,a3##ty=i64
;;   ld a4,0(a1)
;;   add a4,a4,a0
;;   lui a2,65535
;;   slli a5,a2,4
;;   add a4,a4,a5
;;   li a5,0
;;   sub a0,zero,a3
;;   and a1,a5,a0
;;   not a3,a0
;;   and a5,a4,a3
;;   or a1,a1,a5
;;   lw a0,0(a1)
;;   j label1
;; block1:
;;   ret
