;;! target = "riscv64"
;;!
;;! settings = ['enable_heap_access_spectre_mitigation=true']
;;!
;;! compile = true
;;!
;;! [globals.vmctx]
;;! type = "i64"
;;! vmctx = true
;;!
;;! [globals.heap_base]
;;! type = "i64"
;;! load = { base = "vmctx", offset = 0, readonly = true }
;;!
;;! # (no heap_bound global for static heaps)
;;!
;;! [[heaps]]
;;! base = "heap_base"
;;! min_size = 0x10000
;;! offset_guard_size = 0xffffffff
;;! index_type = "i64"
;;! style = { kind = "static", bound = 0x10000000 }

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store offset=0x1000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load offset=0x1000))

;; function u0:0:
;; block0:
;;   lui a3,65535
;;   addi a3,a3,-4
;;   sltu a3,a3,a0
;;   ld a2,0(a2)
;;   add a2,a2,a0
;;   lui a4,1
;;   add a2,a2,a4
;;   sub a5,zero,a3
;;   not a3,a5
;;   and a3,a2,a3
;;   sw a1,0(a3)
;;   j label1
;; block1:
;;   ret
;;
;; function u0:1:
;; block0:
;;   lui a2,65535
;;   addi a2,a2,-4
;;   sltu a2,a2,a0
;;   ld a1,0(a1)
;;   add a1,a1,a0
;;   lui a3,1
;;   add a1,a1,a3
;;   sub a5,zero,a2
;;   not a2,a5
;;   and a3,a1,a2
;;   lw a0,0(a3)
;;   j label1
;; block1:
;;   ret
