;;! target = "riscv64"
;;!
;;! settings = ['enable_heap_access_spectre_mitigation=true']
;;!
;;! compile = true
;;!
;;! [globals.vmctx]
;;! type = "i64"
;;! vmctx = true
;;!
;;! [globals.heap_base]
;;! type = "i64"
;;! load = { base = "vmctx", offset = 0, readonly = true }
;;!
;;! [globals.heap_bound]
;;! type = "i64"
;;! load = { base = "vmctx", offset = 8, readonly = true }
;;!
;;! [[heaps]]
;;! base = "heap_base"
;;! min_size = 0x10000
;;! offset_guard_size = 0
;;! index_type = "i64"
;;! style = { kind = "dynamic", bound = "heap_bound" }

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i64 1)

  (func (export "do_store") (param i64 i32)
    local.get 0
    local.get 1
    i32.store8 offset=0x1000)

  (func (export "do_load") (param i64) (result i32)
    local.get 0
    i32.load8_u offset=0x1000))

;; function u0:0:
;; block0:
;;   ld t3,8(a2)
;;   lui t4,1048575
;;   addi t4,t4,4095
;;   add t3,t3,t4
;;   ugt t0,a0,t3##ty=i64
;;   ld t3,0(a2)
;;   add t3,t3,a0
;;   lui t4,1
;;   add t3,t3,t4
;;   li t4,0
;;   andi t1,t0,255
;;   not a0,t1
;;   addi a2,a0,1
;;   or a4,t1,a2
;;   srli a6,a4,63
;;   andi t0,a6,1
;;   addi t0,t0,-1
;;   not t2,t0
;;   and a2,t4,t2
;;   and a3,t3,t0
;;   or a5,a2,a3
;;   sb a1,0(a5)
;;   j label1
;; block1:
;;   ret
;;
;; function u0:1:
;; block0:
;;   ld t3,8(a1)
;;   lui t4,1048575
;;   addi t4,t4,4095
;;   add t3,t3,t4
;;   ugt t0,a0,t3##ty=i64
;;   ld t3,0(a1)
;;   add t3,t3,a0
;;   lui t4,1
;;   add t3,t3,t4
;;   li t4,0
;;   andi t1,t0,255
;;   not a0,t1
;;   addi a2,a0,1
;;   or a4,t1,a2
;;   srli a6,a4,63
;;   andi t0,a6,1
;;   addi t0,t0,-1
;;   not t2,t0
;;   and a1,t4,t2
;;   and a3,t3,t0
;;   or a5,a1,a3
;;   lbu a0,0(a5)
;;   j label1
;; block1:
;;   ret
