;;! target = "riscv64"
;;!
;;! settings = ['enable_heap_access_spectre_mitigation=true']
;;!
;;! compile = true
;;!
;;! [globals.vmctx]
;;! type = "i64"
;;! vmctx = true
;;!
;;! [globals.heap_base]
;;! type = "i64"
;;! load = { base = "vmctx", offset = 0, readonly = true }
;;!
;;! [globals.heap_bound]
;;! type = "i64"
;;! load = { base = "vmctx", offset = 8, readonly = true }
;;!
;;! [[heaps]]
;;! base = "heap_base"
;;! min_size = 0x10000
;;! offset_guard_size = 0
;;! index_type = "i32"
;;! style = { kind = "dynamic", bound = "heap_bound" }

;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
;; !!! GENERATED BY 'make-load-store-tests.sh' DO NOT EDIT !!!
;; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

(module
  (memory i32 1)

  (func (export "do_store") (param i32 i32)
    local.get 0
    local.get 1
    i32.store offset=0xffff0000)

  (func (export "do_load") (param i32) (result i32)
    local.get 0
    i32.load offset=0xffff0000))

;; function u0:0:
;; block0:
;;   slli a5,a0,32
;;   srli a7,a5,32
;;   auipc a6,0; ld a6,12(a6); j 12; .8byte 0xffff0004
;;   add a5,a7,a6
;;   ult t3,a5,a7##ty=i64
;;   trap_if t3,heap_oob
;;   ld t3,8(a2)
;;   ugt t3,a5,t3##ty=i64
;;   ld t4,0(a2)
;;   add a7,t4,a7
;;   auipc t4,0; ld t4,12(t4); j 12; .8byte 0xffff0000
;;   add a7,a7,t4
;;   li t4,0
;;   andi a2,t3,255
;;   sltu a3,zero,a2
;;   sub a5,zero,a3
;;   and t3,t4,a5
;;   not t4,a5
;;   and t1,a7,t4
;;   or a0,t3,t1
;;   sw a1,0(a0)
;;   j label1
;; block1:
;;   ret
;;
;; function u0:1:
;; block0:
;;   slli a5,a0,32
;;   srli a7,a5,32
;;   auipc a6,0; ld a6,12(a6); j 12; .8byte 0xffff0004
;;   add a5,a7,a6
;;   ult t3,a5,a7##ty=i64
;;   trap_if t3,heap_oob
;;   ld t3,8(a1)
;;   ugt t3,a5,t3##ty=i64
;;   ld t4,0(a1)
;;   add a7,t4,a7
;;   auipc t4,0; ld t4,12(t4); j 12; .8byte 0xffff0000
;;   add a7,a7,t4
;;   li t4,0
;;   andi a1,t3,255
;;   sltu a3,zero,a1
;;   sub a5,zero,a3
;;   and t3,t4,a5
;;   not t4,a5
;;   and t1,a7,t4
;;   or a0,t3,t1
;;   lw a0,0(a0)
;;   j label1
;; block1:
;;   ret
